network: DHCPv4 cleanups
systemd/systemd pull request #16880
Opened 2020-08-28 05:07 UTC by yuwata

2020-08-28 06:16 UTC, keszybz requested changes

2020-08-28 06:16 UTC, keszybz commented on src/network/networkd-dhcp4.c
> +        /* Add back static routes since kernel removes while DHCPv4 address is removed from when lease expires */
Bad sentence.

2020-08-28 06:16 UTC, keszybz commented on man/networkctl.xml
> +        call <command>reload</command> command for applying the new settings.</para></listitem>
"... it is necessary to call `networkctl reload` first to apply new settings."

2020-08-28 09:13 UTC, yuwata commented
@keszybz Thank you for the review and suggestion. Updated.

2020-08-28 16:00 UTC, poettering approved these changes

2020-08-28 16:00 UTC, poettering commented on src/network/networkd-dhcp4.c
> +                sd_ipv4acd_stop(link->network->dhcp_acd);
cast to `(void)` maybe, since you ignore return values here?

Hmm, I also think it would make sense to make sd_ipv4acd_stop() idempotent, i.e. robust to calls when it is already stopped. i.e. move the if check you do in advance here, basically inside the function itself so that it becomes a NOP when already stopped?

2020-09-04 00:06 UTC, yuwata commented
@poettering Thank you for the comment, and sorry for late response.

> Hmm, I also think it would make sense to make sd_ipv4acd_stop() idempotent, i.e. robust to calls when it is already stopped. i.e. move the if check you do in advance here, basically inside the function itself so that it becomes a NOP when already stopped?

I added 6a776e3. I hope it addresses your request. PTAL.

2020-09-04 13:54 UTC, merged