resolve: follow-ups for extra DNS stub listener
systemd/systemd pull request #16951
Opened 2020-09-04 07:46 UTC by yuwata

Follow-ups for #16044.

Closes #16948.

2020-09-04 08:09 UTC, poettering requested changes

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-conf.h
> +        DNS_STUB_LISTENER_YES = DNS_STUB_LISTENER_UDP | DNS_STUB_LISTENER_TCP,
ha, this makes so much sense. Doesn't even change the actual values, but makes it so much more useful! excellent!

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-dns-stub.c
> +                l->tcp_fd = safe_close(l->tcp_fd);
doesn't matter, but you could also use `sd_event_source_set_io_fd_own()` so that you don#t need to handle the fd at all anymore

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-dns-stub.c
> +                        .in.sin_port = l->port != 0 ? htobe16(l->port) : htobe16(53),
doesn't matter, but you could move the ternary op inside the htobe16()? (might need to suffix 53 with U then though)

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-dns-stub.c
> +        if (bind(fd, &sa.sa, l->family == AF_INET ? sizeof(struct sockaddr_in) : sizeof(struct sockaddr_in6)) < 0) {
maybe we should add a helper for this one day: 

SOCKADDR_LEN() which checks the family and then returns sizeof(sockaddr_in), sizeof(sockaddr_in6) or SOCKADDR_UN_LEN() or SOCKADDR_LL_LEN() or -EAFNOSUPPORT or so.

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-dns-stub.c
> +        }
hmm, but we should set the matching optoins for ipv6 here, i.e. IPV6_RECVPKTINFO + IPV6_RECVHOPLIMIT

2020-09-04 08:09 UTC, poettering commented on src/resolve/resolved-dns-stub.c
> +                r = setsockopt_int(fd, IPPROTO_IP, IP_FREEBIND, true);
should call IPV6_FREEBIND socktopt on ipv6

2020-09-04 10:43 UTC, keszybz reviewed
This partially overlaps with #16947. Let's merge yours first, and then I'll rebase my changes on top.

2020-09-04 10:43 UTC, keszybz commented on man/resolved.conf.xml
> +        must be in the square brackets. If the port is not specified, then the service takes port as 53.
"takes port as 53" doesn't make much sense. Just say "uses port 53"

2020-09-04 14:14 UTC, yuwata commented
@poettering and @keszybz Thank you for the review. I've force-pushed a revised version, which addresses all your comments, and fixes several critical bugs.

2020-09-05 13:49 UTC, keszybz commented
bionic-i386: 347/811 test-process-util                       TIMEOUT 30.06 s , looks unrelated.

2020-09-05 13:55 UTC, keszybz commented
LGTM.

2020-09-05 13:55 UTC, merged