core: propagate start limit hit from triggered unit to path unit
systemd/systemd pull request #17031
Opened 2020-09-11 20:19 UTC by poettering

Fixes: #16669

2020-09-12 07:58 UTC, keszybz requested changes
Looks like a good fix, but I think the check in the first patch looks like something that grew organically over time and should be refactored now.

2020-09-12 07:58 UTC, keszybz commented on src/core/automount.c
> +                    UNIT_MASKED)|| other->type != UNIT_MOUNT)
Hmm, the states that are left are UNIT_STUB and UNIT_MERGED. I think it'd be cleaner at this point to invert the condition (and maybe even emit a warning if we hit that path. Wouldn't that mean some fuckup in the unit handling logic if a stub unit or a merged unit emitted a notification?).

Also, space before `||` is missing.

2020-09-14 11:29 UTC, poettering commented
Force pushed a new version, which upgrades these tests to assert() and turns them around. PTAL.

I think they should be asserts since it shouldn't be possible we get into the state where state changes are triggered on UNIT_STUB or UNIT_MERGED unit load states.

2020-09-14 19:50 UTC, keszybz commented
Looks reasonable. I guess that if we ever get the logic wrong, at least it'll be easy to notice with all the asserts.

2020-09-14 19:51 UTC, keszybz commented
bionic-i386 timed out, and semaphoreci says something about lxc. Looks unrelated.

2020-09-14 19:51 UTC, merged