network: Allow vxlan to be created without .network file
systemd/systemd pull request #17073
Opened 2020-09-16 01:06 UTC by ssahani

closes https://github.com/systemd/systemd/issues/17064

2020-09-16 17:16 UTC, poettering requested changes

2020-09-16 17:16 UTC, poettering commented on man/systemd.netdev.xml
> +          <para>Takes a boolean. When true vxlan does not require .network file. Defaults to <literal>false</literal>.
I find this confusing, i.e. the primary effect of this is that the netdev is not associated with an underlying iface, and that's what should be mentioned here, no?

2020-09-17 07:00 UTC, yuwata commented
@ssahani I've updated man page as requested by @poettering, and added a test for the setting.

@poettering PTAL.

2020-09-17 08:24 UTC, ssahani commented
Thank you @yuwata

2020-09-17 08:33 UTC, yuwata commented
CentOS CI (Arch Linux + sanitizers) failure is in `test_wireguard()`, seems not related.

2020-09-17 11:33 UTC, merged