man: update InitialCongestionWindow= and InitialAdvertisedReceiveWindow=
systemd/systemd pull request #17087
Opened 2020-09-17 08:03 UTC by yuwata

Fixes #16643.

cc @ryancdotorg.

2020-09-18 11:24 UTC, keszybz commented
I don't think it makes much sense to keep backwards compat for this. If someone wrote a large number (either directly or using a multiplier suffix), this is almost certainly because they were mislead by our faulty documentation. In that scenario they would be better off if we ignored the option, rather than as "honouring" the option in a way that breaks their networking. 

Based on @ryancdotorg linked, 1k would be considered far outside of the realm of useful values. So anything with "k" suffix is already broken, and with "M" even more so. I think we should simply reject any numbers equal to or higher than 1024.

2020-09-29 05:04 UTC, yuwata commented
@keszybz Thank you for the comment, and sorry for late response. Now the value is limited from the above with 1024. And k, M, G suffixes support is dropped. PTAL.

2020-09-29 06:34 UTC, keszybz requested changes

2020-09-29 06:34 UTC, keszybz commented on man/systemd.network.xml
> +            receiving host. Takes a size in bytes between 1 and 1023. Note that 100 is considered an
"Takes a number between 1 and 1023."

2020-09-29 07:06 UTC, yuwata commented
@keszybz Thanks. Updated. Setting the green label.

2020-09-29 10:51 UTC, keszybz commented
bionic-i386 timed out in boot-smoke. Let's assume this is unrelated unless something else fails.

2020-09-30 08:55 UTC, merged