Make MountAPIVFS=yes default
systemd/systemd pull request #17152
Opened 2020-09-24 08:24 UTC by keszybz

Another chunk from #17079.

2020-09-25 13:57 UTC, poettering requested changes

2020-09-25 13:57 UTC, poettering commented on src/core/load-fragment.c
> +int config_parse_exec_mount_apivfs(const char *unit,
we usually line break function headers after the `(` these days

2020-09-25 13:59 UTC, poettering commented
hmm, so this looks good codewise and everything

but i wonder: wouldn't it actually be sufficient to just the flip the default? iirc MountAPIVFS= is a NOP anyway if /proc is already mounted, no? And if that's the case the fact that with this PR MountAPIVFS= remains off by default unless RootImage=/RootDirectory= are set doesn't get us anything, since even if it was on then it wouldn't be doing anything anyway.

or am I confused?

2020-09-25 14:06 UTC, keszybz commented
> but i wonder: wouldn't it actually be sufficient to just the flip the default? iirc MountAPIVFS= is a NOP anyway if /proc is already mounted, no? And if that's the case the fact that with this PR MountAPIVFS= remains off by default unless RootImage=/RootDirectory= are set doesn't get us anything, since even if it was on then it wouldn't be doing anything anyway.

I wanted to keep the possibility to have RootDirectory= with static /proc,/dev. I was thinking about the case how people set up chroots for programs traditionally: create a subdirectory with the binaries and the minimum data files and the minimum device nodes required. The sad truth is that even with hidepid=, /proc exposes waaaay too much information. We'd still support such setups except that people would need to specify MountAPIVFS=false.

2020-09-25 14:31 UTC, poettering commented
But that would still work: just set MountAPIVFS=no, just like in your case.

My suggestion would be: just flip the default to be MountAPIVFS=yes. this would have zero effect if /proc/ and /sys/ are already mounted. And if they aren#t mounted it would mean we'd start mounting them now. But if the user sets =no explicitly we'd not do that either.

See the path_is_mount_point() checks in namespace.c's mount_sysfs(), mount_procfs() and mount_bind_dev(): they have no effect if there's already a mount point in place, which means we can just turn MountAPIVFS= on by default, and thus make it opt-out instead of opt-in.

2020-09-26 19:11 UTC, keszybz commented
Indeed, I don't know why I was trying to make it so complicated.

2020-09-26 19:14 UTC, keszybz commented
One centosci failed in TEST-43-PRIVATEUSER-UNPRIV and the other in TEST-44-LOG-NAMESPACE, probably unrelated.

2020-09-30 12:12 UTC, poettering commented on src/core/mount.c
> +        m->exec_context.mount_apivfs = true;
hmm, actually, this doesn't look right... right now if the bool is set this has the effect that a mount namespace is created... (see exec_needs_mount_namespace()) which we actually don#t want here. (in particular not for mount units...) my bad, sorry for the confusion

I figure we have to have this as two bools after all, my bad. When the bool is unset turn it on but do not enable the namespace logic, when the bool is true enable the namespace logic and turn it off, and when is off do not propagate that to the namespace logic.

2020-09-30 12:13 UTC, poettering commented
I suck, my bad, previous version of the patch was actually more correct I guess. Sorry!

2020-09-30 13:21 UTC, keszybz commented
Reverted to the previous version.

2020-10-01 08:59 UTC, poettering commented on src/core/execute.c
> +        if (c->root_image || !empty_or_root(c->root_directory))
i added #17219 now which should make this a bit prettier

2020-10-01 09:00 UTC, merged