basic/virt: Detect PowerVM hypervisor.
systemd/systemd pull request #17236
Opened 2020-10-02 19:14 UTC by hramrach

Currently systemd-detect-virt fails to detect running under PowerVM.

Add code to detect PowerVM based on code in util-linux.

Signed-off-by: Michal Suchanek <msuchanek@suse.de>

2020-10-03 08:19 UTC, keszybz requested changes
Looks reasonable. But it also needs an update in man/systemd-detect-virt.xml. See for 80cc3e3eabd2cf4e31ae3f0d6e2ac7b61d0a1832 for a recent example that added "proot". Also, if it would be possible, please remove the dot from the commit title.

2020-10-03 08:19 UTC, keszybz commented on src/basic/virt.c
> +                                && access("/proc/device-tree/chosen/qemu,graphic-width", F_OK) != 0)
For consistency with other parts of the code, please align this like this:
```C
                if (access("/proc/device-tree/ibm,partition-name", F_OK) == 0 &&
                    access("/proc/device-tree/hmc-managed?", F_OK) == 0 &&
                    access("/proc/device-tree/chosen/qemu,graphic-width", F_OK) != 0)

```

2020-10-05 15:52 UTC, poettering requested changes

2020-10-05 15:52 UTC, poettering commented on man/systemd-detect-virt.xml
> +          </row>
hmm, actually the "morerows" field a few rows up needs to be updated from 12 to 13, otherwise the formatted table will be improperly aligned.

2020-10-06 06:24 UTC, merged