Make test-ipcrm not fail cryptically
systemd/systemd pull request #17407
Opened 2020-10-20 16:07 UTC by keszybz

2020-10-20 18:01 UTC, poettering requested changes

2020-10-20 18:01 UTC, poettering commented on src/shared/clean-ipc.c
> +                                r = clean_posix_shm_internal(de->d_name, kid, uid, gid, rm);
this doesn't look right. You need to path_join() things here

2020-10-20 18:26 UTC, keszybz commented on src/shared/clean-ipc.c
> +                                r = clean_posix_shm_internal(de->d_name, kid, uid, gid, rm);
Please see the commit message.

2020-10-21 07:03 UTC, poettering commented on src/shared/clean-ipc.c
> +                                r = clean_posix_shm_internal(de->d_name, kid, uid, gid, rm);
still sloppy... ;-)

2020-10-21 07:04 UTC, merged