RFC: clean up failed {service|scope}'s cgroups when the last process exits
systemd/systemd pull request #17422
Opened 2020-10-23 06:18 UTC by anitazha

So you have a service/scope and one of its processes is stuck in D state.
The unit is sent a `systemctl stop` and the process is sent the SIGTERM
then SIGKILL. It doesn't respond and after `TimeoutStopSec` the unit is
marked as failed because it times out while processes are still around.
The unit's cgroup remains in the file system (for example,
`/system.slice/test.service`).

When the process comes out of D state it processes the signals and exits.
Pid1 gets the SIGCHLD and tries to figure out what unit this process belongs
to based on what cgroup it's in, but since the unit's cgroup path information
was released earlier, pid1 thinks the process belongs to the unit's parent
(from the previous example, pid1 thinks the process belongs to system.slice).
This parent cgroup probably has many subgroups and processes under it
and cannot be removed, leaving the initial `/system.slice/test.service`
there until something is started and stopped under it again or
`system.slice` is stopped.

D state is one example but this happens to any process that happens to
stick around after the final kill signal state.

The fix I'm proposing is to keep the unit's cgroup path information
around if pid1 fails to `rmdir` the cgroup. When the last process exits
and sends the cgroup empty notification, the service/scope can try to
prune the cgroup if the unit is marked as failed.

2020-10-23 06:21 UTC, anitazha commented
I *think* this might help with #16350 but I only tested minimally with cgroups2

2020-10-23 13:40 UTC, poettering commented
Hmm, I'd do this differently. Maybe introduce `unit_maybe_release_cgroup()`. which is a wrapper around `unit_release_cgroup()` and checks if the cgroup is actually empty first. If it's not it returns immediately, otherwise it calls the real function.

Calling that function should then be safe and robust from pretty much any suitable place.

2020-10-24 01:14 UTC, anitazha commented
Updated with a wrapper. But I think it's only applicable in `unit_prune_cgroup` where my original check was; the other 2 uses don't use the wrapper because the cgroup should be released regardless of whether it is empty or not (they're `unit_free` and `unit_set_cgroup_path`).

2020-10-26 09:40 UTC, poettering requested changes

2020-10-26 09:40 UTC, poettering commented on src/core/cgroup.c
> +}
this functin should probably return 1 if it actually did something, and 0 if not.

That way callers will know if anything was released

2020-10-26 09:40 UTC, poettering commented on src/core/cgroup.c
> +                return log_unit_debug_errno(u, r, "Error checking if the cgroup is recursively empty, ignoring: %m");
i'd really eat up the error here (though debug log about it, as you do) and then proceed as if the cgroup wasn't empty

2020-10-26 09:40 UTC, poettering commented on src/core/cgroup.c
> +        (void) unit_maybe_release_cgroup(u);
if the cgroup was not actually released the rest of the function should not be processed either I guess. Hence, taking my suggestion further up into account, maybe change this to:

```c
if (unit_maybe_release_cgroup(u) <= 0) /* Returns > 0 if the cgroup was pruned */
        return;
```

2020-10-26 09:40 UTC, poettering commented on src/core/service.c
> +                unit_prune_cgroup(u);
should really have a "break" here. Or  a `_fallthrough_`, but that would be weird

2020-10-27 00:58 UTC, anitazha commented
Updated according to comments

2020-10-27 07:40 UTC, keszybz commented
LGTM.

2020-10-27 08:02 UTC, poettering commented
lgtm, too

2020-10-27 12:20 UTC, merged