manager: always store watchdog timeout, even if watchdog is not ready
systemd/systemd pull request #17460
Opened 2020-10-27 07:47 UTC by danc86

Commit 986935cf ("pid1: update manager settings on reload too")
introduced this new logic, which discards any attempt to set the
runtime watchdog timeout if watchdog_set_timeout() reported an error.
That can happen if /dev/watchdog does not exist or is not working.

But there is an important situation where /dev/watchdog may not exist:
if it is provided by a kernel module that is loaded late in
boot, after pid 1 has loaded its configuration, the
watchdog_set_timeout() call may return an error but the watchdog still
would have been opened successfully on the next ping.

When RuntimeWatchdogSec= is loaded on first boot, or set via DBus, we
need to store the new timeout regardless whether /dev/watchdog exists
and is operational, or not. This restores the previous behaviour from
systemd < v246.

2020-10-27 08:41 UTC, poettering requested changes
So this doesn't look right. Watchdog hw/drivers typically don't support all possible timeouts, but just a few discrete choices. Hence we have to set the timeout to some value, which the driver then finds a close approximation for, and read it back to see what the actually configured timeout was. The resulting timeout we then need to take into account for pinging the device regularly enough. That's why watchdog_set_timeout() takes a pointer to a timeout instead of a literal value, it is both an input *and* output parameter. The updated timeout is stored in `m->watchdog[]` and `m->overriden_watchdog[]`. 

This propagation step from the hw back to the two array fields is also necessary when we start using a device later on, that wasn't available at first. And that's missing right now.

2020-10-27 08:41 UTC, poettering commented on src/core/manager.c
> +                                watchdog_set_timeout(&timeout);
given that we actively ignore the return code, please cast result explicitly to `(void)`

2020-10-27 08:41 UTC, poettering commented on src/core/manager.c
> +                        watchdog_set_timeout(p);
as above

2020-12-07 10:09 UTC, keszybz commented
@danc86 another round?

2020-12-08 04:42 UTC, yuwata commented
Replaced by #17895.

2020-12-08 04:42 UTC, closed without merging