network: selinux hook handling to enumerate nexthop
systemd/systemd pull request #17480
Opened 2020-10-28 17:15 UTC by purushottamc

When selinux is enabled, the call of
manager_rtnl_enumerate_nexthop() fails.

This fix is to facilitate selinux hook handling for
enumerating nexthop.

In manager_rtnl_enumerate_nexthop() there is a check
if "Not supported" is returned by the send_netlink() call.
This check expects that -EOPNOTSUPP is returned,
the selinux hook seems to return -EINVAL instead.

Thus adding a call in the manager_rtnl_enumerate_nexthop
for the extra reutrn -EINVAL.

2020-10-28 18:08 UTC, yuwata requested changes
Please mention in the commit message that kernel older than 5.3 (more specifically https://github.com/torvalds/linux/commit/65ee00a9409f751188a8cdc0988167858eb4a536) does not support nexthop handling through netlink. And if SELinux is enforced in the order kernel, calling `RTM_GETNEXTHOP` returns -EINVAL.

2020-10-28 18:08 UTC, yuwata commented on src/network/networkd-manager.c
> +                log_debug("sd_netlink_call failed to get nexthop: return value = %d \n", r);
Please drop this line, as `manager_enumerate_internal()` is also used for enumerating other properties e.g., address.

2020-10-28 18:08 UTC, yuwata commented on src/network/networkd-manager.c
> +                if ((r == -EOPNOTSUPP || r == -EINVAL) && name) {
Please ignore `-EINVAL` only when SELinux is enforcing.
```
if (name && (r == -EOPNOTSUPP || (r == -EINVAL && mac_selinux_enforcing()))) {
```

2020-10-29 09:00 UTC, poettering commented
hmm, let me get this right? this is a bug in the selinux code in kernel? shouldn't this be fixed in the kernel instead?

2020-10-30 00:22 UTC, yuwata requested changes
Please include selinux-util.h.

2020-10-30 00:29 UTC, yuwata commented
@poettering
> hmm, let me get this right? this is a bug in the selinux code in kernel? shouldn't this be fixed in the kernel instead?

SELinux denies unknown netlink command with `-EINVAL`.
See https://github.com/torvalds/linux/blob/726eb70e0d34dc4bc4dada71f52bba8ed638431e/security/selinux/hooks.c#L5868-L5883.
The netlink nexthop commands are added in kernel 5.3. So, SELinux enabled older kernel returns `-EINVAL` there.

2020-10-30 10:47 UTC, yuwata requested changes

2020-10-30 10:47 UTC, yuwata commented on src/network/networkd-manager.c
> +#include "selinux-util.h"
Please sort the header alphabetically.

2020-10-30 10:57 UTC, yuwata approved these changes
LGTM.

2020-10-30 12:05 UTC, keszybz commented
centosci (arch linux + sanitizers): `12:41:26 ...'vagrant ssh' exited with an unexpected EC: 255`. No idea what failed there.

2020-10-31 11:05 UTC, purushottamc commented
Hi @yuwata 

Thanks for your help
when you are planning to merge this change?

2020-11-01 14:28 UTC, merged

2020-11-01 14:28 UTC, yuwata commented
@purushottamc Sorry for late merge. But it was week end :-)