seccomp: don't install filters for archs that can't use syscalls
systemd/systemd pull request #17483
Opened 2020-10-29 00:06 UTC by greg904

Stop installing filters for architectures that already can't use
syscalls because they were disabled using the SystemCallArchitecture=
options. This speeds up boot because libseccomp can be slow.

2020-10-29 10:10 UTC, poettering requested changes

2020-10-29 10:10 UTC, poettering commented on src/shared/seccomp-util.c
> +                SCMP_ARCH_X32         /* native */
please leave the comma in. Since a long time a trailing comma is actually fine in C

2020-10-29 10:10 UTC, poettering commented on src/shared/seccomp-util.c
> -                (uint32_t) -1
i'd leave this EOL marker in, it's simpler that way, i.e. drop the `seccomp_local_archs_len` variable below.

Of course that means we need two different markers now: EOL and "disabled". I'd continue using `UINT32_MAX` (aka `(uint32_t) -1` as EOL marker, and use `0` (aka `SCMP_ARCH_NATIVE`) as "disabled" marker. That should be safe, given that we don't use `SCMP_ARCH_NATIVE` here in this context, as we want to list literal archs only, not the pseudo-arch `SCMP_ARCH_NATIVE`.

2020-10-29 10:10 UTC, poettering commented on src/shared/seccomp-util.c
> +const size_t seccomp_local_archs_len = sizeof(seccomp_local_archs) / sizeof(seccomp_local_archs[0]);
there's the ELEMENTSOF() macro for cases like this btw. But as pointed out above, I'd just drop this and use two distinct markers for EOL and "disabled" in the array above, to simplify things.

2020-10-29 10:10 UTC, poettering commented on src/shared/seccomp-util.c
>           * The important thing is that you can block the old 32-bit x86 syscalls.
the seccomp_arch_add() loop here should also take the `seccomp_local_archs[]` array into account and skip blocking the archs that are already blocked. After all, it's quite likely we call seccomp_restrict_archs() twice: once in PID 1 for PID 1 itself and then possibly in various childrens to further restrict things. For example, PID 1 might block x32 already, since mostly obsolete. And then various services might block both x32 and i386, leaving only the native arch x86_64.

Hence it makes sense to not filter x32 twice.

Also, there should be an early exit here if it is noticed that the seccomp program put together here is actually empty because all archs blocked here were already blocked before.

2020-10-29 16:32 UTC, greg904 commented
Thank you for the review. I think I fixed the issues in the comments.

The tests don't pass. I don't understand where the logic is wrong.

2020-12-05 19:55 UTC, greg904 commented
For some reason I reran the tests on my PC and now they are passing. I must have done something incorrectly previously... I guess I can mark the PR as ready now.

2020-12-07 21:52 UTC, bluca commented
bionic-i386 is the usual timeout anc CentOS/Arch failed in networkd, which seems unrelated. Waiting for @poettering to see if he's happy with the modifications since his first review.

2020-12-10 15:13 UTC, merged