udev: Add support to configure Generic Segment Offload
systemd/systemd pull request #17628
Opened 2020-11-16 16:57 UTC by ssahani

2020-11-16 19:55 UTC, yuwata reviewed
I am not sure but maybe these settings should be moved to .link file, instead of .network file.

2020-11-16 19:55 UTC, yuwata commented on src/network/networkd-network.h
> +        uint32_t gso_max_size;
`config_parse_iec_size()` takes `size_t`. Please use `size_t` for `gso_max_size`.

2020-11-16 20:00 UTC, yuwata commented on src/network/networkd-network-gperf.gperf
> +Link.GenericSegmenOffloadMaxBytes,           config_parse_iec_size,                                    0,                             offsetof(Network, gso_max_size)
Segmen -> Segment

2020-11-16 23:23 UTC, ssahani commented
> I am not sure but maybe these settings should be moved to .link file, instead of .network file.

These are same as group/multicast/allmulticast etc. Hence it should be here. Thanks for the review .ptal

2020-11-17 01:21 UTC, yuwata commented
> > I am not sure but maybe these settings should be moved to .link file, instead of .network file.
> 
> These are same as group/multicast/allmulticast etc. Hence it should be here. Thanks for the review .ptal

In what sense "these are the same"? .link file already has `GenericSegmentationOffload=` boolean setting. Does the setting have no correspondence to the new settings?

2020-11-17 01:34 UTC, ssahani commented
> In what sense "these are the same"? .link file already has `GenericSegmentationOffload=` boolean setting. Does the setting have no correspondence to the new settings?

`.link` file turns on the tx-generic-segmentation feature. Here  are setting 

gso_max_size:  Maximum size of generic segmentation offload
gso_max_segs:  Maximum number of segments that can be passed to the NIC for GSO

What is your confusion ?

2020-11-17 02:02 UTC, yuwata commented
> > In what sense "these are the same"? .link file already has `GenericSegmentationOffload=` boolean setting. Does the setting have no correspondence to the new settings?
> 
> `.link` file turns on the tx-generic-segmentation feature. Here are setting
> 
> gso_max_size: Maximum size of generic segmentation offload
> gso_max_segs: Maximum number of segments that can be passed to the NIC for GSO
> 
> What is your confusion ?

I do not have enough knowledge about them. So, please let me know. Are these options corresponding to each other? E.g., what happens if `tx-generic-segmentation` is disabled? Are `gso_max_size` and `gso_max_segs` ignored in that case? Or these `gso_max` settings are independent of `tx-generic-segmentation`?

2020-11-17 02:15 UTC, ssahani commented
>I do not have enough knowledge about them. So, please let me know. Are these options corresponding to each other? E.g., what happens if tx-generic-segmentation is disabled? Are gso_max_size and gso_max_segs ignored in that case? Or these gso_max settings are independent of tx-generic-segmentation?

```GenericSegmentationOffload=``` I should have written offload . It means  physical device’s TX offloading capabilities.  Device driver can offload or not. Not like `tx-generic-segmentation` off.  As per I know gso_max_size and gso_max_segs will *not* be ignored.

2020-12-11 16:52 UTC, ssahani commented
Cc @bluca

2020-12-16 11:14 UTC, bluca commented
Needs rebase.

Regarding where to place the setting, I think the current approach makes sense: tx-generic-segmentation/GenericSegmentationOffload are like other settings managed via ethtool in the old ways - they are device driver settings, so they get configured by udev.
gso_max_size/segs on the other hand are interface settings, manged via iproute2, so it makes sense that they handled by networkd.

At least this is my understanding from looking at ethtool/iproute2 interfaces and documentation about the features. I have not looked at the kernel code.

2020-12-16 11:33 UTC, ssahani commented
rebased thanks fir the review.

2021-01-10 06:14 UTC, yuwata commented
Still I am not sure this should be added to .network or .link. But, at least, please rebase this PR.

2021-01-11 09:56 UTC, ssahani commented
rebased ptal thanks !

2021-01-12 11:27 UTC, poettering commented
This really looks like something that should be in .link, not .network

I mean the effect of this is not really visible to the network is it? It's an implementation detail of the server that should be invisble outside? If that's the case then it should be a .link option, not a .network one.

2021-01-12 11:28 UTC, poettering commented
(i mean, the line between what belongs in .network and what in .link is blurry, and there are options belonging in both ultimately, because they are a property of the local hw that has effects on the network, but as I understand GSO it's primarily an implementation detail locally with no visibility outside of the local machine hence in this case it appears pretty clear to me this falls onto the .link side to me)

2021-01-12 13:40 UTC, ssahani commented
updated thanks for the review. ptal

2021-01-12 14:02 UTC, yuwata requested changes
Mostly ok. Several nitpicks.

2021-01-12 14:02 UTC, yuwata commented on src/udev/net/link-config-gperf.gperf
> +Link.GenericSegmentOffloadMaxSegments, config_parse_uint32,                   0,                             offsetof(link_config, gso_max_segments)
Please add a line break at the end of the file.

2021-01-12 14:02 UTC, yuwata commented on test/fuzz/fuzz-link-parser/directives.link
> +GenericSegmentOffloadMaxSegments=
Please merge the last commit with the previous.

2021-01-12 14:40 UTC, yuwata approved these changes

2021-01-12 20:42 UTC, merged