sd-device-enumerator: do not return error when a device is removed
systemd/systemd pull request #17660
Opened 2020-11-19 01:53 UTC by iplayinsun

If /sys/class/OOO node is created and destroyed during booting (kernle driver initialization fails),
systemd-udev-trigger.service fails due to race condition.

***** race condition ***********************************************************************************
 1. kernel driver create /sys/class/OOO
 2. systemd-udev-trigger.service execues "/usr/bin/udevadm trigger --type=devices --action=add"

 3. device_enumerator_scan_devices() => enumerator_scan_devices_all() => enumerator_scan_dir("class") =>
    opendir("/sys/class") and iterate all subdirs ==> enumerator_scan_dir_and_add_devices("/sys/class/OOO")

 4. kernel driver fails and destroy /sys/class/OOO
 5. enumerator_scan_dir_and_add_devices("/sys/class/OOO") fails in opendir("/sys/class/OOO")

 6. "systemd-udev-trigger.service" fails
 7. udev coldplug fails and some device units not ready
 8. mount units asociated with device units fail
 9. local-fs.target fails
 10. enters emergency mode
********************************************************************************************************

***** status of systemd-udev-trigger.service unit ******************************************************
$ systemctl status systemd-udev-trigger.service
 systemd-udev-trigger.service - udev Coldplug all Devices
   Loaded: loaded (/usr/lib/systemd/system/systemd-udev-trigger.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-01-02 13:16:54 KST; 22min ago
     Docs: man:udev(7)
           man:systemd-udevd.service(8)
  Process: 2162 ExecStart=/usr/bin/udevadm trigger --type=subsystems --action=add (code=exited, status=0/SUCCESS)
  Process: 2554 ExecStart=/usr/bin/udevadm trigger --type=devices --action=add (code=exited, status=1/FAILURE)
  Main PID: 2554 (code=exited, status=1/FAILURE)

  Jan 02 13:16:54 localhost udevadm[2554]: Failed to scan devices: No such file or directory
  Jan 02 13:16:54 localhost systemd[1]: systemd-udev-trigger.service: Main process exited, code=exited, status=1/FAILURE
  Jan 02 13:16:54 localhost systemd[1]: systemd-udev-trigger.service: Failed with result 'exit-code'.
  Jan 02 13:16:54 localhost systemd[1]: Failed to start udev Coldplug all Devices.
*******************************************************************************************************

***** journal log with Environment=SYSTEMD_LOG_LEVEL=debug in systemd-udev-trigger.service  ***********
  Jan 01 21:57:20 localhost udevadm[2039]: sd-device-enumerator: Scanning /sys/bus
  Jan 01 21:57:20 localhost udevadm[2522]: sd-device-enumerator: Scan all dirs
  Jan 01 21:57:20 localhost udevadm[2522]: sd-device-enumerator: Scanning /sys/bus
  Jan 01 21:57:21 localhost udevadm[2522]: sd-device-enumerator: Scanning /sys/class
  Jan 01 21:57:21 localhost udevadm[2522]: sd-device-enumerator: Failed to scan /sys/class: No such file or directory
  Jan 01 21:57:21 localhost udevadm[2522]: Failed to scan devices: No such file or directory
*******************************************************************************************************

2020-11-19 07:53 UTC, yuwata requested changes
Instead of ignoring the return value here, but please ignore `ENOENT` after `opendir()` in `enumerator_scan_dir_and_add_device()`:
```
dir = opendir(path);
if (!dir)
        /* this is necessarily racey, so ignore missing directories */
        return errno == ENOENT ? 0 : -errno;
```

2020-11-19 11:33 UTC, iplayinsun commented
The enumerator_scan_dir_and_add_device() is also called in device_enumerator_scan_subsystems().
At enumerator_scan_dir_and_add_device(), we should check if "/sys/module" exists or not.

`
int device_enumerator_scan_subsystems(sd_device_enumerator *enumerator) {
....
        /* modules */
	if (match_subsystem(enumerator, "module")) {
                k = enumerator_scan_dir_and_add_devices(enumerator, "module", NULL, NULL);
                if (k < 0) {
                        log_debug_errno(k, "sd-device-enumerator: Failed to scan modules: %m");
                        r = k;
		}
	}
`

2020-11-19 16:43 UTC, yuwata commented
Hmm? Sorry, I cannot catch what you want to say. Could you elaborate more?

2020-11-19 16:54 UTC, yuwata commented
Note that we already do the similar check in `enumerator_scan_devices_tag()`.

2020-11-20 06:08 UTC, iplayinsun commented
Sorry for the brief explanation.

If we apply the code you suggested has one error handling issue.

If we do not apply any patch and  "/sys/module" does not  exist, 
device_enumerator_scan_subsystems() will fail with "sd-device-enumerator: Failed to scan modules: No such file or directory".

**The related code in device_enumerator_scan_subsystems()**  
```
device_enumerator_scan_subsystems() {
   .....

            /*  It wil fail if "/sys/module" does not exist. */
            k = enumerator_scan_dir_and_add_devices(enumerator, "module", NULL, NULL);  
            if (k < 0) {              
                    log_debug_errno(k, "sd-device-enumerator: Failed to scan modules: %m");
                    r = k;
            }
```

The code you suggested will recognize this error condition **as normal**.

I don't know what to do when "/sys/module" does not exist.

P.S. There are the same situations for "/sys/subsystem" and "/sys/bus".

2020-11-20 07:48 UTC, yuwata commented
These directories should always exist, and if one of them does not exist, then the subsequent `enumerator_scan_dir()` below should be failed. So, I think it is OK to ignore ENOENT in `enumerator_scan_dir_and_add_devices()`.
```
/* subsystem drivers */
        if (match_subsystem(enumerator, "drivers")) {
                k = enumerator_scan_dir(enumerator, subsysdir, "drivers", "drivers");
                if (k < 0) {
                        log_debug_errno(k, "sd-device-enumerator: Failed to scan drivers: %m");dir = opendir(path);
if (!dir)
        /* this is necessarily racey, so ignore missing directories */
        return errno == ENOENT ? 0 : -errno;

                        r = k;
                }
        }
```
Or, how about the following:
```
dir = opendir(path);
if (!dir)
        /* this is necessarily racey, so ignore missing directories */
        return (errno == ENOENT && (subdir1 || subdir2)) ? 0 : -errno;
```
Then, the calls you concern correctly fail when the directories do not exist.

2020-11-20 10:09 UTC, iplayinsun commented
I've uploaded the new patch you mentioned. 

The first patch you suggest is simple and good.
But I prefer code that tells us the exact location when an error occurs.
Although it is a bit more complicated.

Thanks

2020-11-24 12:38 UTC, merged