man: mention that "systemctl disable" on statically enabled units is not supported
systemd/systemd pull request #17695
Opened 2020-11-23 07:55 UTC by yuwata

Closes #17689.

2020-11-23 19:29 UTC, floppym commented
Is the term "statically enabled" defined anywhere? How would the average user know what that means?

2020-11-25 06:22 UTC, yuwata commented
Yeah, 'statically enabled' is not a good words to explain the state of e.g. systemd-modules-load.service. Thanks.

2020-11-25 09:05 UTC, keszybz requested changes
Oh, I started a review but never posted it.

2020-11-25 09:05 UTC, keszybz commented on man/systemctl.xml
> +            Please use <command>mask</command> instead.</para>
There's a multitude of problems here. The existing description is vague and partially incorrect, and the UX here is pretty bad, and we need a proper fix not a tiny bandaid.

1. This clarification needs to be part of the first paragraph, where we describe in general terms that the command does. 
2. > Using disable on statically enabled units is not supported

Actually, this is wrong. `systemctl disable` is perfectly happy to remove symlinks to such units, e.g. from /etc. Instead, it seems it will not remove symlinks in /usr/lib. (I didn't look at the code recently, so please verify.)

3. We should not recommend `mask`, because `mask` has usability issues. If a unit is statically enabled in /usr/lib, that means that most likely it cannot be safely disabled. We shouldn't recommend overriding that distributor choice to users blindly. Instead, most likely, either the unit should not be disabled, or the packaging should be changed so it has an [Install] section.

4. While at it, maybe say "This removes symlinks to the unit file from the unit configuration directory, ..." instead of "This removes all symlinks to the unit files backing the specified units from the unit configuration directory, ...". All that additional verbosity doesn't help.

A bigger issue is the success return value if there's nothing to be done. I think we should at least emit a warning when the unit is symlinked in /usr/lib that we're ignoring those links. We already emit a big warning when calling `enable` on units without [Install], and I think we should have something symmetric here.

2020-11-25 10:31 UTC, TriMoon commented on man/systemctl.xml
> +            Please use <command>mask</command> instead.</para>
Isn't it more intuitive from the user's pov. to mask statically enabled units in `/usr/lib` when using `disable`?
Ofcourse it could cause some problems for some units provided by the packager, but hey the user (administrator) of the system should have the last word and decision on these matters.
So if the admin executes `disable` (s)he **wants** it to stop activating after all by own choice...

2022-11-27 12:07 UTC, keszybz commented
I hope https://github.com/systemd/systemd/pull/25437 will get merged. Let's close this one.

2022-11-27 12:07 UTC, closed without merging