pager: stop disabling urlification under a pager
systemd/systemd pull request #17776
Opened 2020-11-30 09:20 UTC by keszybz

Less 568 properly shows urlified strings.

Putative NEWS entry:
* Urlification is now enabled by default even when a pager is used.
  Previously it was disabled, because less would not show such markup
  properly. This has been fixed in less 568.
  Please either upgrade less, or use SYSTEMD_URLIFY=0 to disable the
  feature.

2020-11-30 10:44 UTC, yuwata commented
LGTM. If you like, it is better to include the NEWS entry within this PR?

2020-11-30 11:13 UTC, keszybz commented
I started including NEWS entries within commit messages. That way whoever is arranging NEWS can easily paste the text into NEWS, since they are going over the commit list anyway and have easy access to the commit message. This way we avoid merge conflicts, but also we might tweak the behaviour before the release, and it's better to avoid churn in the NEWS file and even more conflicts.

2020-12-01 14:22 UTC, poettering requested changes

2020-12-01 14:22 UTC, poettering commented on src/shared/pretty-print.c
> +                        cached_urlify_enabled = colors_enabled();
the comment a few lines up also needs some updating/removal.

2020-12-01 20:24 UTC, keszybz commented
I dropped the comment. I don't see much point in talking about old less versions in our code base.

2020-12-02 07:45 UTC, poettering commented
makes sense! lgtm

2020-12-02 07:50 UTC, yuwata commented
Ubuntu CIs seems broken in timedated test. cc @mbiebl ?

The failures are not related. Merging.

2020-12-02 07:50 UTC, merged

2020-12-02 13:39 UTC, mbiebl commented
Am Mi., 2. Dez. 2020 um 08:50 Uhr schrieb Yu Watanabe <
notifications@github.com>:

> Ubuntu CIs seems broken in timedated test. cc @mbiebl
> <https://github.com/mbiebl> ?
>
Unfortunately, I have no idea why it fails.