mkosi: Add gdb to final images
systemd/systemd pull request #17869
Opened 2020-12-06 11:44 UTC by DaanDeMeyer

Let's add a debugger to the mkosi images so we can debug coredumps
from inside mkosi qemu VMs (and hopefully in the future from
mkosi systemd-nspawn containers as well).

2020-12-07 09:22 UTC, keszybz commented
Shouldn't this be done when appropriate using `--package=gdb` instead?

2020-12-07 11:00 UTC, DaanDeMeyer commented
Having to add it manually leads to users starting the qemu vm, encountering a segmentation fault in one of the tools, trying to run gdb on the coredump and then finding out gdb isn't installed. Installing it by default makes things "just work". We probably shouldn't do this for everything but a debugger seems core enough that we can add it by default.

2020-12-07 11:46 UTC, keszybz commented
Yeah, but how often will that be used? `dnf install --setopt install_weak_deps=False gdb` over an empty installation of F34 wants to add `Installed size: 158 M`. Is that worth it?

2020-12-07 12:06 UTC, DaanDeMeyer commented
Installed size for development images shouldn't really matter too much though right? We should also be looking at the diff in size between images with and without gdb instead of over an empty Fedora image. I'd also look more at how much extra time is needed to build the images with gdb included and maybe extra overhead in package download size.  I'll do some measurements and report back.

2020-12-07 22:56 UTC, DaanDeMeyer commented
Fedora image without gdb:

```
Executed in  126.10 secs   fish           external 
   usr time   58.08 secs  740.00 micros   58.08 secs 
   sys time   14.88 secs  233.00 micros   14.88 secs 

Installed size: 743.0M
```

Fedora image with gdb:

```
Executed in  136.57 secs   fish           external 
   usr time   63.43 secs    0.00 micros   63.43 secs 
   sys time   16.66 secs  1150.00 micros   16.66 secs 

Installed size: 856.3M
```

So indeed 110M increase in installed size and 10 extra seconds to build the image. The 10 extra seconds seem a lot but it's generally recommended to use cached images so I don't find this too bad. I personally don't mind the extra disk space used. If It's too big of a problem, I'll need to add config dropin support to mkosi so systemd's images can be augmented with local config files more easily than is possible today.

2020-12-08 09:02 UTC, keszybz commented
I'd be inclined to merge this... Does anyone else have an opinion?

2020-12-09 12:49 UTC, poettering requested changes
so I keep running into this all the time too. I'd be even more interested in strace though...

would be fine to merge like htis, but needs rebase, and package lists should be ordered alphabetically

2020-12-09 12:49 UTC, poettering commented on .mkosi/mkosi.opensuse
> +        gdb
please keep ordered alphabetically

2020-12-09 17:31 UTC, DaanDeMeyer commented
Rebased and added a second commit that adds strace as well.

2020-12-09 17:32 UTC, poettering commented
lgtm

2020-12-09 20:10 UTC, merged