udev-builtin-blkid: add VOLUME_SET_ID and DATA_PREPARER_ID
systemd/systemd pull request #17925
Opened 2020-12-10 11:31 UTC by karelzak

The new libblkid release will provide these variables. Let's keep is
accessible also from udev-db for the rest of the system.

The variables have been added to libblkid by https://github.com/karelzak/util-linux/pull/1215/commits/5cbffdb74f6fec51b2cf260bea66375823fe65e7

2020-12-10 11:58 UTC, poettering requested changes

2020-12-10 11:58 UTC, poettering commented on src/udev/udev-builtin-blkid.c
> +                udev_builtin_add_property(dev, test, "DATA_PREPARER_ID", s);
no ID_FS prefix?

2020-12-10 11:58 UTC, poettering commented
What are these two props btw? which fs are they from?

2020-12-11 09:20 UTC, karelzak commented
Fixed, and I have added another two missing variables. 

> What are these two props btw? which fs are they from?

These identifiers are from iso9660 and UDF ... so stuff to describe CD/DVDs. Maybe @pali knows more details about how these identifiers are used by media produces.

2020-12-11 10:34 UTC, pali commented
Yes, those identifiers and from iso9660 and udf filesystems. As you know iso9600 is used on CD/DVDs and udf on any kind of media (optical, hard disk, removable flash, ...). As udf is designed as universal (udf = universal disk format) it contains lot of identifiers.

Imagine that you have data files which are very big and cannot be stored on one (udf) harddisk. Therefore you store them on more hard disks. To mark hard disks that they belongs together you set same _volume set identifier_ on all of them. Each of these hard disks in one volume set should have differet _volume identifier_. And now imagine that you have too many hard disks with same _volume set identifier_ and you want to logical mark some data to distinguish (or to create second hierarchy). And for this purpose there is _logical volume identifier_ which is same across all hard disks which have same logical data. Formally it can be said that _volume set_ consists of _volumes_ and data itself are stored in _logical volumes_ which spans one or more _volume_ (of the same _volume set_). Therefore on udf filesystem you have 3 identifiers: volume set, volume and logical volume. All these identifiers are stored in UNICODE and therefore are human readable.

udf specification for _logical volume identifier_ says: _This name is typically what is displayed to the user._ And therefore all udf implementations exports this identifier as standard system label.

In iso9660 which is used on CD/DVDs there is similar situation. Just you have only _volume identifier_ and _volume set identifier_. _volume identifier_ is system label and describe one CD/DVD. _volume set identifier_ then describe to which "set" this one CD/DVD belongs.

2020-12-11 14:38 UTC, poettering commented
lgtm

2020-12-12 04:21 UTC, merged