networkd: add RouteDenyList
systemd/systemd pull request #17983
Opened 2020-12-15 06:08 UTC by devonpringle9

Allow configuration for IPv6 discovered routes to be ignored instead of
adding them as a route. This can be used to block unwanted routes, for
example, you may wish to not receive some set of routes on an interface
if they are causing issues.

2020-12-15 06:41 UTC, yuwata requested changes
Looks mostly good. Several minor comments.

2020-12-15 06:41 UTC, yuwata commented on src/network/networkd-ndisc.c
> +
Please move the above logic to `ndisc_router_process_route()`.

2020-12-15 06:41 UTC, yuwata commented on src/network/networkd-ndisc.c
> +                if (set_contains(network->ndisc_deny_listed_route_prefix, &ip.in6))
I do not think this is necessary, as set_ensure_put() below handles the case correctly.

2020-12-15 06:41 UTC, yuwata commented on src/network/networkd-ndisc.c
> +                        return log_oom();
Then, do TAKE_PTR() only when r > 0.

2020-12-15 06:42 UTC, yuwata commented
Also, please update fuzzer's directives.

2020-12-15 17:02 UTC, yuwata requested changes

2020-12-15 17:02 UTC, yuwata commented on src/network/networkd-ndisc.c
> +int config_parse_ndisc_deny_listed_route_prefix(
Ah, I noticed you copied `config_parse_ndisc_deny_listed_prefix()`. Could you merge the two functions?

2020-12-15 17:02 UTC, yuwata commented on src/network/networkd-network-gperf.gperf
> +IPv6AcceptRA.RouteDenyList,                  config_parse_ndisc_deny_listed_route_prefix,              0,                             0
Then, setting the correct offset here.

2020-12-18 09:01 UTC, yuwata commented
OK. I've pushed a revised version.

2020-12-18 09:27 UTC, ssahani commented
@yuwata we can add route allow list here too. I mean another patch

2020-12-18 09:31 UTC, yuwata commented
Let's do that later...

2020-12-18 09:45 UTC, devonpringle9 commented
Thank you for pushing this along, I was struggling with a couple of the comments.

2020-12-18 12:44 UTC, merged