meson: Use configure_file when version-tag is specified
systemd/systemd pull request #18192
Opened 2021-01-10 12:35 UTC by DaanDeMeyer

vcs_tag() is slow. When the version-tag meson option is set,
we can use configure_file() directly to speed up incremental
builds.

Before (with version-tag set to v247):

```
‣ Running build script...
[1/418] Generating version.h with a custom command

real    0m0.521s
user    0m0.229s
sys     0m0.067s
```

After (with version-tag set to v247):

```
‣ Running build script...
ninja: no work to do.

real    0m0.094s
user    0m0.048s
sys     0m0.022s
```

2021-01-10 13:38 UTC, DaanDeMeyer commented
Added a second commit that uses a fixed version-tag when in developer mode so builds made in development mode can automatically take advantage of the speedups made possible by using a fixed version-tag.

2021-01-10 14:34 UTC, bluca commented
Do we need a new option, if the build mode is used?

2021-01-11 04:19 UTC, yuwata commented on meson.build
> +                version_tag = 'v@0@-dev'.format(meson.project_version().to_int() + 1)
`+ 1` for version here causes something strange after we release RC version, that is, after v248-rc1 is released, the tag becomes `v249-dev`. I think `+ 1` should be dropped.

2021-01-11 07:35 UTC, fbuihuu commented
> Added a second commit that uses a fixed version-tag when in developer mode so builds made in development mode can automatically take advantage of the speedups made possible by using a fixed version-tag.

That 's quite surprising because having an accurate version in development mode is very useful (actually I would have said that it's been introduced for that purpose). Having the info of which commit in my devel branch I'm testing is helpful, much more than optimizing git bisection sessions that I seldomly do. 

Also you're likely to rebuild a big part of the sources when bisecting (unless you're switching between 2 close commits but that's unlikely until you reach the end of bisect session) no ?

Anyways can we make this optional for the development mode ?

Or maybe drop the second commit and use the fixed version-tag when you do bisection ?

2021-01-11 11:03 UTC, mbiebl commented
> That 's quite surprising because having an accurate version in development mode is very useful (actually I would have said that it's been introduced for that purpose). Having the info of which commit in my devel branch I'm testing is helpful, much more than optimizing git bisection sessions that I seldomly do.

I agree. TBH, when building / bisecting systemd, those 400ms are the least of my worries.

2021-01-11 17:25 UTC, poettering commented
i don't have a strong opinion on this.I did notice that this was slow before those, and I think speedy builds actually do matter, to make contributions easy. Would love @keszybz's take on this.

I'd be fine with conditionalizing this on development mode or not. I must say I personally never used the fact that the version carries the git commit id for anything...

2021-01-11 17:26 UTC, poettering commented
you could also give this a meson option of its own, with yes/no/auto, and where auto means = derive it from development mode

2021-01-11 18:46 UTC, DaanDeMeyer commented
> you could also give this a meson option of its own, with yes/no/auto, and where auto means = derive it from development mode

I had the idea to give `version-tag=auto` the special meaning to use the current meson project version as the version tag. That seems like it would be sufficient so we don't need a completely new option for this. Of course I'd prefer this to be the default but that might be a bit of a stretch. 

> I'd be fine with conditionalizing this on development mode or not. I must say I personally never used the fact that the version carries the git commit id for anything...

Same for me. But this does not seem to be universal as @fbuihuu and @mbiebl's comments show (and I assume @keszybz since he added this in the first place).

2021-01-14 10:29 UTC, bluca commented
I'd love to speed up builds after rebases, as it would make my dev experience much better, as I'm constantly switching and rebasing very similar branches. Of course wouldn't want to cause issues for other use cases, so an extra build option would be fine for me.

2021-01-15 10:00 UTC, keszybz requested changes
> > Added a second commit that uses a fixed version-tag when in developer mode so builds made in development mode can automatically take advantage of the speedups made possible by using a fixed version-tag.
> 
> That 's quite surprising because having an accurate version in development mode is very useful (actually I would have said that it's been introduced for that purpose). Having the info of which commit in my devel branch I'm testing is helpful, much more than optimizing git bisection sessions that I seldomly do.

Exactly. For me, the primary appeal of having the precise git version reported is when hacking on systemd and this is when I'm likely to forget to install or get lost which of the many very similar versions is running at the time. Please drop the second commit.

2021-01-15 10:00 UTC, keszybz commented on meson.build
> +                meson.project_version()]
It doesn't matter too much, but the indentation is misleading... Maybe move the first entry to a separate line too?

2021-01-15 10:13 UTC, DaanDeMeyer commented
Removed the second commit as requested.

> I'd love to speed up builds after rebases, as it would make my dev experience much better, as I'm constantly switching and rebasing very similar branches. Of course wouldn't want to cause issues for other use cases, so an extra build option would be fine for me.

We don't really need a new build option for this. Just setting the version-tag option to a fixed value (e.g. `-D version-tag=bluca` will be sufficient to speed up incremental builds and builds after rebase.

2021-01-15 10:31 UTC, bluca commented
> Removed the second commit as requested.
> 
> > I'd love to speed up builds after rebases, as it would make my dev experience much better, as I'm constantly switching and rebasing very similar branches. Of course wouldn't want to cause issues for other use cases, so an extra build option would be fine for me.
> 
> We don't really need a new build option for this. Just setting the version-tag option to a fixed value (e.g. `-D version-tag=bluca`) will be sufficient to speed up incremental builds and builds after rebase.

That works just fine, thank you!

2021-01-15 11:29 UTC, bluca commented
Just the indentation left to fix, so upgrading the label

2021-01-15 18:34 UTC, merged