network: Use ordered_hashmap_ensure_put
systemd/systemd pull request #18233
Opened 2021-01-13 13:05 UTC by ssahani

2021-01-13 15:28 UTC, yuwata requested changes

2021-01-13 15:28 UTC, yuwata commented on src/libsystemd-network/sd-dhcp-server.c
>                  return -ENOMEM;
`return r;`

2021-01-13 15:28 UTC, yuwata commented on src/libsystemd-network/sd-dhcp-server.c
> +        r = ordered_hashmap_ensure_put(&server->vendor_options, &dhcp_option_hash_ops, v, v);
Hmm, this is not a fault in this PR, but we should use `ordered_set` instead of `ordered_hashmap` here.

2021-01-13 15:28 UTC, yuwata commented on src/libsystemd-network/sd-dhcp6-client.c
> +        r = ordered_hashmap_ensure_put(&client->vendor_options, &dhcp6_option_hash_ops, v, v);
Same here, `oredered_set` should be used.

2021-01-14 05:40 UTC, ssahani commented
updated thanks for the review. pal

2021-01-15 13:27 UTC, bluca commented
Is this separate from https://github.com/systemd/systemd/pull/18243 ?

2021-01-15 13:34 UTC, ssahani commented
> Is this separate from #18243 ?

yes

2021-01-15 13:43 UTC, bluca approved these changes
LGTM - leaving some time to give @yuwata a chance to have another look

2021-01-16 21:16 UTC, yuwata requested changes

2021-01-16 21:16 UTC, yuwata commented on src/libsystemd-network/sd-dhcp-server.c
> +                                ordered_set_size(server->vendor_options), server->vendor_options);
Please also update the case `SD_DHCP_OPTION_VENDOR_SPECIFIC` in dhcp_option_append().

2021-01-17 08:34 UTC, ssahani commented
updated thanks for the review ptal

2021-01-17 09:32 UTC, yuwata approved these changes

2021-01-17 11:07 UTC, merged