network: Allow to set static hostname
systemd/systemd pull request #18337
Opened 2021-01-21 14:23 UTC by ssahani

closes https://github.com/systemd/systemd/issues/17403

2021-01-22 01:34 UTC, yuwata requested changes

2021-01-22 01:34 UTC, yuwata commented on man/systemd.network.xml
> +          <term><varname>SetStaticHostname=</varname></term>
I think it is better to not introduce a new setting, but accept `UseHostname=static`.

2021-01-22 01:34 UTC, yuwata commented on src/network/networkd-network.h
> +        bool dhcp_set_static_hostname;
Maybe, its better to introduce a enum:
```
typedef enum UseHostname {
    USE_HOSTNAME_NO,
    USE_HOSTNAME_YES,
    USE_HOSTNAME_STATIC,
    _USE_HOSTNAME_MAX,
    _USE_HOSTNAM_INVALID = -1,
} UseHostname;
```
and then introduce a `_from_string()` with `DEFINE_PRIVATE_STRING_TABLE_LOOKUP_FROM_STRING_WITH_BOOLEAN()`.

2021-01-22 01:34 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +                }
Is it necessary to also set the 'transient' hostname in the above? I do not think so...

2021-01-22 01:34 UTC, yuwata commented on src/network/networkd-manager.c
> +int manager_set_static_hostname(Manager *m, const char *hostname) {
How about to merge this with `manager_set_hostname()`? They are almost equivalent.

2021-01-22 01:34 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +
I do not think we should unset the static hostname. If we do so, then every time we restart or stop networkd, the static hostname is unset. We already unset the transient hostname in the above, so it makes the system's hostname become `FALLBACK_HOSTNAME`, especially every time on shutdown the system...

2021-01-22 13:30 UTC, ssahani commented
Updated thanks for the review. ptal

2021-01-22 19:18 UTC, bluca commented
CI looks unhappy:

```
582/582 check-directives                        FAIL     0.07 s (exit status 1)

--- command ---
13:34:36 /home/runner/work/systemd/systemd/tools/check-directives.sh /home/runner/work/systemd/systemd
--- stdout ---
378a379
> SetStaticHostname=
Looks like test/fuzz/fuzz-network-parser/directives.network hasn't been updated
```

2021-01-23 14:05 UTC, ssahani commented
> CI looks unhappy:
> 
> ```
> 582/582 check-directives                        FAIL     0.07 s (exit status 1)
> 
> --- command ---
> 13:34:36 /home/runner/work/systemd/systemd/tools/check-directives.sh /home/runner/work/systemd/systemd
> --- stdout ---
> 378a379
> > SetStaticHostname=
> Looks like test/fuzz/fuzz-network-parser/directives.network hasn't been updated
> ```

Yes dropped now . thanks !

2021-01-25 05:10 UTC, yuwata requested changes

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +        [USE_HOSTNAME_BOTH]   = "both",
`both`? I do not have any reason to set both transient and static hostname. Note that `SetStaticHostname` method updates /etc/hostname and sets kernel hostname. While `SetHostname` just set the kernel hostname. So, calling both method is meaningless.

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-dhcp4.c
>          if (link->network->dhcp_use_hostname) {
`if (IN_SET(link->network->dhcp_use_hostname, USE_HOSTNAME_YES, USE_HOSTNMAE_STATIC))`

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +                }
Please move the debug log in `if (hostname)` block. Also, as already commented in the above, `USE_HOSTNAME_BOTH` is meaning less, so how about something like the following:
```
if (hostname) {
    log_link_debug(link, "Setting...");
    r = manager_set_hostname(link->manager, hostname, link->network->dhcp_use_hostname == USE_HOSTNAME_STATIC);
    if (r < 0)
         log_link_error_errno(...);
}
```

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-manager.c
> +                (void) manager_set_hostname(m, m->dynamic_hostname, false);
If `bus` is not ready when setting hostname at first, then, this always try to set transient hostname...

How about the following?
```
# networkd-manager.h
Manager {
    (...);
    char *transient_hostname;
    char *static_hostname;
    (...);
}

# networkd-manager.c
if (m->static_hostname)
    (void) manager_set_hostname(m, m->static_hostname, true);
else if (m->transient_hostname)
    (void) manager_set_hostname(m, m->transient_hostname, false);
```

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-manager.c
> +                        return log_oom();
Then, 
```
if (static_hostname)
    r = free_and_strdup(&m->static_hostname, hostname);
else
    r = free_and_strdup(&m->transient_hostname, hostname);
if (r < 0)
    return log_oom();
```

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-manager.c
> +
It is not necessary to `strdup()` the method name.

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-manager.c
> +                        kind,
Simple, `static_hostname ? "SetStaticHostname" : "SetHostname"` is enough.

2021-01-25 05:10 UTC, yuwata commented on src/network/networkd-manager.h
> +int manager_set_hostname(Manager *m, const char *hostname, bool static_hostname);
Not a big matter, but the name `bool static_hostname` is redundant, `bool static` or `bool is_static` is enough.

2021-01-25 11:08 UTC, ssahani commented on src/network/networkd-dhcp4.c
> +        [USE_HOSTNAME_BOTH]   = "both",
The idea behind the both is clear logic what going to happen as you said above. If you think it's reductact we can drop this and update in man only.

2021-08-11 17:00 UTC, closed without merging