Tree wide various cleanups
systemd/systemd pull request #18372
Opened 2021-01-25 12:17 UTC by ssahani

2021-01-25 14:08 UTC, yuwata requested changes
Could you squash changes "tighten variable scope used in loop"?

2021-01-25 14:08 UTC, yuwata commented on src/core/namespace.c
> +        assert(n);
Hmm? Maybe, `assert(m || n == 0);`?

2021-01-25 14:08 UTC, yuwata commented on src/core/target.c
> +        for (unsigned k = 0; k < ELEMENTSOF(deps); k++) {
`size_t` is better.

2021-01-25 14:08 UTC, yuwata commented on src/basic/sigbus.c
> +        for (unsigned u = 0; u < SIGBUS_QUEUE_MAX; u++)
`size_t` is better.

2021-01-25 14:08 UTC, yuwata commented on src/coredump/coredump.c
> +        for (unsigned i = 0; i < _META_MAX; i++) {
`size_t`?

2021-01-25 14:08 UTC, yuwata commented on src/coredump/coredump.c
> +        for (unsigned n = 0; n < iovw->count; n++) {
Please use `size_t`.

2021-01-25 14:08 UTC, yuwata commented on src/coredump/coredump.c
> +                for (unsigned i = 0; i < ELEMENTSOF(meta_field_names); i++) {
`size_t`

2021-01-25 14:16 UTC, yuwata requested changes

2021-01-25 14:16 UTC, yuwata commented on src/basic/virt.c
> +        for (unsigned i = 0; i < ELEMENTSOF(dmi_vendors); i++) {
`size_t`

2021-01-25 14:16 UTC, yuwata commented on src/core/dbus-execute.c
> +        for (unsigned i = 0; i < c->n_temporary_filesystems; i++) {
`size_t`

2021-01-25 14:16 UTC, yuwata commented on src/core/device.c
> +        for (unsigned i = 0; i < ELEMENTSOF(device_found_map); i++) {
`size_t`

2021-01-25 14:16 UTC, yuwata commented on src/libsystemd-network/sd-dhcp-server.c
> +        for (unsigned i = 0; i < server->pool_size; i++) {
`uint32_t`?

2021-01-25 17:51 UTC, ssahani commented
Thanks for reviewing.  I may have missed something. ptal

2021-01-26 20:38 UTC, bluca commented
Please use "treewide: tighten variable scope used in loop" and squashfs all those commits into a single one

2021-01-27 07:18 UTC, keszybz commented
LGTM. I'll just squash it.

2021-01-27 07:19 UTC, merged

2021-01-27 09:22 UTC, ssahani commented
Thanks for the review @keszybz