table: drop trailing white spaces when align_percent of the last cell in row is 0
systemd/systemd pull request #18430
Opened 2021-02-01 16:49 UTC by yuwata

Fixes #18415.

2021-02-01 17:11 UTC, poettering requested changes
hmm, this is problematic in case a cell uses an ansi color with background. i am pretty sure in that case the full cell should be highlighted with the bg color, not just the text.

that's the reason I didn't bother stripping the whitespace in the first place. i.e. figuring out whether some ansi sequence induces a background color or not was something i didn't want to get into

2021-02-01 17:11 UTC, poettering commented on src/shared/format-table.c
> +                                                        delete_trailing_chars(aligned, NULL);
hmm, sounds pointless to first add the space, and then drop it again.  The space should not be added at all in the first place. 

moreover i guess the whitespace should also be suppressed for any alignment

2021-02-15 17:09 UTC, poettering commented
> that's the reason I didn't bother stripping the whitespace in the first place. i.e. figuring out whether some ansi sequence induces a background color or not was something i didn't want to get into

maybe an easy way out is to leave the spaces in when color is enabled, and only suppress it when color is turned off. This would then make thing things look good still on a terminal, but when piped to some pipeline we'll suppres the trailing space, since color is automatically turned off there

2021-02-16 19:00 UTC, yuwata commented
@poettring Thank you for the suggestion. Updated. PTAL.

2021-02-17 22:48 UTC, poettering commented on src/shared/format-table.c
> +                                                    (!colors_enabled() || !table_data_color(d)))
hmm, i think this also needs:

```c
… &&
(!urlify_enabled() || !d->url))
```

2021-02-18 19:23 UTC, yuwata commented
@poettering Updated. URLification is also checked. PTAL.

2021-02-19 05:04 UTC, merged