networkd: add UseFQDN option for DHCPv6
systemd/systemd pull request #18543
Opened 2021-02-10 18:41 UTC by vmagro

Summary:
Similar to DHCPv4's UseHostname option, add a UseFQDN config option in
[DHCPv6] to set the system's transient hostname if the FQDN option is
set in the DHCPv6 response from the server.

Test Plan:
Booted a vm with `mkosi qemu`, ran dnsmasq on that interface to assign
the FQDN `myvm.test.vinn.ie` to the VM.
(`sudo dnsmasq --interface=vt-image --dhcp-range=fc00::100,fc00::200
--dhcp-leasefile=leasefile --port 0 --no-daemon --enable-ra
--dhcp-host=52:54:00:12:34:56,myvm --domain=test.vinn.ie --log-dhcp`)

`systemd-networkd` then set the transient hostname accordingly

```
$ journalctl
Feb 09 17:33:04 archlinux systemd-networkd[332]: ens2: DHCPv6 address fc00::1a8/128 (valid for 1d, preferred for 1d)
Feb 09 17:33:04 archlinux dbus-daemon[341]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.0' (uid=981 pid=332 comm="/usr/lib/systemd/systemd-networkd ")
Feb 09 17:33:04 archlinux systemd[1]: Starting Hostname Service...
Feb 09 17:33:04 archlinux dbus-daemon[341]: [system] Successfully activated service 'org.freedesktop.hostname1'
Feb 09 17:33:04 archlinux systemd[1]: Started Hostname Service.
Feb 09 17:33:04 archlinux dbus-daemon[341]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service' requested by ':1.9' (uid=0 pid=379 comm="/usr/lib/systemd/systemd-hostnamed ")
Feb 09 17:33:04 archlinux systemd[1]: Starting Authorization Manager...
Feb 09 17:33:04 archlinux polkitd[380]: Started polkitd version 0.118
Feb 09 17:33:04 archlinux polkitd[380]: Loading rules from directory /etc/polkit-1/rules.d
Feb 09 17:33:04 archlinux polkitd[380]: Loading rules from directory /usr/share/polkit-1/rules.d
Feb 09 17:33:04 archlinux polkitd[380]: Finished loading, compiling and executing 2 rules
Feb 09 17:33:04 archlinux dbus-daemon[341]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
Feb 09 17:33:04 archlinux polkitd[380]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Feb 09 17:33:04 archlinux systemd[1]: Started Authorization Manager.
Feb 09 17:33:04 myvm.test.vinn.ie systemd-hostnamed[379]: Hostname set to <myvm.test.vinn.ie> (transient)

$ hostnamectl --transient
myvm.test.vinn.ie
```

2021-02-10 21:03 UTC, yuwata requested changes
Thanks. Looks mostly ok. But please update the man page.

Also, could you drop the journal log from the commit message? It is too long...

2021-02-10 21:03 UTC, yuwata commented on src/network/networkd-dhcp6.c
> +                                log_link_error_errno(link, r, "Failed to set transient hostname to '%s': %m", hostname);
`shorten_overlong()` in the above may fail. Please conditionalize this as follows:
```
if (hostname) {
    r = manager_set_hostname();
    ...
}
```

2021-02-10 22:11 UTC, vmagro commented
Thanks for the quick review, I added the conditional you described and updated the man page to describe this as the dhcpv6 equivalent of UseHostname

2021-02-11 01:16 UTC, yuwata approved these changes

2021-02-11 04:30 UTC, merged

2021-02-17 19:32 UTC, flo-wer commented
Is there any particular reason to use `UseFQDN=` instead of `UseHostname=`? As the man page and the code suggests, it is the same functionality as for [DHCPv4], therefore it should use the same name.

2021-02-17 20:03 UTC, yuwata commented
The name is based on RFC for DHCPv4 and DHCPv6.
DHCPv4 option 12 is called hostname. See, https://tools.ietf.org/html/rfc2132#section-3.14.
DHCPv6 option 39 is called FQDN, See, https://tools.ietf.org/html/rfc4704#section-4.