man: document how to use --network-interface= during boot
systemd/systemd pull request #18858
Opened 2021-03-03 16:41 UTC by poettering

Fixes: #18793

2021-03-03 20:53 UTC, keszybz requested changes
Looks nice.

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        <para>Note that any network interface specified this way must exist already at the time the container
must already exist ?

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        is invoked. If the container shall be invoked automatically at boot via a
invoked → started (I don't think we ever talk about *invoking* containers)

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        fully asynchronous, and network interfaces might be discovered and probed only later during the boot
"disovered and probed" → "discovered" ?

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        <para>As with <option>--network-interface=</option> the underlying Ethernet network interface must
Comma after "As with --network-interface"

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        exist already at the time the container is started, and thus similar unit file drop-ins as described
must already exist

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        above might be useful.</para></listitem>
Ditto ditto

2021-03-03 20:53 UTC, keszybz commented on man/systemd-nspawn.xml
> +        above might be useful.</para></listitem>
Ditto, Ditto

2021-03-04 16:23 UTC, poettering commented
Force pushed new version, only changes are the suggested ones. Upgrading green label.

2021-03-04 17:55 UTC, merged