tree-wide: use UINT64_MAX or friends
systemd/systemd pull request #18852
Opened 2021-03-03 05:08 UTC by yuwata

2021-03-03 14:32 UTC, poettering requested changes
looks good, some comments

2021-03-03 14:32 UTC, poettering commented on src/cgtop/cgtop.c
>                          (void) usleep(last_refresh + arg_delay - t);
what about this one?

2021-03-03 14:32 UTC, poettering commented on src/cgtop/cgtop.c
>                                  arg_delay += USEC_PER_MSEC*250;
and this one?

2021-03-03 14:32 UTC, poettering commented on src/cryptsetup/cryptsetup.c
> +                until = usec_add(now(CLOCK_MONOTONIC), arg_timeout);
The ask_password_xyz() functions currently take an until param of 0 as meaning "wait forever". hence this changes behaviour quite a bit. That said, those functions should probably be fixed to make "0" mean, don#t wait at all, and USEC_INFINITY mean wait forever

2021-03-03 14:32 UTC, poettering commented on src/shared/format-table.h
> +#define table_set_sort(...) table_set_sort_internal(__VA_ARGS__, (size_t) SIZE_MAX)
ah, yes, i love it. This was too easy to fuck up

2021-03-03 20:02 UTC, yuwata commented
@poettering Thank you for the review. The all above points are addressed. PTAL.

2021-03-04 22:11 UTC, yuwata commented
Rebased.

2021-03-05 16:51 UTC, keszybz reviewed
LGTM. I'll submit a follow-up patch to remove some parens from around SIZE_MAX and friends.

2021-03-05 16:51 UTC, keszybz commented on src/shared/format-table.h
> +#define table_set_display(...) table_set_display_internal(__VA_ARGS__, (size_t) SIZE_MAX)
I think the cast here is unnecessary. After all, SIZE_MAX better be of size_t.

2021-03-05 16:51 UTC, keszybz commented on src/basic/audit-util.h
> +#define AUDIT_SESSION_INVALID (UINT32_MAX)
UINT32_MAX already has it's own set of ().

2021-03-05 16:51 UTC, merged