shared: add new IMAGE_VERSION=/IMAGE_ID= field to /etc/os-release
systemd/systemd pull request #19093
Opened 2021-03-23 15:22 UTC by poettering

This specifes two new optional fields for /etc/os-release:
IMAGE_VERSION= and IMAGE_ID= that are supposed to identify the image of
the current booted system by name and version.

This is inspired by the versioning stuff in
https://github.com/systemd/mkosi/pull/683.

In environments where pre-built images are installed and updated as a
whole the existing os-release version/distro identifier are not
sufficient to describe the system's version, as they describe only the
distro an image is built from, but not the image itself, even if that
image is deployed many times on many systems, and even if that image
contains more resources than just the RPMs/DEBs.

In particular, "mkosi" is a tool for building disk images based on
distro RPMs with additional resources dropped in. The combination of all
of these together with their versions should also carry an identifier
and version, and that's what IMAGE_VERSION= and IMAGE_ID= is supposed to
be.

2021-03-23 15:22 UTC, poettering commented
/cc @bluca this might be interesting to you?

2021-03-23 15:26 UTC, poettering commented
Before adding this i was unsure if this fit into /etc/os-release or if another file either new or maybe /etc/machine-info would be a better place. But I always came back to think that /etc/os-release is the best place because it has similar semantics to the rest of the data declared there: it is the same for all deployments of the piece of software, is controlled by the vendor of it and generated at build time. The main different to the existing ID= + VERSION_ID= fields is that it's a more comprehensive thing: it not only encodes which distro and version and packages are wrong but also in what combination they are used, i.e. it should stabilize package selections and their version plus additional configuration on top.

I hope this explains the backgorund of my thinking here a bit. (I was thinking of adding this to os-release, but I didn't want to dump too much philosophical BS in there, and I think it's good to keep some level of ambiguity in all of this, as I'd figure people would use this differently in different usecases that are different from my own)

2021-03-23 15:32 UTC, bluca approved these changes
Yes very much so - in fact, I've been using for years now $VENDOR_ID and a couple other namespaced identifiers in our os-release with the exact same semantics you mentioned. LGTM!

2021-03-28 16:17 UTC, Conan-Kudo requested changes
I would prefer this to actually be a separate file, because `os-release` is managed by a package and I don't want to change that often, whereas these values would change every time I build an image. Why wouldn't we do this in a separate file?

2021-03-28 16:40 UTC, bluca commented
> I would prefer this to actually be a separate file, because `os-release` is managed by a package and I don't want to change that often, whereas these values would change every time I build an image. Why wouldn't we do this in a separate file?

Well, at least for me the intended use for this is for assembled images, read-only or not, which are not upgraded via packages, but built and shipped. So appending one line to the existing file or another one when the image is built shouldn't make too much difference - it's never updated anyway (you get a new image).
Using the existing file is simple as everybody already supports parsing it and making available its key-value pairs.

2021-03-28 16:45 UTC, bluca commented
> > I would prefer this to actually be a separate file, because `os-release` is managed by a package and I don't want to change that often, whereas these values would change every time I build an image. Why wouldn't we do this in a separate file?
> 
> Well, at least for me the intended use for this is for assembled images, read-only or not, which are not upgraded via packages, but built and shipped. So appending one line to the existing file or another one when the image is built shouldn't make too much difference - it's never updated anyway (you get a new image).
> Using the existing file is simple as everybody already supports parsing it and making available its key-value pairs.

In other words, at least in my mind, this is not something you _always_ set for distros like Debian or Fedora which might build images, but then upgrade via dpkg/rpm. It's something you set when post-processing a buildroot or yocto image before shipping it.

2021-03-29 13:46 UTC, poettering commented
> I would prefer this to actually be a separate file, because `os-release` is managed by a package and I don't want to change that often, whereas these values would change every time I build an image. Why wouldn't we do this in a separate file?

It has very similar semantics as the other stuff in /etc/os-release.

The idea is that an image builder patches /etc/os-release with this info during the image build process.

Note that /usr/lib/systemd/os-release is the typically what the package manager maintains, and /etc/os-release either doesn't exist or is a symlink there, or (in case of fedora) is generated from the data in /usr/lib plus some extensions). And that's precisely the mechanism I'd build on here: the image builder should take the RPM supplied data from /usr/lib/systemd/os-release and extend it with these two fields and write the result to /etc/os-release, so that there's clear separation on the RPM supplied versoin and the one specific to the local image. 

BUILD_ID= is another field that might be generated and exist in /etc/os-release only and not in /usr/lib/systemd/os-release btw.

Hence, I still think just adding these two fields is the best way to go on.

2021-03-29 14:07 UTC, Conan-Kudo commented
@poettering But this causes systemd-nspawn to choke, which led to me having to fix things for CentOS and RHEL 8 so that `/etc/os-release` was a symlink to `/usr/lib/os-release`. When it was a real file, things didn't work properly.

2021-03-29 14:40 UTC, poettering commented
> @poettering But this causes systemd-nspawn to choke, which led to me having to fix things for CentOS and RHEL 8 so that `/etc/os-release` was a symlink to `/usr/lib/os-release`. When it was a real file, things didn't work properly.

Can you elaborate? "choke"? "didn't work properly"? in which way?

2021-03-29 15:13 UTC, Conan-Kudo commented
nspawn attempted to create a symlink but failed because the file already existed, and it wouldn't successfully boot until I fixed it.

2021-03-29 15:22 UTC, poettering commented
> nspawn attempted to create a symlink but failed because the file already existed, and it wouldn't successfully boot until I fixed it.

hmm, have a bug link or so? nspawn doesn't write that thing at all. tmpfiles.d/ stuff will create it as symlink if it is missing, but that if the inode already exists it will gracefully step away (though debug log this). 

Have any further info on this? error messages or so?

2021-03-31 08:46 UTC, merged

2021-03-31 08:46 UTC, keszybz commented
LGTM.