resolvectl: introduce dump-caches command
systemd/systemd pull request #19104
Opened 2021-03-24 16:03 UTC by yuwata

2021-03-24 19:59 UTC, poettering requested changes
I'd really prefer if we'd synthesize JSON from the cache instead, and return that to clients. It would be processable then, and shouldn't be too difficult to synthesize. i.e. add dns_resource_key_to_json() and dns_resource_key_from_json() or so, and similar for dns_resource_record(). Pass the RR RDATA stuff as base64 blob.

2021-03-24 19:59 UTC, poettering commented on src/resolve/resolved-dns-cache.c
> +        y_str = dns_resource_key_to_string(y->rr ? y->rr->key : y->key);
dns_resource_key_compare_func() + dns_resource_record_compare_func() already exist

2021-03-25 09:45 UTC, keszybz commented
Since @yuwata gave thumbsup for the json idea, let's mark this as "needs rework".

2021-04-28 21:29 UTC, poettering commented
This reminds me of #19451 a bit, i.e. generate server-side json, pass to client via dbus, and then just prettify and output it there.

2023-06-12 16:43 UTC, closed without merging