unit: coldplug both job and nop_job if possible
systemd/systemd pull request #19180
Opened 2021-04-02 03:27 UTC by Geass-LL

Sometimes, both job and nop_job are deserialized. In this case,
if we only cold plug the job, the nop_job will also stuck in the
job list.

2021-04-02 03:35 UTC, Geass-LL commented
### Method to reproduce
### 1. create test1.service test2.service test3.service and test.target:

`test1.service`
```shell
[Unit]
Description=whorweTEST1

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/systemd/system/test1.sh

[Install]
WantedBy=test.target
```
`test1.sh`
```shell
systemctl daemon-reload &
systemctl try-restart test3.service
```
`test2.service`
```shell
[Unit]
Description=whorweTEST2
After=test1.service

[Service]
ExecStart=/usr/bin/true

[Install]
WantedBy=test.target
```
`test3.service`
```shell
[Unit]
Description=whorweTEST3
After=test2.service

[Service]
ExecStart=/usr/bin/true

[Install]
WantedBy=test.target
```
`test.target`
```shell
[Unit]
Description=whorweTEST_TARGET
```

#### 2. restart test.target
`systemctl restart test.target`

#### 3. check job list
`systemctl list-jobs`
```shell
[root@localhost ~]# systemctl list-jobs
 JOB UNIT          TYPE  STATE  
 926 test.target   start waiting
1025 test1.service start running
1026 test3.service start waiting
1027 test3.service nop   waiting
 927 test2.service start waiting
```

2021-04-07 03:00 UTC, Geass-LL commented
Releted PR: https://github.com/systemd/systemd/pull/13124
@keszybz Please take a look.

2021-04-12 03:49 UTC, Geass-LL commented
ping. @poettering @keszybz

2021-07-06 12:52 UTC, Geass-LL commented
ping. @keszybz

2021-07-27 12:15 UTC, yanfangw commented
Could anyone review this PR? I have faced same problem, and can reproduce by the given method.

2021-08-16 13:06 UTC, poettering requested changes

2021-08-16 13:06 UTC, poettering commented on src/core/unit.c
> +        if (u->job || u->nop_job) {
this check is unecessary, you check each job below anyway

2021-08-16 13:06 UTC, poettering commented on src/core/unit.c
> +                        if ( q < 0 && r >= 0 ) {
coding style, no space after ( and before )

2021-08-16 13:06 UTC, poettering commented on src/core/unit.c
> +                        }
coding style, no {} around single-line if blocks

2021-08-16 13:06 UTC, poettering commented on src/core/unit.c
> +                        }
no {} around single-line if blocks

2021-08-16 13:33 UTC, poettering commented
Sorry for the late review.

To speed things up now I just fixed the nits myself, and posted the result as #20447. I kept the attribution to you intact, given you did the actual work.

Let's close this here, and continue there.

2021-08-16 13:33 UTC, closed without merging