sd-dhcp-client: introduce sd_dhcp_client_is_running()
systemd/systemd pull request #19291
Opened 2021-04-11 22:39 UTC by yuwata

Split out from #19271.

2021-04-12 07:58 UTC, keszybz requested changes

2021-04-12 07:58 UTC, keszybz commented on src/libsystemd-network/sd-dhcp-client.c
> +        assert_return(client, -EINVAL);
Just return false in this case, like in 3bbb76f621?

2021-04-12 07:58 UTC, keszybz commented on src/libsystemd-network/sd-dhcp-client.c
> +        return client->state != DHCP_STATE_INIT;
This returns true also for `DHCP_STATE_STOPPED`... On purpose?

2021-04-12 07:58 UTC, keszybz commented on src/systemd/sd-dhcp-client.h
> +int sd_dhcp_client_is_running(sd_dhcp_client *client);
`const`?

2021-04-13 04:16 UTC, yuwata commented
@keszybz Thank you for your review. All comments are addressed.

2021-04-14 20:18 UTC, bluca approved these changes
LGTM, but waiting for @keszybz since he left comments earlier

2021-04-14 20:31 UTC, merged