journald: enforce longer line length limit during "setup" phase of st…
systemd/systemd pull request #19337
Opened 2021-04-16 10:20 UTC by syyhao1994

…ream protocol

This PR made modification on Lennart Poettering's basis. Fix the LineMax's function failure problem.

Fixes: #18993
Replaces: #19008， #19018

Signed-off-by: Yangyang Shen <shenyangyang4@huawei.com>

2021-04-16 10:21 UTC, syyhao1994 commented
@poettering PTAL

2021-04-16 12:25 UTC, syyhao1994 commented
With the PR https://github.com/systemd/systemd/pull/19337
``` 
-- Logs begin at Fri 2021-04-16 20:14:55 CST, end at Fri 2021-04-16 20:23:31 CST. --
Apr 16 20:20:59 localhost.localdomain systemd[1]: Starting test journald line max...
Apr 16 20:20:59 localhost.localdomain bash[5174]: asdkfjasasdfjasdlfajssdjfsdjfskldfjsljfdklsjdflksjdflksjdflsjdflksjdflksdjflsdj
Apr 16 20:20:59 localhost.localdomain bash[5174]: flsdjfasdjfalsjdfalsdkjfasdjfaksldfjaaskldjfalskdjfasldjfasldjfasldfjalsdjfalsd
Apr 16 20:20:59 localhost.localdomain bash[5174]: jfasdlkfssssssssssssssssssssssssssssssssssssssssssssssssssssssaaaaaaaaaaaaaaaaa
Apr 16 20:20:59 localhost.localdomain bash[5174]: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddd
Apr 16 20:20:59 localhost.localdomain systemd[1]: test.service: Succeeded.
Apr 16 20:20:59 localhost.localdomain systemd[1]: Started test journald line max.
```
And with this pr:
```
Apr 16 20:22:17 localhost.localdomain systemd[1]: Starting test journald line max...
Apr 16 20:22:17 localhost.localdomain bash[6164]: asdkfjasasdfjasdlfajssdjfsdjfskldfjsljfdklsjdflksjdflksjdflsjdflksjdflksdjflsdj
Apr 16 20:22:17 localhost.localdomain bash[6164]: flsdjfasdjfalsjdfalsdkjfasdjfaksldfjaaskldjfalskdjfasldjfasldjfasldfjalsdjfalsd
Apr 16 20:22:17 localhost.localdomain bash[6164]: jfasdlkfssssssssssssssssssssssssssssssssssssssssssssssssssssssaaaaaaaaaaaaaaaaa
Apr 16 20:22:17 localhost.localdomain bash[6164]: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffff
Apr 16 20:22:17 localhost.localdomain bash[6164]: fffffffdddddddddddddddddddddddddddd
Apr 16 20:22:17 localhost.localdomain systemd[1]: test.service: Succeeded.
Apr 16 20:22:17 localhost.localdomain systemd[1]: Started test journald line max.
```

2021-04-17 01:05 UTC, syyhao1994 commented
@bluca PTAL. This PR i have made about 20+ days...

2021-04-20 14:31 UTC, syyhao1994 commented
@poettering @bluca Please take a look at this.

2021-04-20 20:24 UTC, poettering requested changes
looks good, but please use MIN()

2021-04-20 20:24 UTC, poettering commented on src/journal/journald-stream.c
> +                size_t tmp_remaining = remaining > line_max ? line_max : remaining;
use MIN()

2021-04-21 03:10 UTC, syyhao1994 commented on src/journal/journald-stream.c
> +                size_t tmp_remaining = remaining > line_max ? line_max : remaining;
Done! PTAL.

2021-04-21 08:29 UTC, syyhao1994 commented
@poettering @bluca PTAL.

2021-04-21 09:50 UTC, bluca commented
please rebase on latest `main` and force-push, to fix CI errors

2021-04-21 10:48 UTC, poettering commented
Lgtm. Lets merge once the ci agrees.

2021-04-21 13:14 UTC, NickYang24 commented
> 
> 
> please rebase on latest `main` and force-push, to fix CI errors

Thank you for your attention. Rebase done! PTAL.

2021-04-21 13:16 UTC, syyhao1994 commented
> please rebase on latest `main` and force-push, to fix CI errors

Thank you for you attention. Rebase done! PTAL.

2021-04-21 15:05 UTC, syyhao1994 commented
@poettering @bluca The CI failure seems nothing to do with this pr. PTAL.

2021-04-21 15:22 UTC, merged