systemctl-edit: Support fallback to emacs if available
systemd/systemd pull request #19780
Opened 2021-06-01 22:01 UTC by frozencemetery

My rationale for ordering is that vi* or nano will be installed on most Linuxes by default, while emacs isn't.  Therefore, prefer it if present.  While personally I'd prefer emacs over nano, the current list appears to be ordered by user-friendliness, so I've kept nano in front.

The current editor list was set at the time systemctl-edit was added in 7d4fb3b1c5e ; the only change was the addition of "editor" in 9391a1c3d6c94c478b0016a81df3f874fd99260e.  Given the existence of .dir-locals.el, I assume at least one developer is also using emacs, so hopefully this isn't too controversial to add support for :)

2021-06-02 07:30 UTC, poettering commented
I am not convinced we should add this. Otherwise people will just keep suggesting more editors we should just add there.

I am an emacs user myself, but i think emacs is probably something you better pick via $PAGER, then we automatically dump people in.

2021-06-02 08:02 UTC, dnicolodi commented
Also, I think most Emacs users would prefer `emacsclient` as `$EDITOR` rather than plain `emacs`.

2021-06-02 10:07 UTC, keszybz reviewed
I think this is OK to do. If people have emacs installed (and it is generally not installed by default, then they are probably OK with using it). If people ask for other editors to be added, I think that is OK too. After all, the patches would be trivial, and we don't really care.

I would only require that the editors are well-known open-source programs, and that they run in "terminal blocking mode".

> Also, I think most Emacs users would prefer `emacsclient` as `$EDITOR` rather than plain `emacs`.

No, I know this to be very confusing when the editor is launched externally. Most users are not expecting an editing window somewhere else.

2021-06-02 10:07 UTC, keszybz commented on src/systemctl/systemctl-edit.c
> +                FOREACH_STRING(p, "editor", "nano", "emacs", "vim", "vi") {
I don't think we should start an editor that pops up a graphical window. This is confusing to users. The editor must be a "text editor" that shows up in the current terminal and blocks it until exit.
`emacs -nw` would be acceptable and better.

But then this loop would have to be changed…

2021-06-02 10:18 UTC, dnicolodi commented
I think that the fallback values are there just to get an editor of some sort when `$EDITOR` is not set rather than failing. I don't think that having a different editor to pop up based on which packages are installed on the system is the least surprising behavior. Adding one more editor to the list we go from a situation in which who wants to use Emacs need to set `$EDITOR` to a situation in which who want to use Vim but has Emacs installed needs to set `$EDITOR`. I don't think one is preferable over the other.

> If people ask for other editors to be added, I think that is OK too. After all, the patches would be trivial, and we don't really care.

Do you really want to be in the busyness of deciding in which orders editors need to be probed? :)

2021-06-02 11:13 UTC, keszybz commented
> I think that the fallback values are there just to get an editor of some sort when `$EDITOR` is not set rather than failing.

Agreed.

> I don't think that having a different editor to pop up based on which packages are installed on the system is the least surprising behavior. Adding one more editor to the list we go from a situation in which who wants to use Emacs need to set `$EDITOR` to a situation in which who want to use Vim but has Emacs installed needs to set `$EDITOR`. I don't think one is preferable over the other.

True. So I think `emacs -nw` should be added *after* `vim`. With that, people who had `vim` will still get `vim`, and only people who didn't have `nano` or `vim` will get `emacs`. (I think we should still put emacs before `vi`, because plain `vi` is almost unusable and I don't think anyone wants to use it if they have a choice.

> Do you really want to be in the busyness of deciding in which orders editors need to be probed? :)

So, let's make the rule that new editors are added near the end (keeping stuff like `vi` at the very end).

2021-06-02 14:15 UTC, frozencemetery commented
Moved emacs after vim as requested.

2021-06-02 14:26 UTC, frozencemetery commented
I'm not sure if you're asking for a change to the invoked editor or not.  `emacs -nw` could work there but would involve a change to the loop as you say.  `emacs-nox` is another possibility, though that won't work if people have the GUI installed.

2021-06-02 15:14 UTC, keszybz commented
Yes, I was asking for a change to the loop. As written, `emacs` will potentially invoke a graphical program, which I think is the wrong thing to do, as explained above.

`emacs-nox` is a package name (at least under Fedora). `emacs -nw` should be a portable way to invoke a non-graphical emacs.

2021-06-02 18:03 UTC, frozencemetery commented
Okay, updated.

I believe this fixes a bug where arguments from the environment-set editor would be applied to fallback editors.  I can split that out into a separate commit if you'd prefer.

2021-06-07 16:03 UTC, poettering commented
so, is this really worth it? does anyone else do this? we don#t live in a vacuum here. hence, do the other typical programs that spawn an editor like this run emacs? i.e. "git commit"? "visudo"? "crontab -e"? and tools like that?

if not, i really see no point in any of this, because emacs lovers who want this won't survive without setting PAGER to their editor anyways.

2021-06-07 16:21 UTC, vcaputo commented
I believe including `vim` explicitly in the list is a sort of invitation for such additions...

2021-06-10 22:44 UTC, bluca commented
> so, is this really worth it? does anyone else do this? we don#t live in a vacuum here. hence, do the other typical programs that spawn an editor like this run emacs? i.e. "git commit"? "visudo"? "crontab -e"? and tools like that?
> 
> if not, i really see no point in any of this, because emacs lovers who want this won't survive without setting PAGER to their editor anyways.

iirc the default for the vast majority of command line tools is to call `editor`, which resolves to the user preferred editor if configured, or to some distro default otherwise

2021-06-19 01:53 UTC, Conan-Kudo commented
> > so, is this really worth it? does anyone else do this? we don#t live in a vacuum here. hence, do the other typical programs that spawn an editor like this run emacs? i.e. "git commit"? "visudo"? "crontab -e"? and tools like that?
> > if not, i really see no point in any of this, because emacs lovers who want this won't survive without setting PAGER to their editor anyways.
> 
> iirc the default for the vast majority of command line tools is to call `editor`, which resolves to the user preferred editor if configured, or to some distro default otherwise

The `editor` tool doesn't exist outside of Debian, unfortunately...

2021-08-12 14:41 UTC, poettering commented
my question still stands? does any other tool have a fallback for "emacs -nw"? should we really be the ones who add this first? sounds so weird to me. I mean, emacs users have to set EDITOR  anyway, if they want it, why should we behave differently from visudo, cron -e, git commit and all those other tools that invoke $EDITOR?

2021-08-13 08:12 UTC, poettering requested changes
I am not convinced about the emacs -nw addition, but here's a review of the code changes

2021-08-13 08:12 UTC, poettering commented on src/systemctl/systemctl-edit.c
> +        editor_args = strv_split(editor, WHITESPACE);
you leak this memory. even if we'll shortly exec some other process here, and the leak doesn't really matter too much, as a matter of hygiene, please don't leak memory

2021-08-13 08:12 UTC, poettering commented on src/systemctl/systemctl-edit.c
> +        args = reallocarray(args, argc + 1, sizeof(*args));
this is a bit weird in order. usually when realloc()/reallocarray() is used, the result is assigned to some temporary var, and then when it is non-NULL it is used to override the original var. here you do it differently: you keep a shadow variable, that you immediately update, and then you sync it back to the original one, later

2021-08-13 08:12 UTC, poettering commented on src/systemctl/systemctl-edit.c
> +        args = reallocarray(args, argc + 1, sizeof(*args));
but, what i don't get, afaics args is always NULL here on input, hence why use reallocarray() at all? a plain new() would suffice too. This also then makes the "args_save" argument to this function unnecessary

2021-08-16 13:31 UTC, frozencemetery commented
Thanks for the review.  If systemd decides that a change to use `emacs` or `emacs -nw` is welcome, I'm happy to make the changes.

2021-08-16 13:36 UTC, poettering commented
still curious if there's any prior art, and any other relevant project does the fallback to "emacs -nw" thing

2021-08-16 14:23 UTC, frozencemetery commented
> still curious if there's any prior art, and any other relevant project does the fallback to "emacs -nw" thing

In case you're trying to ask me this question: `emacs -nw` is @keszybz's proposal, not mine.

2021-08-16 14:36 UTC, poettering commented
well, i meant, emacs in general, not just "-nw" mode

2021-08-16 14:44 UTC, poettering commented
(or to say this differently: yes if we add emacs then definitely in "-nw" mode. I am just wondering whether to add it at all, if noone else has it in their list. So the question is: is there any prior art where relevant projects fallback to emacs or emacs -nw if EDITOR is not set?)

2021-08-17 14:39 UTC, frozencemetery commented
I no longer really care whether this merges or not, but:

> I am just wondering whether to add it at all, if noone else has it in their list. So the question is: is there any prior art where relevant projects fallback to emacs or emacs -nw if EDITOR is not set?

Not that I'm aware of.  However, there's also no prior art for falling back to nano or vim that I could find - and I don't think anyone's proposing removing those.  (Plenty of fallback to vi and editor, though.)

2021-08-18 14:04 UTC, poettering commented
> Not that I'm aware of. However, there's also no prior art for falling back to nano or vim that I could find - and I don't think anyone's proposing removing those. (Plenty of fallback to vi and editor, though.)

Well, the vim thing is just because "vi" is such a useless tool on most distros. i.e. "vi" is just an insult to users if "vim" exists. If you ask me distros should always run vim if vi is requested and vim is installed. still running a serously cut down version of vim is simply mean and pointless. 

here are the sources of debian's "sensible-editor":

https://sources.debian.org/src/sensible-utils/0.0.9/sensible-editor/

it uses nano and nano-tiny as primary fallback. So I'd argue there's prior art for that, and quite prominent one at that.

2021-08-18 14:05 UTC, poettering commented
to make this clear, the same way as we prefer `vim` over `vi`, i think we should prefer `emacs -nw` over `emacs` — if we decide to add emacs at all

2021-08-20 08:40 UTC, TriMoon commented
Why not remove the whole fallback mechanism and return with an error message saying you need an editor configured in `$EDITOR` instead?

That way everyone will be happy in the long run.

2022-08-03 08:06 UTC, poettering commented
PR would need a rebase. But frankly as pointed out I am not overly convinced about this. 

So if there's still major interest, and if @keszybz or so wants this, then please file a new rebased PR, but I personally don#t really see the point...

2022-08-03 08:06 UTC, closed without merging