Add a network timeout option to journal-upload
systemd/systemd pull request #19827
Opened 2021-06-05 13:41 UTC by codergem

When network connectivity to a systemd-journal-remote
server is down, systemd-journal-upload blocks forever in the call to the
curl_easy_perform api and gets killed by systemd after a watchdog
timeout. This results in a coredump. This change allows optionally
configuring systemd-journal-upload to use a maximum timeout
of for its curl operation, using curl's CURLOPT_TIMEOUT option.

> Which versions I saw this issue in:
Saw this issue in version 229 and 243.

> How I reproduced :
I have two devices D1 and D2, where D2 uses systemd-journal-upload to send its journal logs to D1's systemd-journal-remote. In the midst of a significant log rate on D2, when physical network connectivity between D1 and D2 goes down, we see the issue mentioned in commit description.

> Debug logs seen :
Aug 20 06:47:46 D2 ip[29201]: > POST /upload HTTP/1.1
Aug 20 06:47:46 D2 ip[29201]: Host: 172.17.17.2:19532
Aug 20 06:47:46 D2 ip[29201]: User-Agent: systemd-journal-upload systemd 229
Aug 20 06:47:46 D2 ip[29201]: Content-Type: application/vnd.fdo.journal
Aug 20 06:47:46 D2 ip[29201]: Transfer-Encoding: chunked
Aug 20 06:47:46 D2 ip[29201]: Accept: text/plain
Aug 20 06:47:46 D2 ip[29201]: Expect: 100-continue
Aug 20 06:47:46 D2 ip[29201]: [1B blob data]
Aug 20 06:47:47 D2 ip[29201]: * Done waiting for 100-continue
Aug 20 06:50:38 D2 systemd[1]: systemd-journal-upload.service: Watchdog timeout (limit 3min)!
Aug 20 06:50:38 D2 systemd[1]: systemd-journal-upload.service: Main process exited, code=dumped, status=6/ABRT
Aug 20 06:50:38 D2 systemd[1]: systemd-journal-upload.service: Unit entered failed state.
Aug 20 06:50:38 D2 systemd[1]: systemd-journal-upload.service: Failed with result 'core-dump'.

2021-06-05 13:48 UTC, codergem commented
- This pull request was raised to replace https://github.com/systemd/systemd/pull/17077. Have mentioned the reasons for that on https://github.com/systemd/systemd/pull/17077 at the end-of-page comment.
- Have addressed the changes that were last requested. So, you could compare with last patch on https://github.com/systemd/systemd/pull/17077.
- Do let me know in case further changes are required.

Sorry for the inconvenience if any.

2021-06-05 13:53 UTC, codergem commented
@poettering , request a review. Thanks.

2021-06-07 15:07 UTC, poettering requested changes

2021-06-07 15:07 UTC, poettering commented on man/journal-upload.conf.xml
> +        For details, see <citerefentry><refentrytitle>systemd.timer</refentrytitle><manvolnum>5</manvolnum></citerefentry>.
`systemd.time` is the right man page, i.e. drop the final "r".

2021-06-07 15:08 UTC, poettering commented on man/journal-upload.conf.xml
> +        For details, see <citerefentry><refentrytitle>systemd.timer</refentrytitle><manvolnum>5</manvolnum></citerefentry>.
(i see i mistyped that in my original comment, sorry for that)

2021-06-07 15:09 UTC, poettering commented on src/journal-remote/journal-upload.c
> +                }
please drop the {} around the if block here, as per our coding style we avoid them if there's only a single expression used inside the {}, like it is here

2021-06-07 15:09 UTC, poettering commented
looks great, just two minor nits.

2021-06-13 16:03 UTC, codergem commented
> looks great, just two minor nits.

Changes added. Not sure why two tests failed. One test had these two lines in it:
...
"invoke-rc.d: initscript gdm3, action "reload" failed."
...
"upstream             FAIL non-zero exit status 17"

2021-06-13 16:06 UTC, codergem commented
Tested the change in my setup and saw the below msg occurred as expected (used "NetworkTimeoutSec=120s"):

"Upload to http://172.17.17.2:19532/upload failed: Operation timed out after 120000 milliseconds with 0 bytes received"

2021-06-14 09:16 UTC, merged