NO MERGE: Initial implementation of dbus export
systemd/systemd pull request #20294
Opened 2021-07-24 17:51 UTC by igo95862

Interfaces from:
org.freedesktop.home1
org.freedesktop.hostname1
org.freedesktop.import1
org.freedesktop.locale1
org.freedesktop.LogControl1
org.freedesktop.login1
org.freedesktop.machine1
org.freedesktop.oom1
org.freedesktop.portable1
org.freedesktop.resolve1
org.freedesktop.systemd1
org.freedesktop.timedate1

2021-07-24 17:52 UTC, igo95862 commented
Would you mind providing feedback?

2021-07-24 18:03 UTC, igo95862 commented
How about putting the interface export as an auto-feature?

2021-07-26 15:16 UTC, poettering commented
Why this at all? Why isnt the cmdline-based export approach enough?

2021-07-26 16:08 UTC, igo95862 commented
> Why this at all? Why isnt the cmdline-based export approach enough?

Because not everyone know there are `--bus-introspect` arguments for certain binaries. I did not know until @keszybz pointed it out.

Even more not every binary has dbus support. I had to go through source code to figure out which ones do.

I mostly need them for code generation but I think its also nice that it would give an overview of what dbus interfaces are available for systemd.

2021-07-26 16:10 UTC, igo95862 commented
Projects that export their dbus introspection XML:

* NetworkManager
* fwupd
* Flatpak
* Gnome Shell
* Tracker3
* Avahi
* GeoClue

2021-07-27 12:23 UTC, keszybz requested changes
I think this is pretty OK.

Some high-level questions I had myself:
- do we want this at all? A bunch of different projects export such information (I have 92 files in /usr/share/dbus-1/interfaces/ on Fedora 34…). So I think it's fine that we do it too.
- should there be a single target or should meson handle iteration over the executables? I didn't like the approach with `output:'interfaces'`, but it seems to work quite well. It turns out it'd be pretty awkward to let meson do the iteration, because we don't have the interface list available, and only discover the list of outputs during build. So I think that approach is OK.
- there is some duplication with the list of documented xml interfaces using in `update-dbus-docs`. But we don't have everything documented, so I think it's OK to use a separate list here and generate the files based on that.

The whole thing should be made configurable… So please add a new meson option (`dbus-interfaces-dir` or so), and change
```py
dbus_interfaces_dir = get_option('dbus-interfaces-dir')
if dbus_interfaces_dir == '':
   dbus_interfaces_dir = get_option('datadir') + '/dbus-1'

...
install : dbus_interfaces_dir != 'no',
install_dir : dbus_interfaces_dir,
...
```

2021-07-27 12:23 UTC, keszybz commented on tools/dbus_exporter.py
> +    list_interfaces_process.check_returncode()
Please use `check=True` instead of an explicit check.

Is this using black or some other similar concept? Please use idiomatic python indentation similar to
```py
run([executable.absolute(), '--bus-introspect=list'],
       capture_output=True,
       text=True,
       check=True)
```
Not only is that vastly more readable, it's shorter too.

`text=True` or `universal_newlines=True` is preferred over explicit decoding.

2021-07-27 12:23 UTC, keszybz commented on tools/dbus_exporter.py
> +    interface_names = [x.split('\t')[1] for x in interfaces_lines]
Please just `.split()` here, to avoid hardcoding that the separator is a tab.

2021-07-27 12:23 UTC, keszybz commented on tools/dbus_exporter.py
> +        )
Same as above, please use `run([…], capture_output=True, text=True, check=True)`.

2021-07-27 12:23 UTC, keszybz commented on meson.build
> +systemd_exe = executable(
Maybe just make that `dbus_programs += executable(` (here and below)? Defining the variable just for one use is quite verbose.

2021-07-27 12:23 UTC, keszybz commented on meson.build
> +)
Please match the surrounding indentation style… Something like this:
```py
      custom_target(
             ...
             command : [export_dbus_interfaces_py, '@OUTPUT@', prog.full_path()])
```

You can drop the argument parsing then in the helper. `sys.argv[1]` and `sys.argv[2:]` are good enough.

2021-07-27 12:23 UTC, keszybz commented on meson.build
> +export_dbus_interfaces = find_program('tools/dbus_exporter.py')
Please call the variable and the program the same. We didn't always do this in the past, but now we're pretty good about this, and it makes it much easier to jump to the right file when looking at the meson command…
```
export_dbus_interfaces_py = find_program('tools/export_dbus_interfaces.py')
```

2021-07-27 12:29 UTC, igo95862 commented on tools/dbus_exporter.py
> +    list_interfaces_process.check_returncode()
I thought the minimum python version is 3.5? `text` and `universal_newlines` are from 3.7
> Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.

2021-07-27 12:40 UTC, igo95862 commented on meson.build
> +)
> You can drop the argument parsing then in the helper. `sys.argv[1]` and `sys.argv[2:]` are good enough.

I would have to manually implement conversions to `Path` class.

It is possible to setup argument parses to not require `--long-arguments` and instead use same behavior as `sys.argv[1]` and `sys.argv[2:]`.

2021-07-27 15:01 UTC, poettering commented
Is there any spec/doc/written down explanation about this dir? I mean, a long time ago we exposed that too, but it's so weird, since dbus introspection mixes type info with state into one XML mess, hence pretending the data was static is messy.

i.e. what tool do you have in mind that actually cares about that dir?

i know that some projects cargo cult these dirs, I used to maintain some which did. But I fail to see the point. If there's no consumer of this that actually reads the dir, and thus enshrines its location and semantics in code or spec or so then I am not convinced this is desirable.

Hence, please don't list which apps provide these files, tell me which files *process* the dir.

2021-07-27 17:53 UTC, igo95862 commented
Any code generator for dbus binds uses the introspection data from that folder. For example, [`gdbus-codegen`](https://developer.gnome.org/gio/stable/gdbus-codegen.html), [`dbus-codegen-go`](https://github.com/amenzhinsky/dbus-codegen-go) and etc... 

If someone wants to generate the binds they would go to that directory. (as I did)

> dbus introspection mixes type info with state into one XML mess

There won't be any state and type mix because each file only describes one interface independent of path.

An alternative might be placing some file called `where_to_find_systemd_introspection.txt` to that folder with instructions that `--bus-introspect` exist for certain systemd binaries.

2021-07-27 17:54 UTC, igo95862 commented on meson.build
> +)
I made the arguments to be position only but still with argparse. Its backward compatible to 3.5 I think.

2021-07-27 19:53 UTC, igo95862 commented on tools/dbus_exporter.py
> +    list_interfaces_process.check_returncode()
https://github.com/systemd/systemd/blob/99c645b81aa47899ae3e0f920947a7d86cca5a86/README#L195

2021-07-28 08:27 UTC, keszybz commented on tools/dbus_exporter.py
> +    list_interfaces_process.check_returncode()
Yeah, we probably shouldn't use `text`. But `universal_newlines` was there since python 3.0 or maybe even older. Please use that.

2021-07-28 08:31 UTC, keszybz commented on meson.build
> +        systemd_logind_exe = executable(
`dbus_programs += …` here.

2021-07-28 08:33 UTC, igo95862 commented on meson.build
> +        systemd_logind_exe = executable(
I will fix it later this evening.

2021-07-28 15:40 UTC, poettering commented
> Any code generator for dbus binds uses the introspection data from that folder. For example, [`gdbus-codegen`](https://developer.gnome.org/gio/stable/gdbus-codegen.html), [`dbus-codegen-go`](https://github.com/amenzhinsky/dbus-codegen-go) and etc...

Neither of these tools encode the dir though, or do they?

My assumption would be that noone actually uses the dir directly for code generation, but they all copy the interfaces files into their source tree, and then generate from there.

Isn't this a documentaiton issue more than anything else? i.e. shouldn't the man pages that document our D-Bus interfaces, mention which command to type in to acquire the current interface files?

If some tool would actually ook at that dir directly I'd be more sympathetic to this dir, but given its underspecification, and that actually no code actually really uses it makes me a bit conservative since it#s entirely redundant info that only developers ever should need. But the ones which do need to read the man pages anyway.

> 
> If someone wants to generate the binds they would go to that directory. (as I did)

2021-07-28 16:46 UTC, igo95862 commented
I found a project that explicitly mentions and uses the interfaces folder.

Its KDE: https://develop.kde.org/docs/d-bus/accessing_dbus_interfaces/

> Fortunately for us, this is precisely what Qt allows us to do. The only requirement is an XML file describing the D-Bus service. Such files are installed in the D-Bus prefix in the interfaces directory.

> Due to this combination of ease of use and compile-time checking, this is generally the preferred mechanism to use when accessing complicated D-Bus interfaces.

They have a `DBUS_INTERFACES_INSTALL_DIR` CMake variable that is set to `/usr/share/dbus-1/interfaces`

2021-12-10 07:51 UTC, keszybz commented
I forgot about this. I think we can merge this. It's lightweight enough that we can merge even if there aren't other users outside of KDE>

2021-12-10 07:51 UTC, merged

2021-12-10 08:00 UTC, igo95862 commented
@keszybz Thank you for merging my commit.

BTW `systemd-networkd` recently gained XML exports as well. This pull request was done before that. May I create another pull request that exports XML from it?

2021-12-10 08:02 UTC, mbiebl commented
from a packaging PoV: would you expect these files to be shipped in the main systemd package or in a -dev package?

2021-12-10 09:33 UTC, igo95862 commented
> Yes, please.

Ok, I will do that this evening.

2021-12-10 23:24 UTC, asavah commented
This PR breaks cross-compilation see #21730