Alternative to #20288
systemd/systemd pull request #20344
Opened 2021-07-29 15:10 UTC by poettering

I think this is a bit prettier, since it leaves our usual coding style assumptions in place, and clear separates out the codepaths safe to run from a signal handler and those which are not.

2021-07-29 15:27 UTC, keszybz reviewed
I'd say that sorting the array in place was a nice optimization. As mentioned in the original commit message, all callers create a temporary array to call this function, so duplicating the array is unnecessary in all cases. This also makes the code a bit more complicated… I think the new comment in freeze() is good, but I'm meh about the rest of the patch.

2021-07-29 15:27 UTC, keszybz commented on src/basic/fd-util.c
> +        for (fd = 3; fd >= 0; fd = fd < max_fd ? fd + 1 : -1) {
`int fd` here…

2021-07-29 15:27 UTC, keszybz commented on src/shared/exec-util.c
> +         * instead of plain close_all_fds() here, since we this to be compatible with being called from
Garbled sentence here…

2021-08-12 09:41 UTC, poettering commented
I force pushed a new version now, and I still think we shouldn't mangle input parameters needlessly. PTAL.

I looked at the close_all_fds() invocations, and as it turns out the majority passes 0 or 1 exception fds, so I figured it is worth adding explicit optimizatoin steps for those two cases, and for the remaining case the existing logic that uses stack allocation to copy the fd (for the typical case of few fds) and falls back to malloc (for the exceptional case of a large number of fds) should be OK.

I also added a test case, that checks if all fallback codepaths work correctly by making /proc and close_range() unavailable (via overmounting/seccomp).

2021-10-06 13:29 UTC, keszybz requested changes
> fd-util: split out inner fallback loop of close_all_fds() as close_all_fds_without_malloc()
>
> While we are at it, add two optimizations:

Hmm, can we plase have the split as a separate commit? It's pointlessly hard to review things when code moves are combined with other changes.

2021-10-06 13:29 UTC, keszybz commented on src/test/test-fd-util.c
> +        n_fds = MIN((max_fd & ~1U) - 10U, 5000U);
If `max_fd` is an int, why do we force the other operands to be unsigned?

2021-10-12 14:45 UTC, dnicolodi commented on src/basic/fd-util.c
> +                /* Close exactly one, then we don't need no sorting. This is a pretty common case, hence
I think this should read `Close all except one, ...`

2021-10-12 15:08 UTC, poettering commented on src/test/test-fd-util.c
> +        n_fds = MIN((max_fd & ~1U) - 10U, 5000U);
we ultimately want an unsigned value out of it, i.e. a size for an array. Also, bitwise operations on signed types of different sizes are weird, i.e. there will be sign extension going on, and I can't even think about what this really means here, so i made the unsigned stuff explicitl

2021-10-12 20:24 UTC, yuwata approved these changes
LGTM.

2021-10-27 15:02 UTC, bluca commented on src/basic/fd-util.c
> +                if (!IN_SET(de->d_type, DT_LNK, DT_UNKNOWN))
not sure I follow - this ensures that only symlinks or unknown types are closed below? Shouldn't it be the other way around?

2021-10-27 15:07 UTC, bluca commented on src/test/test-fd-util.c
> +static void seccomp_prohibit_close_range(void) {
shouldn't this return true if seccomp is enabled and false otherwise, so that the test below can avoid claiming to be testing the functionality and instead mark as skipped?

2021-10-27 15:08 UTC, poettering commented on src/basic/fd-util.c
> +                if (!IN_SET(de->d_type, DT_LNK, DT_UNKNOWN))
look into /proc/self/fd/ – each fd gets a symlink there, hence we are only interested in those dentries. we filter out anything here that definitely is not a symlink.

2021-10-27 15:08 UTC, bluca approved these changes
looks good, just two minor things

2021-10-27 15:09 UTC, bluca commented on src/basic/fd-util.c
> +                if (!IN_SET(de->d_type, DT_LNK, DT_UNKNOWN))
ah got it - looking at the diff context forgot this was looking at that

2021-10-27 20:02 UTC, merged