Fix typo in dbus property name ("OnSuccesJobMode")
systemd/systemd pull request #20466
Opened 2021-08-17 17:57 UTC by CyberShadow

I noticed this typo while troubleshooting something.

Not sure what the consequences of fixing it now are. Hope this helps. :)

2021-08-17 18:07 UTC, bluca commented
yeah we need to add a new one with the right name, and mark the old one as deprecated in the comments but leave it there, I'm afraid

2021-08-17 19:55 UTC, bluca approved these changes
lgtm

2021-08-17 21:21 UTC, yuwata requested changes

2021-08-17 21:21 UTC, yuwata commented on src/core/dbus-unit.c
> +        SD_BUS_PROPERTY("OnSuccesJobMode", "s", property_get_job_mode, offsetof(Unit, on_success_job_mode), SD_BUS_VTABLE_PROPERTY_CONST), /* deprecated */
Please add `SD_BUS_VTABLE_HIDDEN` flag.

2021-08-18 05:23 UTC, yuwata approved these changes
LGTM.

2021-08-18 07:00 UTC, merged

2021-08-18 14:56 UTC, poettering commented
lgtm