Nic coalesce support
systemd/systemd pull request #20477
Opened 2021-08-18 13:11 UTC by DaanDeMeyer

Includes one commit from @yuwata that still needs to land, will rebase once that happens so don't merge yet.

I'm not entirely sure about the naming of the options. I went with names that mostly match the names from the fields of the corresponding ethtool ioctl struct with two modifications:

- Make sure config names for microseconds always end in USec
- Add Coalesce to fields that didn't contain Coalesce in the name already to clearly indicate that they are coalescing settings.

2021-08-18 13:37 UTC, poettering requested changes

2021-08-18 13:37 UTC, poettering commented on src/shared/ethtool-util.c
> +#include "strv.h"
please keep this sorted

2021-08-18 13:37 UTC, poettering commented on src/shared/ethtool-util.c
> +) {
please move to end of previous line

2021-08-18 13:37 UTC, poettering commented on src/shared/ethtool-util.c
> +        }
please use separate parser functions if the fields are sufficeintly different. also use parse_sec() for parsing time values.

StatsBlockCoalesceUSec should probably be called StatisticsBlockCoalesceSec=. i.e, please no unnecessary abbreviations. And we use seconds as default time unit everywhere, please do so here too. If people specify other time units explicitly that takes precedence of course, and parse_sec() takes care of that.

2021-08-18 16:58 UTC, yuwata requested changes

2021-08-18 16:58 UTC, yuwata commented on src/shared/ethtool-util.c
> +        dst->set = false;
Please do not update `dst`, as `rvalue` may be an invalid string.

2021-08-18 16:58 UTC, yuwata commented on src/shared/ethtool-util.c
> +                return 0;
Please unset the values in that case:
```
if (isempty(rvalue)) {
    dst->value = 0;
    dst->set = false;
    return 0;
}
```

2021-08-18 16:58 UTC, yuwata commented on src/shared/ethtool-util.c
> +                return 0;
Same here.

2021-08-18 16:58 UTC, yuwata commented on src/shared/ethtool-util.h
> +        uint64_t value;
`uint64_t` -> `usec_t`

2021-08-19 11:16 UTC, DaanDeMeyer commented on src/shared/ethtool-util.c
> +                UPDATE(ecmd.rx_coalesce_usecs, coalesce->rx_coalesce_usecs.value, need_update);
Here we convert from unsigned 64-bit to unsigned 32-bit implicitly. Do we need to check anywhere if the value provided by the user is too large to fit inside unsigned 32-bit?

2021-08-19 11:34 UTC, DaanDeMeyer commented
Removed usec_opt and just reuse u32_opt for the usec values instead. In the `coalesce_parse_sec()` function we check if the parsed microseconds fit in the unsigned 32-bit value field of u32_opt.

2021-08-19 13:29 UTC, yuwata approved these changes
LGTM.

2021-08-19 23:32 UTC, merged