test: skip oomd test on a unified container on a hybrid host
systemd/systemd pull request #20705
Opened 2021-09-10 12:43 UTC by yuwata

Fixes #20593
Fixes #20655.

2021-09-10 12:44 UTC, yuwata commented
(I have no idea what we should do in oomd on such a case.)

2021-09-10 12:44 UTC, yuwata commented
cc @anitazha and @DaanDeMeyer

2021-09-10 14:47 UTC, DaanDeMeyer commented
Slightly out of my league as well. Let's wait for anita.

2021-09-10 17:21 UTC, anitazha commented
I need to check in more detail when I'm not AFK but memory.current is provided when the memory controller is enabled. So I think the correct message would be something like "cgroup2 memory controller is not enabled". And the actual daemon should also include a condition check for the memory controller.

2021-09-11 06:31 UTC, yuwata commented
Ah, checking the existence of memory controller is better. Thanks. Will update.

2021-09-11 11:57 UTC, yuwata commented
@anitazha Updated. PTAL.

2021-09-11 12:17 UTC, bluca commented
test-oomd still unhappy

2021-09-11 13:36 UTC, yuwata commented
Still not sure this is a correct way, but at least, now semaphoreci is green. PTAL.

2021-09-11 13:51 UTC, yuwata commented
What's the difference between `cg_kernel_controllers()` and `cg_mask_supported()`??

2021-09-12 00:54 UTC, anitazha requested changes
> What's the difference between `cg_kernel_controllers()` and `cg_mask_supported()`??

It looks like `cg_kernel_controllers()` parses /proc/cgroup which lists all the controllers (cgroup v1 and v2) compiled in the kernel (including information about how many cgroups are using them and whether they were disabled via boot parameter, etc.). But `cg_mask_supported()` will figure out which hierarchy systemd is using and list the available controllers based on the current hierarchy. For unified (cgroup v2) this will be /sys/fs/cgroups/cgroup.controllers.

Thanks for fixing this Yu the current approach lgtm. Should be good to merge after removing the calls to `cg_kernel_controllers()`

2021-09-12 00:54 UTC, anitazha commented on src/oom/oomd.c
> +
This is not needed since we have `cg_mask_supported` below

2021-09-12 00:54 UTC, anitazha commented on src/oom/test-oomd-util.c
> +
This is not needed since we have `cg_mask_supported` below

2021-09-12 01:31 UTC, yuwata commented
@anitazha Thank you for your review and the explanation. `cg_kernel_controllers()` are dropped. Upgrading the green label.

2021-09-12 11:56 UTC, bluca approved these changes
LGTM, thanks for fixing this, we can go back to seeing all green ticks yay

2021-09-12 11:56 UTC, merged