Use a simple kernel-compatible header for ioprio
systemd/systemd pull request #20736
Opened 2021-09-14 14:56 UTC by keszybz

2021-09-14 15:02 UTC, bluca approved these changes
LGTM

2021-09-14 15:08 UTC, poettering requested changes

2021-09-14 15:08 UTC, poettering commented on meson.build
> +                                 #include <unistd.h>'''],     # no known header declares ioprio_get
smells like something that would get added to `<sched.h>`, if it ever gets added, maybe look there too?

2021-09-14 15:08 UTC, poettering commented on src/basic/missing_syscall.h
> +        return syscall(__NR_ioprio_get, which, who, ioprio);
typo in first arg

2021-09-14 15:08 UTC, poettering commented on src/basic/missing_ioprio.h
> +#define IOPRIO_CLASS_SHIFT 13
i'd cover these via some `#ifndef` too, just in case this ever gets added to sched.h or so. i figure a single conditionalization suffices, i.e. `#ifndef IOPRIO_CLASS_NONE` or so.

and maybe add `#include <sched.h>` to the top?

2021-09-14 15:10 UTC, bluca commented
butterfly effect in action:

```
../src/basic/limits-util.c: In function ‘physical_memory’:01:29
../src/basic/limits-util.c:25:14: error: implicit declaration of function ‘sysconf’; did you mean ‘sscanf’? [-Werror=implicit-function-declaration]01:29
   25 |         sc = sysconf(_SC_PHYS_PAGES);01:29
      |              ^~~~~~~01:29
      |              sscanf01:29
../src/basic/limits-util.c:25:14: error: nested extern declaration of ‘sysconf’ [-Werror=nested-externs]01:29
../src/basic/limits-util.c:25:22: error: ‘_SC_PHYS_PAGES’ undeclared (first use in this function)01:29
   25 |         sc = sysconf(_SC_PHYS_PAGES);
```

2021-09-14 18:15 UTC, keszybz commented on src/basic/missing_syscall.h
> +        return syscall(__NR_ioprio_get, which, who, ioprio);
Arrgh, I was in a hurry but wanted to push this before leaving.

2021-09-14 18:22 UTC, keszybz commented
Updated with all the suggestions.

2021-09-14 18:38 UTC, yuwata commented
```
03:36:25     archlinux_systemd_ci: ../build/src/basic/procfs-util.c:185:28: error: implicit declaration of function 'sysconf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
03:36:25     archlinux_systemd_ci:         ticks_per_second = sysconf(_SC_CLK_TCK);
03:36:25     archlinux_systemd_ci:                            ^
03:36:25     archlinux_systemd_ci: ../build/src/basic/procfs-util.c:185:28: note: did you mean 'sscanf'?
03:36:25     archlinux_systemd_ci: /usr/include/stdio.h:415:28: note: 'sscanf' declared here
03:36:25     archlinux_systemd_ci: extern int __REDIRECT_NTH (sscanf, (const char *__restrict __s,
03:36:25     archlinux_systemd_ci:                            ^
03:36:25     archlinux_systemd_ci: /usr/include/sys/cdefs.h:192:6: note: expanded from macro '__REDIRECT_NTH'
03:36:25     archlinux_systemd_ci:      name proto __asm__ (__ASMNAME (#alias)) __THROW
03:36:25     archlinux_systemd_ci:      ^
03:36:25     archlinux_systemd_ci: ../build/src/basic/procfs-util.c:185:36: error: use of undeclared identifier '_SC_CLK_TCK'
03:36:25     archlinux_systemd_ci:         ticks_per_second = sysconf(_SC_CLK_TCK);
03:36:25     archlinux_systemd_ci:                                    ^
03:36:25     archlinux_systemd_ci: 2 errors generated.
```

2021-09-14 19:37 UTC, yuwata commented
Still CIs are unhappy.

2021-09-15 07:00 UTC, keszybz commented
> Still CIs are unhappy.

But each time for a different reason! This is really a butterfly effect.

2021-09-15 07:16 UTC, poettering commented
lgtm

2021-09-21 10:16 UTC, poettering commented
CI fialure

```
../src/machine/operation.c: In function ‘operation_done’:
../src/machine/operation.c:31:18: error: implicit declaration of function ‘read’; did you mean ‘readv’? [-Werror=implicit-function-declaration]
   31 |         else if (read(o->errno_fd, &r, sizeof(r)) != sizeof(r)) { /* Try to acquire error code for failed operation */
      |                  ^~~~
      |                  readv
../src/machine/operation.c:31:18: err
```

2021-09-21 10:24 UTC, keszybz commented
I don't understand why I won't see those failures here. I even copied the compiler command line and the builds pass.

2021-09-21 10:40 UTC, keszybz commented
I don't see those failure on Fedora, but I see then on Debian. Anyway, it should pass now.

2021-09-21 11:09 UTC, bluca commented
Can you rebase to pick up af861917c5118cb9f1490f407d86f40fd5e01437 so that we can be sure packit builds are happy too?

2021-09-21 12:04 UTC, bluca commented
And now of course it times out...

2021-09-21 12:04 UTC, bluca commented
/packit copr-build

2021-09-21 13:30 UTC, bluca commented
This doesn't look good:

```
TEST-01-BASIC:                      FAIL     ( 35 s)
TEST-02-UNITTESTS:                  FAIL     (  2 s)
TEST-03-JOBS:                       FAIL     (  0 s)
TEST-04-JOURNAL:                    FAIL     (  1 s)
TEST-05-RLIMITS:                    FAIL     (  0 s)
TEST-06-SELINUX:                    SUCCESS  (  0 s)
TEST-07-ISSUE-1981:                 FAIL     (  1 s)
TEST-08-ISSUE-2730:                 FAIL     ( 33 s)
TEST-09-ISSUE-2691:                 SUCCESS  (  1 s)
TEST-10-ISSUE-2467:                 FAIL     (  1 s)
TEST-11-ISSUE-3166:                 SUCCESS  (  0 s)
TEST-12-ISSUE-3171:                 FAIL     (  1 s)
TEST-13-NSPAWN-SMOKE:               SUCCESS  (  1 s)
TEST-14-MACHINE-ID:                 SUCCESS  (  2 s)
TEST-15-DROPIN:                     FAIL     (  0 s)
TEST-16-EXTEND-TIMEOUT:             FAIL     (  1 s)
TEST-17-UDEV:                       SUCCESS  (  1 s)
TEST-18-FAILUREACTION:              FAIL     (  0 s)
TEST-19-DELEGATE:                   SUCCESS  (  1 s)
TEST-20-MAINPIDGAMES:               FAIL     (  0 s)
TEST-22-TMPFILES:                   FAIL     (  1 s)
TEST-23-TYPE-EXEC:                  FAIL     (  1 s)
TEST-24-CRYPTSETUP:                 FAIL     ( 34 s)
TEST-26-SETENV:                     FAIL     (  0 s)
TEST-27-STDOUTFILE:                 FAIL     (  1 s)
TEST-28-PERCENTJ-WANTEDBY:          FAIL     (  1 s)
TEST-29-PORTABLE:                   SUCCESS  (  5 s)
TEST-30-ONCLOCKCHANGE:              SUCCESS  (  0 s)
TEST-31-DEVICE-ENUMERATION:         SUCCESS  (  1 s)
TEST-32-OOMPOLICY:                  SUCCESS  (  1 s)
TEST-33-CLEAN-UNIT:                 FAIL     (  0 s)
TEST-34-DYNAMICUSERMIGRATE:         FAIL     (  1 s)
TEST-37-RUNTIMEDIRECTORYPRESERVE:   FAIL     (  1 s)
TEST-38-FREEZER:                    SUCCESS  (  0 s)
TEST-39-EXECRELOAD:                 FAIL     (  1 s)
TEST-40-EXEC-COMMAND-EX:            FAIL     (  0 s)
TEST-41-ONESHOT-RESTART:            FAIL     (  1 s)
TEST-42-EXECSTOPPOST:               FAIL     (  1 s)
TEST-43-PRIVATEUSER-UNPRIV:         FAIL     (  0 s)
TEST-44-LOG-NAMESPACE:              FAIL     (  1 s)
TEST-46-HOMED:                      FAIL     (  1 s)
TEST-47-ISSUE-14566:                FAIL     (  0 s)
TEST-48-START-STOP-NO-RELOAD:       FAIL     (  1 s)
TEST-49-RUNTIME-BIND-PATHS:         FAIL     (  1 s)
TEST-50-DISSECT:                    SUCCESS  (  5 s)
TEST-51-ISSUE-16115:                FAIL     (  0 s)
TEST-52-HONORFIRSTSHUTDOWN:         FAIL     (  1 s)
TEST-53-ISSUE-16347:                SUCCESS  (  0 s)
TEST-54-CREDS:                      FAIL     (  1 s)
TEST-55-OOMD:                       FAIL     (  1 s)
TEST-57-ONSUCCESS-UPHOLD:           FAIL     (  1 s)
TEST-58-REPART:                     SUCCESS  (  1 s)
TEST-59-RELOADING-RESTART:          FAIL     (  0 s)
TEST-60-MOUNT-RATELIMIT:            FAIL     (  1 s)
TEST-62-RESTRICT-IFACES:            SUCCESS  (  1 s)
TEST-63-ISSUE-17433:                FAIL     (  0 s)
TEST-64-UDEV-STORAGE:               SUCCESS  (  0 s)
TEST-65-ANALYZE:                    FAIL     (  1 s)
```

2021-09-21 13:40 UTC, keszybz commented
Hmm
```
+ env --unset=UNIFIED_CGROUP_HIERARCHY --unset=SYSTEMD_NSPAWN_UNIFIED_HIERARCHY /bin/systemd-nspawn --register=no --kill-signal=SIGKILL --directory=/var/tmp/systemd-test.aTbJgI/root --setenv=SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-51.units:/usr/lib/systemd/tests/testdata/units: /lib/systemd/systemd systemd.unit=testsuite.target systemd.wants=testsuite-51.service systemd.wants=end.service
Spawning container root on /var/tmp/systemd-test.aTbJgI/root.
Press ^] three times within 1s to kill container.
Failed to read machine ID from container image: Invalid argument
E: nspawn failed with exit code 1
```

2021-09-21 13:47 UTC, bluca commented
I've kicked s390x too, let's see if it happens again

2021-09-21 13:54 UTC, keszybz commented
packit failed with: `pigz: abort: write error on <stdout> (No space left on device)`

2021-09-21 14:37 UTC, bluca commented
ppc64 too:

```
TEST-01-BASIC:                      FAIL     ( 51 s)
TEST-03-JOBS:                       FAIL     (  3 s)
TEST-04-JOURNAL:                    FAIL     (  1 s)
TEST-05-RLIMITS:                    FAIL     (  2 s)
TEST-06-SELINUX:                    SUCCESS  (  0 s)
TEST-07-ISSUE-1981:                 FAIL     (  0 s)
TEST-08-ISSUE-2730:                 FAIL     ( 54 s)
TEST-09-ISSUE-2691:                 FAIL     (  0 s)
TEST-10-ISSUE-2467:                 FAIL     (  1 s)
TEST-11-ISSUE-3166:                 FAIL     (  0 s)
TEST-12-ISSUE-3171:                 FAIL     (  0 s)
TEST-13-NSPAWN-SMOKE:               FAIL     (  1 s)
TEST-14-MACHINE-ID:                 FAIL     (  0 s)
TEST-15-DROPIN:                     FAIL     (  1 s)
TEST-16-EXTEND-TIMEOUT:             FAIL     (  0 s)
TEST-17-UDEV:                       FAIL     (  1 s)
TEST-18-FAILUREACTION:              FAIL     (  0 s)
TEST-19-DELEGATE:                   FAIL     (  0 s)
TEST-20-MAINPIDGAMES:               FAIL     (  1 s)
TEST-22-TMPFILES:                   FAIL     (  0 s)
TEST-23-TYPE-EXEC:                  FAIL     (  0 s)
TEST-24-CRYPTSETUP:                 FAIL     ( 56 s)
TEST-26-SETENV:                     FAIL     (  0 s)
TEST-27-STDOUTFILE:                 FAIL     (  0 s)
TEST-28-PERCENTJ-WANTEDBY:          FAIL     (  1 s)
TEST-29-PORTABLE:                   FAIL     (  0 s)
TEST-30-ONCLOCKCHANGE:              FAIL     (  1 s)
TEST-31-DEVICE-ENUMERATION:         FAIL     (  0 s)
TEST-32-OOMPOLICY:                  FAIL     (  1 s)
TEST-33-CLEAN-UNIT:                 FAIL     (  0 s)
TEST-34-DYNAMICUSERMIGRATE:         FAIL     (  0 s)
TEST-36-NUMAPOLICY:                 FAIL     (  1 s)
TEST-37-RUNTIMEDIRECTORYPRESERVE:   FAIL     (  0 s)
TEST-38-FREEZER:                    FAIL     (  1 s)
TEST-39-EXECRELOAD:                 FAIL     (  0 s)
TEST-40-EXEC-COMMAND-EX:            FAIL     (  0 s)
TEST-41-ONESHOT-RESTART:            FAIL     (  1 s)
TEST-42-EXECSTOPPOST:               FAIL     (  0 s)
TEST-43-PRIVATEUSER-UNPRIV:         FAIL     (  1 s)
TEST-44-LOG-NAMESPACE:              FAIL     (  0 s)
TEST-46-HOMED:                      FAIL     (  0 s)
TEST-47-ISSUE-14566:                FAIL     (  1 s)
TEST-48-START-STOP-NO-RELOAD:       FAIL     (  0 s)
TEST-49-RUNTIME-BIND-PATHS:         FAIL     (  0 s)
TEST-50-DISSECT:                    FAIL     (  1 s)
TEST-51-ISSUE-16115:                FAIL     (  1 s)
TEST-52-HONORFIRSTSHUTDOWN:         FAIL     (  0 s)
TEST-53-ISSUE-16347:                FAIL     (  0 s)
TEST-54-CREDS:                      FAIL     (  1 s)
TEST-55-OOMD:                       FAIL     (  0 s)
TEST-57-ONSUCCESS-UPHOLD:           FAIL     (  1 s)
TEST-58-REPART:                     FAIL     (  0 s)
TEST-59-RELOADING-RESTART:          FAIL     (  1 s)
TEST-60-MOUNT-RATELIMIT:            FAIL     (  0 s)
TEST-62-RESTRICT-IFACES:            FAIL     (  1 s)
TEST-63-ISSUE-17433:                FAIL     (  0 s)
TEST-64-UDEV-STORAGE:               SUCCESS  (  0 s)
TEST-65-ANALYZE:                    FAIL     (  1 s)
```

2021-09-21 15:45 UTC, keszybz commented
```
--x-- Running TEST-65-ANALYZE --x--
+ make -C TEST-65-ANALYZE setup run
make: Entering directory '/tmp/autopkgtest.AXhch5/build.IiK/systemd/test/TEST-65-ANALYZE'
TEST-65-ANALYZE SETUP: test analyze
Reusing existing cached image /tmp/autopkgtest.AXhch5/build.IiK/systemd/test/TEST-65-ANALYZE/../default.img → /tmp/autopkgtest.AXhch5/build.IiK/systemd/test/default.img
'/var/tmp/systemd-test.0Cf9Ip/default.img' -> '/tmp/autopkgtest.AXhch5/build.IiK/systemd/test/default.img'
I: Masking supporting services
ln: failed to access '/var/tmp/systemd-test.0Cf9Ip/root/etc/systemd/system/systemd-hwdb-update.service': Structure needs cleaning
make: *** [Makefile:2: setup] Error 1
make: Leaving directory '/tmp/autopkgtest.AXhch5/build.IiK/systemd/test/TEST-65-ANALYZE'
```

Dunno, this feels like some hardware failure.

2021-09-21 18:17 UTC, bluca commented
re-runs are failing too, seems unlikely to be a coincidence, although I really can't tell how this would break nspawn...

2021-09-21 18:33 UTC, mrc0mmand commented
Well, I guess the TEST-* fails are caused by this:

```
I: Install system fonts
I: Install keymaps
I: Install terminfo files
D: Installing /lib/terminfo/l/linux
D: Install executables from the service files
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/cryptdisks-early.service: No such file or directory
I: Attempting to install /bin/bash (based on unit file reference)
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/cryptdisks.service: No such file or directory
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/hwclock.service: No such file or directory
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/rc.service: No such file or directory
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/rcS.service: No such file or directory
sed: can't read /var/tmp/systemd-test.wpb3Gh/root//lib/systemd/system/x11-common.service: No such file or directory
I: Attempting to install /bin/kmod (based on unit file reference)
I: Attempting to install /bin/plymouth (based on unit file reference)
D: Installing /usr/lib/s390x-linux-gnu/libply.so.5.0.0
D: Installing /bin/plymouth
I: Attempting to install /bin/rm (based on unit file reference)
I: Attempting to install /bin/true (based on unit file reference)
I: Attempting to install /etc/rc.local (based on unit file reference)
D: Installing /etc/rc.local
I: Attempting to install /lib/systemd/systemd (based on unit file reference)
I: Attempting to install /lib/systemd/systemd-backlight (based on unit file reference)
I: Attempting to install /lib/systemd/systemd-binfmt (based on unit file reference)
I: Attempting to install /lib/systemd/systemd-bless-boot (based on unit file reference)
make: Leaving directory '/tmp/autopkgtest.AZiAbh/build.gIz/systemd/test/TEST-01-BASIC'
--x-- Result of TEST-01-BASIC: 2 --x--
make: *** [Makefile:2: setup] Error 1
```

As building of the test image fails when running the first test (which is TEST-01-BASIC), all subsequent tests try to use the half-baked image left over by TEST-01-BASIC. Now the question is what's causing this test to fail during setup.

2021-09-21 18:34 UTC, bluca commented
ugh we should really stop the test run when that happens

2021-09-21 18:57 UTC, keszybz commented
OK, I'll need to take a deeper look.

2021-09-21 18:59 UTC, bluca commented
I'm trying to reproduce on an s390x porter box

2021-09-21 19:00 UTC, mrc0mmand commented
Doing something like `make -C test/TEST-01-BASIC clean setup debug=1` on one of such systems should give us an answer (and I guess I should look into some logging improvements regarding `test/test-functions` stuff...).

2021-09-21 19:01 UTC, bluca commented
gah I don't have root so can't run the tests

2021-09-21 20:36 UTC, mrc0mmand commented
I managed to reproduce it with my very WIP PR (https://github.com/systemd/systemd-centos-ci/pull/308), and the issue seems to be with the `systemd-bless-boot` binary:

```
22:32:31 + [[ 1 -eq 1 ]]
22:32:31 + for path in "" bin sbin usr/bin usr/sbin
22:32:31 + [[ -e /var/tmp/TEST-01-BASIC_sanitizers-nspawn/root//usr/lib/systemd/systemd-bless-boot ]]
22:32:31 + for path in "" bin sbin usr/bin usr/sbin
22:32:31 + [[ -e /var/tmp/TEST-01-BASIC_sanitizers-nspawn/root/bin//usr/lib/systemd/systemd-bless-boot ]]
22:32:31 + for path in "" bin sbin usr/bin usr/sbin
22:32:31 + [[ -e /var/tmp/TEST-01-BASIC_sanitizers-nspawn/root/sbin//usr/lib/systemd/systemd-bless-boot ]]
22:32:31 + for path in "" bin sbin usr/bin usr/sbin
22:32:31 + [[ -e /var/tmp/TEST-01-BASIC_sanitizers-nspawn/root/usr/bin//usr/lib/systemd/systemd-bless-boot ]]
22:32:31 + for path in "" bin sbin usr/bin usr/sbin
22:32:31 + [[ -e /var/tmp/TEST-01-BASIC_sanitizers-nspawn/root/usr/sbin//usr/lib/systemd/systemd-bless-boot ]]
22:32:31 ++ find_binary /usr/lib/systemd/systemd-bless-boot
22:32:31 ++ local bin=/usr/lib/systemd/systemd-bless-boot
22:32:31 ++ [[ -z '' ]]
22:32:31 ++ [[ -x /usr/lib/systemd/systemd-bless-boot ]]
22:32:31 ++ strstr /usr/lib/systemd/systemd-bless-boot .so
22:32:31 ++ '[' /usr/lib/systemd/systemd-bless-boot '!=' /usr/lib/systemd/systemd-bless-boot ']'
22:32:31 ++ type -P /usr/lib/systemd/systemd-bless-boot
22:32:31 + bin=
22:32:31 + return 1
22:32:31 + for fun in inst_symlink inst_script inst_binary inst_simple
22:32:31 + inst_simple /usr/lib/systemd/systemd-bless-boot
22:32:31 + [[ -f /usr/lib/systemd/systemd-bless-boot ]]
22:32:31 + return 1
22:32:31 + return 1
22:32:31 + '[' /usr/lib/systemd/systemd-bless-boot '!=' /usr/lib/systemd/systemd-bless-boot ']'
22:32:31 + '[' /usr/lib/systemd/systemd-bless-boot '!=' /usr/lib/systemd/systemd-bless-boot ']'
22:32:31 + '[' systemd-bless-boot == plymouth ']'
22:32:31 make: *** [Makefile:2: setup] Error 1
22:32:31 make: Leaving directory '/root/systemd/test/TEST-01-BASIC'
```

Looking at the recent PRs, this is not the first one where the issue occurs, so it's definitely caused by @keszybz's changes.

2021-09-21 20:42 UTC, mrc0mmand commented
> > Looking at the recent PRs, this is not the first one where the issue occurs, so it's definitely caused by @keszybz's changes.
> 
> You mean definitely _not_ caused by these changes?

Whoops, yeah, definitely **not** caused.

Looking at the code from #20591, we need to use `HAVE_GNU_EFI` here as well:
https://github.com/msekletar/systemd/blob/fbe3a414e1d8f7b05dccf3d24d4fa475eb9c6bc9/units/meson.build#L184

since the `HAVE_GNU_EFI` guard is used to build `systemd-bless-boot` in the first place:

https://github.com/msekletar/systemd/blob/fbe3a414e1d8f7b05dccf3d24d4fa475eb9c6bc9/meson.build#L2226-L2254

/cc @msekletar

2021-09-21 20:45 UTC, bluca commented
Nice catch! Want to send a PR?

2021-09-21 20:46 UTC, mrc0mmand commented
> Nice catch! Want to send a PR?

Will do!

2021-09-22 08:09 UTC, msekletar commented
@mrc0mmand thanks for looking into this!

2021-09-22 08:21 UTC, yuwata commented
Two ubuntu CIs are timed out. That should not be related, I hope. LGTM.

2021-09-22 09:17 UTC, bluca commented
@keszybz want to give this a rebase to pick up the fix for the above issue? Just in case

2021-09-22 14:46 UTC, merged