various sysctl-util.c cleanups
systemd/systemd pull request #20746
Opened 2021-09-15 07:30 UTC by poettering

2021-09-15 07:42 UTC, yuwata approved these changes
LGTM.

2021-09-15 10:14 UTC, poettering commented
hmm, the CI failures are probably relevant

2021-09-15 11:29 UTC, yuwata commented
```
======================================================================
FAIL: test_sysctl (__main__.NetworkdNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/test/test-network/systemd-networkd-tests.py", line 2750, in test_sysctl
    self.assertEqual(read_ipv6_sysctl_attr('dummy98', 'forwarding'), '1')
AssertionError: '0' != '1'
- 0
+ 1
```

2021-09-15 11:31 UTC, yuwata commented
```
Setting '/proc/sys/net/ipvipv4/ip_forward' to '1'
dummy98: Cannot turn on IPv4 packet forwarding, ignoring: No such file or directory
dummy98: Cannot configure IPv6 packet forwarding, ignoring: Invalid argument
```

2021-09-15 11:33 UTC, yuwata requested changes

2021-09-15 11:33 UTC, yuwata commented on src/basic/sysctl-util.c
> +                p = strjoina("net/ipv", af_to_ipv4_ipv6(af), "/", property);
`"net/ipv"` -> `"net/"`

2021-09-15 11:33 UTC, yuwata commented on src/basic/sysctl-util.c
> +                p = strjoina("net/ipv", af_to_ipv4_ipv6(af), "/", property);
Same here. `"net/ipv"` -> `"net/"`

2021-09-15 11:37 UTC, yuwata requested changes

2021-09-15 11:37 UTC, yuwata commented on src/basic/sysctl-util.c
> +                if (!ifname_valid(ifname))
`"all"` and `"default"` should be also allowed.

2021-09-15 11:37 UTC, yuwata commented on src/basic/sysctl-util.c
> +                if (!ifname_valid(ifname))
Here too.

2021-09-15 14:41 UTC, poettering commented
force pushed a new version. fixed the issues raised, and added a test to make sure the CI failure from earlier doesn't regress

2021-09-15 14:44 UTC, yuwata approved these changes
LGTM.

2021-09-15 22:01 UTC, merged

2021-09-18 04:44 UTC, floppym commented on src/basic/sysctl-util.c
> +        return write_string_file(p, value, WRITE_STRING_FILE_VERIFY_ON_FAILURE | WRITE_STRING_FILE_DISABLE_BUFFER);
We intentionally made sysctl_write() call write() directly in 521251d2757295b6e9df4b51c7cb33929fbd65c4 to resolve #7744. It seems likely that you have re-introduced that problem.