basic: add recurse_dir() function as modern replacement for nftw()
systemd/systemd pull request #20910
Opened 2021-10-01 15:27 UTC by poettering

The new API is built around openat(), O_PATH, statx() and thus be much nicer feature-wise and less prone to races.

2021-10-04 09:33 UTC, poettering commented
Uh, that gcc CI failure is weird. Makes no sense to me at all? Anyone can make sense of this? compiler bug?

2021-10-04 09:48 UTC, mrc0mmand commented on src/test/test-recurse-dir.c
> +        assert(nftw(p, nftw_cb, 64, FTW_PHYS|FTW_MOUNT) >= 0);
`assert_se()`? Since otherwise it breaks with `-Db_ndebug=true`.

2021-10-04 09:53 UTC, mrc0mmand commented
> Uh, that gcc CI failure is weird. Makes no sense to me at all? Anyone can make sense of this? compiler bug?

I guess both the newly introduced tests should use `assert_se()` instead of `assert()` (in cases where we call some function), otherwise the tests might not work as expected with `-Db_ndebug=true`.

2021-10-04 13:07 UTC, mrc0mmand commented
This makes the computer sad:

```
 465/1263 test-recurse-dir                                                                            FAIL              0.85s   killed by signal 6 SIGABRT
>>> SYSTEMD_KBD_MODEL_MAP=/build/src/locale/kbd-model-map SYSTEMD_LANGUAGE_FALLBACK_MAP=/build/src/locale/language-fallback-map PATH=/systemd-meson-build:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl MALLOC_PERTURB_=60 /systemd-meson-build/test-recurse-dir
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
entry 17 different: /usr/share/man/da.ISO8859-1/ vs /usr/share/man/da/
Code should not be reached at src/test/test-recurse-dir.c:149, function main(). Aborting. 💥
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

2021-10-04 16:22 UTC, mrc0mmand commented
Debian/Ubuntu is still unhappy:

```gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  main (argc=1, argv=0x7ffccc8b7ae8) at ../src/src/test/test-recurse-dir.c:148
148	                if (!streq_ptr(list_nftw[i], list_recurse_dir[i])) {
(gdb) bt full
#0  main (argc=1, argv=0x7ffccc8b7ae8) at ../src/src/test/test-recurse-dir.c:148
        i = 0
        list_recurse_dir = 0x0
        p = 0x55780bd962b8 "/usr/share/man"
        r = 0
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
(gdb) p list_recurse_dir
$3 = (char **) 0x0
```

because `/usr/share/man` is empty in the mkosi images:

```
# ls -la /usr/share/man
total 0
drwxr-xr-x 1 root root    0 Feb 22  2021 .
drwxr-xr-x 1 root root 1070 Oct  4 18:13 ..
```

reproducer:

```
# mkdir empty
# ./test-recurse-dir empty/
Segmentation fault (core dumped)
```

2021-10-05 15:05 UTC, yuwata commented on src/basic/recurse-dir.c
> +                 */
Not a matter, but the comment has unnecessary blank line. Did you forget to add something after the enumerated entries??

2021-10-05 15:05 UTC, yuwata commented on src/basic/recurse-dir.c
> +                                                 statx_mask != 0 ? &sx : NULL,
Should this be `sx_valid ? &sx : NULL`??

2021-10-05 15:05 UTC, yuwata commented on src/basic/recurse-dir.c
> +                                         statx_mask != 0 ? &sx : NULL,
Same here.

2021-10-05 15:05 UTC, yuwata commented on src/basic/recurse-dir.h
> +                const struct statx *sx,  /* statx data (unly if statx_mask was non-zero */
unly -> only

Also, missing ')'

2021-10-05 15:13 UTC, poettering commented on src/basic/recurse-dir.c
> +                 */
nope, the list is complete, it's the three "clean" cases we have in the inner loop: pin by O_DIRECTORY, pin by O_PATH, and no pinning of the directory entry.

2021-10-05 15:13 UTC, poettering commented on src/basic/recurse-dir.c
> +                 */
(will remove the empty line)

2021-10-05 15:16 UTC, poettering commented on src/basic/recurse-dir.c
> +                                                 statx_mask != 0 ? &sx : NULL,
no, this is intended: we don#t want to pass the statx data unless the user actually asked for it by setting `statx_mask` to non-zero. We'll query statx() for some other internal reasons, but in that case I dont think we should pass the acquired data along in order not to hide bugs.

2021-10-05 15:16 UTC, poettering commented on src/basic/recurse-dir.c
> +                                                 statx_mask != 0 ? &sx : NULL,
will add comments about this

2021-10-05 15:45 UTC, yuwata requested changes

2021-10-05 15:45 UTC, yuwata commented on src/shared/cgroup-setup.c
> +                log_debug_errno(r, "Failed to trim cgroup %s: %m", path);
Maybe, add ", ignoring" ??

2021-10-05 15:45 UTC, yuwata commented on src/shared/cgroup-setup.c
> +                                log_debug_errno(q, "Failed to trim compat systemd cgroup %s: %m", path);
Also here. The error will be ignored.

2021-10-05 15:45 UTC, yuwata commented on src/shared/kbd-util.c
> +        if (r < 0 && r != -EEXIST)
Not a matter, but if I remember correctly, `set_consume()` does not return `-EEXIST`.

Also, you can use `set_ensure_consume()`.

2021-10-05 15:45 UTC, yuwata commented on src/shared/kbd-util.c
> +                }
Why do you ignore `-ENOMEM` in this case?

2021-10-05 15:45 UTC, yuwata commented on src/test/test-kbd-util.c
> +                assert(keymap_exists(*m) > 0);
`assert_se()`?

2021-10-05 15:45 UTC, yuwata commented on src/test/test-kbd-util.c
> +                log_info("Found keympa: %s", *m);
"keympa" -> "keymap"

2021-10-06 09:01 UTC, poettering commented on src/shared/kbd-util.c
> +        if (r < 0 && r != -EEXIST)
Hmm, using set_ensure_consume() would mean we couldn't pass a compound struct as userdata anymore, and then couldn't just free the set vi `_cleanup_(set_free_freep)` anymore there, we#d have to define a new destructor to destroy the structure then. So I figured it's simpler to just pre-allocate the Set and pass a pointer to that.

2021-10-06 09:23 UTC, yuwata commented on src/shared/kbd-util.c
> +        if (r < 0 && r != -EEXIST)
Indeed.

2021-10-06 18:46 UTC, yuwata requested changes

2021-10-06 18:46 UTC, yuwata commented on src/shared/cgroup-setup.c
> +                log_debug_errno(r, "Failed to trim cgroup %s, ignoring: %m", path);
Nah, `-ENOENT` should be ignored. Currently, all negative errno is returned at the end.

2021-10-07 00:19 UTC, yuwata requested changes

2021-10-07 00:19 UTC, yuwata commented on src/shared/cgroup-setup.c
> +                log_debug_errno(r, "Failed to iterate through cgroup %s, ignoring: %m", path);
Then, the error will not be ignored. Please drop ", ignoring".

2021-10-07 00:19 UTC, yuwata commented on src/shared/cgroup-setup.c
> +                        log_debug_errno(errno, "Failed to trim cgroup %s, ignoring: %m", path);
The error will not be ignored. Please drop ", ignoring".

2021-10-07 00:19 UTC, yuwata commented on src/shared/cgroup-setup.c
> +        if (q > 0 && streq(controller, SYSTEMD_CGROUP_CONTROLLER))
`controller` is non-NULL? Then, I'd like to add assert() at the beginning. Or, streq_ptr() is better.

2021-10-07 13:00 UTC, yuwata approved these changes

2021-10-07 20:12 UTC, merged