coredump: Add --all option
systemd/systemd pull request #20946
Opened 2021-10-06 12:50 UTC by DaanDeMeyer

This option has coredumpctl look at all journals instead of only the
local ones. This allows coredumpctl to show information about remote
coredumps if the coredumps are made available in /var/lib/systemd/coredump
and the corresponding journals are made available in /var/log/journal.

This is already possible using the --directory option but --all makes it
more user friendly since users don't have to enter the journal directory
anymore as long as it's available under /var/log/journal.

2021-10-06 17:25 UTC, yuwata requested changes
Please update help message, shell completions, and man page.

2021-10-06 19:23 UTC, bluca commented on shell-completion/bash/coredumpctl
> +                -A --debugger-arguments --json -n --all'
zsh too

2021-10-06 20:25 UTC, poettering requested changes

2021-10-06 20:25 UTC, poettering commented on man/coredumpctl.xml
> +        <listitem><para>Look at all available journal files in /var/log/journal (excluding journal
enclose the dir in `<filename>` tag

also, please suffix dirs with `/` to indicate that tey are dirs. We try to do that all across our docs. i.e. `/var/log/journal/` rather than `/var/log/journal` please

2021-10-07 11:24 UTC, bluca approved these changes
lgtm

2021-10-07 11:37 UTC, bluca commented
```
coredumpctl --help output is too wide:
     --all                     Look at all journal files instead of only local ones
```

2021-10-07 13:30 UTC, yuwata approved these changes
LGTM.

2021-10-07 20:13 UTC, merged