journal: Don't discard kmsg messages coming from journald itself
systemd/systemd pull request #20982
Opened 2021-10-11 13:16 UTC by DaanDeMeyer

Previously, we discarded any kmsg messages coming from journald
itself to avoid infinite loops where potentially the processing
of a kmsg message causes journald to log one or more messages to
kmsg which then get read again by the kmsg handler, ...

However, if we completely disable logging whenever we're processing
a kmsg message coming from journald itself, we also prevent any
infinite loops as we can be sure that journald won't accidentally
generate logging messages while processing a kmsg log message.

This change allows us to store all journald logs generated during
the processing of log messages from other services in the system
journal. Previously these could only be found in kmsg which has
low retention, can't be queried using journalctl and whose logs
don't survive reboots.

With this approach there's a chance that important logging messages 
from journald are discarded as any errors generated during the 
processing of its own kmsg messages will be discarded. However, 
given the mentioned problems with kmsg, this still seems like it would
make debugging journald much easier since there's a much bigger chance
that journald logs will still be available due to the journal's higher
overall retention.

2021-10-12 07:49 UTC, poettering commented on src/journal/journald-kmsg.c
> +                }
is this really an improvement? previously you had the full set of journald messages in kmsg. Yes, they didn't end up on disk, but it was relatively easy to debug journald because you knew where to look.

With this change now journald will go entirely silent while we write stuff and there's no way to get the data out of journald.

What am I missing?

2021-10-12 08:11 UTC, daandemeyer commented on src/journal/journald-kmsg.c
> +                }
We'll still get all the journald messages in kmsg and the journal that are generated by journald when writing log messages that don't come from journald itself. What we won't get is log messages if something goes wrong while writing log messages generated by journald from kmsg to the journal.

I think this is OK because the amount of log messages coming from journald will be a very small percentage of all log messages generated by the system. As a result, the chance that something will go wrong when logging a journald log message to the journal seems equally small.

What we gain is the longer retention and logs that survive boots for journald log messages (and all all the other goodness provided by having logs in the journal). I'm planning to add some extra logging around journal rotations for example and such logs are likely to occur between boots. Having those log messages available after rebooting can help a lot when debugging journald.

So like all things it's a trade-off but I'd be willing to add a small chance that we miss error log messages of errors that occur when writing a  journald message coming from kmsg to the journal if it means we can have all other journald log messages stored in the journal.

2021-10-22 15:13 UTC, poettering commented on src/journal/journald-kmsg.c
> +                }
I don#t buy this I must say. Consider this: you enable debug logging for sd-event (e.g. set SD_EVENT_PROFILE_DELAYS env var). Suddenly, the mere act of an event arriving will trigger a log event. Thus, if we'd not ignore our own log stuff, we'll generate a log message when an event happens which we'll then results in an event to us, which we'll log about, ad infinitum. It's not sufficient to disable logging once we figured out what kind of event this is. We can't allow logging from before that to loopback to us either.

I think the only reasonable thing is to say "sorry, but we'll never process any log events that could come from any part of our code" like we currently do.

2021-10-22 16:56 UTC, daandemeyer commented on src/journal/journald-kmsg.c
> +                }
As mentioned in the Telegram chat, the current approach of dropping journald messages doesn't handle the sd-event debug scenario either. The difference would be that with the current approach, we'd spam kmsg ad infinitum whereas with my approach, we'd spam kmsg and the journal as well when that happens.

I wonder if it would be that much worse if we were to also log to the journal in case we get one of those loops. If we end up spamming kmsg, I'm pretty sure we're going to get angry users regardless, especially if we end up amplifying since that would end with journald consuming a full core eventually (I think).

I wonder if we should have a separate journald instance for processing kmsg that isn't allowed to log at all. Or we have journald log to a memfd like you mentioned and have a separate process that can't log just for processing that memfd. The rate limiting approach you mentioned would have the same problem in that everything that logs before we check the ratelimit can trigger an infinite loop without any rate limiting applied.

2021-10-27 09:52 UTC, poettering commented on src/journal/journald-kmsg.c
> +        LogTarget t = log_get_target();
please don't do function calls up here where we otherwise just declare variables and maybe initialize them with constants.

2021-10-27 09:52 UTC, poettering commented on src/journal/journald-kmsg.c
> +        log_set_target(t);
i'd prefer if we reset target/level only if we actually changed it...

2021-11-03 11:07 UTC, DaanDeMeyer commented
> So I'd be willing to try this, but please use ratelimit_below() as extra safety net if we open this up.

Couldn't we just use journald's own rate limiting mechanism for this? Maybe we configure stricter LogRateLimitBurst and LogRateLimitInterval settings for it?

Pretty much the first thing that server_dispatch_message() does after we call it from the kmsg handler is check the ratelimit so now that we pass a client context from the kmsg handler when handling a journald message, the rate limiting should kick in automatically (still need to verify)

2021-11-05 14:16 UTC, DaanDeMeyer commented
CI failures on focal-amd64 for clock, dissect and portable tests. Those all seem unrelated to this change.

2021-11-09 16:18 UTC, poettering commented on src/basic/log.h
> +#define LOG_NULL (LOG_EMERG - 1)
Please add comment explaining this.

2021-11-09 16:30 UTC, poettering requested changes
i'd still prefer if we had explicit ratelimiting, hardcoded here instead of relying on the generic per-unit ratelimit only. i.e. the existing ratelimiting is configurable via unit files, and i am not convinced this is the right place, after all this is not about ratelimiting logs from ourselves generically, but specifically those that came over the kmsg channel. I think it shouldn't be configurable, but a hardcoded safety net.

2021-11-09 16:30 UTC, poettering commented on src/journal/journald-kmsg.c
> +        int log_max_level;
maybe:

```c
int saved_log_max_level = INT_MAX;
```

2021-11-09 16:30 UTC, poettering commented on src/journal/journald-kmsg.c
> +        log_max_level = log_get_max_level();
please move this where you actually override the log level, i.e. right before the log_set_max_level() in the if condition below.

2021-11-09 16:30 UTC, poettering commented on src/journal/journald-kmsg.c
> +                log_set_max_level(log_max_level);
and then matching the above change this to:

```c
if (saved_log_max_level != INT_MAX)
        log_set_max_level(log_max_level);
```

or in other words: let's do this save/restore stuff only if we actually changed the log level

2021-11-09 16:30 UTC, poettering commented on src/basic/log.h
> +#define LOG_NULL (LOG_EMERG - 1)
in particular, mention that this is only OK as value for the maximum log level threshold, and not as a level/priority people could set on a message

2021-11-12 17:12 UTC, DaanDeMeyer commented
Added the hardcoded ratelimit. I'm really bad at coming up with sane values for stuff like this so let me know if the values should be relaxed

2021-11-14 15:15 UTC, DaanDeMeyer commented
ppc64el and s390x both timed out

2021-11-17 15:49 UTC, poettering commented on src/journal/journald-server.c
> +        log_info("ABC");
left over from debugging?

2021-11-17 15:49 UTC, poettering commented
lgtm, but please drop the left-over log msg

2021-11-18 19:37 UTC, DaanDeMeyer commented
CI failures are all timeouts or the JSON test failure

2021-11-18 19:37 UTC, merged

2024-12-19 07:27 UTC, linker99 commented
If the kernel or other services keep printing logs to the /dev/kmsg file, causing the systemd - journald service to time out, is this situation normal or a performance issue of systemd - journald itself?

2024-12-19 07:28 UTC, linker99 commented
If the kernel or other services keep printing logs to the /dev/kmsg file, causing the systemd - journald service to time out, is this situation normal or a performance issue of systemd - journald itself?

2024-12-19 08:44 UTC, yuwata commented
@linker99 Could you open a new issue with detailed setup and logs?

2024-12-24 07:31 UTC, linker99 commented
> If the kernel or other services keep printing logs to the /dev/kmsg file, causing the systemd - journald service to time out, is this situation normal or a performance issue of systemd - journald itself?