veritysetup-generator, fstab-generator: Setup and mount usr verity device when 'usrhash' (and optionally systemd.verity_usr_*) is present as kernel command line parameter
systemd/systemd pull request #21357
Opened 2021-11-13 22:41 UTC by mbd98

_First contribution to a big FOSS project, let's hope I didn't do anything too stupid!_ :D

When building a GPT image with mkosi having `UsrOnly=true` and `Verity=true`, the parameter `usrhash` will be added to the kernel command line.  As of right now, veritysetup-generator and fstab-generator ignore `usrhash`.  This PR aims to resolve this!

2021-11-14 04:52 UTC, yuwata requested changes
Not familiar with the functionality. Just superficial comments.

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +                  "                and hash %s.", name, data_what, hash_what, options, hash);
The indentation is now broken, especially when `name` is not "root". How about simply inline the message?
```
log_debug("Using %s verity data device %s, hash device %s, options %s, and hash %s.", ...);
```

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
>          /* If all three pieces of information are missing, then verity is turned off */
It is better to add assertions:
```
assert(name);
assert(service);
```

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +static int create_device(const char *name, const char *service, char *hash, char *data_what, char *hash_what, char *options) {
Please constify all arguments.

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +static int determine_device(char *hash, char **data_what_p, char **hash_what_p) {
Constify `hash` and drop `_p` suffix:
`determine_device(const char *hash, char **data_what, char **hash_what)`

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> -                return 0;
Please do not drop these conditions:
```
if (!hash)
        return 0;

if (!*data_what && !*hash_what)
        return 0;
```

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +        if (arg_root_hash && !arg_root_data_what && !arg_root_hash_what) {
Please drop this condition.

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +        if (arg_usr_hash && !arg_usr_data_what && !arg_usr_hash_what) {
Also here.

2021-11-14 04:52 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +        if (!(*data_what_p)) {
`()` is redundant.

2021-11-14 04:52 UTC, yuwata commented on src/fstab-generator/fstab-generator.c
> +static int determine_device(char **what_p, char **hash_p, const char *name) {
Please drop `_p` suffix. Also, `hash` is not modified in this function, so simply `const char *hash` should be ok.

2021-11-14 04:52 UTC, yuwata commented on src/fstab-generator/fstab-generator.c
> +        assert(hash_p);
Please add `assert(name);`

2021-11-14 04:52 UTC, yuwata commented on src/fstab-generator/fstab-generator.c
>                  return log_oom();
Please use `path_join()`:
```
*what = path_join("/dev/mapper/", name);
if (*what)
        return log_oom();
```

2021-11-14 23:31 UTC, yuwata reviewed
Only super super minor comments. Superficially looks good. I do not know if this works or not, usefull or not.
cc @bluca and @poettering.

2021-11-14 23:31 UTC, yuwata commented on src/fstab-generator/fstab-generator.c
> +
Drop this unnecessary blank line; we usually locate the error handling just after the function call.

2021-11-14 23:31 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> -
Please do not touch like this needlessly.

2021-11-15 21:53 UTC, mbd98 commented
Adjustments made, thanks for the feedback!

2021-11-17 10:50 UTC, poettering commented on src/veritysetup/veritysetup-generator.c
> +#define USR_NAME "usr"
let's not use macros for this. Just use the literal strings. they are short, hard to mistype, and so easy to grok. no need for the extra indirection

2021-11-17 12:24 UTC, poettering requested changes

2021-11-17 12:24 UTC, poettering commented on src/veritysetup/veritysetup-generator.c
> +static int create_device(const char *name, const char *service, const char *hash, const char *data_what, const char *hash_what, const char *options) {
given this takes so many function parameters, please line break the arguments, one argument per line, see how this is done elsewhere in the codebase

2021-11-17 12:24 UTC, poettering commented on src/veritysetup/veritysetup-generator.c
> +                log_error("Verity information incomplete, hash device unspecified.");
please include the `name` in the log message, to make this easy to grok.

2021-11-17 12:24 UTC, poettering commented on src/veritysetup/veritysetup-generator.c
> +                log_debug("Hash is shorter than 128 bits (32 characters), ignoring for discovering verity partition.");
Please change this function to take a name as first argument so that you can include it in the log messages here.

Note that the hash value should be called root hash either way, it's the root hash of the merkle tree after all... the fact that it can also the roothash of the rootfs (i.e. the "root root hash") is confusing, and we supress the double "root" from the short names because of that. But for the /usr root hash it should still be said. Hence call it in the english language form "Root hash" and "/usr root hash" please.

2021-11-17 12:24 UTC, poettering commented on src/veritysetup/veritysetup-generator.c
> +                log_info("Using data device %s and hash device %s for %s.", arg_root_data_what, arg_root_hash_what, ROOT_NAME);
move this log message inside the determine_device() function?

2021-11-17 12:24 UTC, poettering commented on src/fstab-generator/fstab-generator.c
> +#define USR_NAME "usr"
pleas drop, just use the literal strings

2021-11-17 12:27 UTC, poettering commented on man/systemd-veritysetup-generator.xml
> +      </varlistentry>
don't copy the whole prose here, instead just do:

```xml
      <varlistentry>
        <term><varname>usrhash=</varname></term>
        <term><varname>systemd.verity_usr_data=</varname></term>
        <term><varname>systemd.verity_usr_hash=</varname></term>
        <term><varname>systemd.verity_usr_options=</varname></term>
        <listitem><para>Equivalent to their counterparts for the root file system as described above, but apply to the `/usr/` file system instead.</para></listitem>
      </varlistentry>

2021-11-17 12:28 UTC, poettering commented
please also update kernel-command-line(7)

2021-11-18 02:42 UTC, mbd98 commented
@poettering Pushed some changes, thanks for the feedback!

I had modified kernel-command-line(7) to include details about the usr-specific stuff, was there a particular change you'd like to it?

2021-11-18 09:42 UTC, poettering commented on man/systemd-veritysetup-generator.xml
> +        <listitem><para>Equivalent to their counterparts for the root file system as described above, but apply to the `/usr/` file system instead.</para></listitem>
`/usr/` → `<filename>/usr/</filename>`

2021-11-18 09:43 UTC, poettering commented
one minor fix with the docbook markup otherwise looks good to go.

2021-11-19 03:42 UTC, yuwata approved these changes
Two minor points.

2021-11-19 03:42 UTC, yuwata commented on src/veritysetup/veritysetup-generator.c
> +        int r = 0;
Unnecessary initialization.

2021-11-19 03:42 UTC, yuwata commented on man/systemd-veritysetup-generator.xml
> +    <para>Currently, only two verity devices may be set up with this generator, backing the root and usr file systems of the
Also use `<filename>/use</filename>` here?

2021-11-22 13:08 UTC, bluca approved these changes

2021-11-22 13:09 UTC, merged