Do not require a valid version when parsing sd-boot loader entries
systemd/systemd pull request #21364
Opened 2021-11-14 15:36 UTC by viccie30

This fixes #20820. As noted in that issue, version info is not used in sorting. @poettering's simplification of entry parsing makes this a (less than) one line change.

2021-11-14 17:30 UTC, medhefgo requested changes
Userspace does not cope with version being NULL. This should also touch the boot loader spec.

2021-12-06 11:00 UTC, keszybz commented
bootspec_pick_name_version() is called in two places: config_entry_add_linux() in boot.c, and it handles expects NULL and handles it graciously. But boot_entry_load_unified() also calls it, and does `strdup()` on the string. So it needs to be adjusted.

2022-05-22 00:46 UTC, bluca commented
> bootspec_pick_name_version() is called in two places: config_entry_add_linux() in boot.c, and it handles expects NULL and handles it graciously. But boot_entry_load_unified() also calls it, and does `strdup()` on the string. So it needs to be adjusted.

This fixes a problem in debian unstable and the PR has stalled, so I've updated it

2022-05-22 07:05 UTC, medhefgo commented
Bootloader spec requires a version field. If this requirement is dropped, you should really update the spec then.

2022-05-22 10:17 UTC, keszybz commented
I don't see this. The spec is a wall of text, but at least the description of `version` explicitly says "this field is optional."  I think we can merge this as is. If there's some adjustment needed in the spec, we we can do that later.

(We tentatively discussed rewriting / reordering the text in the spec to be more "spec-like". I.e. the reference description first, and the motivation and explanations and howtos later. But that's not blocking other changes to the spec.)

2022-05-22 10:17 UTC, merged