getty-generator: add kernel cmdline and env vars to disable it
systemd/systemd pull request #21422
Opened 2021-11-17 17:31 UTC by bluca

systemd.getty_auto/rd.systemd.getty_auto/SYSTEMD_GETTY_AUTO can be used
to disable the generator. Enabled by default.

2021-11-17 20:42 UTC, poettering requested changes
looks good, but some fixes please

2021-11-17 20:42 UTC, poettering commented on man/systemd-getty-generator.xml
> +        <term><varname>rd.systemd.getty_auto</varname></term>
please also add reference to kernel-command-line(7)

2021-11-17 20:42 UTC, poettering commented on man/systemd-getty-generator.xml
> +
the `rd.` version should go: we don't do gettys in the initrd anyway...

2021-11-17 20:42 UTC, poettering commented on man/systemd-getty-generator.xml
> +        <term><varname>rd.systemd.getty_auto</varname></term>
please suffix with "=", since we expect an argument

2021-11-17 20:42 UTC, poettering commented on man/systemd-getty-generator.xml
> +        <listitem><para>Those options take an optional boolean argument, and default to yes.
Those → These?

2021-11-17 20:42 UTC, poettering commented on man/systemd-getty-generator.xml
> +        The generator is enabled by default, and a negative value may be used to disable it.
negative → false?

(i.e. most people would probably set =1 and =0 as values, but if you write negative people might misunderstand tht this means =-1...)

2021-11-17 20:42 UTC, poettering commented on src/getty-generator/getty-generator.c
> +            (proc_cmdline_key_streq(key, "rd.systemd.getty_auto") && in_initrd())) {
as mentioned, please drop the rd. flavour

2021-11-17 20:52 UTC, bluca commented
updated

2021-11-17 21:02 UTC, poettering commented
kernel-command-line mn page fix is still missing

2021-11-17 21:08 UTC, bluca commented
> kernel-command-line mn page fix is still missing

I added it - or did you mean at the bottom?

2021-11-17 21:09 UTC, bluca commented
added in "See also" as well

2021-11-18 10:38 UTC, merged

2021-11-18 12:56 UTC, poettering commented
> > kernel-command-line mn page fix is still missing
> 
> I added it - or did you mean at the bottom?

man/kernel-command-line.xml is still missing an entry for this!

2021-11-18 13:02 UTC, bluca commented
> > > kernel-command-line mn page fix is still missing
> > 
> > 
> > I added it - or did you mean at the bottom?
> 
> man/kernel-command-line.xml is still missing an entry for this!

ahah sorry, I thought you meant adding a link from this manpage to that one - will send another PR