systemctl: add shutdown -s option
systemd/systemd pull request #21680
Opened 2021-12-08 12:04 UTC by lnussel

Shows the scheduled shutdown action and time if there's one.

2021-12-08 12:05 UTC, lnussel commented
Not sure what's the most obvious choice for an option here. show (-s), query (-q) or list (-l)? -q is often used for quiet though.

2021-12-08 13:25 UTC, bluca commented
Wouldn't a long option (`--show`) be more readable?

2021-12-08 14:55 UTC, medhefgo commented
shutdown is a legacy binary we provide for compatibilty. It should not be getting any new features.

2021-12-08 15:03 UTC, bluca commented
oh right, I missed that this was for the shutdown command rather than systemctl itself - then yes @medhefgo is right. Can this be added to systemctl reboot/poweroff/etc instead?

2021-12-08 15:05 UTC, medhefgo commented
> oh right, I missed that this was for the shutdown command rather than systemctl itself - then yes @medhefgo is right. Can this be added to systemctl reboot/poweroff/etc instead?

It's adding it for both. So the shutdown part just needs to be removed. Also needs update to manpage.

2021-12-08 15:47 UTC, lnussel commented
The long option probably is nicer indeed though

2021-12-09 09:52 UTC, keszybz commented
I think it is OK to add this. `shutdown` is a compat command, but effectively we're the new owners of it on Linux, since most people are using our implementation. But please call the option `--show`. This reduces the risk of a conflict with another implementation.

(FWIW, I don't think `shutdown` is going away. Similarly to the `3` and `5` options on the kernel command line, things which are convenient will be always used.)

But please add the man page entry.

2021-12-09 10:55 UTC, lnussel commented
Looks like  I went into a rabbit hole looking at the shutdown handling :/
Anyway, one thing at a time. Renamed to --show and added mention in man page.

2021-12-09 11:07 UTC, bluca commented
Please update shell-completion/ too

2021-12-09 12:22 UTC, lnussel commented
Looks like there is no existing shell completion for the shutdown command? Only systemctl is covered but the change doesn't impact systemctl in a user visible way.

2021-12-09 13:02 UTC, keszybz requested changes

2021-12-09 13:02 UTC, keszybz commented on man/shutdown.xml
> +        there is any</para></listitem>
Missing '.'.

2021-12-09 13:35 UTC, lnussel commented on man/shutdown.xml
> +        there is any</para></listitem>
eagle eyes :+1:

2021-12-09 14:07 UTC, merged