network: Do NOT add unspecified (::/0, 0.0.0.0/0) wireguard routes
systemd/systemd pull request #22054
Opened 2022-01-08 12:32 UTC by igo95862

Breaks systems configured before systemd 250.

See #21964.

2022-01-08 12:33 UTC, igo95862 commented
I have not yet updated documentation but will do soon.

2022-01-08 12:36 UTC, zx2c4 commented
NACK.

Special casing one route doesn't make sense and isn't the right way to solve this problem, as mentioned in https://github.com/systemd/systemd/issues/21964#issuecomment-1003771183.

2022-01-08 12:38 UTC, zx2c4 requested changes
There's no reason to bifurcate the discussion in #21964, where we were discussing this. Please bring things back to there. Strong n'ack on the approach of this PR. Do not merge.

2022-01-09 16:13 UTC, igo95862 commented
See #22065

2022-01-09 16:13 UTC, closed without merging