use mfree to free memory and set NULL
systemd/systemd pull request #22700
Opened 2022-03-10 12:08 UTC by weizhixiangcoder

2022-03-10 12:23 UTC, yuwata requested changes
Please use `git push --force` when you update your existing PR, then it is not necessary to recreate a new PR.

2022-03-10 12:23 UTC, yuwata commented on src/libsystemd-network/test-dhcp6-client.c
> +        char **list = NULL;
These shadows the above declarations.

2022-03-10 12:23 UTC, yuwata commented on src/libsystemd-network/test-dhcp6-client.c
> +        int r;
This is not used.

2022-03-10 12:23 UTC, yuwata commented on src/libsystemd-network/test-dhcp6-client.c
> +#include "alloc-util.h"
These are not necessary, and not sorted alphabetically.

2022-03-10 12:23 UTC, yuwata commented on src/test/test-cgroup-util.c
> +        assert(vals3[0] && !vals3[1]);
Why do you convert `assert_se()` into `assert()`? `assert()` may be disabled when -DNDEBUG is provided to the compiler command line option. Moreover this is a testing code, please use `assert_se()`.

2022-03-10 12:28 UTC, weizhixiangcoder commented
> 

OK

2022-03-10 12:49 UTC, yuwata requested changes

2022-03-10 12:49 UTC, yuwata commented on src/libsystemd-network/test-dhcp6-client.c
> +#include "alloc-util.h"
I cannot catch why you add the header. Do you have any issue on the test?

2022-03-10 12:49 UTC, yuwata commented on src/test/test-cgroup-util.c
> +        assert(vals3[0] && !vals3[1]);
No no. Please use `assert_se()`. Please read my previous comment.

2022-03-10 12:49 UTC, yuwata commented on src/test/test-cgroup.c
> +        path = mfree(path);
Hm, this is not bad, but if you change this, then please change the declaration of `path` as `_cleanup_free_ char *path = NULL;`. This is much safer.

2022-04-17 20:55 UTC, yuwata requested changes

2022-04-17 20:55 UTC, yuwata commented on src/test/test-cgroup.c
>          log_debug("test_d: %s", path);
One more free() in the below must be replaced.

2022-04-17 20:55 UTC, yuwata commented on src/test/test-cgroup.c
> +#include "alloc-util.h"
Please sort headers.

2022-04-17 20:56 UTC, weizhixiangcoder commented
好的，已经收到来自您的邮件！

2022-08-03 08:46 UTC, poettering commented
Ping?

2022-08-03 08:46 UTC, weizhixiangcoder commented
好的，已经收到来自您的邮件！

2023-06-12 21:06 UTC, poettering commented
this seems to have stalled. let's close this. patch would certainly still be welcome if updated, with the raised issues addressed once it passes CI, but given it's stuck and this is mostly a clean-up, not a bugfix, let's just close this.

2023-06-12 21:06 UTC, closed without merging

2023-06-12 21:06 UTC, weizhixiangcoder commented
好的，已经收到来自您的邮件！