varlink: varlink_error_invalid_parameter(...) always returns EINVAL
systemd/systemd pull request #22750
Opened 2022-03-15 12:55 UTC by vchillara

varlink_error(...) expects a json object as the third parameter. Passing a string variant causes
parameter sanitization to fail, and it returns -EINVAL. Pass object variant instead.

2022-03-15 13:11 UTC, yuwata requested changes

2022-03-15 13:11 UTC, yuwata commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
Creating a new object in a error handling is not good in general...
I am not familiar with varlink library, but is it possible to introduce, say `varlink_error_string()` or something which takes string json object?

2022-03-15 14:45 UTC, poettering commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
I think that's OK. THis is so high-level. We have to buffer the generated varlink stuff anyway, hence allocating a json object is fine, too

2022-03-15 14:51 UTC, poettering commented on src/shared/varlink.c
> +                return varlink_error(v, VARLINK_ERROR_INVALID_PARAMETER, parameters);
this doesn't look right. we should also pass an object here with one field called "parameter" that points to the first element of the parameters list. See the comment at the top of the function about this.

or in other words: the json_build() line you added needs to be added both for the case where a string and where an object is passed.

2022-03-15 14:56 UTC, yuwata requested changes

2022-03-15 14:56 UTC, yuwata commented on src/shared/varlink.c
> +        int r = 0;
It is not necessary to initialize `r` here. Please simply `int r;`.

2022-03-15 14:56 UTC, yuwata commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
Still I do not like it, but I am not familiar with this, hence, it is OK, as it is liked by @poettering.

But please move `_cleanup_(json_variant_unrefp) JsonVariant *parameters_obj = NULL;` to this `if` block.

2022-03-16 09:16 UTC, vchillara commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
@yuwata  now that we're using parameters_obj in both if blocks, does it still make sense to move the declaration to within the block(s)?

2022-03-16 10:49 UTC, bluca commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
yes, they are used independently

2022-03-16 10:50 UTC, bluca commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
(which means by moving we pay the cost of the _cleanup_ only if it's actually needed and the block is entered, and given each block returns there's no need for the var to live longer)

2022-03-16 11:29 UTC, bluca commented on src/shared/varlink.c
> +                if(r < 0)
style nit: missing space before `(`

2022-03-16 11:38 UTC, bluca approved these changes

2022-03-16 17:01 UTC, poettering commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
please replace `JSON_BUILD_STRING(json_variant_string(parameters))` by JSON_BUILD_VARIANT(parameters)`. i.e. we can just reuse the string variant we already have, no need to allocate a new one.

2022-03-16 17:02 UTC, poettering commented
looks good, just one minor simplifcation please

2022-03-17 06:21 UTC, vchillara commented on src/shared/varlink.c
> +                                        JSON_BUILD_PAIR("parameter", JSON_BUILD_STRING(json_variant_string(parameters)))));
> please replace `JSON_BUILD_STRING(json_variant_string(parameters))` by JSON_BUILD_VARIANT(parameters)`. i.e. we can just reuse the string variant we already have, no need to allocate a new one.

updated

2022-03-17 11:12 UTC, merged