tmpfiles: Split networkd entries into a separate file
systemd/systemd pull request #23205
Opened 2022-04-27 10:32 UTC by DaanDeMeyer

Many distributions ship systemd-networkd as a separate file so we
need to be able to ship the tmpfiles networkd entries as part of
that separate networkd package. Let's split the networkd entries
into a separate file to make that possible.

2022-04-27 10:39 UTC, bluca commented
Didn't we have some issues in the past with splitting tmpfiles, due to users overriding them and suddenly the override not working anymore as the settings moved, or something like that? How was that solved?

2022-04-27 11:25 UTC, yuwata requested changes

2022-04-27 11:25 UTC, yuwata commented on tmpfiles.d/meson.build
> +         ['systemd-networkd.conf', 'ENABLE_NETWORKD'],
For resolved, we have systemd-resolve.conf. So, maybe systemd-network.conf is better??

Note, we have systemd-network.conf for sysusers.

2022-04-27 11:39 UTC, yuwata approved these changes
LGTM. Only one minor thing.

I guess, 'backward incompatibility' should not a big problem here. As, it is only used by our daemons that uses sd-network, and it is not exported yet.

2022-04-27 11:39 UTC, yuwata commented on tmpfiles.d/meson.build
> +         ['systemd-network.conf', 'ENABLE_NETWORKD'],
That's not your fault, but could you sort the entries?

2022-04-27 11:45 UTC, DaanDeMeyer commented
Added a second commit that sorts the entries

2022-04-27 12:19 UTC, poettering commented
hmm, so i though this was proposed before, but there were some reservations. Anyone remembers? @keszybz you?

2022-04-27 12:20 UTC, poettering commented
can't find it in the issues/prs though

2022-04-27 12:22 UTC, poettering commented
ah, right, now i remember: these dirs are used for inotify watching by various of our tools (resolved for example), thus we can't really add them in when networkd is later installed because the stuff waiting for networkd notifications would then not start watching the stuff magically, because it's too late then.

the dirs and the system user for this should just be installed always, even if the networkd binary is dropped in later only.

At least as long as any component that is a client to networkd is installed.

2022-04-27 12:34 UTC, DaanDeMeyer commented
Should we create the dirs unconditionally then? The issue is that in centos, there's two different source rpms for the main systemd rpm and the systemd-networkd rpm which lives in EPEL. The main systemd rpm is compiled without networkd support and so these tmpfiles stanzas are not included in the main systemd tmpfiles.d/ snippet.

The systemd-networkd is (naturally) built with systemd-networkd enabled, but the main systemd snippet (that now has the networkd stuff inside of it) does not become part of the networkd package. The end result is that on a system with systemd and systemd-networkd installed, those networkd directories don't get created because they're not part of any tmpfiles.d/ snippet.

If we unconditionally create the systemd-networkd user and tmpfiles.d/ directory, that problem would be fixed.

2022-04-27 12:47 UTC, yuwata commented
I think this should be merged, and networkd rpm should restart resolved when it is installed.

2022-04-27 13:08 UTC, poettering commented
well, but why? having those dirs doesn't matter at all, no?

it's not just resolved, it's also timesyncd and wait online stuff, i.e. everything using sd_network_monitor...

i am not sure why bother with this. /run/systemd/ is systemd's private playground. if you enable networkd at all during build it should be totally ok to create some extra dirs there even though they aren't filled untill networkd is actually installed. after all the dirs are *used* already before that, i.e. that timesyncd/resolved/wait-online subscribe to it...

2022-04-28 03:25 UTC, yuwata commented
Hm, indeed. After re-considering, I think the directories are unconditionally created.

2022-04-28 03:30 UTC, yuwata commented
Wait, but the entries requires user systemd-network, but the user is added by sysusers.d/systemd-network.conf. And the file may be shipped with separated package for networkd...

2022-04-28 06:58 UTC, DaanDeMeyer commented
Yes exactly, that's the problem I'm trying to fix.

If I understand @poettering correctly, he suggests we additionally create these directories if resolved or timesyncd are enabled. That would then require the systemd-network.conf sysusers file to ship with the main systemd rpm instead of the networks rpm.

2022-04-28 07:27 UTC, keszybz commented
> these dirs are used for inotify watching by various of our tools (resolved for example), thus we can't really add them in when networkd is later installed because the stuff waiting for networkd notifications would then not start watching the stuff magically, because it's too late then.

Can we fix that? IIRC, in other places we watch the parent directory also. If we could allow the directory to be created later, this would all become simpler.

> I think this should be merged, and networkd rpm should restart resolved when it is installed.

Ah, that is another solution. resolved can be restarted at any time, so we can just a %trigger scriptlet.

Also, I see that the scriptlets do not restart networkd on package upgrades. Would it be safe to do so?

2022-04-28 11:10 UTC, anitazha commented
> Also, I see that the scriptlets do not restart networkd on package upgrades. Would it be safe to do so?

I was wondering about this. If you're using something like userspace RA wouldn't this cause any drops when restarting systemd-networkd?

2022-04-28 11:30 UTC, yuwata commented
> > Also, I see that the scriptlets do not restart networkd on package upgrades. Would it be safe to do so?
> 
> I was wondering about this. If you're using something like userspace RA would this cause any drops when restarting systemd-networkd?

Right. Restarting networkd causes that RA, DHCPv6, and IPv4LL addresses are dropped. Only DHCPv4 address is kept by default.

2022-04-29 16:27 UTC, DaanDeMeyer commented
So what's the conclusion here? Do we go the other way and create the dies and user if resolved or timesyncd are enabled?

2022-04-29 18:03 UTC, yuwata commented
I think the tmpfiles can be split by making sd-network watch parent directories if /run/systemd/network/links or friends do not exist.
IIRC, sd-bus does the similar thing.

2022-05-02 14:35 UTC, DaanDeMeyer commented
> I think the tmpfiles can be split by making sd-network watch parent directories if /run/systemd/network/links or friends do not exist.

I just checked and we already do this it seems? See `monitor_add_inotify_watch()` and `sd_network_monitor_flush()` which updates the monitor as the necessary directories are added.

2022-05-02 15:10 UTC, yuwata commented
Indeed. Then, the initial concern https://github.com/systemd/systemd/pull/23205#issuecomment-1110936055 is already solved.

2022-05-03 12:12 UTC, DaanDeMeyer commented
https://github.com/systemd/systemd/pull/23254 is slightly related

2022-05-03 15:24 UTC, keszybz commented on tmpfiles.d/meson.build
> +         ['README',               ''],
Let's keep README at the top, unsorted.

2022-05-03 18:46 UTC, DaanDeMeyer commented
Added a NEWS entry to describe the change.

2022-05-03 22:02 UTC, yuwata approved these changes

2022-05-04 02:48 UTC, merged