Actually run shellcheck on CI
systemd/systemd pull request #23475
Opened 2022-05-22 14:21 UTC by nabijaczleweli

#23374

2022-05-22 14:33 UTC, mrc0mmand requested changes
I don't think this is correct. Answering the comment from https://github.com/systemd/systemd/issues/23374#issuecomment-1133902874 there are two factors that might be culprits here:

1) We do only differential shellcheck in each PR (`VALIDATE_ALL_CODEBASE=true`), i.e. we check only files changed by that PR

2) The "miss" in https://github.com/systemd/systemd/issues/23374#issuecomment-1133902874 was most ilkely caused by the  `FILTER_REGEX_EXCLUDE: .*/(man/.*|.*\.(in|SKELETON)|tools/coverity\.sh)$` regex, which ignores the template files (`*.in`) by default, since they are not usually compatible with shellcheck before they're processed by a templating engine

2022-05-22 21:05 UTC, nabijaczleweli commented
In workable state now, IMO

2022-05-23 09:15 UTC, mrc0mmand reviewed
A couple of nits, otherwise LGTM, thanks!

2022-05-23 09:15 UTC, mrc0mmand commented on .github/workflows/linter.yml
> -          VALIDATE_BASH: true
Why this change? The validators default to `false` when at least one of them is set to `true`, so the original `VALIDATE_BASH: true` should work just fine.

2022-05-23 09:15 UTC, mrc0mmand commented on .github/workflows/linter.yml
> -          #        https://github.com/rhysd/actionlint/commit/09a60b0f5761c2d066def294e541c25a89756eea
Unnecessary ident change?

2022-05-23 09:15 UTC, mrc0mmand commented on .github/workflows/linter.yml
> -          FILTER_REGEX_EXCLUDE: .*/(man/.*|.*\.(in|SKELETON)|tools/coverity\.sh)$
Oh well, this is unfortunate, but it is what it is, thanks for figuring this out.

2022-05-23 11:11 UTC, mrc0mmand commented
(To test this out you'll have to explicitly "touch" the kernel-install script, since by reverting the fixup commit this PR effectively doesn't touch kernel-install at all.)

2022-05-23 11:32 UTC, nabijaczleweli commented on .github/workflows/linter.yml
> -          #        https://github.com/rhysd/actionlint/commit/09a60b0f5761c2d066def294e541c25a89756eea
Right, the defaults table misled me, and the BASH=true -> SHFMT=false conversion made the YAML validator run, which exploded on >80-character lines; fixed

2022-05-23 11:32 UTC, nabijaczleweli commented
Blegh, yeah; validated, fixed, should be g2g

2022-05-23 11:40 UTC, mrc0mmand approved these changes
Awesome, LGTM, thanks!

2022-05-23 11:50 UTC, keszybz commented on .github/workflows/linter.yml
> +          #            09a60b0f5761c2d066def294e541c25a89756eea
Please drop this chunk.

2022-05-23 11:50 UTC, keszybz commented on .github/workflows/linter.yml
> +          FILTER_REGEX_EXCLUDE: .*/(man/.*|([^k]|k(k|ek)*([^ek]|e[^kr]))*(k(k|ek)*e?)?\.(in|SKELETON)|tools/coverity\.sh)$
This is scary ;) Can we maybe use a negative match here:
`…|(?<!kernel-install)\.(in|SKELETON)|…` ?
Don't know if this is supported by this engine.

2022-05-23 11:51 UTC, mrc0mmand commented on .github/workflows/linter.yml
> +          FILTER_REGEX_EXCLUDE: .*/(man/.*|([^k]|k(k|ek)*([^ek]|e[^kr]))*(k(k|ek)*e?)?\.(in|SKELETON)|tools/coverity\.sh)$
Unfortunately, no, this uses Bash's POSIX regex engine (`regex(3)`), so no fancy lookaheads/lookbehinds here.

2022-05-23 12:41 UTC, nabijaczleweli commented on .github/workflows/linter.yml
> +          FILTER_REGEX_EXCLUDE: .*/(man/.*|([^k]|k(k|ek)*([^ek]|e[^kr]))*(k(k|ek)*e?)?\.(in|SKELETON)|tools/coverity\.sh)$
That's what I tried (and helpfully the documentation doesn't say; well it says it's RE, which it isn't), but it uses bash `[[ =~ ]]`, which is ERE, to match these

2022-05-23 19:16 UTC, merged