journal: ensure the logical status of LOCATION_TAIL and LOCATION_HEAD
systemd/systemd pull request #23480
Opened 2022-05-23 05:48 UTC by ChenQi1989

sd_journal_next call after sd_journal_seek_tail should always return
0 instead of go anywhere else to seek for a journal entry. The same
logic applies to sd_journal_previous and sd_journal_seek_head.

The LOCATION_TAIL and LOCATION_HEAD only have logical meaning, the
end/beginning of the journal. The real entry location is determined
by some follow-up journal location related call. For example, the real
location of LOCATION_TAIL, by desgin I guess, is determined by the
time an immediate follow-up call, sd_journal_previous, is made.

So any sd_journal_next call immediately after sd_journal_seek_tail
should return 0. sd_journal_previous and sd_journal_seek_head, the same.

Fixes #9934

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>

2022-05-23 06:34 UTC, yuwata commented
CIs are in red.

2022-05-26 05:27 UTC, ChenQi1989 commented
Any comment on this one?

2022-05-30 08:44 UTC, DaanDeMeyer commented
I'm not too familiar with this code but shouldn't the fix be made in `next_beyond_location()`? In fact, in `next_beyond_location()`, we already have logic to check for EOF and to return early if that's the case. Can you check why that logic isn't triggered? I'm pretty sure if possible we should fix that condition instead of adding a new one to `real_journal_next()`.

2022-05-30 08:44 UTC, DaanDeMeyer requested changes
I'm not too familiar with this code but shouldn't the fix be made in next_beyond_location()? In fact, in next_beyond_location(), we already have logic to check for EOF and to return early if that's the case. Can you check why that logic isn't triggered? I'm pretty sure if possible we should fix that condition instead of adding a new one to real_journal_next().

2022-05-30 09:03 UTC, ChenQi1989 commented
@DaanDeMeyer 
Are you referring to the following code block in next_beyond_location?
        /* If we hit EOF before, we don't need to look into this file again
         * unless direction changed or new entries appeared. */
        if (f->last_direction == direction && f->location_type == LOCATION_TAIL &&
            n_entries == f->last_n_entries)
                return 0;

We can see that it's checking the file's location instead of the journal's location.
Looking at the codes, it's iterating all journal files, if the above condition meets, it proceeds to parse the remaining journal files.
The codes are as below:
        for (i = 0; i < n_files; i++) {
                JournalFile *f = (JournalFile *)files[i];
                bool found;

                r = next_beyond_location(j, f, direction);
                if (r < 0) {
                        log_debug_errno(r, "Can't iterate through %s, ignoring: %m", f->path);
                        remove_file_real(j, f);
                        continue;
                } else if (r == 0) {
                        f->location_type = LOCATION_TAIL;
                        continue;
                }

sd_journal_seek_tail/head is setting journal's LOCATION_TAIL/HEAD, and we need a check against it.

2022-05-30 09:18 UTC, ChenQi1989 commented
@DaanDeMeyer
Are you referring to the following code block in next_beyond_location?

`
/* If we hit EOF before, we don't need to look into this file again * unless direction changed or new entries appeared. */ 
if (f->last_direction == direction && f->location_type == LOCATION_TAIL && 
    n_entries == f->last_n_entries) 
        return 0;
`

We can see that it's checking the file's location instead of the journal's location.
Looking at the codes, it's iterating all journal files, if the above condition meets, it proceeds to parse the remaining journal files.
The codes are as below:

`
for (i = 0; i < n_files; i++) {
            JournalFile *f = (JournalFile *)files[i];
            bool found;

            r = next_beyond_location(j, f, direction);
            if (r < 0) {
                    log_debug_errno(r, "Can't iterate through %s, ignoring: %m", f->path);
                    remove_file_real(j, f);
                    continue;
            } else if (r == 0) {
                    f->location_type = LOCATION_TAIL;
                    continue;
            }
.....
}
`

However, sd_journal_seek_tail/head is setting journal's LOCATION_TAIL/HEAD, and we need a check against it.

2022-05-30 09:20 UTC, ChenQi1989 commented
@DaanDeMeyer 
I tried to make the comment a little easier to read, but github's 'add code' button does not work well enough.
Hope you still get what I mean.

2022-06-06 01:18 UTC, ChenQi1989 commented
@DaanDeMeyer ping

2022-07-01 01:46 UTC, ChenQi1989 commented
ping

2022-07-05 13:25 UTC, DaanDeMeyer commented
@ChenQi1989 Can you test https://github.com/systemd/systemd/pull/23909? I think that might be a better solution.

2022-07-05 20:13 UTC, closed without merging