resolve: known-answer suppression fix for ageing entries
systemd/systemd pull request #23611
Opened 2022-06-03 09:48 UTC by vchillara

Optimization for known answer suppression for ageing entries.
RFC 6762 section 7.1 suggests that a Multicast DNS querier SHOULD NOT include records in the Known-Answer list whose remaining TTL is less than half of their original TTL.
This is useful in general to keep the information in cache current, but particularly so when browsing for mDNS services (PR #22532 ).
Skipping cached records whose age is >50% TTL from the known answers enables us to receive updated info from the network if the service is still alive.

2022-06-03 11:51 UTC, medhefgo commented on src/resolve/resolved-dns-cache.c
> +                                t = now(CLOCK_BOOTTIME);
This should be done outside the loop.

2022-06-03 11:51 UTC, medhefgo commented on src/resolve/resolved-dns-cache.c
> +                        if ((t >= j->until) || (j->until - t) < (0.5 * (j->rr->ttl * USEC_PER_SEC)))
I doubt thing this needs float math:
```suggestion
                        if ((t >= j->until) || (j->until - t) < (j->rr->ttl * (USEC_PER_SEC / 2)))
```

2022-06-03 12:08 UTC, vchillara commented on src/resolve/resolved-dns-cache.c
> +                                t = now(CLOCK_BOOTTIME);
Moved outside

2022-06-03 12:09 UTC, vchillara commented on src/resolve/resolved-dns-cache.c
> +                        if ((t >= j->until) || (j->until - t) < (0.5 * (j->rr->ttl * USEC_PER_SEC)))
Changed as suggested

2022-06-15 04:47 UTC, vchillara commented
@medhefgo addressed your comments. Any further feedback?

2022-06-15 06:40 UTC, yuwata requested changes

2022-06-15 06:40 UTC, yuwata commented on src/resolve/resolved-dns-cache.c
> +                        if ((t >= j->until) || (j->until - t) < (j->rr->ttl * (USEC_PER_SEC / 2)))
Please drop redundant `()`, and use `usec_sub_unsigned()`:
`if (usec_sub_unsigned(t, j->until) < j->rr->ttl * USEC_PER_SEC / 2)`

2022-06-15 06:40 UTC, yuwata commented on src/resolve/resolved-dns-cache.c
> +                         * half the TTL remaining as known answers. */
Not a big matter, but it is not necessary to wrap comment so frequently. We allow about 109ch per line.

2022-06-15 06:40 UTC, yuwata commented on src/resolve/resolved-dns-cache.c
>  int dns_cache_export_shared_to_packet(DnsCache *cache, DnsPacket *p) {
But please wrap the long line in the commit message.

2022-06-15 12:31 UTC, yuwata approved these changes
LGTM.

2022-06-15 12:31 UTC, yuwata commented on src/resolve/resolved-dns-cache.c
> +                         */
Not a fun of unnecessary line break at the end of comment. But, not a big matter.

2022-06-16 01:44 UTC, merged