fix: sd_id128_get_invocation now works for user services if keyring is unavailable
systemd/systemd pull request #23628
Opened 2022-06-04 20:21 UTC by i-do-cpp

`sd_id128_get_invocation` only returned success if `get_invocation_from_keyring` succeeded. This is a problem when no keyring is available.
This patch makes `sd_id128_get_invocation` first try `get_invocation_from_environment` (and return on success) and then try `get_invocation_from_keyring`.  
This has the effect that `sd_id128_get_invocation` now correctly returns the `invocation id` for user services if no keyring is available.

2022-06-06 08:22 UTC, yuwata requested changes

2022-06-06 08:22 UTC, yuwata commented on src/libsystemd/sd-id128/sd-id128.c
> -                        return r;
Please do not change the order of the two `get_invocation_from_xxx()`.
I guess the issue can be fixed by fixing the return value handling:
```
r = get_invocation_from_environment();
if (r != -ENXIO)
        return r;
```

2022-06-06 16:28 UTC, i-do-cpp commented on src/libsystemd/sd-id128/sd-id128.c
> -                        return r;
Thank you for reviewing this PR!
The suggested change would still fail without a keyring as the following `get_invocation_from_keyring` call overrides the `get_invocation_from_environment` call.

We now return the result of `get_invocation_from_environment` if the call succeeded, please have another look.

2022-06-09 04:00 UTC, yuwata requested changes

2022-06-09 04:00 UTC, yuwata commented on src/libsystemd/sd-id128/sd-id128.c
> +                }
We do not use implicit cast from integer to boolean. How about the following?
```
if (r >= 0) {
        *ret = saved_invocation_id;
        return 0;
} else if (r != -ENXIO)
        return r;
```

2022-06-09 20:34 UTC, i-do-cpp commented on src/libsystemd/sd-id128/sd-id128.c
> +                }
sounds good, the diff is now exactly what you suggested

2022-06-09 20:38 UTC, yuwata approved these changes
LGTM. Thank you.

2022-06-09 23:28 UTC, merged