Fixes for NULL-pointer arguments based on gcc warnings
systemd/systemd pull request #23658
Opened 2022-06-07 14:30 UTC by keszybz

Continuation of #23654.

2022-06-07 17:02 UTC, medhefgo approved these changes

2022-06-09 04:42 UTC, yuwata requested changes

2022-06-09 04:42 UTC, yuwata commented on src/test/test-dns-domain.c
> +        assert(expect);  /* for gcc */
This must be after `if (r >= 0)`.

2022-06-09 05:57 UTC, keszybz commented on src/test/test-dns-domain.c
> +        assert(expect);  /* for gcc */
Ah, indeed. Updated.

2022-06-09 11:16 UTC, yuwata approved these changes

2022-06-09 11:16 UTC, yuwata commented
```
../../src/systemd/src/shared/firewall-util-nft.c:931:74: error: too few arguments to function call, expected 5, have 4
        (void) in_addr_prefix_to_string(af, address, prefixlen, &addr_str);
               ~~~~~~~~~~~~~~~~~~~~~~~~                                  ^
../../src/systemd/src/basic/in-addr-util.h:96:5: note: 'in_addr_prefix_to_string' declared here
int in_addr_prefix_to_string(
    ^
1 error generated.
```
@keszybz Could you rebase this PR?

2022-06-09 16:47 UTC, bluca approved these changes

2022-06-09 16:48 UTC, merged