test: import hostname and locale tests from debian/ubuntu test suite
systemd/systemd pull request #23709
Opened 2022-06-11 04:19 UTC by yuwata

2022-06-12 04:32 UTC, yuwata commented
TODO: support debian patch: https://salsa.debian.org/systemd-team/systemd/-/blob/debian/experimental/debian/patches/debian/Use-Debian-specific-config-files.patch

2022-06-14 00:17 UTC, yuwata commented
Now this is ready. Please take a look!

2022-06-14 09:11 UTC, mrc0mmand requested changes
Looks excellent, just a couple of nits, thanks for working on this!

2022-06-14 09:11 UTC, mrc0mmand commented on test/test-functions
> +    for p in in "$@"; do
```suggestion
    for p in "$@"; do
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/test-functions
> +        for i in $(find "$p" 2>/dev/null || :); do
This will fall apart with paths containing spaces, maybe use something like:

```bash
while read -r item; do
...
done < <(find "$p" 2>/dev/null)
# No need for || : here
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/assert.sh
>      if [[ "$rc" != "0" ]]; then
```suggestion
    if [[ $rc -ne 0 ]]; then
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/assert.sh
> +    local rc exp=$1
```suggestion
    local rc exp="${1:?}"
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/assert.sh
>      if [[ "$1" != "$2" ]]; then
```suggestion
    if [[ "${1?}" != "${2?}" ]]; then
```
(No colons, since we want fail only on unset values, not empty ones)

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/assert.sh
> +    if ! [[ "$2" =~ $1 ]]; then
```suggestion
    if ! [[ "${2?}" =~ ${1?} ]]; then
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/assert.sh
> +    if [[ "$2" =~ $1 ]]; then
```suggestion
    if [[ "${2?}" =~ ${1?} ]]; then
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/testsuite-73.sh
> +    for ((i=0;i<20;i++)); do
```suggestion
    for ((i = 0; i < 20; i++)); do
```

2022-06-14 09:11 UTC, mrc0mmand commented on test/units/testsuite-73.sh
> +    trap restore_keymap EXIT
This could be, theoretically, simplified by using

```suggestion
    trap restore_keymap RETURN
```

and dropping all the

```bash
    restore_keymap
    trap - EXIT
```

statements below. Similarly in other functions.

2022-06-14 09:40 UTC, yuwata commented on test/units/assert.sh
> +    local rc exp=$1
Should this with colon?

2022-06-14 09:41 UTC, mrc0mmand commented on test/units/assert.sh
> +    local rc exp=$1
Ah, mea culpa, also without colon, I blame the muscle memory :-)

2022-06-14 12:09 UTC, yuwata commented
@mrc0mmand Thank you for the review. I hope all points are addressed. PTAL.

2022-06-14 13:30 UTC, mrc0mmand approved these changes
LGTM, thank you!

2022-06-15 03:00 UTC, merged