Follow-ups to #22587 and #23269
systemd/systemd pull request #23712
Opened 2022-06-11 15:37 UTC by topimiettinen

Add links to documentation to NetLabel, LSM, Netlabel Fallback Peer Labeling
and NFT.

Use a positive boolean function nft_identifier_good() to help grok the checks
more easily than nft_identifier_bad().

Escape logged invalid items.

Add an ASSERT_PTR() for 'data' in config_parse_netlabel().

Use a different debug message when NFT operation fails.

Align nfproto_table strings.

Remove NFT_SET_MSGS, it's only used once.

2022-06-12 12:05 UTC, topimiettinen commented
focal-amd64 fails with
```
upstream             FAIL non-zero exit status 1
```
Probably not related since other focals and everything else pass the tests.

2022-06-14 01:03 UTC, yuwata requested changes
Please do not squash changes. At least, please split the changes into two: for NFT and for NetLabel.

2022-06-14 01:03 UTC, yuwata commented on src/core/dbus-cgroup.c
>                                  return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid NFT table name %s.", table);
Please also escape the string in error message.

2022-06-14 01:03 UTC, yuwata commented on src/core/dbus-cgroup.c
>                                  return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid NFT set name %s.", set);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/core/dbus-execute.c
>                                  return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid NFT table name %s.", table);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/core/dbus-execute.c
>                                  return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid NFT set name %s.", set);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/network/networkd-netlabel.c
> +        Set **set = ASSERT_PTR(data);
Please insert a empty line between the function prototype and variable declaration.

Also, you can drop `assert(set);` below.

2022-06-14 01:03 UTC, yuwata commented on src/shared/firewall-util-nft.c
> +                log_debug_errno(r, "Failed to %s NFT family %s table %s set %s IP address %s: %m",
Maybe, better to add comma or colon between entries? E.g.
```
"Failed to %s NFT: family=%s, table=%s, set=%s, address=%s: %m"
```

2022-06-14 01:03 UTC, yuwata commented on src/shared/firewall-util-nft.c
> +                log_debug("%s NFT family %s table %s set %s IP address %s",
Also here.
```
"%s NFT: family=%s, table=%s, set=%s, address=%s"
```

2022-06-14 01:03 UTC, yuwata commented on src/shared/firewall-util-nft.c
>          [NFPROTO_NETDEV] = "netdev",
Please align with "=".

2022-06-14 01:03 UTC, yuwata commented on src/core/load-fragment.c
> +                        return log_syntax(unit, LOG_WARNING, filename, line, 0, "Invalid table name %s, ignoring", esc);
`cescape()` may fail. Please wrap `esc` with `strna()`.

2022-06-14 01:03 UTC, yuwata commented on src/core/load-fragment.c
> +                        return log_syntax(unit, LOG_WARNING, filename, line, 0, "Invalid set name %s, ignoring", esc);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/network/networkd-netlabel.c
> +                                   "Bad NetLabel label, ignoring: %s", esc);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/shared/firewall-util-nft.c
> +                        return log_syntax(unit, LOG_WARNING, filename, line, 0, "Invalid table name %s, ignoring", esc);
Also here.

2022-06-14 01:03 UTC, yuwata commented on src/shared/firewall-util-nft.c
> +                        return log_syntax(unit, LOG_WARNING, filename, line, 0, "Invalid set name %s, ignoring", esc);
Also here.

2022-06-14 06:46 UTC, yuwata commented
Now I am preparing a PR based on this. Please wait for a while.

2022-06-24 03:25 UTC, yuwata commented
Sorry, #22587 and #23269 are reverted. Please resubmit them with this change. Closing.

2022-06-24 03:25 UTC, closed without merging