core: Fix memory leaks
systemd/systemd pull request #23793
Opened 2022-06-21 11:56 UTC by steelman

arg_early_core_pattern and arg_watchdog_device hold pointers to memory
allocated with strdup() (inside path_make_absolute_cwd). The memory needs
to be freed in reset_arguments() during reload rather than forgotten.

2022-06-21 16:10 UTC, keszybz requested changes
Looks OK, apart from the one thing.

2022-06-21 16:10 UTC, keszybz commented on src/core/main.c
> +static char *arg_watchdog_device = NULL;
Please drop this chunk: see the comment above in line 117.

2022-06-21 17:09 UTC, steelman commented on src/core/main.c
> +static char *arg_watchdog_device = NULL;
Fixed. I've seen a commit that removed NULL assignments there but because it moved them to reset_arguments() I wasn't sure it is going to be fine (I am never 100% sure how automatic initialization works for each variable)

2022-06-21 18:10 UTC, keszybz commented on src/core/main.c
> +static char *arg_watchdog_device = NULL;
static variables are initialized to 0. So initializing them to e.g. NULL is a cosmetic thing to make it clearer to the reader what the initialization value is. But here we are initializing them explicitly in a different place, so initialization was removed here.

2022-06-22 00:31 UTC, bluca approved these changes

2022-06-22 00:31 UTC, merged