tmpfiles: accept additional tmpfiles lines via credential
systemd/systemd pull request #24014
Opened 2022-07-14 09:19 UTC by poettering

2022-07-14 11:06 UTC, bluca commented
Could you please add a test for this in TEST-54-CREDS?

2022-07-14 11:07 UTC, bluca approved these changes

2022-07-14 12:31 UTC, yuwata requested changes

2022-07-14 12:31 UTC, yuwata commented on man/systemd-tmpfiles.xml
> +        drop-in.</para></listitem>
"drop-in" -> "config"?

2022-07-14 12:31 UTC, yuwata commented on man/systemd-tmpfiles.xml
> +        <listitem><para>The contents of this credential may contain additional lines to operate on. The
I think, it is better to mention the priority of the contents. What happens when configs in tmpfiles.d and tmpfiles.extra contradicts?

2022-07-15 15:10 UTC, bluca commented on man/tmpfiles.d.xml
> +      <para>If the caret character (<literal>^</literal>) is used, the argument (i.e. 6th) column is takes a
/is takes/takes/

2022-07-15 15:24 UTC, yuwata requested changes

2022-07-15 15:24 UTC, yuwata commented on src/tmpfiles/tmpfiles.c
> +                        return log_syntax(NULL, LOG_ERR, fname, line, SYNTHETIC_ERRNO(EINVAL), "Reading from credential requested, but not credential name specified.");
not -> no

2022-07-15 15:24 UTC, yuwata commented on src/tmpfiles/tmpfiles.c
> +                if (IN_SET(r, -ENXIO, -ENOENT)) {
How about the other error case?

2022-07-15 16:44 UTC, yuwata commented
LGTM. But please rebase.

2022-07-16 06:14 UTC, yuwata commented
Lint Code Base CI does not like the test code:
```
In /github/workspace/test/TEST-54-CREDS/test.sh line 7:
NSPAWN_ARGUMENTS="${NSPAWN_ARGUMENTS:-} "\
                                         ^-- SC2140 (warning): Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```
How about the following?
```sh
NSPAWN_CREDS=(
    "--set-credential=mynspawncredential:strangevalue"
)
NSPAWN_ARGUMENTS="${NSPAWN_ARGUMENTS:-} ${NSPAWN_CREDS[*]}"

QEMU_CREDS=(
    "-fw_cfg name=opt/io.systemd.credentials/myqemucredential,string=othervalue"
    "-smbios type=11,value=io.systemd.credential:smbioscredential=magicdata"
    "-smbios type=11,value=io.systemd.credential.binary:binarysmbioscredential=bWFnaWNiaW5hcnlkYXRh"
    "-smbios type=11,value=io.systemd.credential.binary:sysusers.extra=dSBjcmVkdGVzdHVzZXIK"
    "-smbios type=11,value=io.systemd.credential.binary:tmpfiles.extra=ZiAvdG1wL3NvdXJjZWRmcm9tY3JlZGVudGlhbCAtIC0gLSAtIHRtcGZpbGVzc2VjcmV0Cg=="
)
QEMU_OPTIONS="${QEMU_OPTIONS:-} ${QEMU_CREDS[*]}"

KERNEL_CREDS=(
    "systemd.set_credential=kernelcmdlinecred:uff"
    "systemd.set_credential=sysctl.extra:kernel.domainname=sysctltest"
    "systemd.set_credential=login.motd:hello"
    "systemd.set_credential=login.issue:welcome"
    "rd.systemd.import_credentials=no"
)
KERNEL_APPEND="${KERNEL_APPEND:-} ${KERNEL_CREDS[*]}"
```

2022-07-20 22:07 UTC, poettering commented
> How about the following?

Excellent! That works and looks pretty! Thank you!

Will rebase with that and push a new version shortly. PTAL

2022-07-20 22:14 UTC, yuwata approved these changes

2022-07-21 10:51 UTC, bluca commented
Could this be related? Any idea @mrc0mmand ?

```
00:48:39 FAILED TASKS:
00:48:39 -------------
00:48:39 TEST-35-LOGIN
```

2022-07-21 10:52 UTC, mrc0mmand commented
> Could this be related? Any idea @mrc0mmand ?
> 
> ```
> 00:48:39 FAILED TASKS:
> 00:48:39 -------------
> 00:48:39 TEST-35-LOGIN
> ```

Nah, that's #24040.

2022-07-21 10:55 UTC, merged