decgroupsv1ification: first steps – remove from docs, and generate warnings
systemd/systemd pull request #24072
Opened 2022-07-21 21:15 UTC by poettering

It appears unlikely we can quickly remove cgroupsv1 support from our tree. But I guess we can start with removing any mentions of it from the docs, and generating warnings if people still use cgroupsv1-specific options.

This doesn't change anything code-wise really, it just simplifies the docs by removing a lot of cgroupsv1/cgroupsv2 conditionalizations.

2022-07-22 13:34 UTC, DaanDeMeyer approved these changes

2022-07-22 13:45 UTC, keszybz requested changes
I know that this is how we used to do things, but I think we should be more user-friendly and keep mentions of the obsolete settings in the docs. This is something we discussed during one of the meetings. Instead of simply dropping the docs, I'd very much prefer to add a section like "History" or "Obsolete Interfaces" and add a few short paragraphs there:

  BlockIOWeight= ,BlockIODeviceWeight=, …, have been obsoleted. Use IOWeight=, IODeviceWeight=…, instead. 

The motivation for this is that users will encounter those old settings in their units, and if we have this in the docs, it's much easier for users to figure out that the setting is deprecated (and later that is has been removed). People can also link to this section of the man page as  documentation. Only having this embedded in code and logs is not enough for many use cases. This transitions will go on for a long time, so easily-accessible and linkable docs for this will be very useful.

This would be a one time addition, so there wouldn't be any maintenance burden.

2022-07-22 13:45 UTC, keszybz commented on src/core/load-fragment.c
> +                           "This is an obsolete cgroupv1 setting, please update to use MemoryMax= instead. Support for MemoryLimit= will be removed soon.");
"Unit uses MemoryLimit=; please use MemoryMax= instead. Support for MemoryLimit= will be removed soon."

2022-07-22 14:18 UTC, poettering commented
> BlockIOWeight= ,BlockIODeviceWeight=, …, have been obsoleted. Use IOWeight=, IODeviceWeight=…, instead.

We have carried this for a long time. This PR gets rid of that. That's the whole point.

2022-07-22 14:34 UTC, keszybz commented
We can drop the detailed explanations of the old options. That's a lot of text that we don't need. If the choice is only between "drop everything" (like in the current version), and "keep things unchanged", then actually the latter is would be better. But I hope we can strike the middle (or 90-th centile) ground of removing everything but a brief mention to guide users in the right direction.

2022-08-23 07:33 UTC, keszybz commented
I did some small fixups to your commits (as discussed above) and add a commit that adds "History" sections with a list of removed settings. The PR needed a rebase anyway, so I didn't open a new pull request. I hope that's OK.

2022-08-24 15:00 UTC, merged