sysctl: add --strict option to fail if sysctl does not exists
systemd/systemd pull request #24087
Opened 2022-07-22 15:35 UTC by qdeslandes

systemd-sysctl currently fails silently under any of these conditions:
- Missing permission to write a sysctl.
- Invalid sysctl (path doesn't exists).
- Ignore failure flag ('-' in front of the sysctl name).

Because of this behaviour, configuration issues can go unnoticed as
there is no way to detect those unless going through the logs.

--strict option forces systemd-sysctl to fail if a sysctl is invalid or
if permission are insufficient. Errors on sysctl marked as "ignore
failure" will still be ignored.

Also, added integration tests for systemd-sysctl.

2022-07-22 15:49 UTC, poettering commented
looks good, but needs man page update, too.

2022-07-22 16:41 UTC, qdeslandes commented
Updated man page to include details about new option.

2022-07-22 18:12 UTC, DaanDeMeyer commented
Forgot to push manpage update?

2022-07-22 19:31 UTC, poettering commented
yupp, man page missing in git commit? maybe forgot to add via "git add"?

2022-07-24 06:35 UTC, qdeslandes commented
Pushed update with the man page change...

2022-07-24 11:57 UTC, yuwata commented
```
15:42:18 ../man/systemd-sysctl.service.xml:73: parser error : Opening and ending tag mismatch: para line 70 and listitem
15:42:18         </listitem>
15:42:18                    ^
15:42:18 ../man/systemd-sysctl.service.xml:74: parser error : Opening and ending tag mismatch: listitem line 69 and varlistentry
15:42:18       </varlistentry>
15:42:18                      ^
15:42:18 ../man/systemd-sysctl.service.xml:81: parser error : Opening and ending tag mismatch: varlistentry line 67 and variablelist
15:42:18     </variablelist>
15:42:18                    ^
15:42:18 ../man/systemd-sysctl.service.xml:82: parser error : Opening and ending tag mismatch: variablelist line 60 and refsect1
15:42:18   </refsect1>
15:42:18              ^
15:42:18 ../man/systemd-sysctl.service.xml:161: parser error : Opening and ending tag mismatch: refsect1 line 59 and refentry
15:42:18 </refentry>
15:42:18            ^
15:42:18 ../man/systemd-sysctl.service.xml:162: parser error : Premature end of data in tag refentry line 6
15:42:18 
15:42:18 ^
15:42:18 unable to parse ../man/systemd-sysctl.service.xml
```

2022-07-24 11:57 UTC, yuwata requested changes
LGTM, except for the CI error about the man page.

2022-07-24 11:58 UTC, yuwata commented on man/systemd-sysctl.service.xml
> +          character.
Missing `</para>`.

2022-07-25 08:15 UTC, DaanDeMeyer approved these changes

2022-07-25 08:15 UTC, merged