Migrate cgroups to bus-locator.h
systemd/systemd pull request #24251
Opened 2022-08-08 20:04 UTC by josh-gordon-fb

Migrated cgroups.c to use new bus-locator.h bus_call_method call

2022-08-08 20:11 UTC, DaanDeMeyer requested changes
We don't use the internal commit message template in systemd. Please modify the commit message to just a description of the change.

Also, the second commit needs to be merged into the first one. We want to be able to build systemd from each commit, that wouldn't work with the first commit

2022-08-08 20:11 UTC, DaanDeMeyer commented on src/core/cgroup.c
> +                               bus_systemd_mgr,
Please align this line and the following ones just like it was before

2022-08-08 20:11 UTC, DaanDeMeyer commented on src/core/cgroup.c
> +#include "bus-locator.h"
Please sort includes

2022-08-09 05:40 UTC, yuwata approved these changes

2022-08-09 07:20 UTC, merged