Reduce sd_bus verbosity with bus functions
systemd/systemd pull request #24252
Opened 2022-08-08 20:12 UTC by gtwang01

Summary:
D-Bus functions are less verbose than sd_bus functions.
This modifies some sd_bus calls to equivalent bus calls.

Test Plan:
meson build -Dmode=developer
meson compile -C build
meson test -C build

2022-08-08 20:45 UTC, bluca approved these changes

2022-08-09 00:08 UTC, evverx commented
@gtwang01 I wonder why the "From" field in the commit message is `{{ <{{>`?

2022-08-09 00:11 UTC, evverx commented
@mrc0mmand on a somewhat related note I think https://github.com/systemd/systemd/blob/main/.github/workflows/coverity.yml#L31 should probably avoid using `--pretty=\"%aE\"` coming from random commit messages.

2022-08-09 00:14 UTC, gtwang01 commented
> @gtwang01 I wonder why the "From" field in the commit message is `{{ <{{>`?

I... have no idea. Does this happen often?

2022-08-09 00:26 UTC, evverx commented
I don't think it happens very often. It should be possible to change that by running something like
```sh
git config --global user.name "firstname lastname"
git config --global user.email "realaddress@example.com"
git commit --reset-author --amend
```
and force-pushing the branch.

2022-08-09 00:48 UTC, evverx commented
@gtwang01 thanks! FWIW looking at https://github.com/systemd/systemd/pull/24251 it appears templates of some kind were used to set up `git` and `{{` and `}}` were copied verbatim even though they should have probably been removed somewhere.

2022-08-09 01:14 UTC, yuwata requested changes
Could you drop the unnecessary fields of the commit message, e.g. test plan, reviewers, and so on.

2022-08-09 01:14 UTC, yuwata commented on src/sulogin-shell/sulogin-shell.c
> +                "ss", SPECIAL_DEFAULT_TARGET, "isolate");
Please use 16ch indentation.

2022-08-09 02:07 UTC, vcaputo commented
It's surprising how much it pleases me to see PRs migrating code to the less verbose BusLocator-oriented API.

2022-08-09 05:45 UTC, yuwata approved these changes

2022-08-09 07:19 UTC, merged

2022-08-09 08:37 UTC, DaanDeMeyer commented
> It's surprising how much it pleases me to see PRs migrating code to the less verbose BusLocator-oriented API.

These make for amazing starter tasks to get new people familiar with contributing. I'm going to be rather sad once we run out of them.