dissect: drop unused arguments
systemd/systemd pull request #24482
Opened 2022-08-28 03:52 UTC by yuwata

2022-08-28 08:22 UTC, mrc0mmand approved these changes
The loopback devices are truly an infinite source of _fun_.

2022-08-28 08:22 UTC, mrc0mmand commented on src/shared/loop-util.c
> +                        return log_debug_errno(r, "Failed to determine if a file descritor is attached to the loopback device: %m");
descritor -> descriptor

2022-08-28 10:37 UTC, bluca commented
Why is the diskseq stuff being removed? We got it added to newer kernels to fix these races - of course won't help with older kernels, but at some point if should work out no?

2022-08-28 10:46 UTC, yuwata commented
> Why is the diskseq stuff being removed? We got it added to newer kernels to fix these races - of course won't help with older kernels, but at some point if should work out no?

As you can see, at least now it is not used, ie the argument is completely ignored. Please revert it when it is used.

2022-08-28 10:48 UTC, yuwata commented
Or, are there any places I dropped in this PR where the diskseq is really used?

2022-08-28 10:49 UTC, bluca commented
But it was used when it was introduced? Where did that stuff go?

2022-08-28 10:53 UTC, yuwata commented
I cannot dig the git history now from cellphone, but I guess these entries in LoopDevice were stopped to be used when Lennart stop to use sd_device_monitor for detecting loopback devices.

2022-08-28 12:50 UTC, bluca commented
@poettering do you remember what's the full story? It was quite hard to get the diskseq stuff in the kernel and it was explicitly to fix these issues, it's a pity if it was all for naught...

2022-08-29 05:29 UTC, yuwata commented
@bluca diskseq or friends are not used since 1b010ae7c96d953f11a9925d4c5aef29befc86d1.

2022-08-31 09:49 UTC, yuwata commented
BTW @mrc0mmand Does this help issue #24450?? Could you run a stress test for TEST-50-DISSECT with this PR?

2022-08-31 12:30 UTC, mrc0mmand commented
> BTW @mrc0mmand Does this help issue #24450?? Could you run a stress test for TEST-50-DISSECT with this PR?

I ran TEST-50-DISSECT 100 times in a row with this PR and it didn't fail a single time, so I'm inclined to say it might potentially fix that issue (but won't say it directly, otherwise something else breaks).

2022-09-01 09:58 UTC, poettering commented on src/shared/loop-util.h
> -        uint64_t diskseq; /* Block device sequence number, monothonically incremented by the kernel on create/attach, or 0 if we don't know */
I'd really keep the diskseq, it's how we can pin our use of the loopback device. Even if the current dissection stuff doesn#t use it, it probably should, and condition the partition removal to only execute if it still matches the original diskseq (enclosed in a BSD lock)

2022-09-01 10:03 UTC, poettering requested changes

2022-09-01 10:03 UTC, poettering commented on src/shared/loop-util.c
> +static int device_has_block_children(int nr) {
should be renamed to `loop_block_device_has_children()` or so. It doesn't work for generic block devices anymore, after all, just for loopback devices

2022-09-01 10:03 UTC, poettering commented on src/shared/loop-util.c
> +         * again. This suffices to make the partitions go away. Ugly but appears to work. */
so, back when i added this code i wasn't aware of BLKPG_DEL_PARTITION. I wonder if a loop around that wouldn't have the same effect but be less ugly?

i.e. remove all partitions in a loop, until none are left?

2022-09-01 14:18 UTC, poettering commented
Inspired by this I prepped a PR in #24530, which fixes a bunch of related things. It also gets rid of the attach empty file logic entirely, in favour of explicit partition deletion, as I suggested above.

That new PR makes the last two of the commits in this PR redundant, I guess. (one because it drops the empty file attach stuff, the other because we actually add proper locking around clear+delete of block devices. at least in my tests this makes things entirely clean in test-loop-block even with 200 threads and 200 iterations)

2022-09-01 16:59 UTC, yuwata commented
@poettering Thanks. I will update or close this after your PR is merged.

2022-09-02 20:37 UTC, closed without merging