repart: Add support for setting a partitiont's UUID to zero
systemd/systemd pull request #24560
Opened 2022-09-04 16:54 UTC by DaanDeMeyer

This is useful when we need to fill in the UUID later, such as when
using verity partitions.

2022-09-04 18:37 UTC, yuwata requested changes

2022-09-04 18:37 UTC, yuwata commented on src/partition/repart.c
> +                                TABLE_UUID, !sd_id128_is_null(p->new_uuid) || p->new_uuid_is_set ? p->new_uuid : p->current_uuid,
Why not simply use `p->new_uuid_is_set`? I think `!sd_id128_is_null()` is completely redundant.

2022-09-04 18:37 UTC, yuwata commented on src/partition/repart.c
> +        if (!sd_id128_is_null(p->new_uuid) || p->new_uuid_is_set)
Also here.

2022-09-04 18:37 UTC, yuwata commented on src/partition/repart.c
> +                else if (sd_id128_is_null(p->new_uuid) && !p->new_uuid_is_set) {
Also here.

2022-09-04 18:37 UTC, yuwata commented on src/partition/repart.c
> +                if (sd_id128_is_null(p->new_uuid) && !p->new_uuid_is_set && !sd_id128_is_null(uuid))
And here.

2022-09-04 18:37 UTC, yuwata commented on src/partition/repart.c
> +        r = sd_id128_from_string(rvalue, &partition->new_uuid);
How about to accept a special value `"empty"`?

2022-09-05 09:06 UTC, poettering commented on src/partition/repart.c
> +        if (streq(rvalue, "empty")) {
Is "empty" the right word? we can't really set it to "empty". only to `00000000-0000-0000-0000-000000000000`, which maybe we should call "null" (after all, the C macro for it is called `SD_ID128_NULL`?)

Also, please mention this shortcut in the man page

2022-09-05 12:12 UTC, poettering commented
lgtm

2022-09-05 13:05 UTC, keszybz requested changes

2022-09-05 13:05 UTC, keszybz commented on src/partition/repart.c
>                          p->new_uuid = uuid;
I think ` p->new_uuid_is_set` should be set here, even if it does not matter for current logic, just so that we have a self-consistent state.

2022-09-05 13:56 UTC, yuwata approved these changes
LGTM.

2022-09-05 14:19 UTC, merged