xdg-autostart-service: expand tilde in Exec lines
systemd/systemd pull request #24658
Opened 2022-09-13 14:57 UTC by davidedmundson

In typical desktop file parsing it is expected that "~" expands to a home directory.

Users may write an autostart file with "Exec=myCoolService ~/.someSpecialConfig" which worked before the systemd migration.

Downstream bug: https://bugs.kde.org/show_bug.cgi?id=455252#c18

2022-09-13 19:06 UTC, yuwata requested changes

2022-09-13 19:06 UTC, yuwata commented on src/xdg-autostart-generator/test-xdg-autostart.c
> +
doubled empty line.

2022-09-13 19:06 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +#include "user-util.h"
Please sort.

2022-09-13 19:06 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                tilde_expanded = strreplace(percent, "~", home);
I do not think we should replace all `"~"`, e.g. `"foo~baz~aaa"`.
I think we should replace tilde only when the string starts with single tilde and remaining is empty or path:
- `"~"` -> `"/home/username"`
- `"~/path/to/file"` -> `"/home/username/path/to/file"`

2022-09-14 21:29 UTC, yuwata requested changes
Looks mostly good. Several minor suggestions or coding style issues.

2022-09-14 21:29 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                 * Expand ~ if it comes as part of a path
Strictly speaking, 'part of a path' -> 'beginning of a path'

2022-09-14 21:29 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                if (percent[0] == '~' && (strlen(percent) == 1 || percent[1] == '/')) {
Not a matter, but using `isempty()` and `path_is_absolute()` is better.
```
if (percent[0] == '~' && (isempty(percent + 1) || path_is_absolute(percent + 1))) {
```

2022-09-14 21:29 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                        r = get_home_dir(&home);
Please insert an empty line between variable declaration and code.

2022-09-14 21:29 UTC, yuwata commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                }
Please drop unnecessary `{}` for single line block.

2022-09-15 10:30 UTC, davidedmundson commented
Thanks for the help, it's always tricky with coding styles and string functions when jumping into foreign projects.

2022-09-15 11:36 UTC, yuwata approved these changes

2022-09-15 12:00 UTC, davidedmundson commented
>The test is still broken when running as part of TEST-02:

Right, the code is doing the right things. The test fails as I'm comparing to "getenv("HOME")" which apparently isn't always set. I've ported the test to use the same get_home_dir function

2022-09-15 18:43 UTC, merged

2022-09-16 09:10 UTC, poettering commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                        tilde_expanded = strjoin(home, &percent[1]);
path_join() sounds safer?

2022-09-16 09:12 UTC, poettering commented
Hmm, ~ is only allowed at the beginning of arguments?

AFAICS the .deskop spec doesn't specify this syntax. And intention to add it there?

2022-09-16 09:12 UTC, poettering commented
Did GNOME also support this ~ extension? Or was that a KDE thing?

2022-09-16 09:14 UTC, poettering commented on src/xdg-autostart-generator/xdg-autostart-service.c
> +                 */
Can you include in this comment that this is an extension to the .desktop spec?

2022-10-11 09:58 UTC, benzea commented
> Did GNOME also support this ~ extension? Or was that a KDE thing?

No, it does not look like GNOME ever supported this (i.e. neither the .desktop file code nor the used g_shell_parse_argv API does it).

2022-10-11 10:31 UTC, davidedmundson commented
Sorry for the delay, it's easy to miss comments in a merged PR.

I have addressed the technical parts at https://github.com/systemd/systemd/pull/24963

>Did GNOME also support this ~ extension? Or was that a KDE thing?

Apparently it's only a KDE thing. It's not explicitly supported in the spec to be expanded. But it is listed as saying it should be escaped if it is to be preserved. For that reason this patch also explicitly doesn't break the spec. 

Unfortunately in KDE we had quite a lot of flexible Exec parsing; which wasn't problematic at the time, but it's caused some fallout after we switched. Some we've sent back to the users, some I've tried to upstream if I thought it was more universal and not risky.

It's only at the start of args as the goal is to have a more shell like syntax.