systemd/udev: nvme/nvmf are not showed up in /dev/disk/by-path
systemd/systemd pull request #24748
Opened 2022-09-19 17:28 UTC by wxiong38

In the newer kernel, nvme_core.multipath=Y is set by default. With this setting, nvme/nvmf devices are not showed up in /dev/disk/by-path.

The patch fixes the issues. With the patch,  nvme/nvmf are showed up in /dev/dis/by-path:

lrwxrwxrwx. 1 root root 13 Sep 18 17:16 pci-0581:10:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx. 1 root root 13 Sep 19 12:23 pci-0582:18:00.0-nvme-1 -> ../../nvme1n1
lrwxrwxrwx. 1 root root 13 Sep 19 12:23 pci-0584:28:00.0-nvme-1 -> ../../nvme2n1
lrwxrwxrwx. 1 root root 13 Sep 19 12:23 pci-0585:48:00.0-nvme-1 -> ../../nvme3n1
lrwxrwxrwx. 1 root root 13 Sep 19 12:23 pci-0588:30:00.0-nvme-1 -> ../../nvme4n1
lrwxrwxrwx. 1 root root 13 Sep 19 12:23 pci-05ae:78:00.0-nvme-1 -> ../../nvme5n1
lrwxrwxrwx. 1 root root 13 Sep 18 17:16 pci-05b2:a0:00.0-nvme-1 -> ../../nvme6n1

Signed-off-by: Wen Xiong<wenxiong@linux.ibm.com>

2022-09-20 06:06 UTC, yuwata requested changes
Could you explain more in the commit message?
When the kernel config was introduced? Which kernel version changes the default?
Also, please provide an example syspath for a nvme block device with the kernel config enabled.

BTW, we do not use "Signed-off-by" tag. Unless your company really requests that, please drop it.

2022-09-20 06:06 UTC, yuwata commented on rules.d/60-persistent-storage.rules
> +KERNEL=="nvme*[0-9]n*[0-9]", IMPORT{builtin}="path_id"
Why this is required? I think `path_id` builtin command is called by the previous line, so this line is redundant.

2022-09-20 06:06 UTC, yuwata commented on src/udev/udev-builtin-path_id.c
> +#include "fs-util.h"
Please sort the header.

2022-09-20 06:06 UTC, yuwata commented on src/udev/udev-builtin-path_id.c
> +				syspath = strjoina(syspath, nvme_ctl);
I cannot follow, but it seems `syspath` build from `parent` here is almost equivalent to the syspath obtained by `dev`.

Why not to simply build name with the same logic that `"nvme"` subsystem uses?

2022-09-20 06:06 UTC, yuwata commented on src/udev/udev-builtin-path_id.c
> +					path_prepend(&path, "pci-%s", m[4]);
No no, please do not do like that, but update `parent` device with the syspath.

2022-09-20 06:28 UTC, yuwata commented
Please provide the result of `udevadm info --attribute-walk /sys/class/block/nvme0n1`.

2022-09-20 06:40 UTC, yuwata commented
Hm, on my system multipath seems to be enabled.
```sh
$ cat /sys/module/nvme_core/parameters/multipath
Y
```
And, still symlinks are created without changing anything.
```sh
$ udevadm info /sys/class/block/nvme0n1
P: /devices/pci0000:00/0000:00:1c.4/0000:3c:00.0/nvme/nvme0/nvme0n1
M: nvme0n1
R: 1
U: block
T: disk
D: b 259:0
N: nvme0n1
L: 0
S: disk/by-id/nvme-eui.1922908022470001001b448b44ccb9d6
S: disk/by-id/nvme-WDC_PC_SN720_SDAQNTW-512G-1001_192290802247
S: disk/by-path/pci-0000:3c:00.0-nvme-1
Q: 1
E: DEVPATH=/devices/pci0000:00/0000:00:1c.4/0000:3c:00.0/nvme/nvme0/nvme0n1
E: SUBSYSTEM=block
E: DEVNAME=/dev/nvme0n1
E: DEVTYPE=disk
E: DISKSEQ=1
E: MAJOR=259
E: MINOR=0
E: USEC_INITIALIZED=15698390
E: ID_SERIAL_SHORT=192290802247
E: ID_WWN=eui.1922908022470001001b448b44ccb9d6
E: ID_MODEL=WDC PC SN720 SDAQNTW-512G-1001
E: ID_REVISION=10160101
E: ID_SERIAL=WDC_PC_SN720_SDAQNTW-512G-1001_192290802247
E: ID_PATH=pci-0000:3c:00.0-nvme-1
E: ID_PATH_TAG=pci-0000_3c_00_0-nvme-1
E: ID_PART_TABLE_UUID=7e773455-103c-4c76-bec0-9fba186c3c65
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-id/nvme-eui.1922908022470001001b448b44ccb9d6 /dev/disk/by-id/nvme-WDC_PC_SN720_SDAQNTW-512G-1001_192290802247 /dev/disk/by-path/pci-0000:3c:00.0-nvme-1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```
```sh
$ ls -l /dev/disk/by-path
total 0
lrwxrwxrwx 1 root root  9 Sep  7 02:23 pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 13 Sep  7 02:23 pci-0000:3c:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx 1 root root 15 Sep  7 02:23 pci-0000:3c:00.0-nvme-1-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root 15 Sep  7 02:23 pci-0000:3c:00.0-nvme-1-part2 -> ../../nvme0n1p2
```

2022-09-20 09:32 UTC, poettering commented on src/udev/udev-builtin-path_id.c
> +		} else if (streq(subsys, "nvme-subsystem")) {
hmm, what's the difference between the subsystems called "nvme" and "nvme-subsystem"? this is weird...

2022-09-20 09:33 UTC, poettering commented
error checking sems entirely absent...

2022-09-20 11:52 UTC, yuwata commented
Hm,,, from https://bugzilla.redhat.com/show_bug.cgi?id=2031810
> ```
> [root@hulk ~]# udevadm info --query=property --name=/dev/nvme0n1
> DEVPATH=/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
> ```

2022-09-20 17:33 UTC, yuwata commented
Replaced with #24766.

2022-09-22 10:29 UTC, closed without merging

2022-11-19 11:05 UTC, daiaji commented
```
cat /etc/udev/rules.d/01-nvme.rules
ACTION=="change", SUBSYSTEM=="nvme", DEVNAME=="/dev/nvme0", ENV{SYSTEMD_WANTS}="device-attach.service", TAG+="systemd"

sudo cat /etc/systemd/system/device-attach.service 
[Unit]
Description=Notify about attached device

[Service]
Type=oneshot
ExecStart=/usr/bin/echo 'device has been attached'

nvme reset /dev/nvme0                        
                                                                                                                                                                                                             journalctl -xe -n all -b -u device-attach.service
-- No entries --

udevadm monitor --environment
KERNEL[1167.744669] change   /devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0 (nvme)
ACTION=change
DEVPATH=/devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0
SUBSYSTEM=nvme
NVME_EVENT=connected
DEVNAME=/dev/nvme0
NVME_TRTYPE=pcie
SEQNUM=4857
MAJOR=238
MINOR=0

```
It seems that udev events bound to nvme will not be triggered.
Is this a fault of similar cause?