udev-builtin-net_id: support getting usb path and slot without pci
systemd/systemd pull request #24981
Opened 2022-10-12 18:40 UTC by chardin-cpi

Several asics have usb controllers that are platform devices and not children of a pci interface. These embedded systems should be able to enumerate interfaces by usb slot or path as well to support configurations based upon predictable interface names as needed.

Signed-off-by: Charles Hardin <charles.hardin@chargepoint.com>

# CODE FREEZE NOTICE

An -rc1 tag has been created and a release is being prepared, so please note that
PRs introducing new features and APIs will be held back until the new version
has been released.

2022-10-12 20:02 UTC, yuwata commented
I will consider this after v252 released.

2022-10-13 08:54 UTC, poettering requested changes
This also requires a flag in NamingSchemeFlags and conditionalization based on that. plus documentation in man/systemd.net-naming-scheme.xml

2022-10-13 08:54 UTC, poettering commented on src/udev/udev-builtin-net_id.c
> +        if (names_pci(dev, &info, &names) < 0) {
I'd really conditionalize this on -ENXIO specifically, not other erros

2022-10-13 08:54 UTC, poettering commented on src/udev/udev-builtin-net_id.c
> +                                udev_builtin_add_property(dev, test, "ID_NET_NAME_SLOT", str);
this is bogus. you are setting both udev props to the exact same string. there's no point in that...

if you have no PCI i guess there's no concept of "slots", hence don't generate this prop at all.

2022-10-15 16:39 UTC, chardin-cpi commented on src/udev/udev-builtin-net_id.c
> +        if (names_pci(dev, &info, &names) < 0) {
sd_device_get returns -ENOENT on the imx8 aarch64 at least - so, conditionalizing on that

2022-10-16 12:22 UTC, poettering commented on man/systemd.net-naming-scheme.xml
> +          <listitem><para>Set <varname>ID_NET_NAME_PATH</varname> for usb devices off a host controller.</para>
I think what matters to say here is that this is *not* connected via a PCI bus.

2022-10-31 20:11 UTC, merged