Install: tiny cleanups
systemd/systemd pull request #25122
Opened 2022-10-25 08:38 UTC by yuwata

2022-10-25 09:14 UTC, bluca approved these changes

2022-10-25 12:59 UTC, keszybz requested changes

2022-10-25 12:59 UTC, keszybz commented on src/shared/install.c
> -                        continue;
No, this is wrong. `return` was added inadvertently in 94e7298d309fef7710174def820e9d38e512a086. We want to do the full loop here and collect any errors in `changes`.

2022-10-25 12:59 UTC, keszybz commented on src/shared/install.c
> -                        continue;
We should fix this before the release. I added this to the milestone.

2022-10-25 15:32 UTC, yuwata commented
@keszybz Updated. PTAL.

2022-10-28 12:36 UTC, keszybz commented
LGTM.

2022-10-28 12:36 UTC, merged