network: wifi: check SSID when AP interfaces gain carrier
systemd/systemd pull request #25488
Opened 2022-11-22 15:35 UTC by sipraga

The only signal the kernel gives when an AP interface is configured with a particular SSID is when it gains carrier. In that event, it should be possible to query the SSID and reconfigure.

2022-11-22 15:36 UTC, sipraga commented
This is a draft fix for https://github.com/systemd/systemd/issues/25384.

2022-11-30 01:10 UTC, yuwata requested changes
Looks basically good to me. Several coding style requests.

2022-11-30 01:10 UTC, yuwata commented on src/network/networkd-link.c
> +                link_get_wlan_interface(link);
Missing error handling.

2022-11-30 01:10 UTC, yuwata commented on src/network/networkd-wifi.h
> +int link_get_wlan_interface(Link *link);
Please add a typedef for `Link` in the above, like for `Manager`.

2022-12-05 15:30 UTC, sipraga commented
Thanks @yuwata for checking. I still need to check something more on my end before I fix this up. I will update when ready.

2022-12-08 16:25 UTC, sipraga commented
Hi @yuwata

I have addressed the style comments you had.

In my testing, I found that the kernel's interface is not quite good enough to cover all scenarios. Specifically, if the AP undergoes rapid reconfigurations, it may lose and gain carrier a couple of times, but the kernel will silently drop linkdown/linkup events if the transition is short enough such that the time between a new linkup event and the last linkup event was less than 1 second.

This was very strange and finally I found my answer by reading the code in Linux related to link_watch.

Anyway, in order to improve on this situation, I would propose that the kernel emits an NL80211_CMD_START_AP on the multicast group whenever an AP goes up. That gives networkd something to react to. I have updated my commit to include handling for this scenario as well.

Please tell me what you think of this approach. I don't ask you to comment on whether the kernel change would be accepted (that is for Linux maintainers to decide), but rather your opinion as the maintainer of a consumer of this API (networkd).

If you find this agreeable, I will:

1. submit suitable changes to the linux-wireless mailing list to add the START_AP event
2. come back to this PR when the changes have landed in a stable kernel
3. then we can merge this

If you prefer, I can split the commit into two:

1. the original proposal I had (which covers the vast majority of realistic scenarios); this could be merged even today if you like
2. the extra code added to handle the new kernel event, which will make networkd fully robust.

Hope that makes sense. Thank you!

2022-12-15 08:26 UTC, yuwata approved these changes
Looks mostly good. Several minor nitpicks.

Even if the kernel will provide better notification in the future, we need to still support the old kernel for a while. Hence, let's go with this logic.

2022-12-15 08:26 UTC, yuwata commented on src/network/networkd-wifi.c
> +
Not a big matter, but please drop the empty line.

2022-12-15 08:26 UTC, yuwata commented on src/network/networkd-link.c
> +        if (IN_SET(link->wlan_iftype, NL80211_IFTYPE_AP, NL80211_IFTYPE_P2P_GO)) {
Please add a brief comment why we need to actively update SSID or so.

2022-12-15 09:27 UTC, sipraga commented
> Looks mostly good. Several minor nitpicks.
> 
> Even if the kernel will provide better notification in the future, we need to still support the old kernel for a while. Hence, let's go with this logic.

Thanks! I will follow up later today and address your comments.

FYI, here is the kernel change I submitted (no feedback yet): https://lore.kernel.org/linux-wireless/20221209152836.1667196-1-alvin@pqrs.dk/

2022-12-15 15:31 UTC, sipraga commented
@yuwata address your comments, should be good to go now

2022-12-15 15:42 UTC, yuwata approved these changes

2022-12-15 15:43 UTC, yuwata commented
LGTM. Thank you!

2022-12-15 18:38 UTC, merged