blkid: add helpers that get gpt partition uuid as sd_id128_t
systemd/systemd pull request #25534
Opened 2022-11-25 17:58 UTC by poettering

just some refactoring to make things simpler.

2022-11-25 22:14 UTC, yuwata requested changes

2022-11-25 22:14 UTC, yuwata commented on src/partition/repart.c
> +                log_debug_errno(r, "Partition %u:%u has no UUID.", major(partition_devno), minor(partition_devno));
`DEVNUM_FORMAT_STR` can be used.

2022-11-25 22:14 UTC, yuwata commented on src/partition/repart.c
> +                log_debug_errno(r, "Failed to read partition UUID off %u:%u: %m", major(partition_devno), minor(partition_devno));
- `"off"` -> `"of"`
- `DEVNUM_FORMAT_STR` can be used.

2022-11-25 22:14 UTC, yuwata commented on src/shared/blkid-util.h
>  #  include "macro.h"
Please insert an empty line after the `sd` header.

2022-11-25 22:14 UTC, yuwata commented on src/shared/blkid-util.h
> +static inline int blkid_partition_get_uuid_id128(blkid_partition p, sd_id128_t *ret) {
missing assertion for `p`

2022-11-25 22:14 UTC, yuwata commented on src/shared/blkid-util.h
> +static inline int blkid_partition_get_type_id128(blkid_partition p, sd_id128_t *ret) {
Also here.

2022-11-25 22:14 UTC, yuwata commented on src/shared/dissect-image.c
> +                                log_debug_errno(r, "Failed to read partitiont type UUID, ignoring: %m");
`"partitiont"` -> `"partition"`

2022-11-29 10:48 UTC, poettering commented
updated, ptal

2022-11-29 11:10 UTC, DaanDeMeyer approved these changes

2022-11-29 11:32 UTC, yuwata approved these changes

2022-11-29 15:05 UTC, merged