nspawn: reduce number of sockets
systemd/systemd pull request #25575
Opened 2022-11-30 14:47 UTC by brauner

Currently, nspawn opens a multitude of sockets to send various stuff between
the child and parent. This is excessive and wasteful. Just rely on two
well-defined sockets. An outer socket used for synchronization between the
monitor and the outer child and a an inner socket for synchronization between
monitor and inner child.

Note, before this branch can be merged
https://github.com/systemd/systemd/pull/25513
should first be merged.

Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>

2022-11-30 15:32 UTC, brauner commented on src/nspawn/nspawn.c
> +                        l = send(fd_outer_socket_pair[0], &arg_uid_shift, sizeof arg_uid_shift, MSG_NOSIGNAL);
What?

2022-12-13 12:06 UTC, poettering requested changes
sorry for taking so long. looks vastly simpler. Thanks so much.

2022-12-13 12:06 UTC, poettering commented on src/nspawn/nspawn.c
> +                        l = send(fd_outer_socket_pair[0], &arg_uid_shift, sizeof arg_uid_shift, MSG_NOSIGNAL);
I think the correct response is "CodeQL, go home, you are drunk!"

2022-12-13 12:06 UTC, poettering commented on src/nspawn/nspawn.c
> +                r = expose_port_send_rtnl(fd_inner_socket);
so, we'll now enqueue the kmsg fifo first on fd_inner_socket, nd the rtnl stuff after that…

2022-12-13 12:06 UTC, poettering commented on src/nspawn/nspawn.c
> +                r = expose_port_watch_rtnl(event, fd_inner_socket_pair[0], on_address_change, expose_args, &rtnl);
… but here we'll read the rtnl stuff first, and the kmsg stuff second. 

I think the fix is esay: just move the next block that reads fd_kmsg_fifo off the inner socket pair, before this block

2022-12-13 12:06 UTC, poettering commented on src/nspawn/nspawn.c
> +                l = send(fd_inner_socket, &arg_unified_cgroup_hierarchy, sizeof(arg_unified_cgroup_hierarchy), MSG_NOSIGNAL);
hmmm, so here we send something on the inner socket, but from the outer process?

2022-12-13 12:06 UTC, poettering commented on src/nspawn/nspawn.c
> +                l = recv(fd_inner_socket_pair[0], &arg_unified_cgroup_hierarchy, sizeof(arg_unified_cgroup_hierarchy), 0);
afaics you can simply change from the inner to the outer fd, to make this systematic. The ordering should already be OK.

2022-12-13 15:00 UTC, brauner commented on src/nspawn/nspawn.c
> +                r = expose_port_watch_rtnl(event, fd_inner_socket_pair[0], on_address_change, expose_args, &rtnl);
done

2022-12-14 17:36 UTC, poettering commented
excellent, thanks!

2022-12-14 17:36 UTC, merged