network: Fix set bond device MAC address failed
systemd/systemd pull request #25628
Opened 2022-12-05 04:12 UTC by zhangjian3032

Issue:
When device is in bond mode and booting up, there is a probability of set bond MAC address failed due to `Device or resource busy` error.

In systemd-networkd, set MAC address steps are:
1. Try to set MAC address to device.
2. If failed with `Device or resource busy`, then `Down` the device.
3. Try to set MAC address to device again.

Currently, Even down the bond device, the bond device is still return `Device or resource busy` error. So the MAC address set failed.

The root cause is that this not enough to down the bond device. We need to down all the slaves of the bond device.
About this descprition, we could use those commands to check:
```shell
We have two network devices: eth0, bond1, eth0 is slave of bond1.
They are all up.

1. Down bond1, and set MAC address to bond1.
~# ip link set bond1 down
~# ip link set bond1 address 00:11:22:33:44:55
ip: SIOCSIFHWADDR: Device or resource busy

2. Down eth0, and set MAC address to bond1.
~# ip link set eth0 down
~# ip link set bond1 address 00:11:22:33:44:55
Set okay.
```

Fix:
When setting the mac for the second time, if the device kind is bond, then we need to down the slave devices of bond device.

Tested: Verified in a long time test( reboot cycles ).

Fixes: #25627

Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>

2022-12-05 05:45 UTC, yuwata requested changes
LGTM, except for one minor point.
Could you add a simple test to test/test-network/systemd-networkd-tests.py ?

2022-12-05 05:45 UTC, yuwata commented on src/network/networkd-setlink.c
> +                        if (link->kind && streq_ptr(link->kind, "bond")) {
`streq_ptr()` gracefully handles the case that `link->kind` is `NULL`. Hence, please simply do like the following:
```c
if (streq_ptr(link->kind, "bond")) {
```

2022-12-06 04:20 UTC, yuwata commented on test/test-network/conf/23-bond199.network
> +MACAddress=00:11:22:33:44:55
Please append the line break at the end.

2022-12-06 04:21 UTC, yuwata commented on test/test-network/systemd-networkd-tests.py
> +        self.assertRegex(output, 'link/ether 00:11:22:33:44:55')
Please use `self.assertIn('...', output)`.

2022-12-06 04:24 UTC, yuwata commented on test/test-network/systemd-networkd-tests.py
> +    def test_bond_mac_config(self):
Please merge this with the above `test_bond_primary_slave()`.

Also, maybe, to reproduce the reported issue, first configure the bond interface without `MACAddress=` setting, then create an drop-in for `23-bond199.network`, e.g. `23-bond199.network.d/mac.conf` with
```
[Link]
MACAddress=00:11:22:33:44:55
```
then call `networkctl reload`, and check if the MAC address is applied.

2022-12-06 07:00 UTC, zhangjian3032 commented on test/test-network/conf/23-bond199.network
> +MACAddress=00:11:22:33:44:55
okay, done

2022-12-06 07:00 UTC, zhangjian3032 commented on test/test-network/systemd-networkd-tests.py
> +        self.assertRegex(output, 'link/ether 00:11:22:33:44:55')
okay, down

2022-12-06 07:01 UTC, zhangjian3032 commented on test/test-network/systemd-networkd-tests.py
> +    def test_bond_mac_config(self):
okay, May just insert into `test_bond_primary_slave ()` is okay, done

2022-12-07 04:29 UTC, zhangjian3032 commented
There is a `TEST-29-PORTABLE' CI error here, and I don't know what the reason is.  Could you kindly have a look. @mrc0mmand

2022-12-07 04:32 UTC, yuwata commented
> There is a `TEST-29-PORTABLE' CI error here, and I don't know what the reason is. Could you kindly have a look. 

The test is now quite unstable. Please ignore.

2022-12-07 04:34 UTC, yuwata commented
CI failures are unrelated. Merging.

2022-12-07 04:34 UTC, merged