WIP: Implement --luks-pbkdf-force-iterations for homed
systemd/systemd pull request #25621
Opened 2022-12-03 15:36 UTC by AidanGG

This PR implements `--luks-pbkdf-force-iterations` for homed. Like the counterpart `--pbkdf-force-iterations` of cryptsetup (https://gitlab.com/cryptsetup/cryptsetup/-/blob/main/src/utils_luks.c#L131-135) it forces a specific number of iterations to use for the PBKDF, to avoid a benchmarking dependency on the current hardware. Like cryptsetup, setting this causes the desired time cost to be ignored.

2022-12-05 21:25 UTC, poettering requested changes
looks pretty good, but see comments.

(but maybe i misunderstood the libcryptsetup API on this, but I think I didn't?)

2022-12-05 21:25 UTC, poettering commented on src/home/homework-luks.c
> +                .iterations = benchmark ? 0 : user_record_luks_pbkdf_force_iterations(hr),
so this doesn't look right, i.e. with this what happens if i set the field to 0? and what if it is set to UINT32_MAX?

I presume a "0" that doesn't mean "benchmark" cannot actually be specified, right?

So here's what I think we should do:

1. Use UINT64_MAX for the indicator for "use benchmarked value", not UINT32_MAX
2. use CLAMP() to clamp all other values to the range 1…UINT32_MAX (which appears to be the valid range for libcryptsetup)

2022-12-05 21:25 UTC, poettering commented on src/shared/user-record.c
> +        return MIN(h->luks_pbkdf_force_iterations, UINT32_MAX);
as per the comment above I think this should be:

```c
if (h->luks_pbkdf_force_iterations == UINT64_MAX) /* propagate default "benchmark" mode as itself */
        return UINT64_MAX;

return CLAMP(h->luks_pbkdf_force_iterations, 1, UINT32_MAX); /* clamp everything else to actually accepted number of iterations of libcryptsetup */
```

2022-12-06 05:53 UTC, AidanGG commented
I think I have addressed your review.

2022-12-06 13:35 UTC, poettering commented
lgtm. excellent! thanks!

2022-12-06 14:56 UTC, bluca approved these changes

2022-12-06 14:56 UTC, merged