Fix Positivo-vaio Pro PW key toggle touchpad
systemd/systemd pull request #25669
Opened 2022-12-07 18:34 UTC by drosdeck

Resolve #25668

2022-12-07 19:13 UTC, bluca approved these changes

2022-12-08 00:35 UTC, yuwata requested changes

2022-12-08 00:35 UTC, yuwata commented on hwdb.d/60-keyboard.hwdb
> +evdev:name:AT Translated Set 2 keyboard:dmi:bvn*:bvr*:bd*:svnPositivoBahia-VAIO:pnVJ[FP][EW]*:pvr*:*
Now this also accept `FW`  and `PE`. Please add only what you really want.

2022-12-08 12:00 UTC, yuwata approved these changes

2022-12-08 19:51 UTC, merged