Add JSON and table output to systemd-analyze's plot
systemd/systemd pull request #25790
Opened 2022-12-20 09:31 UTC by joshua-zivkovic

We wanted to have programmatic access to the data presented in systemd-analyze's plot's SVG output, so this PR adds the ability to output `plot` data as JSON or table format. This is controlled by using the `--JSON=` and `--table` command line options. 

Note:
The `show_table` function in `src/analyze/analyze-plot.c` appears a few times throughout the project so it might be worth re-factoring it into `shared/`.

2023-01-06 14:12 UTC, poettering requested changes
looks pretty good. some minor comments

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +#include "format-table.h"
please keep includes sorted

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +static int produce_plot_as_svg(UnitTimes* times, HostInfo* host, BootTimes* boot, char* pretty_times) {
these parameters should get some "const"

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +        for (u = times; u->has_data; u++) {
we nowadays prefer if the iterator variable is declared inside the `for()` line, i.e..

```
for (UnitTimes *u = times; …
```

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +static int produce_plot_as_text(UnitTimes* times) {
please constify the argument

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +                                   u->deactivating);
these time values should probably have a cell type of TABLE_TIMESPAN_MSEC to be shown the best way.

we usually line break table_add_many() parameter lists, so that you have:

```c
r = table_add_many(
                table, 
                TABLE_STRING, u->name, 
                TABLE_TIMESPAN_MSEC, u->activated,
                …
```

i.e. each field gets a line of its own, always pairing cell type and value

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +        r = show_table(table, "Units");
propagate the error, i.e.

```c
return show_table(…
```

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +
please keep function calls and their immediate error handling together.

i.e. place empty lines to separate each function call and its auxiliary code. But keep the function call with its immediate auxiliary code together, and error handling belongs to that.

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze-plot.c
> +        }
the two functions called here already log about their errors, which they then return. Thus by logging here too you will generate two error messages for the same error, which we don't like. just propagate `r` via `return r` without logging about it again.

Also see https://systemd.io/CODING_STYLE/#logging

2023-01-06 14:12 UTC, poettering commented on src/analyze/analyze.c
> +                }
please remove {} for these. we only place them if we define a variable here, whose scope we want to limit

2023-01-11 12:15 UTC, poettering commented on src/analyze/analyze.c
> +                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "--table and --json= are mutually exclusive");
these log messages are full sentences btw, hence should really end in a full stop `.`

2023-01-11 12:17 UTC, poettering commented on src/analyze/analyze-plot.c
> +        }
the 2nd and 3rd line of the two if/else branches are the same, hence move them out of the branches, and after the whole statement. if you do each branch is just a single line, thus you can drop the {}, and it becomes a lot shorter

2023-01-11 12:19 UTC, poettering commented on src/analyze/analyze-plot.c
> +                               const char* pretty_times) {
we usually break long function parameter lists like so:

```c
static int produce_plot_as_svg(
        const UnitTimes* …,
        …,
        …) {
```

i.e. already break before the first parameter, and indent to double the usual indentation (i.e. 16 spaces).

some older code doesn't do that yet, but let's do that for all new code.

2023-01-11 12:22 UTC, poettering commented
btw, we generally do line breaks at 109ch, as `.editorconfig`, `.vimrc`, `.dir-locals.el` all encode. you break lines more aggressively than that.

2023-01-11 14:55 UTC, joshua-zivkovic commented
> btw, we generally do line breaks at 109ch, as `.editorconfig`, `.vimrc`, `.dir-locals.el` all encode. you break lines more aggressively than that.

Would you mind giving an example of this? I've been following surrounding code for how to deal with formatting on the most part.

2023-01-13 02:05 UTC, yuwata requested changes
Please add brief tests for the new settings in test/units/testsuite-65.sh.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +static void limit_times_to_boot(const BootTimes* boot, UnitTimes* u) {
We usually use `Type *var` instead of `Type* var`.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +                const UnitTimes* times,
Please drop `const` qualifier for `times`, then you can drop spurious cast in the `for` loop below.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +                const char* pretty_times) {
Please use `Type *var` format.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +        UnitTimes* u;
Please drop it here, and declare in each `for` loop.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +        for (u = (UnitTimes*)times; u->has_data; u++) {
`for (UnitTimes *u = times; u->has_data; u++) {`

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +        for (u = (UnitTimes*)times; u->has_data; u++) {
Also here.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +static int show_table(Table* table, const char* word) {
`Type *var`

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +                        return log_error_errno(r, "Failed to add table row: %m");
Please use `table_log_add_error()`.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze-plot.c
> +                        return log_error_errno(r, "Failed to show table: %m");
Please use `table_log_print_error()`.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze.c
> +
If you dropped empty lines before `break` in the above, then please do not insert another empty line here.

2023-01-13 02:05 UTC, yuwata commented on src/analyze/analyze.c
> +
Also here.

2023-01-13 09:22 UTC, joshua-zivkovic commented on src/analyze/analyze-plot.c
> +        UnitTimes* u;
The last `for` loop relies on using `u` as it was previously changed by the `for` loop before.

2023-01-18 14:31 UTC, poettering commented
lgtm. but the ci didn't like it, but it looks like that is the CI's fault, some network issue.

could you rebase and push again, to trigger this again?

2023-01-18 17:11 UTC, merged