network: fix race between RTM_NEWLINK and NL82011_CMD_NEW_INTERFACE
systemd/systemd pull request #25825
Opened 2022-12-21 15:30 UTC by sipraga

When a new wireless network interface is created by the kernel, it emits both RTM_NEWLINK and NL80211_CMD_NEW_INTERFACE. These events can arrive in either order and networkd must behave correctly in both cases.

The typical case is that RTM_NEWLINK is handled first, in which case networkd creates a Link object and starts tracking it. When the NL80211_CMD_NEW_INTERFACE message is handled, networkd then populates the Link object with relevant wireless properties such as wireless interface type (managed, AP, etc.).

In the event that the order is reversed however, networkd will fail to populate these wireless properties because at the time of processing the nl80211 message, the link is considered unknown. In that case, a debug message is emitted:

  systemd-networkd[467]: nl80211: received new_interface(7) message for link '109' we don't know about, ignoring.

This is problematic because after the subsequent RTM_NEWLINK message, networkd will have an incomplete view of the link. In particular, if a .network configuration matches on some of the missing wireless properties, such as WLANInterfaceType=, then it will never match.

The above race can be reproduced by using the mac80211_hwsim driver. Suppose that there exists a .network configuration:

  [Match]
  WLANInterfaceType=ap
  ...

Now loop the creation/destruction of such an AP interface:

  while true
  do
    iw dev wlan0 interface add uap0 type __ap
    iw dev uap0 del
  done

The above debug message from networkd will then be observed very quickly. And in that event, the .network file will fail to match.

To address the above race, have the nl80211 message handler store the interface index in a set in case a Link object is not found on NL80211_CMD_NEW_INTERFACE. The handler for RTM_NEWLINK can then query this set, and explicitly request the wireless properties from nl80211 upon the creation of the Link object.

2022-12-22 01:26 UTC, yuwata requested changes
Looks almost good to me. Several minor comments.

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-wifi.c
> +                                log_error_errno(r, "Failed to add new wireless interface index to set: %m");
Please downgrade the log level (maybe to warning), and mention that the failure will be ignored (i.e., append `", ignoring"` like the other log messages).

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-wifi.c
> +                        return r;
Please drop this. The debugging log below is useful.

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-wifi.c
> +                        return 0;
Also here. Please drop `return 0;`.

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-link.c
> +                        log_link_warning_errno(link, r, "Failed to get wireless interface: %m");
Please append `", ignoring"`.

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-link.c
> +                set_remove(manager->new_wlan_links, INT_TO_PTR(link->ifindex));
You can optimize the lines with `if (set_remove(manager->new_wlan_links, INT_TO_PTR(link->ifindex))) {`.

2022-12-22 01:26 UTC, yuwata commented on src/network/networkd-manager.h
> +        Set *new_wlan_links;
All set or hashmap named with "links" holds `Link` objects.
So, I'd like to rename `new_wlan_links` -> `new_wlan_ifindexes`, `new_wlan_ifindices`, or something like that to indicate that the set holds indexes.

2022-12-22 13:22 UTC, sipraga commented
Thanks as always for the quick review! I addressed your comments now

2022-12-23 00:11 UTC, yuwata requested changes

2022-12-23 00:11 UTC, yuwata commented on src/network/networkd-link.c
> +                        log_link_warning_errno(link, r, "Failed to get wireless interface: %m, ignoring");
Please make `%m` located at the end:
```c
log_link_warning_errno(link, r, "Failed to get wireless interface, ignoring: %m");
```

2022-12-23 00:11 UTC, yuwata commented on src/network/networkd-wifi.c
> +                                log_warning_errno(r, "Failed to add new wireless interface index to set: %m, ignoring");
Also here: `", ignoring: %m"`

2022-12-23 00:11 UTC, yuwata commented on src/network/networkd-wifi.c
> +                        r = set_ensure_put(&manager->new_wlan_ifindices, NULL, INT_TO_PTR(ifindex));
This updates `r` to be used by the debugging logs below. Please introduce another variable here:
```c
int q = set_ensure_put(...);
if (q < 0)
        log_warning_errno(q, "Failed to ...");
```

2022-12-23 10:23 UTC, sipraga commented
comments addressed :)

2023-01-12 04:28 UTC, yuwata approved these changes
LGTM. Sorry for late review.

2023-01-12 04:28 UTC, merged