logs-show: Stop using source monotonic/realtime timestamp in display
systemd/systemd pull request #25832
Opened 2022-12-22 11:13 UTC by DaanDeMeyer

Not using the same timestamp source for all logs being displayed can result in hard to parse logs because the timestamps of subsequent logs might not be in increasing order. Let's make sure we use the same timestamp source for all the logs we display.

2022-12-23 01:45 UTC, yuwata requested changes
The initial half of `sd_journal_get_realtime_usec()` and `sd_journal_get_monotonic_usec()` are equivalent. How about to introduce `sd_journal_get_dual_timestamp()`?

2022-12-23 01:45 UTC, yuwata commented on src/shared/logs-show.c
>          if (!realtime_good)
You can drop the boolean variable:
```c
if (sd_journal_get_realtime_usec(...) < 0)
        ret_ts->realtime = USEC_INFINITY;
```

2022-12-23 01:45 UTC, yuwata commented on src/shared/logs-show.c
>                  *ret_boot_id = SD_ID128_NULL;
Also here.
```c
if (sd_journal_get_monotonic_usec(...) < 0) {
        ...
}
```

2022-12-23 17:45 UTC, poettering commented
hmm, i don't grok the rationale? so far we showed the most accurate time we have but use the order of reception as ordering. Why isn't that OK? Can you elaborate?

2022-12-23 17:46 UTC, poettering commented
(I mean, people might be confused about that initially, but asynchronous systems are not that hard to grok, so maybe we should just document that?)

we could also add some switch to journalctl to show by reception time, never sender time, but I'd really just make that an option only, that people have to opt in?

or what am I missing?

2023-01-02 11:44 UTC, DaanDeMeyer commented
Hmm, I agree this probably isn't ideal, since logs will still be shown out of order, let's close for now

2023-01-02 11:44 UTC, closed without merging