hwdb: Add Chuwi Hi10X (N4120 version) iio matrix
systemd/systemd pull request #26116
Opened 2023-01-20 07:39 UTC by Waltibaba

There is a later model version of the Chuwi Hi10X that has significantly changed components compared to the existing hwdb one. Differentiator (on Chuwi forums, in thesofproject, etc.) is the N4120 rather than the N4100 processor. The svn and pn seem to be identical, my Chuwi Hi10X matches with the old model except for the changed KIOX000A* iio sensor. With the added ACCEL_MOUNT_MATRIX, my device works on gnome and has the correct (right-up) output in monitor-sensor.

2023-01-20 08:19 UTC, yuwata requested changes

2023-01-20 08:19 UTC, yuwata commented on hwdb.d/60-sensor.hwdb
> +
Please drop space in this empty line.

2023-01-20 10:41 UTC, yuwata approved these changes

2023-01-20 11:06 UTC, bluca commented
spurious space was still there, fixed it

2023-01-20 14:16 UTC, merged

2025-05-25 22:02 UTC, callegar commented
I also have a Hi10X (4120). I think that there are two issues with this:

1. Entries for the tilt sensor are inverted. The tilt sensor reports tilt/face up when it is tilt/face down.

2. There is a problem in how the rotation matrix is managed when you have a `video` entry on the kernel command line to get the linux console rotated, e.g. `video=DSI-1:panel_orientation=right_side_up`. Note that you need this if you want to see boot information correctly, use a console or enter a LUKS password. In this case, in the desktop environment you get the automatic rotation wrong, skewed by the same amount of the rotation you asked to linux itself. Maybe this point is not a problem with the rotation matrix in this PR, but in how the hdwb is managed in general.