localed: check both vc_keymap and X11 before returning early
systemd/systemd pull request #26190
Opened 2023-01-25 08:53 UTC by YHNdnzj

Currently, if vc_keymap is unchanged, localed just returns without modifying anything. However, the X11 part may need updating too. So we should check for both and ensure they are unmodified.

2023-01-25 09:17 UTC, yuwata requested changes
Thank you for working on this, and I am sorry that recently I am working so slowly...

I am slowly working on the issue by a kind of more comprehensive way.

2023-01-25 09:18 UTC, yuwata commented on src/locale/localed.c
> +                x11_modified = r > 0; /* save the result of conversion to emit changed properties later. */
This causes security issue, as `vconsole_convert_to_x11()` updates `Context`. So, with this change, unprivileged users can update `Context` without any authentications.

2023-01-25 11:17 UTC, YHNdnzj commented
@yuwata Should I continue working on this or just leave it to you?

2023-01-25 11:37 UTC, yuwata commented
> @yuwata Should I continue working on this or just leave it to you?

Today, I worked on the issue, and already finished half way. I can easily guess your work and mine mostly duplicated. So, unless you really want to continue this, please wait my PR for a while.

2023-01-25 11:40 UTC, YHNdnzj commented
> Today, I worked on the issue, and already finished half way. I can easily
guess your work and mine mostly duplicated. So, unless you really want to
continue this, please wait my PR for a while.

I guess I’ll wait then :)

2023-01-26 14:36 UTC, yuwata commented
-> #26219.

2023-01-26 14:36 UTC, closed without merging