sd-notify: support overriding NOTIFYACCESS= during runtime
systemd/systemd pull request #26214
Opened 2023-01-26 10:42 UTC by YHNdnzj

Closes #25963

2023-01-26 16:13 UTC, YHNdnzj commented
@mrc0mmand This doesn't seem to be a problem in this PR?

```
[   19.843036] testsuite-64.sh[422]: + udevadm lock --device=/dev/mapper/encbtrfs0 --device=/dev/mapper/encbtrfs1 --device=/dev/mapper/encbtrfs2 --device=/dev/mapper/encbtrfs3 mkfs.btrfs -M -d raid1 -m raid1 -L btrfs_mencdisk -U deadbeef-dead-dead-beef-000000000003 /dev/mapper/encbtrfs0 /dev/mapper/encbtrfs1 /dev/mapper/encbtrfs2 /dev/mapper/encbtrfs3
[   20.042343] testsuite-64.sh[2554]: ERROR: /dev/mapper/encbtrfs1 appears to contain an existing filesystem (jmicron_raid_member)
[   20.042476] testsuite-64.sh[2554]: ERROR: use the -f option to force overwrite of /dev/mapper/encbtrfs1
[   20.042515] testsuite-64.sh[2554]: btrfs-progs v6.1.2
[   20.042561] testsuite-64.sh[2554]: See http://btrfs.wiki.kernel.org for more information.
[   20.044506] testsuite-64.sh[422]: + udevadm wait --settle --timeout=30 /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000003 /dev/disk/by-label/btrfs_mencdisk
[   50.182213] testsuite-64.sh[2555]: Timed out for waiting devices being initialized.
```

2023-02-08 11:39 UTC, YHNdnzj commented
Hmm, there are heap corruptions that I don't really know how to fix :/

2023-03-21 09:52 UTC, mrc0mmand commented
> Hmm, there are heap corruptions that I don't really know how to fix :/

I think you need to update the property definition as well:

```diff
diff --git a/src/core/dbus-service.c b/src/core/dbus-service.c
index b3ed47eb5b..4f5e79c5fb 100644
--- a/src/core/dbus-service.c
+++ b/src/core/dbus-service.c
@@ -223,7 +223,7 @@ const sd_bus_vtable bus_service_vtable[] = {
         SD_BUS_PROPERTY("ExitType", "s", property_get_exit_type, offsetof(Service, exit_type), SD_BUS_VTABLE_PROPERTY_CONST),
         SD_BUS_PROPERTY("Restart", "s", property_get_restart, offsetof(Service, restart), SD_BUS_VTABLE_PROPERTY_CONST),
         SD_BUS_PROPERTY("PIDFile", "s", NULL, offsetof(Service, pid_file), SD_BUS_VTABLE_PROPERTY_CONST),
-        SD_BUS_PROPERTY("NotifyAccess", "s", property_get_notify_access, offsetof(Service, notify_access), SD_BUS_VTABLE_PROPERTY_CONST),
+        SD_BUS_PROPERTY("NotifyAccess", "s", property_get_notify_access, 0, 0),
         SD_BUS_PROPERTY("RestartUSec", "t", bus_property_get_usec, offsetof(Service, restart_usec), SD_BUS_VTABLE_PROPERTY_CONST),
         SD_BUS_PROPERTY("TimeoutStartUSec", "t", bus_property_get_usec, offsetof(Service, timeout_start_usec), SD_BUS_VTABLE_PROPERTY_CONST),
         SD_BUS_PROPERTY("TimeoutStopUSec", "t", bus_property_get_usec, offsetof(Service, timeout_stop_usec), SD_BUS_VTABLE_PROPERTY_CONST),
```

since now you're still passing `s->notify_access` to `property_get_notify_access()` and casting it to `Service*` (or at least that's what I think happens).

2023-03-21 10:03 UTC, YHNdnzj commented
> I think you need to update the property definition as well

Thank you! I'm not yet familiar with the dbus thing

2023-03-21 11:45 UTC, YHNdnzj commented
Sanitizer is happy now :D

2023-03-21 22:03 UTC, poettering requested changes
looks excellent!

2023-03-21 22:03 UTC, poettering commented on src/core/service.h
> +        NotifyAccess notify_access_override;
hmm, the separate boolean seems unnecessary. just make sure notify_access_override defaults to _NOTIFY_ACCESS_INVALID initially, and use that as indicator that no override has been set yet.

2023-03-21 22:03 UTC, poettering commented on src/core/service.h
> +        return s->notify_access_override_enable ? s->notify_access_override : s->notify_access;
with the suggestion above, this would  then become:

```c
return s->notify_access_override < 0 ? s->notify_access : s->notify_access_override;
```

2023-03-21 22:03 UTC, poettering commented on src/core/service.c
> +                }
can you add a comment here explaining briefly that it's not necessary to check here that access is strictly only "closed down" rather than "opened up" because that happens implicitly since we already refused access to this interface if you weren't allowed by the current policy.

(i mean, i for one immediately thought that this was missing here: a check that we only go from ALL to MAIN/EXEC/NONE and from MAIN/EXEC to NONE, but none of the other transitions. But that check isn't really necessary here given that the policy that is changed here locked down the policy change request itself already)

2023-03-22 00:44 UTC, YHNdnzj commented
```
3月 22 08:11:04 H test.sh[351]: + systemd-notify MAINPID=351
3月 22 08:11:05 H systemd[1]: notify.service: Got notification message from PID 351 (MAINPID=351)
3月 22 08:11:05 H systemd[1]: notify.service: New main PID 351 belongs to service, we are happy.
3月 22 08:11:05 H systemd[1]: notify.service: Supervising process 351 which is not our child. We'll most likely not notice when it exits.
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Closing set fd 24
3月 22 08:11:05 H test.sh[351]: + systemd-notify NOTIFYACCESS=main
3月 22 08:11:05 H systemd[1]: notify.service: Got notification message from PID 351 (NOTIFYACCESS=main)
3月 22 08:11:05 H systemd[1]: notify.service: notify_access=all
3月 22 08:11:05 H systemd[1]: notify.service: notify_access_override=main
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Closing set fd 24
3月 22 08:11:05 H test.sh[351]: + systemd-notify '--status=Sending READY=1 in an unpriviledged process'
3月 22 08:11:05 H systemd[1]: notify.service: Got notification message from PID 351 (STATUS=Sending READY=1 in an unpriviledged process)
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/notify_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesC>
3月 22 08:11:05 H systemd[1]: Closing set fd 24
3月 22 08:11:05 H test.sh[355]: + systemd-notify --ready
3月 22 08:11:05 H systemd[1]: notify.service: Got notification message from PID 351 (READY=1)
3月 22 08:11:05 H systemd[1]: notify.service: Changed start -> running
3月 22 08:11:05 H systemd[1]: notify.service: Job 258 notify.service/start finished, result=done
3月 22 08:11:05 H systemd[1]: Started notify.service.
```

This seems wrong...

2023-03-22 00:45 UTC, YHNdnzj commented
Such error appeared only once. Maybe some sort of race condition?

2023-03-22 00:50 UTC, YHNdnzj commented
[problem.journal.gz](https://github.com/systemd/systemd/files/11035227/problem.journal.gz)
[correct.journal.gz](https://github.com/systemd/systemd/files/11035228/correct.journal.gz)

2023-03-22 10:06 UTC, poettering commented
> Seems fixed by adding a sleep before systemd-notify in subshell. Really weird thinking

systemd-notify will generally try to fake the parent process' pid as sender pid. See man page about this:

>  Note that sd_notify() notifications may be attributed to units correctly only if either the sending process is still around at the time PID 1 processes the message, or if the sending process is explicitly runtime-tracked by the service manager. The latter is the case if the service manager originally forked off the process, i.e. on all processes that match NotifyAccess=main or NotifyAccess=exec. Conversely, if an auxiliary process of the unit sends an sd_notify() message and immediately exits, the service manager might not be able to properly attribute the message to the unit, and thus will ignore it, even if NotifyAccess=all is set for it. When --no-block is used, all synchronization for reception of notifications is disabled, and hence the aforementioned race may occur if the invoking process is not the service manager or spawned by the service manager.
>
> Hence, systemd-notify will first attempt to invoke sd_notify() pretending to have the PID of the invoking process. This will only succeed when invoked with sufficient privileges. On failure, it will then fall back to invoking it under its own PID. This behaviour is useful in order that when the tool is invoked from a shell script the shell process — and not the systemd-notify process — appears as sender of the message, which in turn is helpful if the shell process is the main process of a service, due to the limitations of NotifyAccess=all. Use the --pid= switch to tweak this behaviour.

2023-03-22 10:12 UTC, YHNdnzj commented
> systemd-notify will generally try to fake the parent process' pid as sender pid. 

```
test.sh[355]: + systemd-notify --ready                 
systemd[1]: notify.service: Got notification message from PID 351 (READY=1)
```

The PIDs don't match

2023-03-22 10:17 UTC, YHNdnzj commented
Here's another one similar 😐

```
test.sh[351]: + systemd-notify --pid=342
systemd[1]: notify.service: Got notification message from PID 342, but reception only permitted for main PID 351
```

2023-03-22 10:40 UTC, poettering commented
> The problem is that the PID which manager is getting is the one of parent shell...

yeah, as mentioned, if we have the privs to, systemd-notify will make the notification message to come from the ppid of itself, rather than the pid.

> (And I can reproduce this occasionally with or without this patch)

occasionally? it should be quite systematic.

2023-03-22 10:42 UTC, YHNdnzj commented
> yeah, as mentioned, if we have the privs to, systemd-notify will make the notification message to come from the ppid of itself, rather than the pid.

The PPID of systemd-notify should be the one of subshell. But here it is the parent shell, i.e. the one manager forked off.

2023-03-22 11:20 UTC, YHNdnzj commented
Oh, so the actual issue is that the description of `systemd-notify --pid=` is

> Inform the service manager about the main PID of the service.

but it also uses the PID as source PID...

2023-03-22 14:54 UTC, YHNdnzj commented
Finally CIs are passing

2023-03-23 16:11 UTC, merged