conf: replace config_parse_many_nulstr() with config_parse_config_file()
systemd/systemd pull request #26262
Opened 2023-01-31 08:16 UTC by fbuihuu

All daemons use a similar scheme to read their main config files and theirs drop-ins. The main config files are always stored in /etc/systemd directory and it's easy enough to construct the name of the drop-in directories based on the name of the main config file.

Hence the new helper does that internally, which allows to reduce and simplify the args passed previously to config_parse_many_nulstr().

Besides the overall code simplification it results:

  16 files changed, 87 insertions(+), 159 deletions(-)

it allows to identify clearly the locations in the code where configuration files are parsed.

2023-02-01 08:52 UTC, yuwata requested changes
Looks mostly good. Two minor coding style requests.

2023-02-01 08:52 UTC, yuwata commented on src/core/main.c
> +        if (arg_system) {
Unnecessary `{`

2023-02-01 08:52 UTC, yuwata commented on src/shared/conf-parser.c
> +                dropin_dirs[i++] = strjoina(*p, "systemd/", conf_file, ".d");
As already CodeQL warned, please use `strjoin()` in loop.

2023-02-01 13:44 UTC, yuwata approved these changes

2023-03-04 05:25 UTC, yuwata requested changes

2023-03-04 05:25 UTC, yuwata commented on src/shared/conf-parser.c
> +                return log_oom();
Please do not log from the library-like function: `log_oom()` -> `-ENOMEM`

2023-03-04 05:25 UTC, yuwata commented on src/shared/conf-parser.c
> +                        return log_oom();
Also here: `log_oom()` -> `-ENOMEM`

2023-03-13 08:50 UTC, keszybz commented
LGTM, but needs a rebase.

2023-03-13 09:37 UTC, fbuihuu commented
@keszybz, done.

2023-03-13 18:29 UTC, yuwata approved these changes

2023-03-13 18:31 UTC, merged