network/netdev: add support to create HSR interface
systemd/systemd pull request #26316
Opened 2023-02-05 18:43 UTC by ParksProjets

This PR adds the support for creating HSR (High-availability Seamless Redundancy) and Parallel Redundancy Protocol (PRP) netlinks, defined in IEC 62439. Both are provided by the [hsr] kernel module, added in Linux 3.13. The **iproute2** utility supports HSR since version 3.14.

[hsr]: https://elixir.bootlin.com/linux/v6.2-rc6/source/net/hsr

2023-02-06 10:50 UTC, yuwata requested changes
Thank you for your work.

I'd like to merge two settings `SlaveInterface1=` and `SlaveInterface2=` into single `Ports=`, which takes two interface name separated with space: `Ports=eth0 eth1`. WDYT?

Please add a basic test for hsr in test/test-network.

2023-02-06 10:50 UTC, yuwata commented on man/systemd.netdev.xml
> +        <term><varname>SlaveInterface1=</varname></term>
Please do not use "slave" for new settings. See #26257.
How about "Port1" or so?

2023-02-06 10:50 UTC, yuwata commented on man/systemd.netdev.xml
> +          interface than the one specified in <varname>SlaveInterface1</varname>.</para>
Please always add `=` at the end of the setting name.

2023-02-06 10:50 UTC, yuwata commented on man/systemd.netdev.xml
> +          <literal>PRP</literal> (Parallel Redundancy Protocol).
We usually use lower characters for string values: `"hsr"` and `"prp"`.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        [NETDEV_HSR_PROTOCOL_PRP] = "PRP",
Please make them in lower.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        Link *link = NULL;
The initialization is not necessary. Please drop it. Also, please move the declaration into the loop.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        for (i = 0; i < _NETDEV_HSR_SLAVE_MAX; i++) {
Please declare the enumerator in the for loop, also make the iterator type unsigned (or enum):
```
for (unsigned i = 0; i < _NETDEV_HSR_SLAVE_MAX; i++) {
```

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +                r = link_get_by_name(hsr->meta.manager, hsr->slave_ifaces[i], &link);
Please do not use `meta` directly, but use through `NETDEV()` macro.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +static int netdev_hsr_get_iface_indexes(Hsr *hsr, int *indexes) {
Please name the argument for storing result as `ret` or `ret_indexes`.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +                        indexes[i] = link->ifindex;
Please check the two indexes are different.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        Hsr *hsr;
Not a matter, but nowadays, we have `ASSERT_PTR()` macro. Hence you can declare the variable with assertions below like the following:
```c
Hsr *hsr = ASSERT_PTR(HSR(ASSERT_PTR(netdev)));
```

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        Hsr *hsr;
Also here. If you'd like.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        for (i = 0; i < _NETDEV_HSR_SLAVE_MAX; i++) {
`for (unsigned i = 0; i < _NETDEV_HSR_SLAVE_MAX; i++) {`

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        if (streq(hsr->slave_ifaces[NETDEV_HSR_SLAVE1], hsr->slave_ifaces[NETDEV_HSR_SLAVE2]))
The check here is OK. But not enough, as the name may be an alternative name of another interface. So, as I commented in the above, you need to check the two ifindexes are different in `netdev_hsr_get_iface_indexes()`.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        return netdev_hsr_get_iface_indexes(hsr, NULL) >= 0;
Not familiar, but is it not necessary to wait for the underlying interfaces are ready? E.g. the interfaces are up, or so?

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.c
> +        for (i = 0; i < _NETDEV_HSR_SLAVE_MAX; i++)
Please inline the iterator.

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.h
> +} HsrSlave;
I do not think this enum is necessary...

2023-02-06 10:50 UTC, yuwata commented on src/network/netdev/hsr.h
> +        char *slave_ifaces[_NETDEV_HSR_SLAVE_MAX];
Please rename `slave_ifaces` -> `ports`, `port_names` or so.

2023-02-06 10:50 UTC, yuwata commented on man/systemd.netdev.xml
> +          <para>Name of the first interface bound to the HSR device.</para>
Please mention the setting is mandatory.

2025-04-09 16:43 UTC, bengal commented
Superseded by #36976

2025-04-09 16:59 UTC, closed without merging