unit: always return 1 in log_kill
systemd/systemd pull request #26332
Opened 2023-02-07 13:22 UTC by msizanoen1

This ensures that cg_kill_items returns the correct value to let the manager know that a process was killed.

Fixes https://github.com/systemd/systemd/pull/26315#issue-1571376032

2023-02-07 13:37 UTC, msizanoen1 commented
Confirmed that the bug is completely gone after the patch.

2023-02-07 14:00 UTC, Werkov requested changes
Good catch.

I think `cg_kill_log_func_t` could now be made into `void (*cg_kill_log_func_t)(pid_t pid, int sig, void *userdata)` and it'd also simplify the return value dance in `cg_kill_items`. Perhaps as a followup separate commit to ease backports.

2023-02-07 14:51 UTC, Werkov commented
Ah, right.. So the assignment `ret = ret_log_kill` is semantically wrong since it mixes "killed a process" and "logged a process".

Actually, it makes me wonder, why `(sd-pam`) sticks around. Could it be a race between `fork()` and `prctl(PR_SET_DEATHSIG,...)`? I.e. how would the below patch affect your case:
```diff
diff --git a/src/core/execute.c b/src/core/execute.c
index ac3f096b0da4..d249440c3794 100644
--- a/src/core/execute.c
+++ b/src/core/execute.c
@@ -1258,7 +1258,10 @@ static int setup_pam(

         parent_pid = getpid_cached();

-        r = safe_fork("(sd-pam)", 0, &pam_pid);
+        /* Wait until our main process dies. This will only work if the setresuid() below succeeds,
+         * otherwise the kernel will not allow unprivileged parents kill their privileged children
+         * this way. The control groups kill logic is last resort cleanup. */
+        r = safe_fork("(sd-pam)", FORK_DEATHSIG, &pam_pid);
         if (r < 0)
                 goto fail;
         if (r == 0) {
@@ -1285,12 +1288,6 @@ static int setup_pam(

                 (void) ignore_signals(SIGPIPE);

-                /* Wait until our parent died. This will only work if the above setresuid() succeeds,
-                 * otherwise the kernel will not allow unprivileged parents kill their privileged children
-                 * this way. We rely on the control groups kill logic to do the rest for us. */
-                if (prctl(PR_SET_PDEATHSIG, SIGTERM) < 0)
-                        goto child_finish;
-
                 /* Tell the parent that our setup is done. This is especially important regarding dropping
                  * privileges. Otherwise, unit setup might race against our setresuid(2) call.
                  *

```

2023-02-07 14:55 UTC, msizanoen1 commented
It's working as intended here: `(sd-pam)` is supposed to be terminated by the cgroup kill path. The problem is `cg_kill_items` not returning the proper value which is fixed in this PR.

2023-02-07 14:58 UTC, msizanoen1 commented
It probably won't have any effect - there will still be a delay between `systemd --user` exiting and `(sd-pam)` terminating, and since `user@.service` `KillMode` is set to `mixed` it would get killed instantly by the cgroups kill path.

2023-02-07 15:45 UTC, Werkov commented
I see. _Any detached process (from main) whose `comm` hides under `(` prefix may evade_ systemd's tracking and prevent soon-ish restart of given unit, correct?

The patch is a good fix, I'd suggest adding this reason behind the irregularity into `log_kill` to prevent future confusion.

2023-02-07 15:58 UTC, Werkov commented
(I've set the label after release as this is not so serious to add it after -rc2.)

2023-02-08 09:54 UTC, yuwata commented
LGTM.

This sounds a pure bug fix for me, and there is nothing we need to postpone it. Even if this is postponed, I guess this will be soon backported to stable repositories... So, I'd like to merge this before v253-final.

@poettering @bluca @keszybz WSYT?

2023-02-08 09:58 UTC, Werkov approved these changes

2023-02-08 10:33 UTC, merged