gpt-auto: check if LoaderDevicePartUUID is XBOOTLDR
systemd/systemd pull request #26396
Opened 2023-02-10 19:37 UTC by YHNdnzj

2023-02-22 02:55 UTC, yuwata requested changes

2023-02-22 02:55 UTC, yuwata commented on src/gpt-auto-generator/gpt-auto-generator.c
> +                                log_error_errno(r, "Failed to read loader partition UUID: %m");
The error will be ignored now. So, please downgrade the log level. I think, `log_debug_errno()` is sufficient. At most, `log_info_errno()`.
Then, append ", ignoring" in the message.

2023-03-05 02:40 UTC, yuwata approved these changes
LGTM. But I'd like to wait for @poettering's final review.

2023-03-10 11:32 UTC, YHNdnzj commented
Just rebased to resolve merge conflicts. No functional change :)

2023-06-14 13:54 UTC, poettering requested changes
so this looks great, some comments though.

2023-06-14 13:54 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +            esp_is_valid(m->partitions + PARTITION_ESP,
indentation to 4 space is a bit weird, usually we'd indent this deeper (16spaces?), but doesn't matter

2023-06-14 13:54 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +                        log_debug("EFI loader partition unknown, not mounting ESP.");
please still use log_debug_errno() here, and pass `r` here, even if you don't use `%m` in the format string. the error number is still included in the structure log message as a separate field then, which is a good thing.

i.e. log_xyz_errno() should be used primarily when there's an error code we are acting on, and only secondarily to make %m output something nice

2023-06-14 13:54 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +
could you add a comment somewhere here:

```
/* Let's check if this is actually the ESP that was used for booting. If so, great. If not, let's see if the XBOOTLDR partition we found was used for booting. If so, let's use the ESP from the same disk too. If not, don't mount it */

2023-06-14 13:54 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +                         m->partitions[PARTITION_XBOOTLDR].uuid)) {
this really should check `m->partitions[PARTITION_XBOOTLDR].found` before using `m->partitions[PARTITION_XBOOTLDR].uuid`

2023-06-14 17:20 UTC, YHNdnzj commented
Thank you for the review :)
I’m currently on vacation though. Will update when I get back.

2023-06-19 13:52 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +                }
doesn't matter, but we usually prefer shallow indentation, hence would usually write this as :

```c
if (r == -ENOENT) {
        …
}
if (r < 0) {
        …
}
`` 

but doesn't matter at all

2023-06-19 13:54 UTC, poettering commented on src/gpt-auto-generator/gpt-auto-generator.c
> +                log_debug("LoaderDevicePartUUID points to XBOOTLDR partition, proceeding anyway.");
"anyway" suggests this was a problem of some sort. I think the message generally makes sense for informational reasons, but I'd drop the ", proceeding anyway".

2023-06-19 13:55 UTC, poettering approved these changes
looks good, just some minor things that really don't matter

2023-06-20 09:15 UTC, merged