bootctl: 'graceful' should ignore EFI variable failures
systemd/systemd pull request #26774
Opened 2023-03-12 12:40 UTC by kpfleming

Suppress errors when creating/writing EFI variables during 'bootctl update' if '--graceful' mode is active (as the documentation indicates).

Closes #26773.

2023-03-12 12:52 UTC, bluca commented
It should also return success, not just suppress the log message

2023-03-12 12:54 UTC, kpfleming commented
First push was broken as it would have also suppressed errors during `install`... Second push has the correct code.

2023-03-12 12:58 UTC, kpfleming commented
@bluca Hmm... I copied the pattern from `acquire_esp` in bootctl.c, which is assuming that `log_full_errno` will return 0. That may not be a safe assumption, in which case `acquire_esp` is also broken.

2023-03-12 13:14 UTC, bluca commented
Can you check what the exit code is in that case?

2023-03-12 13:59 UTC, kpfleming commented
Tested and you were correct; status code was non-zero even in graceful mode. This last push corrects that.

2023-03-13 10:30 UTC, poettering commented
i don't get this. what is an uefi system without efi vars? the concept is not precisely optional in the uefi spec, is it?

sounds fine to me to handle gracefully if we can't write efi vars, but a system where efi vars don't exist at all seems super broken. it's also fine if persistent efi vars don't exist, but ultimately any firmware can implement them just in RAM if they want, and if they don't that's super broken.

This sounds like something to fix in your firmware? what am i missing? why make this frankenuefi our problem?

2023-03-13 11:57 UTC, bluca commented
Firmwares do wonky things in the real world - `--graceful` is documented as ignoring failures due to variables, but that's plainly not happening, so I think it makes sense to fix it to make it do what it says on the tin

2023-03-13 11:59 UTC, bluca commented
Or alternatively think about the use case where there's no variables because it's running in a container to update an image, or such cases

2023-03-13 12:00 UTC, poettering commented
> Firmwares do wonky things in the real world - `--graceful` is documented as ignoring failures due to variables, but that's plainly not happening, so I think it makes sense to fix it to make it do what it says on the tin

It is not? what precisely *is* happening? the report never mention what precisely is happening.

And the docs clearly say "…when EFI variables cannot be written…". i.e. nothing about read, only about write.

2023-03-13 12:01 UTC, poettering commented
> Or alternatively think about the use case where there's no variables because it's running in a container to update an image, or such cases

Well, detect the container case automatically already.

2023-03-13 12:13 UTC, bluca commented
> > Firmwares do wonky things in the real world - `--graceful` is documented as ignoring failures due to variables, but that's plainly not happening, so I think it makes sense to fix it to make it do what it says on the tin
> 
> It is not? what precisely _is_ happening? the report never mention what precisely is happening.

The error report has the example:

```
root@core23-a:~# bootctl update --graceful
Skipping "/efi/EFI/systemd/systemd-bootaa64.efi", since same boot loader version in place already.
Skipping "/efi/EFI/BOOT/BOOTAA64.EFI", since same boot loader version in place already.
Failed to create EFI Boot variable entry: No such file or directory
```

> And the docs clearly say "…when EFI variables cannot be written…". i.e. nothing about read, only about write.

They are read as part of the process of updating them, given it's the `update` verb

2023-03-21 12:26 UTC, keszybz requested changes
This looks reasonable, but needs a little cleanup.

With the patch, both the caller suppresses the return value (if `graceful`), and the callee also does this internally. If you're changing the callee to suppress errors, then also make it return 0 so that the caller does not need to be changed.

2023-03-21 12:26 UTC, keszybz commented on src/boot/bootctl-install.c
> +                                              "Failed to access EFI variables, skipping.");
": %m"

2023-03-21 12:26 UTC, keszybz commented on src/boot/bootctl-install.c
> +                                                      "Failed to create EFI Boot variable entry, skipping.");
": %m" here too.

2023-03-21 14:50 UTC, kpfleming commented
I can certainly make `install_variables` suppress the errno return instead of making the caller do it; I chose this pattern as it was what was already being done in other places in the code (in particular calls to `acquire_esp`). This allows the caller to decide whether the particular errno returned is covered by `graceful` completely or not.

2023-03-21 15:10 UTC, kpfleming commented on src/boot/bootctl-install.c
> +                                              "Failed to access EFI variables, skipping.");
Done.

2023-03-21 15:10 UTC, kpfleming commented on src/boot/bootctl-install.c
> +                                                      "Failed to create EFI Boot variable entry, skipping.");
Done.

2023-03-21 15:51 UTC, keszybz commented
> I can certainly make `install_variables` suppress the errno return instead of making the caller do it; I chose this pattern as it was what was already being done in other places in the code (in particular calls to `acquire_esp`). This allows the caller to decide whether the particular errno returned is covered by `graceful` completely or not.

Right now we can have a situation where `install_variables` calls `log_error`, but the caller than then suppresses the error. This is too complicated and error-prone. Please rework `install_variables` to return 0 if `graceful` and the error should be suppressed.

2023-03-21 16:14 UTC, kpfleming commented
Done. I also ensured that the logged messages are the same in both graceful and non-graceful modes when the EFI variables cannot be accessed at all.

2023-03-21 17:17 UTC, keszybz commented on src/boot/bootctl-install.c
>                                         "Failed to determine current boot order: %m");
OK. This should work, but now both the graceful and non-graceful path are almost the same. Please reformat:
```C
int level = graceful ? arg_quiet ? LOG_DEBUG : LOG_INFO : LOG_ERR;
const char *skip = graceful ? ", skipping" : "";
log_full_errno(level, r,
                          r == -ENOENT ? … : …,
                          skip);
return graceful ? 0 : r;
```

And similarly for the case below.

2023-03-21 17:46 UTC, kpfleming commented on src/boot/bootctl-install.c
>                                         "Failed to determine current boot order: %m");
Thanks for the gentle nudge... my C skills are rusty and I hadn't considered refactoring the code that way. It's much clearer now.

2023-03-22 08:16 UTC, merged