Implement --help/--version in all udev builtins
systemd/systemd pull request #26785
Opened 2023-03-13 17:32 UTC by keszybz

2023-03-13 18:22 UTC, yuwata requested changes

2023-03-13 18:22 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +        } else  {
Doubled space after `else`.

2023-03-13 18:22 UTC, yuwata commented on man/udevadm.xml
>          </varlistentry>
commit message: `iqnstalled` -> `installed`

2023-03-13 18:22 UTC, yuwata commented on src/udev/dmi_memory_id/dmi_memory_id.c
> +               "  -h -help            Show this help text\n"
Alignment.

2023-03-14 12:09 UTC, yuwata requested changes

2023-03-14 12:09 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +                               "  -h -help       Show this help text\n"
`-help` -> `--help`

2023-03-14 13:28 UTC, yuwata approved these changes
LGTM except for the above `--help` thing.

2023-03-15 08:37 UTC, keszybz commented
Thank you for the review!

2023-03-15 08:50 UTC, poettering commented on src/udev/v4l_id/v4l_id.c
> +        fd = open(arg_device, O_RDONLY);
O_CLOEXEC

2023-03-15 08:53 UTC, poettering commented on src/udev/ata_id/ata_id.c
> +        for (int n = 0; n < 512; n++)
size_t would be a less surprising choice

2023-03-15 08:56 UTC, poettering commented on src/udev/ata_id/ata_id.c
>          p[offset_words] = le16toh (p[offset_words]);
might as well drop the extra space after the le16toh

2023-03-15 08:56 UTC, poettering commented on src/udev/ata_id/ata_id.c
> +        uint16_t *p = (uint16_t*) identify;
this is an alignment issue btw. identitfy is byte-aligned, and we read it as 16bit value.

maybe rework this to use unaligned_read_u16()?

2023-03-16 15:51 UTC, keszybz commented on src/udev/ata_id/ata_id.c
> +        uint16_t *p = (uint16_t*) identify;
`identify` is actually aligned as `uint16_t`, so this was fine. But I converted it anyway, because the code seems a bit clearer this way and we don't need to care about alignment.

2023-03-16 15:51 UTC, keszybz commented
Please check the last two patches.

2023-03-24 07:01 UTC, keszybz commented
This has been ready for a week. It just needs a quick review of the last two patches.

2023-03-24 07:52 UTC, yuwata approved these changes

2023-03-24 12:38 UTC, keszybz commented
The CI finished a while ago… I assume I can merge this.

2023-03-24 12:38 UTC, merged