hwdb: Fixed Incorrect touchpad dimensions on Thinkpad L14 Gen1 (#22793)
systemd/systemd pull request #26905
Opened 2023-03-20 18:07 UTC by taniishkaaa

FIxes #22793

2023-03-21 00:30 UTC, yuwata requested changes
Please add the rule to 60-evdev.hwdb, instead of 70-touchpad.hwdb.

2023-03-21 00:34 UTC, yuwata commented
Also, please drop the commits in your previous PR and rebase the branch to the current git HEAD, that can be done something like the following:
```sh
$ git remote add upstream https://github.com/systemd/systemd
$ git fetch upstream main
$ git rebase upstream/main
```

2023-03-21 13:11 UTC, poettering commented
yeah, please move the dimension data over, but leave the ID_INPUT_TOUCHPAD_INTEGRATION= field in the current hwdb file

2023-03-21 23:58 UTC, yuwata requested changes

2023-03-21 23:58 UTC, yuwata commented on hwdb.d/70-touchpad.hwdb
> +
All lines are commented out... Please drop the change in 70-touchpad.hwdb.

2023-03-22 16:26 UTC, taniishkaaa commented
Closing this PR in favor of #26937

2023-03-22 16:26 UTC, closed without merging