chase-symlinks: Add chase_symlinks_and_pin() + at() variant
systemd/systemd pull request #26961
Opened 2023-03-24 11:11 UTC by DaanDeMeyer

Helper to chase a path, pin its parent directory and return the filename of the resolved path in its parent directory.

2023-03-24 11:27 UTC, bluca approved these changes

2023-03-24 11:41 UTC, DaanDeMeyer commented
No point in waiting for integration tests since this isn't actually used anywhere yet.

2023-03-24 13:10 UTC, yuwata requested changes

2023-03-24 13:10 UTC, yuwata commented on src/basic/chase.c
> +        assert(!(chase_flags & (CHASE_NONEXISTENT|CHASE_STEP|CHASE_PARENT|CHASE_EXTRACT_FILENAME)));
In the below, CHASE_PARENT and CHASE_EXTRACT_FILENAME are added. Hence, it is not necessary to set it by the caller, but I do not think it is not necessary to trigger the assertion...
So, please drop the two flags from the assertion.

2023-03-24 13:10 UTC, yuwata commented on src/basic/chase.c
> +        assert(!(chase_flags & (CHASE_NONEXISTENT|CHASE_STEP|CHASE_PARENT|CHASE_EXTRACT_FILENAME)));
Also here.

2023-03-24 13:10 UTC, yuwata commented on src/basic/chase.c
> +int chase_and_pin(const char *path, const char *root, ChaseFlags chase_flags, char **ret_filename) {
Hmm... Maybe, `chase_and_open_parent()` is better??

2023-03-26 18:31 UTC, DaanDeMeyer commented
Addressed comments, changes are trivial, so setting the green label.

2023-03-27 08:41 UTC, merged