udev-rules: check tokens order
systemd/systemd pull request #27076
Opened 2023-03-30 20:09 UTC by ldv-alt

When invoked by udevadm verify, warn about rules that have PROGRAM assignments specified after RESULT checks.

2023-03-31 03:21 UTC, yuwata requested changes
Basically LGTM, but several minor suggestions.

2023-03-31 03:21 UTC, yuwata commented on src/udev/udev-rules.c
> +                        log_line_warning(rule_line, "Unexpected PROGRAM after RESULT, reordering.");
Maybe, better to explain why such line is 'unexpected'.

2023-03-31 03:21 UTC, yuwata commented on src/udev/udev-rules.c
> +        LIST_FOREACH(tokens, t, rule_line->tokens) {
Unnecessary '{}'

2023-03-31 03:21 UTC, yuwata commented on src/udev/udev-rules.c
> +        bool has_result = false;
Nowadays we dropped such rule, but still we usually first declare variables then assertions, like old C.

2023-03-31 13:06 UTC, ldv-alt commented
> Basically LGTM, but several minor suggestions.

For the beginning, I decided to add this check just to the verifier, but maybe it would be OK to extend it to the regular case as well.   What do you think?

2023-04-03 14:37 UTC, ldv-alt commented
@yuwata, do you have any more comments?

2023-04-03 14:44 UTC, yuwata approved these changes

2023-04-03 14:44 UTC, merged