Modified to use STRV_MAKE
systemd/systemd pull request #27108
Opened 2023-04-02 15:24 UTC by taniishkaaa

Follow up for #27100

2023-04-02 15:41 UTC, DaanDeMeyer requested changes

2023-04-02 15:41 UTC, DaanDeMeyer commented on src/test/test-env-util.c
> +        assert_se(!strv_env_name_is_valid(STRV_MAKE("HOME", "USER", "SHELL", "USER", NULL)));
The trailing NULLs can be dropped, they're added automatically by `STRV_MAKE()`

2023-04-02 16:03 UTC, bluca commented
also needs a rebase

2023-04-04 13:11 UTC, taniishkaaa commented
Closing this PR in favor of #27130

2023-04-04 13:11 UTC, closed without merging

2023-04-04 13:12 UTC, bluca commented
> Closing this PR in favor of #27130

For future reference, please don't close PRs and reopen, as the context is lost. It is not needed, you can simply force push to the same branch.