man/systemd-mount: Clearify documentation about --bind-device
systemd/systemd pull request #27150
Opened 2023-04-05 11:19 UTC by ukleinek

The documentation suggests that the mount point (i.e. the directory where the device is mounted) is removed when the device vanishes. However only stopping and removing the automount unit is implemented.

So adapt the documentation to reality.

2023-04-05 14:30 UTC, keszybz requested changes
Hmm, I think the unit won't necessarilly be removed either. E.g. if something references it, it'll stay around. I think it's enough to say that it'll be stopped.

2023-04-05 16:49 UTC, poettering commented
hmm, i would not put the word "unit" into this. Maybe say "mountpoint detached"?

2023-04-07 14:33 UTC, keszybz commented
> hmm, i would not put the word "unit" into this. Maybe say "mountpoint detached"?

 "Mountpoint detached" is not a term we have elsewhere… I think the current text is OK. It makes it pretty clear what will happen.

2023-04-07 14:33 UTC, merged

2023-04-11 15:52 UTC, poettering commented
But now it documents something pretty irrelavant detail and artifact of the actually relevant issue: that the mount goes away. The mount unit is just how one subsystem that listens to mount events exposes it: systemd itself.

It's a lot more interesting to say that the *mount* in the kernel goes away, the fact that systemd also follows suit with its state engine, might be interesting to some, but I am pretty sure it's a lot more interesting for most people to know the mount is removed from the mount table.

2023-04-11 18:49 UTC, keszybz commented
When we say "the mount unit is stopped", I'm certain that people would assume that this means that the mount is removed in the kernel mount table. Of course, it doesn't mean this in all scenarios. In particular, the kernels has many mount tables, or somebody might override how the unit works, or whatever. Current phrasing is very straightforward and doesn't lead to any confusion. It says what systemd does, and since this those are systemd docs, that's good enough.