udev: restore compat symlink for nvme devices
systemd/systemd pull request #27164
Opened 2023-04-06 10:40 UTC by keszybz

In 5118e8e71dda211d20e34ec8d3012186ba27d3d3, the rules were changed to add OPTIONS="string_escape=replace" to creation of
ENV{ID_SERIAL}="$env{ID_MODEL}_$env{ID_SERIAL_SHORT}", so that "/" would be escaped. But this also changes how the symlink looks for devices that do not have "/". This adds back the old symlink for compat, except when a slash is present.

In the meantime, we changed the symlink format to include ${ND_NSID}. Since the symlink with unescaped characters are older than that, for compat we only need to cover the older type. (Symlinks without escaping and with ${ND_NSID} were never created.)  This makes it slightly easier on users: the non-deprecated symlinks are with "_${ND_NSID}", so they are easier to distinguish.

Fixes #27155.

Mostly untested :(  I only have a boring nvme device with no special characters in the id, and the symlinks are unchanged for it by this patch.

2023-04-06 10:41 UTC, keszybz commented
@jlebon Since you seems to have the appropriate hardware, please give this a spin.

2023-04-06 10:42 UTC, poettering commented
is this safe? what if the device is called some other special string, i.e. ".." or "."?

2023-04-06 13:52 UTC, yuwata requested changes
Thanks.

2023-04-06 13:52 UTC, yuwata commented on rules.d/60-persistent-storage.rules.in
> +  ENV{ID_MODEL}!="*/*", ENV{ID_SERIAL}!="*/*", \
ID_SERIAL -> ID_SERIAL_SHORT

2023-04-06 13:52 UTC, yuwata commented on rules.d/60-persistent-storage.rules.in
> +  ENV{ID_MODEL}!="*/*", ENV{ID_SERIAL}!="*/*", \
Also here

2023-04-06 13:52 UTC, yuwata commented on rules.d/60-persistent-storage.rules.in
> +  OPTIONS="string_escape=replace", ENV{ID_SERIAL}="$env{ID_MODEL}_$env{ID_SERIAL_SHORT}", SYMLINK+="disk/by-id/nvme-$env{ID_SERIAL}-part%n"
OPTIONS= should be dropped?

2023-04-06 18:43 UTC, yuwata commented
> is this safe? what if the device is called some other special string, i.e. ".." or "."?

#27169

2023-04-06 20:10 UTC, jlebon commented
> @jlebon Since you seems to have the appropriate hardware, please give this a spin.

Yup, appears to fix the case in https://github.com/systemd/systemd/issues/27155 at least.

BTW, if you want to test this locally, you can use QEMU to emulate an NVMe device with an arbitrary serial, e.g.:

```
$ qemu-img create -f qcow2 storage.qcow2 1G
$ qemu-system-x86_64 -device 'nvme,drive=foobar,serial=    foobar' \
	-drive if=none,id=foobar,file=storage.qcow2,format=qcow2 \
	... # your usual QEMU parameters
```

You can also use [`cosa run`](https://coreos.github.io/coreos-assembler/cosa/run/) which natively supports this too. E.g. you can download the [latest Fedora CoreOS stable QEMU image](https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable&arch=x86_64), and then do:

```
$ cosa run fedora-coreos-37.20230322.3.0-qemu.x86_64.qcow2 --add-disk 1G:channel=nvme,serial='      foobar'
...
[core@cosa-devsh ~]$ ls -la /dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_______foobar
lrwxrwxrwx. 1 root root 13 Apr  6 20:07 /dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_______foobar -> ../../nvme0n1
```

And once you're in there, you can do something like the following to test changes

```
[root@cosa-devsh ~]# rpm-ostree usroverlay
[root@cosa-devsh ~]# vi /usr/lib/udev/rules.d/60-persistent-storage.rules
[root@cosa-devsh ~]# systemctl reload systemd-udevd && udevadm trigger
```

2023-04-07 09:14 UTC, keszybz commented
Thanks. The implementation was crappy, but the idea seems OK. Update to fix the implementation.

2023-04-07 09:15 UTC, keszybz commented
> is this safe? what if the device is called some other special string, i.e. ".." or "."?

Nothing. Both `.` and `..` would just fail.

2023-04-07 09:28 UTC, yuwata requested changes
~~Sorry for late comment, but the reported issue is caused not only by 5118e8e71dda211d20e34ec8d3012186ba27d3d3, but also ea0f4578a7e90f5227817058bfb11bb91dbb1431.
See https://github.com/systemd/systemd/issues/27155#issuecomment-1499450665.~~

~~Hence, the string is already escaped when substituting a sysattr to a property.
You need to escape the escaping to introduce the compat devlinks.~~

2023-04-07 12:39 UTC, mrc0mmand commented
> > @jlebon Since you seems to have the appropriate hardware, please give this a spin.
> 
> Yup, appears to fix the case in #27155 at least.
> 
> BTW, if you want to test this locally, you can use QEMU to emulate an NVMe device with an arbitrary serial, e.g.:
> 
> ```
> $ qemu-img create -f qcow2 storage.qcow2 1G
> $ qemu-system-x86_64 -device 'nvme,drive=foobar,serial=    foobar' \
> 	-drive if=none,id=foobar,file=storage.qcow2,format=qcow2 \
> 	... # your usual QEMU parameters
> ```

This is something we already do in our test suite:

https://github.com/systemd/systemd/blob/ddd43f31e3be45a276ec4191eace333f844b98b8/test/TEST-64-UDEV-STORAGE/test.sh#L187-L206

so adding a test for this shouldn't be too hard.

2023-04-07 18:40 UTC, yuwata commented
@keszybz I picked your patch and added test cases in #27169.

2023-04-11 12:44 UTC, closed without merging