man: add working example to LogControl1 manpage
systemd/systemd pull request #27357
Opened 2023-04-21 23:02 UTC by bluca

Add fully working and documented example that can be copied and pasted

2023-04-22 09:47 UTC, keszybz requested changes
Looks pretty good. Some grammar nitpicks.

Also, please do run `gcc -Wall man/logcontrol-example.c -lsystemd`. You'll be amazed ;)

2023-04-22 09:47 UTC, keszybz commented on man/logcontrol-example.c
> + *   s "debug"
Man pages should fit in 80–85 columns. Please break line break this.

2023-04-22 09:47 UTC, keszybz commented on man/logcontrol-example.c
> +  /* Acquire a connection to the bus, letting the library figure out the details.
The comments are too wide. C.f.
`MANWIDTH=80 build/man/man org.freedesktop.LogControl1 | rg '.{80,}'`

2023-04-22 09:47 UTC, keszybz commented on man/logcontrol-example.c
> +  [LOG_TARGET_CONSOLE] = "console",
Maybe align the strings in the usual fashion?
(Also in the next table.)

2023-04-22 09:47 UTC, keszybz commented on man/logcontrol-example.c
> +  /* The bus should be relinquished once finished. The cleanup attribute
"once finished" implicitly refers to the subject of the sentence, i.e. the bus (effectively: "The bus should be relinquished once it is finished"), which is not what was meant. Maybe "before the program finishes"?

There's an adjective/adverb mismatch. Either "nice" and "clean" or "nicely" and "cleanly". (I think grammar says that an adverb should be used here, but people say "nice and clean" actually.)

2023-04-22 09:47 UTC, keszybz commented on man/logcontrol-example.c
> +   * so that clients know who to call.
whom

2023-04-22 09:47 UTC, keszybz commented on man/org.freedesktop.LogControl1.xml
> +      <para>This creates a simple client on the bus (the user bus, when run as normal user). It implements
This implies the system bus when run as root. But I don't think that's the case. `sd_bus_default()` checks if the slice of the caller is called `user-*.slice`. `user@0.service` runs in `/user.slice/user-0.slice`, so you'd get the user bus too.

The docs for `sd_bus_default()` are pretty bad. I couldn't answer this question based on the man page, so I think we should fix the man page.

2023-04-24 10:24 UTC, keszybz approved these changes
LGTM.

2023-04-24 10:24 UTC, merged

2023-04-24 11:02 UTC, poettering commented on man/logcontrol-example.c
> +                           SD_BUS_ERROR_INVALID_ARGS,
SD_BUS_ERROR_UNKNOWN_PROPERTY

2023-04-24 11:04 UTC, poettering commented on man/logcontrol-example.c
> +  sd_bus_default(&bus);
why not use your check() macro here?

2023-04-24 12:43 UTC, bluca commented on man/logcontrol-example.c
> +                           SD_BUS_ERROR_INVALID_ARGS,
https://github.com/systemd/systemd/pull/27378