pid1: add DelegateSubgroup= option
systemd/systemd pull request #27376
Opened 2023-04-24 10:10 UTC by poettering

This is a minimal implementation of #24961 but without any of the logic that touches threaded cgroups and similar. It also only covers a single subgroup, not a path, to make things a bit let risky with descending a tree owner by a less privileged subsystem.

#24961 development appears stuck, and I am not convinced we really want any management of threaded cgroups, nor do we want creating more than a single level of subcgroups. Hence I reimplemented a minimal, reduced version of the PR which should be mergeable with fewer discussions.

(And of course, if we after all should decide one day that more levels of subcgroups managed by systemd or threaded cgroups are in focus we can still add that easily on top. It's easy to start with the minimal version and later extend.)

2023-04-24 10:11 UTC, poettering commented
This ports over nspawn, the service manager itself and udev to the new setting, which all come with integration tests, hence i didn't any new ones.

2023-04-24 10:11 UTC, poettering commented
/cc @Werkov

2023-04-25 13:51 UTC, keszybz reviewed
Looks nice, but I didn't have time to dig into all the code. Some trivial comments about the docs.

2023-04-25 13:51 UTC, keszybz commented on docs/CGROUP_DELEGATION.md
> +also use `DelegateSubgroup=` to let the service manager play your initial
play → put ?

right-away → right away

2023-04-25 13:51 UTC, keszybz commented on man/systemd.resource-control.xml
> +          ownership is pased to the unit's configured user/group) when a process is started in it.</para>
passed

2023-04-26 10:24 UTC, yuwata requested changes

2023-04-26 10:24 UTC, yuwata commented on src/basic/cgroup-util.c
> +        if (IN_SET(p[0], 0, '_', '.'))
`0` can be dropped, as it is already handled by `isempty()` and `filename_is_valid()`.

2023-04-26 10:24 UTC, yuwata commented on src/basic/cgroup-util.c
> +        if (isempty(p))
Not a matter, but `filename_is_valid()` below also calls `isempty()`, hence can be dropped.

2023-04-26 10:24 UTC, yuwata commented on src/core/cgroup.c
> +                return log_unit_error_errno(u, r, "Failed to generate default cgrou path: %m");
typo: `cgrou` -> `cgroup`

2023-04-26 10:24 UTC, yuwata commented on man/systemd.resource-control.xml
> +          accepted name, since the kernel exposes a native control group attribute file by that name). This
"accepted name" -> "acceptable name" ??

2023-04-26 10:24 UTC, yuwata commented on src/core/execute.c
> +                p = path_join(params->cgroup_path, c->delegate_subgroup);
`c->delegate_subgroup` -> `subgroup` ?

2023-04-26 10:24 UTC, yuwata commented on src/core/load-fragment.c
> +        CGroupContext *c = data;
`ASSERT_PTR(data);`

2023-04-26 10:24 UTC, yuwata commented on src/core/load-fragment.c
> +        return 0;
`return free_and_strdup_warn(...);`

2023-04-27 08:25 UTC, poettering commented on src/core/execute.c
> +                p = path_join(params->cgroup_path, c->delegate_subgroup);
ouch!

2023-04-27 08:40 UTC, poettering commented
Addressed al points, rebased and pushed. PTAL!

2023-04-27 09:32 UTC, yuwata approved these changes
LGTM. Two minor comments.

2023-04-27 09:32 UTC, yuwata commented on src/udev/udevd.c
> +                log_debug("Running in delegate subcgroup '%s'.", cgroup);
`delegate` -> `delegated` ??

2023-04-27 09:32 UTC, yuwata commented on src/core/execute.c
>                                  return log_unit_error_errno(unit, r, "Failed to create control group '%s': %m", subcgroup_path);
Please update the log message.

2023-04-27 10:18 UTC, poettering commented
fixed the two issues and rebase. upgrading green label

2023-04-27 10:24 UTC, bluca commented
Can you add explicit coverage for this, checking that it is set up correctly, in TEST-19-DELEGATE?

2023-04-27 11:29 UTC, poettering commented
See https://github.com/systemd/systemd/pull/27376#issuecomment-1519841364

The codepaths are nicely tested already since nspawn, udev and systemd --user all have test cases already and this PR ports over those three to the new logic.

2023-04-27 11:31 UTC, bluca commented
> See [#27376 (comment)](https://github.com/systemd/systemd/pull/27376#issuecomment-1519841364)
> 
> The codepaths are nicely tested already since nspawn, udev and systemd --user all have test cases already and this PR ports over those three to the new logic.

Sure but only incidentally, and at least nspawn I'm pretty sure it's made to work with or without this change. A short integration test that checks that the setup is exactly what it needs to be seems easy and much nicer to spot regressions. If things start failing roundabout in udev it's not going to be as immediately obvious.

2023-04-27 12:24 UTC, bluca approved these changes

2023-04-27 14:37 UTC, merged