coredumpctl: allow mixing --image/--root with --directory/--files
systemd/systemd pull request #27406
Opened 2023-04-25 15:21 UTC by bluca

When root/image is used and we run 'coredumpctl gdb' or so, we'll look for the core
in the root/image. But if it was generated on the host (eg: nspawn) then we won't find
it. Allow mixing, and fallback to the host if we can't match anything in the root/image.

This allows running 'coredumpctl --image=image.raw --directory=/var/log/journal gdb' and
get gdb to open the core but load files/libs from the image.

Also fix bash completion, which was not working for some options.

2023-04-25 23:30 UTC, yuwata commented on src/coredump/coredumpctl.c
> +                 * for example when accessing a core generated by nspawn, so try again with arg_root. */
Maybe, "try again _without_" ?

2023-04-25 23:30 UTC, yuwata commented on src/coredump/coredumpctl.c
>                          return log_error_errno(r, "Cannot access \"%s%s\": %m", strempty(arg_root), filename);
Maybe better to update log message?

2023-04-26 12:28 UTC, DaanDeMeyer commented on src/coredump/coredumpctl.c
> -
This also drops the check if --root and --image are specified together, which should still be disallowed

2023-04-26 12:31 UTC, bluca commented on src/coredump/coredumpctl.c
> -
fixed

2023-04-26 12:34 UTC, DaanDeMeyer requested changes

2023-04-26 12:34 UTC, DaanDeMeyer commented on src/coredump/coredumpctl.c
> +        if ((!!arg_image + !!arg_root) > 1)
Let's simply this to `arg_root && arg_image`

2023-04-26 12:39 UTC, bluca commented on src/coredump/coredumpctl.c
> +        if ((!!arg_image + !!arg_root) > 1)
fixed

2023-04-26 12:40 UTC, DaanDeMeyer commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
I'm not sure why we need to hide this behind `arg_directory` or `arg_file`? The container's journal could also go directory to the host journal no?

2023-04-26 12:57 UTC, bluca commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
the problem is when the core file is not in the container's journal, because systemd itself crashes and we can't get the journal started

2023-04-26 13:05 UTC, DaanDeMeyer commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
Sure, but I'm thinking about nspawn's `--link-journal=host` switch. If that's used, the coredump journal entry will be located in the host's journal and --directory or --file shouldn't be needed in order to access that journal entry, so I'd drop the check for arg_directory or arg_file here and do it unconditionally.

Instead, we should always search both the container's journal and the host's journal and always try to read the machine ID of the root we're operating on (including the host) and add an extra `_MACHINE_ID=` journal match to make sure we only process coredumps belonging to the root we're operating on.

2023-04-26 13:55 UTC, bluca commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
When image is used, the journal is also checked in the image, so that doesn't work

2023-04-26 13:57 UTC, DaanDeMeyer commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
Why wouldn't it? All the journal entries related to the image will have `_MACHINE_ID=<image-machine-id>` set. So if we read the machine ID from the image, we'll only get journal entries related to the image, regardless of whether they're stored in the image's journal or in the host's journal.

2023-04-26 14:18 UTC, bluca commented on src/coredump/coredumpctl.c
> +                if (r == -ENOENT && (arg_directory || arg_file)) {
I don't know, maybe because it's pid1 that crashes - that's the reason I opened the PR, to be able to run coredumpctl gdb in this case, it didn't work otherwise

2023-05-17 14:31 UTC, closed without merging