generators: try to create /tmp when sandboxing before bailing out
systemd/systemd pull request #27468
Opened 2023-04-30 18:23 UTC by bluca

When spawning generators within a sandbox we want a private /tmp, but it might not exist. Try to create it.
If we can't because the FS is r/o, then gracefully bail out.

Fixes https://github.com/systemd/systemd/issues/27436

2023-04-30 18:56 UTC, AdrianVovk commented
What happens on a system where `tmp.mount` is masked and the intent is that /tmp should be a btrfs subvolume?

My understanding of this patch is that, as-is, it'll create /tmp as a regular directory in the real rootfs. This then prevents systemd-tmpfiles from creating it as a subvolume?

If this is the behavior of this patch, perhaps it's just easier to add /tmp to base-filesystem? Here's the workaround I mentioned in the original issue: https://gitlab.com/carbonOS/build-meta/-/blob/141-image-based/patches/systemd/fixup-tmp.patch

2023-04-30 19:00 UTC, bluca commented
That's weird, why would you want /tmp to be persistent on disk? The point of /tmp is that it's guaranteed to be ephemeral

2023-04-30 19:06 UTC, poettering commented
/tmp/ is persistent on many distros, such as rhel, and i think debian, too

2023-04-30 19:10 UTC, bluca commented
mmh I thought we got rid of that already, evidently not

2023-04-30 19:12 UTC, AdrianVovk commented
I personally agree that /tmp should always be a tmpfs. However, I'm just pointing out the status quo behavior of systemd and how it will change due to this PR. And to be entirely fair, systemd does _not_ guarantee that /tmp is ephemeral:

- [Using /tmp safely](https://systemd.io/TEMPORARY_DIRECTORIES/): (emphasis mine)
> /tmp/ and /var/tmp/ are two world-writable directories Linux systems provide for temporary files. The former is **typically** on tmpfs and thus backed by RAM/swap, and flushed out on each reboot.
- [file-hierarchy(7)](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html): (emphasis mine)
> /tmp/
> The place for small temporary files. This directory is **usually** mounted as a "tmpfs" instance, and should hence not be used for larger files. (Use /var/tmp/ for larger files.) This directory is **usually** flushed at boot-up.

I'm pretty sure some distros still have /tmp persistent by default, but I'm not entirely certain about that

2023-04-30 19:41 UTC, AdrianVovk commented
Just double-checking: with your updated change, there will be generators on some distros that _won't_ have /tmp available to them? In that case [this changelog](https://github.com/systemd/systemd/releases/tag/v253) will be incorrect:

> systemd now executes generator programs in a mount namespace
   "sandbox" with most of the file system read-only and write access
    restricted to the output directories, and with a temporary /tmp/
    mount provided. This provides a safeguard against programming errors
    in the generators, but also fixes here-docs in shells, which
    previously didn't work in early boot when /tmp/ wasn't available
    yet. (This feature has no security implications, because the code is
    still privileged and can trivially exit the sandbox.)

2023-04-30 19:43 UTC, bluca commented
I mean it can't both be never created so that it can go in a disk somewhere and also always created so it's always available, pick one

2023-04-30 20:17 UTC, AdrianVovk commented
Perhaps a one-size-fits-all solution could look something like this:

- Add /tmp to base-filesystem (i.e. my workaround) so that it will exist when systemd runs
  - Alternatively, the original version of this MR, but that seems more complicated than just adding to base-fs
- Add `v+`, `q+`, `Q+` types to systemd-tmpfiles, that act just like normal except they will "promote" a directory to a subvolume as long as it is empty (i.e. by deleting the empty dir and creating the subvolume). If the directory is not empty it acts just as a `d` type would
- Switch the tmpfiles.d config that creates /tmp to use `q+` instead of `q`

2023-04-30 22:29 UTC, YHNdnzj approved these changes

2023-04-30 22:30 UTC, YHNdnzj commented
> by deleting the empty dir and creating the subvolume

Hmm, I think this would suffer from TOCTOU

2023-04-30 23:57 UTC, AdrianVovk commented
> TOCTOU

Do you mean between checking if the dir is empty and deleting it? It's one operation: just call `rmdir` and if it succeeds make the subvolume and if it returns ENOTEMPTY fall back to regular directory behavior

If you mean between deleting the dir and putting the subvolume there, then yeah that's a bit more challenging. However, in theory nothing should be using /tmp at that point anyway so if fails to work for that moment its probably not a huge deal?

2023-05-01 00:01 UTC, AdrianVovk commented
Another possible approach:

```c
int make_tmp = !is_dir("/tmp");
if (make_tmp)
    mkdir("/tmp");
safe_fork(... PRIVATE_TMP ...);
if (make_tmp)
    rm_r("/tmp");
```

2023-05-01 06:15 UTC, yuwata approved these changes

2023-05-01 15:19 UTC, yuwata requested changes

2023-05-01 15:19 UTC, yuwata commented on src/core/manager.c
> +        if (is_dir("/tmp", /* follow= */ true) > 0)
If `FORK_PRIVATE_TMP` is set, `mount_nofollow()` is used to mount tmpfs on /tmp, hence, `/tmp` cannot be a symlink.
So, please set `false` for `follow`.

2023-05-01 18:04 UTC, yuwata approved these changes

2023-05-02 09:12 UTC, poettering commented
how, i guess i should read the back story first. the btrfs subvol thing is something to consider, yes. hmpf

2023-05-02 09:14 UTC, YHNdnzj commented
> 0000 → i.e. no access at all, after all we expect that it's either overmounted later by a proper fs with good access mode, or its access is corrected by tmpfiles.d to open it up.

I think we can go with this and add a new modifier for `tmpfiles` to overwrite inode with such access mode.

2023-05-02 09:29 UTC, poettering commented
> > 0000 → i.e. no access at all, after all we expect that it's either overmounted later by a proper fs with good access mode, or its access is corrected by tmpfiles.d to open it up.
> 
> I think we can go with this, and add a new modifier for `tmpfiles` to allow overwriting (recreating) inodes with such access mode.

chmod() is good enough for that, no ned to recreate.

but the btrfs subvol thing is a real dealbreaker. We want to support that I guess. No we could teach base-filesystem to create /tmp/ as btrfs subvol (with a fallback to an mkdir), but I have the suspicion some people would hate us for that, and prefer to configure that via tmpfiles.d/.

this all sucks a bit.

2023-05-02 09:34 UTC, YHNdnzj commented
> but the btrfs subvol thing is a real dealbreaker

That's the exact reason why we need to recreate it :) I believe we can safely use 0000 as a mark that this can be _reinitialized_.

2023-05-02 10:20 UTC, bluca commented
> > > 0000 → i.e. no access at all, after all we expect that it's either overmounted later by a proper fs with good access mode, or its access is corrected by tmpfiles.d to open it up.
> > 
> > 
> > I think we can go with this, and add a new modifier for `tmpfiles` to allow overwriting (recreating) inodes with such access mode.
> 
> chmod() is good enough for that, no ned to recreate.
> 
> but the btrfs subvol thing is a real dealbreaker. We want to support that I guess. No we could teach base-filesystem to create /tmp/ as btrfs subvol (with a fallback to an mkdir), but I have the suspicion some people would hate us for that, and prefer to configure that via tmpfiles.d/.
> 
> this all sucks a bit.

Can we fix the regression first please? This affects a released version, so the fix needs to be backportable. After that, we can wonder about more complicated changes.

2023-05-02 10:28 UTC, merged

2023-05-04 14:36 UTC, keszybz commented
I think the patch as merged is fine. If people don't create `/tmp` on the file system, it's their problem. Such a setup will be broken in various ways, and I don't think we need to try to fix it.

2023-05-04 15:28 UTC, AdrianVovk commented
> I think the patch as merged is fine. If people don't create `/tmp` on the file system, it's their problem. Such a setup will be broken in various ways, and I don't think we need to try to fix it.

How am I then, as a user of `root=tmpfs` (a systemd feature) in an attempt to implement an A/B partitioning schema (following the systemd model), supposed to deal with it?

How will it be broken in various ways?

2023-05-11 19:33 UTC, keszybz commented
> How am I then, as a user of `root=tmpfs` (a systemd feature) in an attempt to implement an A/B partitioning schema (following the systemd model), supposed to deal with it?

In this case, systemd should create the directory in the tmpfs. This patch makes the generator invocations work correctly when the directory doesn't exist, which will happen in other cases.