journal: clean up the FSS related code a bit & add a couple of tests
systemd/systemd pull request #27526
Opened 2023-05-04 13:18 UTC by mrc0mmand

2023-05-04 13:27 UTC, bluca approved these changes

2023-05-04 13:27 UTC, bluca commented on src/libsystemd/sd-journal/journal-authenticate.c
> +        } else
if below can be merged in this line too

2023-05-04 13:29 UTC, mrc0mmand commented on src/libsystemd/sd-journal/journal-authenticate.c
> +        } else
Indeed!

2023-05-06 16:08 UTC, yuwata requested changes

2023-05-06 16:08 UTC, yuwata commented on src/libsystemd/sd-journal/journal-authenticate.c
>                          return -EBADMSG;
indentation.

2023-05-06 16:08 UTC, yuwata commented on src/libsystemd/sd-journal/journal-authenticate.c
> +        if (!p)
How about `if (!p || p == MAP_FAILED)` ?

2023-07-13 13:37 UTC, mrc0mmand commented on src/libsystemd/sd-journal/journal-authenticate.c
> +        if (!p)
Nice!

2023-07-14 00:58 UTC, yuwata approved these changes

2023-07-14 04:30 UTC, merged