Various mkosi improvements and related systemd fixes
systemd/systemd pull request #27571
Opened 2023-05-08 14:14 UTC by DaanDeMeyer

2023-05-08 15:15 UTC, yuwata requested changes

2023-05-08 15:15 UTC, yuwata commented on src/shared/mkfs-util.c
> +                        stdio_fds[1] = -EBADF;
OOM is ignored. Is it intended?

2023-05-08 15:15 UTC, yuwata commented on src/core/main.c
> +                                          empty_to_root(switch_root_dir), switch_root_init);
`switch_root_dir` may not end with `"/"`.
`"%s%s"` -> `"%s/%s"`
`empty_to_root(switch_root_dir)` -> `strempty(switch_root_dir)` ??

2023-05-08 15:15 UTC, yuwata commented on src/core/main.c
> +                                          empty_to_root(switch_root_dir), SYSTEMD_BINARY_PATH);
Also here. And spurious indentation.

2023-05-08 15:15 UTC, yuwata commented on src/core/main.c
> +                        return log_error_errno(r, "Failed to chase %s/sbin/init", empty_to_root(switch_root_dir));
`empty_to_root()` -> `strempty()`

2023-05-12 19:27 UTC, bluca commented
mkosi failures seem related

2023-05-13 09:22 UTC, bluca approved these changes
Commit message says erofs but it's actually squashfs

2023-05-13 09:24 UTC, DaanDeMeyer commented
It's erofs locally, squashfs in CI

2023-05-13 10:09 UTC, merged