loginctl: list-{users,sessions}: add a column for showing state
systemd/systemd pull request #27606
Opened 2023-05-11 05:56 UTC by YHNdnzj

2023-05-15 01:22 UTC, yuwata requested changes
LGTM.

Could you add a brief test for the fields in TEST-73-LOCALE ?

2023-05-15 08:12 UTC, dtardon commented
@YHNdnzj I wonder: is the state really so useful to users that it needs to be listed? It seems nobody has ever asked for this...

2023-05-15 08:19 UTC, YHNdnzj commented
> @YHNdnzj I wonder: is the state really so useful to users that it needs to be listed? It seems nobody has ever asked for this...

I personally encountered people asking for this :)

2023-05-15 18:48 UTC, yuwata approved these changes

2023-05-16 06:12 UTC, YHNdnzj commented
@bluca I don't think the CI failures are related? `Lint Code Base` reports on code not changed in this PR, and `jammy-ppc64el` fails due to network errors.

2023-05-16 06:27 UTC, mrc0mmand commented
> @bluca I don't think the CI failures are related? `Lint Code Base` reports on code not changed in this PR, and `jammy-ppc64el` fails due to network errors.

Don't worry about the shellcheck stuff - a new version of shellcheck got out with additional checks. I'll fix it when I do another round of shell-related fixes.

2023-05-16 09:38 UTC, poettering commented on src/login/loginctl.c
> +                                               user, bus_error_message(&error, r));
this is race: by the time you query the state here the user might aleady have logged out fully. In which case you'll get SD_BUS_ERROR_UNKNOWN_OBJECT. I'd add a check for that and simply skip the entry in that case.

2023-05-16 09:39 UTC, poettering commented on src/login/loginctl.c
> -                }
maybe similar to my suggestion in the previous commit, catch SD_BUS_ERROR_UNKNOWN_OBJECT here and skip the entry

2023-05-16 09:39 UTC, poettering commented on src/login/loginctl.c
> +                if (r < 0)
similar

2023-05-16 16:41 UTC, merged