units: Pass SYSTEMD_SULOGIN_FORCE from pid1 to units
systemd/systemd pull request #27614
Opened 2023-05-11 12:15 UTC by DaanDeMeyer

This allows setting it on the kernel cmdline and having it work
automatically without having to write any dropins or such.

2023-05-11 15:35 UTC, bluca commented
@mrc0mmand could you please restart the sanitizer check here

2023-05-11 17:42 UTC, yuwata commented on units/emergency.service.in
> +PassEnvironment=SYSTEMD_SULOGIN_FORCE
Why not to make `systemd-sulogin-shell` also parse kernel command line options?

2023-05-12 13:56 UTC, YHNdnzj approved these changes

2023-05-12 13:56 UTC, YHNdnzj commented on src/sulogin-shell/sulogin-shell.c
> +                        log_warning_errno(r, "Failed to parse SYSTEMD_LOGIN_FORCE from kernel command line: %m");
```suggestion
                        log_debug_errno(r, "Failed to parse SYSTEMD_SULOGIN_FORCE from kernel command line, ignoring: %m");
```

2023-05-12 13:59 UTC, yuwata requested changes
Please use systemd.sulogin-force or systemd.sulogin.force, and update man page.

2023-05-12 15:28 UTC, DaanDeMeyer commented
> Please use systemd.sulogin-force or systemd.sulogin.force, and update man page.

@yuwata Doesn't parsing it as a kernel cmdline argument make it official? I thought we only exposed these things as environment variables to mark them experimental and not officially supported. So that's why I figured we shouldn't parse it as a regular lowercase cmdline argument but only as an environment variable.

2023-05-12 15:33 UTC, yuwata commented
OK, then please add a comment about that in the code.

2023-05-12 15:43 UTC, DaanDeMeyer commented
Added a comment in the code

2023-05-12 16:29 UTC, yuwata commented on src/sulogin-shell/sulogin-shell.c
> +                        log_warning_errno(r, "Failed to parse SYSTEMD_LOGIN_FORCE from kernel command line: %m");
Not addressed yet

2023-05-13 07:16 UTC, DaanDeMeyer commented
Since the last update was a trivial fix, merging immediately

2023-05-13 07:16 UTC, merged

2023-06-08 11:27 UTC, jayaddison commented
@DaanDeMeyer can you share any more details about the problem(s) that this solves, and how it's intended to be used?

(as context: I ran into an unexpected rescue/recovery condition recently where `systemd-sulogin-shell`'s defaults did not provide system access.  I've learned about `SYSTEMD_SULOGIN_FORCE` from #10397 cc @andhe and am wondering whether Debian could/should plan to use this kernel cmdline option in future)

2023-06-08 11:41 UTC, DaanDeMeyer commented
My use case was debugging VMs, where extra kernel cmdline options can be provided via SMBIOS to systemd-stub, so I just use that to pass SYSTEMD_SULOGIN_FORCE whenever a mkosi VM is booted from the systemd repo for development.

2023-06-08 11:52 UTC, jayaddison commented
Thanks, ok - and what was the limitation that you ran into before the modification?

2023-06-08 11:54 UTC, jayaddison commented
(one note from learning a bit about [`systemd-stub`](https://www.freedesktop.org/software/systemd/man/systemd-stub.html) - I guess you might run into problems attempting this on any secure-boot-enabled systems; may or may not be relevant to your use case, but figured I'd mention it - I _think_ Debian would want to support those conditions, so it's relevant to me)

2023-06-08 11:57 UTC, DaanDeMeyer commented
> Thanks, ok - and what was the limitation that you ran into before the modification?

systemd-sulogin-shell used to only read SYSTEMD_SULOGIN_SHELL from the environment. That means if we wanted to enable it, we'd have to modify the initrd to write a dropin file to add SYSTEMD_SULOGIN_SHELL to the environment. The initrd is read-only so we'd have to rebuild the initrd to enable SYSTEMD_SULOGIN_SHELL which is rather annoying when debugging. By reading it at runtime from the kernel cmdline, we don't have to rebuild the initrd to enable it.

> (one note from learning a bit about [systemd-stub](https://www.freedesktop.org/software/systemd/man/systemd-stub.html) - I guess you might run into problems attempting this on any secure-boot-enabled systems; may or may not be relevant to your use case, but figured I'd mention it - I think Debian would want to support those conditions, so it's relevant to me)

Not an issue, SMBIOS is considered trusted by default. This might not be the case in confidential computing VMs but there's an issue somewhere about not using the extra cmdline arguments from SMBIOS if we detect we're in a confidential computing VM.

2023-06-08 12:09 UTC, jayaddison commented
Ok, mostly got it.  In the Debian case, I was trying to figure out what the corrupt-filesystem recovery experience is like when automated recovery fails.  Is the use case that you want a single-user shell to perform that debugging (and if so, was there a reason that running a different `init` process using `init=` at the command-line isn't acceptable?).

(also, a note / correction: in place of `SYSTEMD_SULOGIN_SHELL` you meant `SYSTEMD_SULOGIN_FORCE`, yep?)

2023-06-08 12:11 UTC, DaanDeMeyer commented
> (also, a note / correction: in place of SYSTEMD_SULOGIN_SHELL you meant SYSTEMD_SULOGIN_FORCE, yep?)

Yeah my bad

> Ok, mostly got it. In the Debian case, I was trying to figure out what the corrupt-filesystem recovery experience is like when automated recovery fails. Is the use case that you want a single-user shell to perform that debugging (and if so, was there a reason that running a different init process using init= at the command-line isn't acceptable?).

It's a bit hard to debug systemd boot failures if I replace it with something else ...

2023-06-08 12:40 UTC, jayaddison commented
Makes sense: so, in interpretation: the goal is to continue to run `systemd`-as-init, as standard, but also to be able to open a shell when necessary to inspect the system state (or something like that, my phrasing probably isn't great).

I don't have many thoughts yet about whether this approach is an ideal one or what the alternatives might be, and I can't promise to add any (I seem to be distratcting myself with various threads at the moment), but I'll think about it for a while and try to provide any useful ideas back.  Feel free to ignore me otherwise; I'm trying to understand what components are available for the Debian case now and in future, and their implications, but that may not be hugely relevant to you.

2023-06-14 09:33 UTC, jayaddison commented
@DaanDeMeyer a suggestion: to me, it feels like reading a variable named `SYSTEMD_SULOGIN_FORCE` (all-caps) is inconsistent with the other kernel commandline variables read by systemd.  There are a few reasons I feel that way:

* The other systemd variables on the kernel cmdline are typically named using a `systemd.*` format.
* Something about the use of an all-caps environment variable name feels problematic to me.  I can't articulate why, though - it's a code smell of some kind.
* The references to `sulogin` and `force` seem over-specific to this particular use case.  While working on a [similar task](https://salsa.debian.org/installer-team/user-setup/-/merge_requests/6), I've landed on the terms "fail open" and "fail closed" to describe how the system behaves when a failure occurs.  The fact that fail-open is implemented by using `sulogin --force` feels to me like an implementation detail that could change.

All this said: I'm not particularly familiar with the culture or architecture of `systemd`, so again - please take with some skepticism.  My intent is to help and to make sure that any interfaces being added are supportable longish-term (settings like this have a tendency to exist over a long timescale), but it's possible that I'm adding more noise/distraction than value.

2023-06-16 08:21 UTC, jayaddison commented
@DaanDeMeyer sorry: I've taken another look at this, and now I see that there is an explanatory comment that explains the intentional choice of uppercase/same cmdline flag name as the environment variable.

That invalidates my arguments one and two, and I don't think that the third argument is likely to be a reason to pause on this.

I think some of my concern is that this appears to unlock a way to login to previously-locked-down systems: but I think that's only true in cases where the kernel commandline can be edited, and as I've mentioned here already, setting the `init=` flag is another way that someone could access the system under those circumstances; so I _think_ that this change does not affect boot-time security properties significantly.