unit-file: support UpheldBy= in [Install] settings (adding Upholds= deps from .upholds/)
systemd/systemd pull request #27638
Opened 2023-05-14 10:35 UTC by YHNdnzj

Closes #26896

2023-05-15 01:03 UTC, yuwata requested changes
Could you add several testcases e.g. in test/units/testsuite-23.Upholds.sh.

2023-05-15 01:03 UTC, yuwata commented on man/systemctl.xml
> +            <varname>BindsTo=</varname> and <varname>Upholds=</varname>
Please use the following rule to add comma.
A, B and/or C -> A, B, and/or C
That is, add a comma before and/or.

2023-05-15 01:03 UTC, yuwata commented on man/systemd.unit.xml
> +    <para>Note: <varname>WantedBy=</varname>, <varname>RequiredBy=</varname> and <varname>UpheldBy=</varname>
Also here, and below.

2023-05-15 18:46 UTC, yuwata approved these changes

2023-05-16 09:05 UTC, poettering commented
lgtm

2023-05-16 13:53 UTC, merged

2023-05-16 21:26 UTC, pothos commented
Thank you for working on this! :tada: