core,bus-unit-util: add missing RestartSteps and RestartMaxDelaySec to bus_append_service_property
systemd/systemd pull request #27673
Opened 2023-05-17 15:36 UTC by YHNdnzj

Follow-up for be1adc27fc61ba723bd0392199f7b82ef9f1c970

2023-05-17 15:47 UTC, yuwata requested changes

2023-05-17 15:47 UTC, yuwata commented on src/shared/bus-unit-util.c
> +                              "RestartSecMax",
This does not work, as `bus_append_parse_sec_rename()` only supports the case that the string ends with `Sec`.

Please update the function, or rename the setting e.g. RestartMaxDelaySec= or so.

2023-05-17 15:47 UTC, bluca approved these changes

2023-05-18 05:33 UTC, yuwata approved these changes

2023-05-18 08:54 UTC, merged