sd-boot,sd-stub: print version during boot
systemd/systemd pull request #27704
Opened 2023-05-19 15:23 UTC by keszybz

The kernel, systemd, and many other things print their version during boot. sd-boot and sd-stub are also important, let's make them advertise their presence more.

If EFI_DEBUG, we print something like systemd-boot@0xC0DE. Let's extend this, and either print "systemd-boot@0xC0DE <version>" (if EFI_DEBUG), or just "systemd-boot <version>" (if !EFI_DEBUG). The pattern is retained so that tools/debug-sd-boot.sh can use it.

When updating the docs, I saw that that the text in HACKING.md was out of date. Instead of trying to update the instructions there, make it shorter and refer the reader to tools/debug-sd-boot.sh for details.

2023-05-19 15:53 UTC, medhefgo commented
Nonono. This will make me and many other people angry as you've just now ruined silent boot.

2023-05-22 10:10 UTC, medhefgo commented
The regex in `debug-sd-boot.sh` needs to be updated for this to work.

2023-05-22 10:12 UTC, medhefgo commented
(Also, is the compiler intelligent enough to drop an empty noinline function?)

2023-05-22 11:37 UTC, keszybz commented
> The regex in `debug-sd-boot.sh` needs to be updated for this to work.

It (still) matches:
```console
$ line='systemd-boot@0xC0DE systemd-3343dfsdfsdfd'
$ [[ "${line}" =~ ${target}@(0x[[:xdigit:]]+) ]]
$ echo ${BASH_REMATCH[1]}
0xC0DE
```

> (Also, is the compiler intelligent enough to drop an empty noinline function?)

Yes. We use empty functions all the time.

2023-05-22 12:58 UTC, medhefgo requested changes
> It (still) matches:

Could've sworn I used line anchors when I wrote it…

Since you're touching it: The next paragraph in the hacking section is also out-of-date. Waiting for the debugger is now a parameter to the `DEFINE_EFI_MAIN_FUNCTION` macro.

2023-05-22 12:58 UTC, medhefgo commented on src/boot/efi/util.h
> + * attached. See debug-sd-boot.sh for how this can be done. */
This is a bit off now.

2023-05-23 13:45 UTC, keszybz commented
Updated.

2023-05-23 15:00 UTC, medhefgo approved these changes

2023-05-23 19:34 UTC, merged