journal: avoid infinite recursion when closing bad journal FD
systemd/systemd pull request #28062
Opened 2023-06-16 21:31 UTC by bluca

When trying to log, if we fail we try to close the journal FD. If it is bad, safe_close() will fail and assert, which will try to log, which will fail, which will try to close the journal FD... Infinite recursion looks very pretty live in gdb, but let's avoid that by immediately invalidating the journal FD before closing it.

2023-06-16 21:37 UTC, vcaputo commented
cute

seems obviously right, lgtm

2023-06-17 05:27 UTC, yuwata requested changes

2023-06-17 05:27 UTC, yuwata commented on src/basic/log.c
> +        safe_close(fd);
Please use TAKE_FD():
```c
safe_close(TAKE_FD(journal_fd));
```

2023-06-17 05:28 UTC, yuwata reviewed
Maybe, better to do the same way in other log_close_xyz()?

2023-06-17 20:17 UTC, yuwata approved these changes

2023-06-17 20:17 UTC, yuwata commented on src/basic/log.c
> +        (void) safe_close_above_stdio(TAKE_FD(console_fd));
`safe_close_above_stdio()` does not return error code, but returns value for invalidating fd.
So, please drop the voidification. We voidify function call only when we ignore the error code.

2023-06-17 20:17 UTC, yuwata commented on src/basic/log.c
> +        (void) safe_close(TAKE_FD(kmsg_fd));
Also here, and below.

2023-06-18 11:31 UTC, merged