network: copy netlabel and add a comment
systemd/systemd pull request #28177
Opened 2023-06-27 18:08 UTC by topimiettinen

Netlabel should be copied also in address_equalify().

Add a helpful message for future contributors about tricky memory management issues of Address structure.

2023-06-28 17:10 UTC, topimiettinen commented
mkosi / opensuse fails because of dnf error, doesn't seem related.

2023-06-28 17:25 UTC, yuwata requested changes
Hm... address_equalify() is for making two Address objects pass address_equal(). But address_equal() does not and should not compare the netlabel. Please copy the label in `link_request_address()` instead.

2023-07-02 09:39 UTC, topimiettinen commented
Ok. Should Address::label be copied as well?

2023-07-03 06:04 UTC, yuwata commented
Hm... By reconsidering about the point raised in this PR (and, IIRC, there are some relevant issues), the current logic of requesting address, route, and so on needs to be completely rewritten...

Not only netlabel and label, all properties needs to be copied. Otherwise, if an address with different label or so already exists, the new properties will not be assigned. But, the copying should not be in link_request_address() or friends, but after the address is really configured. That is, after netlink call succeeds, and we received the corresponding netlink notification.

If you'd like, please fix the issue in that way. Or, please wait for a while, and I will try to fix later.

2023-09-01 11:28 UTC, yuwata commented
I guess this can be closed now?

2023-09-01 15:28 UTC, topimiettinen commented
Yes, it's obsolete.

2023-09-01 15:28 UTC, closed without merging