test-fstab-generator: add build directory to PATH
systemd/systemd pull request #28318
Opened 2023-07-09 13:17 UTC by bluca

When running from the build directory systemd-detect-virt might not be installed, so add the build directory to PATH to use the one that was just built

Fixes https://github.com/systemd/systemd/issues/28316

2023-07-09 13:19 UTC, frebib approved these changes

2023-07-09 13:35 UTC, medhefgo commented
Can't help but wonder if `meson devenv` is supposed to be used for this kind of thing?

2023-07-09 13:40 UTC, bluca commented
> Can't help but wonder if `meson devenv` is supposed to be used for this kind of thing?

A question I'll gladly leave for someone else to answer

2023-07-10 10:56 UTC, DaanDeMeyer requested changes
You should add `env : test_env,` to the meson test definition instead.

2023-07-10 11:03 UTC, yuwata approved these changes

2023-07-10 14:29 UTC, merged