network: DHCP4 allow to set InitialCongestionWindow and InitialAdvert…
systemd/systemd pull request #28335
Opened 2023-07-10 10:47 UTC by ssahani

…isedReceiveWindow

2023-07-10 12:00 UTC, yuwata requested changes
Welcome back!

2023-07-10 12:00 UTC, yuwata commented on man/systemd.network.xml
> +          <para>As in the [Route] section</para>
Missing period at the end.

2023-07-10 12:00 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +        if (link->network->dhcp_initcwnd > 0)
It defaults to zero. Hence, not necessary to conditionalize the assignment.

2023-07-10 12:00 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +int config_parse_dhcp_tcp_window(
Please unify existing `config_parse_tcp_window()` and this one like the following:
1. rename `config_parse_tcp_window()` in networkd-route.c to `config_parse_route_tcp_window()`,
2. move this to networkd-route.c, and rename `config_parse_tcp_window()`,
3. then, make `config_parse_route_tcp_window()` internally call `config_parse_tcp_window()`.

2023-07-10 12:00 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +        Network *network = ASSERT_PTR(userdata);
Not necessary, please drop and use `data` instead:
```c
uint32_t *window = ASSERT_PTR(data);
```

2023-07-10 12:00 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +                assert_not_reached();
Then, this block can be simply `*window = k;`

2023-07-10 14:02 UTC, ssahani commented
> Welcome back!

Thanks much ~

2023-07-10 14:04 UTC, ssahani commented on src/network/networkd-dhcp4.c
> +int config_parse_dhcp_tcp_window(
did with other way around since `route_new_static` is called inside it and in dhcp memory is already allocated

2023-07-12 01:33 UTC, yuwata requested changes
Looks mostly good. Several nitpicks.

2023-07-12 01:33 UTC, yuwata commented on src/network/networkd-route.c
> +int config_parse_route_dhcp_tcp_window(
This is generic and not specific for dhcp. So, please rename this to `config_parse_tcp_window()`.

2023-07-12 01:33 UTC, yuwata commented on src/network/networkd-dhcp4.c
> +        route->initrwnd = link->network->dhcp_initrwnd;
Ah, I forgot that we support semi-static route, that is, Gateway=dhcp4.
So, a route may be already configured something like that,
```
[Route]
Destination=...
Gateway=dhcp4
InitialCongestionWindow=10
InitialAdvertisedReceiveWindow=10
```
In such case, `route->initcwnd` and/or `route->initrwnd` are already set.
So, please check they are zero before assigning dhcp_initcwnd or so.
```c
if (route->initcwnd == 0)
        route->network->dhcp_initcwnd;
if (route->initrwnd == 0)
        route->network->dhcp_initrwnd;
```

2023-07-12 03:35 UTC, ssahani commented
Updated thanks for the review .

2023-07-12 03:40 UTC, yuwata approved these changes

2023-07-15 12:39 UTC, keszybz requested changes

2023-07-15 12:39 UTC, keszybz commented on src/network/networkd-network.h
> +        uint32_t dhcp_initrwnd;
It is unexpected that the two names are abbreviated differently, "Advertised" is skipped in the variable name. The variable is used just a few times, and it's better to not abbreviate at all so it's obvious to the reader what this is. Please rename them to `dhcp_initial_congestion_window` and `dhcp_advertised_receive_window`.

2023-07-15 12:39 UTC, keszybz commented on src/network/networkd-route.c
> +        void *d;
Please make this `uint32_t *`.

2023-07-15 13:57 UTC, ssahani commented
Updated thanks for the review!

2023-07-28 08:57 UTC, merged