basic/memfd: untangle historic `sealed` property
systemd/systemd pull request #28423
Opened 2023-07-17 10:23 UTC by dvdhrm

A series of minor changes to `basic/memfd` which untangles the historic `is/set_sealed()` functionality. With the upstream memfd seals, there is no need to always set and require the full set of seals. Instead, ensure those functions work like the historic out-of-tree sealing again.

See each commit-message for details.

2023-07-30 19:49 UTC, bluca requested changes
> This was recently relaxed, since
newer memfds have `F_SEAL_EXEC` set by default. This broke live-updates
of systemd. Similarly, this patch will break live-udpates, by reducing
the set of seals and thus relying on the receive end to only test for
the reduced set. Given that this worked fine for `F_SEAL_EXEC`, it seems
ok to do this now again.

I'm not sure this is actually ok. But why do it in the first place? What's the goal with removing F_SEAL_SEAL?

2023-07-30 19:49 UTC, bluca commented on src/basic/memfd-util.c
> +int memfd_get_seals(int fd, unsigned int *sealsp) {
ret_seals

2023-08-01 07:42 UTC, dvdhrm commented
> > This was recently relaxed, since
> > newer memfds have `F_SEAL_EXEC` set by default. This broke live-updates
> > of systemd. Similarly, this patch will break live-udpates, by reducing
> > the set of seals and thus relying on the receive end to only test for
> > the reduced set. Given that this worked fine for `F_SEAL_EXEC`, it seems
> > ok to do this now again.
> 
> I'm not sure this is actually ok. But why do it in the first place? What's the goal with removing F_SEAL_SEAL?

There is no reason to test the flag or set it, other than keeping historic behavior. Hence, I thought we might just drop it.

I can include it in `memfd_set_sealed()`, if you prefer.

2023-08-01 07:59 UTC, bluca commented
> > > This was recently relaxed, since
> > > newer memfds have `F_SEAL_EXEC` set by default. This broke live-updates
> > > of systemd. Similarly, this patch will break live-udpates, by reducing
> > > the set of seals and thus relying on the receive end to only test for
> > > the reduced set. Given that this worked fine for `F_SEAL_EXEC`, it seems
> > > ok to do this now again.
> > 
> > 
> > I'm not sure this is actually ok. But why do it in the first place? What's the goal with removing F_SEAL_SEAL?
> 
> There is no reason to test the flag or set it, other than keeping historic behavior. Hence, I thought we might just drop it.
> 
> I can include it in `memfd_set_sealed()`, if you prefer.

If updates can break and there's not much to gain to remove it, then yes please let's keep it for now

2023-08-01 08:16 UTC, dvdhrm commented
(v2: use `ret_seals` and retain `F_SEAL_SEAL` for outgoing memfds)

2023-08-01 09:12 UTC, bluca approved these changes

2023-08-01 14:33 UTC, merged