network: radv - Allow to configure the time between retransmitted Neighbor Solicitation
systemd/systemd pull request #28888
Opened 2023-08-18 11:49 UTC by ssahani

```
[IPv6SendRA]
RouterLifetime=30s
Managed=yes
RetransmitNeighborSolicitationSec=5s
```

```
Frame 12: 110 bytes on wire (880 bits), 110 bytes captured (880 bits) on interface veth99, id 0
Ethernet II, Src: 06:c7:41:95:1d:7f (06:c7:41:95:1d:7f), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::4c7:41ff:fe95:1d7f, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0x25b3 [correct]
    [Checksum Status: Good]
    Cur hop limit: 0
    Flags: 0x80, Managed address configuration, Prf (Default Router Preference): Medium
    Router lifetime (s): 1800
    Reachable time (ms): 0
    Retrans timer (ms): 5000 <===================
    ICMPv6 Option (Source link-layer address : 06:c7:41:95:1d:7f)
    ICMPv6 Option (Prefix information : 2002:da8:1::/64)

```

2023-08-18 12:43 UTC, bluca requested changes
Please add some test coverage for this new option

2023-08-21 09:23 UTC, keszybz requested changes

2023-08-21 09:23 UTC, keszybz commented on man/systemd.network.xml
> +        An unsigned integer ranges 0 to 4294967294. Defaults to 0 seconds.</para>
This configures what is sent as part of the advertisement, right? So this description should say that: "Configures the minimum time that the client should use between retransmitted Neighbor Solicitation message that is sent in the Router Advertisement message. Takes a timespan with the default unit of seconds. … "

"An integer in the range 0…4294967294."

(The fact that it's unsigned is only meaningful in C. Also, if the value is >= 0, this doesn't really matter.)

2023-08-21 09:23 UTC, keszybz commented on src/network/networkd-radv.c
> +                           "Failed to parse router Neighbor Solicitation retransmit, ignoring assignment: %s", rvalue);
Just say "Failed to parse RetransmitNeighborSolicitationSec value, …".

2023-08-21 09:23 UTC, keszybz commented on src/network/networkd-radv.c
> +                           "Router Neighbor Solicitation retransmit = must be in the range 0...%"PRIu32"ms, ignoring: %s", UINT32_MAX, rvalue);
Also here, just use the name of the setting, don't invent a textual description.

The value is in seconds, `ms` is a mistake? Also need a space between the number and unit.

2023-08-22 10:16 UTC, ssahani commented
Updated thanks for the review

2023-08-22 10:54 UTC, yuwata requested changes
Looks mostly good. Several minor comments.

2023-08-22 10:54 UTC, yuwata commented on src/network/networkd-radv.c
> +            DIV_ROUND_UP(usec, USEC_PER_SEC) > UINT32_MAX) {
`USEC_PER_SEC` -> `USEC_PER_MSEC`

2023-08-22 10:54 UTC, yuwata commented on src/network/networkd-radv.c
> +                r = sd_radv_set_retransmit(link->radv, link->network->router_retransmit_usec / USEC_PER_MSEC);
Please use `DIV_ROUND_UP()`.

2023-08-22 10:54 UTC, yuwata commented on src/libsystemd-network/radv-internal.h
> +        uint32_t retransmit;
Please add a short comment that this is in milliseconds. or name `retransmit_msec`.
Otherwise we need to refer RFC 4861 to find its unit.

2023-08-22 10:54 UTC, yuwata commented on man/systemd.network.xml
> +        Neighbor Solicitation message that is sent in the Router Advertisement message. Takes a timespan
Configures the retransmit time, used by clients to retransmit Neighbor Solicitation messages on address resolution and the Neighbor Unreachability Detection algorithm.

2023-08-22 10:54 UTC, yuwata commented on man/systemd.network.xml
> +        with the default unit of seconds. An integer in the range 0…4294967294. Defaults to 0 seconds.</para>
with the default unit of seconds, in the range 0…4294967295 msec.

2023-08-22 10:54 UTC, yuwata commented on man/systemd.network.xml
> +        <term><varname>RetransmitNeighborSolicitationSec=</varname></term>
I think `RetransmitSec=` is enough, as RFC 4861 calls this `retransmit time`.

2023-08-22 10:54 UTC, yuwata commented on man/systemd.network.xml
> +        <listitem><para>Takes a timespan. Configures the minimum time that the client should use between retransmitted
Please drop `Takes a timespan.` here, as it is duplicated.

2023-08-22 11:47 UTC, ssahani commented
Thanks for the review updated

2023-08-22 12:37 UTC, yuwata approved these changes

2023-08-23 03:37 UTC, merged