conf: only parse main config file if not a symlink
systemd/systemd pull request #28956
Opened 2023-08-24 14:49 UTC by tiltingpenguin

This PR adds logic to not parse the main configuration file of a service twice if it is symlinked into the drop-in directory (or a drop-in is linked to the main configuration file) and only parse it as a drop-in. It is a small optimization in the case that the main configuration file is used as a drop-in.

This is a rework following the discussion in https://github.com/systemd/systemd/pull/27152

2023-09-07 12:35 UTC, keszybz reviewed
Looks reasonable.

The checking is `O(n²)`, which could be a problem if there are many drop-ins. But in practice `n` should be very small.

2023-09-07 12:35 UTC, keszybz commented on src/shared/conf-parser.c
> +         _cleanup_strv_free_ char **chased_files = NULL;
This line seems to be indented too much by one space.

2023-09-07 12:35 UTC, keszybz commented on src/shared/conf-parser.c
> +                                log_debug("Found symbolic link between config file and drop-ins. Skipping reading of config file");
It's be nice to include the name of the file that we're skipping.
`log_debug("%s: symlink to drop-in, skipping reading.", fn);` or so.

2023-09-07 12:37 UTC, keszybz commented on src/shared/conf-parser.c
> +                                log_debug("Found symbolic link between config file and drop-ins. Skipping reading of config file");
Or better:
`log_debug("%s: symlink to drop-in, will be read later.", fn);`

2023-09-07 12:38 UTC, keszybz commented
@poettering, ptal if this matches your idea.

2023-09-07 12:49 UTC, tiltingpenguin commented on src/shared/conf-parser.c
> +         _cleanup_strv_free_ char **chased_files = NULL;
Thanks for catching that

2023-09-07 12:50 UTC, YHNdnzj requested changes

2023-09-07 12:50 UTC, YHNdnzj commented on src/shared/conf-parser.c
> +                                log_debug("%s: symlink to drop-in, will be read later.", fn);
```suggestion
                                log_debug("%s: symlink to drop-in, will be read later.", *fn);
```

2023-09-07 12:50 UTC, YHNdnzj commented on src/shared/conf-parser.c
> +                        if (strv_find(chased_files, chased)) {
```suggestion
                        if (strv_contains(chased_files, chased)) {
```

2023-09-07 13:56 UTC, YHNdnzj commented
> The checking is `O(n²)`, which could be a problem if there are many drop-ins. But in practice `n` should be very small.

I reckon this can be optimized further if we step away from all those `chase()`s: #29113

2023-09-08 14:25 UTC, keszybz commented
#29113 was merged, let's close this one.

2023-09-08 14:25 UTC, closed without merging

2023-09-11 09:13 UTC, fbuihuu commented
> I reckon this can be optimized further if we step away from all those `chase()`s: #29113

The way you replaced @tiltingpenguin's (first) contribution is not really nice I must say. Your version reused most of his work and in this case suggesting him to compare the stat structures instead of calling `chase()` would have been more appropriate IMHO.