man: add version information for dbus interfaces
systemd/systemd pull request #29150
Opened 2023-09-10 21:44 UTC by abderrahim

These only go back to version 250 which is the first version to provide the export-dbus-interfaces build target.

2023-09-10 22:06 UTC, abderrahim commented
Tests are failing, marking as draft for now.

2023-09-11 07:28 UTC, bluca commented
/packit build

2023-09-11 07:40 UTC, yuwata commented
```
Failed to mount /proc/sys (type n/a) on /proc/sys (MS_BIND ""): Invalid argument
```
Maybe, the recent revert broke mounting sysfs?
Anyway, not related to this PR.

2023-09-11 07:47 UTC, bluca commented
It worked in the revert PR, so seems unlikely

2023-09-11 07:48 UTC, bluca commented
also it's failing before the build step can start, so shouldn't our fault

2023-09-11 07:50 UTC, bluca approved these changes

2023-09-18 13:03 UTC, keszybz requested changes

2023-09-18 13:03 UTC, keszybz commented on man/org.freedesktop.hostname1.xml
> +      <varname>FirmwareVendor</varname> and
Also here, need oxford comma as in the other PR.

2023-09-19 13:57 UTC, bluca approved these changes

2023-09-19 15:04 UTC, merged

2023-12-08 17:54 UTC, Werkov commented
There is the DBus introspection that gives full information about exiting APIs regardless of version. Generally, users should not rely on version numbers guaranteeing anything in API but on API itself (which is so easy with the introspection).
I don't understand the reasoning of the commit d9d2d16aeaf7c18a7b2486cd7c2db484c99050df.
@abderrahim Can you enlighten me what is the purpose? (If anything it could document history of members added _before_ `export-dbus-interfaces` was available.)

2023-12-08 18:20 UTC, Werkov commented
The website may display the properties generated thanks to `export-dbus-interfaces` for the documented version.

2023-12-08 18:25 UTC, bluca commented
That doesn't tell you when it was added, it just spits out what's there currently

2023-12-08 18:37 UTC, Werkov commented
(If some seeks such an information, I'd point them to an [archive](http://web.archive.org/web/20230000000000*/https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.systemd1.html). Actually, I noticed that also the FDO docs website has own version archive).)

But the point is that such information implicitly guides users away from introspection, which is the reliable way to base API decisions on.
The less rolling/longer cycle a distro is, the greater is the discrepancy between version-based and introspection-based information.

2023-12-08 18:56 UTC, bluca commented
To know when an interface was added