config files: update their header to reflect that they can be install…
systemd/systemd pull request #29242
Opened 2023-09-20 10:12 UTC by fbuihuu

…ed in /usr

Follow-up for c76f2fb0e59340222ce21f85c17d384c114db9de.

2023-09-20 10:13 UTC, fbuihuu commented
/Cc @keszybz @YHNdnzj.

2023-09-20 10:14 UTC, fbuihuu commented
@YHNdnzj let me know if you really want that all directory paths end with '/', I'll update the patch.

2023-09-20 10:16 UTC, YHNdnzj commented
> @YHNdnzj let me know if you really want that all directory paths end with '/', I'll update the patch.

Yeah, I want /etc/ and /usr/ to be suffixed too.

2023-09-20 10:23 UTC, fbuihuu commented
> Yeah, I want /etc/ and /usr/ to be suffixed too.

ok

2023-09-20 10:40 UTC, fbuihuu commented
@YHNdnzj done.

I also reverted the changes in udev.conf since udevd currently supports reading its configuration only from /etc/udev/udev.conf.

2023-09-20 10:57 UTC, bluca approved these changes

2023-09-20 13:59 UTC, YHNdnzj commented on src/journal-remote/journal-remote.conf.in
> +# recommended.  Defaults can be restored by simply deleting the main
Duplicate space?

2023-09-20 14:02 UTC, YHNdnzj commented on src/journal-remote/journal-upload.conf.in
> +# /etc/systemd/journal-upload..conf.d/ directory. The latter is generally
```suggestion
# /etc/systemd/journal-upload.conf.d/ directory. The latter is generally
```

2023-09-20 14:02 UTC, YHNdnzj commented on src/journal-remote/journal-upload.conf.in
> +# recommended.  Defaults can be restored by simply deleting the main
Duplicate space also here

2023-09-20 14:02 UTC, YHNdnzj commented on src/timesync/timesyncd.conf.in
> +# recommended.  Defaults can be restored by simply deleting the main
here too

2023-09-20 14:06 UTC, YHNdnzj commented
Also, the paths in `standard-conf.xml` from your previous PR (c76f2fb0e59340222ce21f85c17d384c114db9de) should be suffixed.

2023-09-20 15:44 UTC, fbuihuu commented
@YHNdnzj thanks for the feedback. PR updated.

2023-09-20 15:56 UTC, poettering commented
I am sorry what? config files cannot get installed in /usr/? why would they?

i don#t follow at all anymore. can we please just get some agreement on all of this? 

this seems all so wrong. These files should never be shipped in /usr/. they are decoration, not more, hence have no place anywhere in systems without /etc/

2023-09-20 16:02 UTC, bluca commented
Shipping defaults in /usr makes sense to me, even if they are all commented out and just decoration by default - we do sometimes patch them to change defaults. Better to patch config files than code to change embedded defaults, no?

2023-09-20 16:06 UTC, poettering commented
i am not convinced we should ship tons of NOPs in /usr/. Systems without /etc/ don't need any of this, hence it shouldn't be there.

2023-09-20 16:07 UTC, poettering commented
what's wrong with just shipping them in /etc/ for people who want a fully populated /etc/? people who don't need that shouldn't have that noise.

2023-09-21 09:32 UTC, fbuihuu commented
> what's wrong with just shipping them in /etc/ for people who want a fully populated /etc/?

Shipping main config files in /etc/ is not helping users to switch to drop-ins exclusively. That's a fact, people are much more used to modifying main config files than creating drop-ins. And editing main config files, which already contain all the sections and the setting names/values is much easier.

So if one wants to customize some PID1 settings and only finds  `/etc/systemd/system.conf.d` directory (no main config file), we hope that users will be tempted to put a drop-in in the existing directory. Furthermore the fact that main config files are missing might suggest that they won't be read, hence another reason for users to prefer drop-ins.

2023-09-21 09:40 UTC, fbuihuu commented
> Shipping defaults in /usr makes sense to me, even if they are all commented out and just decoration by default - we do sometimes patch them to change defaults. Better to patch config files than code to change embedded defaults, no?

In our case we wont patch them even if they're located in /usr because any (downstream) customization would be lost as soon as users create a main config file in /etc (regardless of the settings being changed by the user).

And in any cases drop-in is a much better solution for any other packages that would need to override some defaults. The only issue with is that drop-in in /usr can override main config files in /etc. That's the reason we're trying to switch to drop-ins exclusively and for that we need to teach users.

2023-09-21 09:43 UTC, fbuihuu commented
> i am not convinced we should ship tons of NOPs in /usr/. Systems without /etc/ don't need any of this, hence it shouldn't be there.

The only reason to ship them in /usr is that the templates are a convenient way for users to retrieve the setting defaults. Hence if one look at the current config with `systemd-analyze cat-config` he will find them easily.

If for example `systemd-analyze cat-config --defaults` could show them, we wouldn't need to ship the templates at all.

2023-09-21 16:23 UTC, keszybz requested changes

2023-09-21 16:23 UTC, keszybz commented on src/core/user.conf.in
> +# /etc/systemd/user.conf.d/ directory. The latter is generally recommended.
"the" got lost here. In other places too.

2023-09-21 16:23 UTC, keszybz commented on src/core/system.conf.in
> +# all drop-ins located in /etc/.
This chunk belongs in the other commit.

2023-09-21 16:31 UTC, keszybz commented
LGTM, but we should probably first finish the discussion in https://github.com/systemd/systemd/pull/29244.

2023-10-17 16:56 UTC, merged