pid1: refactoring of unit state machine logging and unit timer refactoring
systemd/systemd pull request #29249
Opened 2023-09-20 16:42 UTC by poettering

2023-09-20 16:44 UTC, poettering commented
just some housekeeping. Nothing new. No real code changes.

2023-09-20 18:04 UTC, yuwata requested changes
One question, and several minor requests.

2023-09-20 18:04 UTC, yuwata commented on src/core/service.c
> +                        service_enter_dead(s, SERVICE_FAILURE_RESOURCES, true);
Please add a short comment for the boolean flag.

2023-09-20 18:04 UTC, yuwata commented on src/core/socket.c
> +                return log_unit_error_errno(UNIT(s), errno, "getpeername failed(): %m");
Hm? Inserted `()` at wrong place?

2023-09-20 18:04 UTC, yuwata commented on src/core/socket.c
> -        TAKE_FD(cfd);
The change is not trivial for me. Could you explain about the change?
Maybe, it is better to split out to another commit or mention the change in the commit message.

2023-09-20 18:04 UTC, yuwata commented on src/core/mount.c
> +                }
I'd like to move the error handling just after `exec_command_set()`. Then we can drop multiple `r >= 0` conditions.

2023-09-20 18:04 UTC, yuwata commented on src/core/mount.c
> +                if (r < 0) {
Also here.

2023-09-20 18:04 UTC, yuwata commented on src/core/automount.c
> +                r = -errno;
`RET_NERRNO()` ?

2023-09-20 18:04 UTC, yuwata commented on src/core/timer.c
>  fail:
Not a matter, but the error handling at the beginning of the function can also use `goto fail;`.

2023-09-20 18:04 UTC, yuwata commented on src/core/timer.c
>  fail:
Also here. we can use `goto fail` on vanished case.

2023-09-27 15:39 UTC, poettering commented
Rebased and addressed all raised issues.

2023-09-28 21:17 UTC, bluca approved these changes

2023-09-28 21:18 UTC, merged