sd-journal: cleanups for generic_array_bisect_plus_one()
systemd/systemd pull request #29417
Opened 2023-10-03 01:14 UTC by yuwata

No functional changes, just refactoring.

split-out of #29334.

2023-10-04 06:15 UTC, DaanDeMeyer requested changes
Journal changes are always hard to review, can you add some more comments where I asked? That would help review the changes

2023-10-04 06:15 UTC, DaanDeMeyer commented on src/libsystemd/sd-journal/journal-file.c
> +        if (direction == DIRECTION_DOWN) {
Can you add a comment for each of the scenarios we handle here as well? I'm having a hard time following

2023-10-04 06:15 UTC, DaanDeMeyer commented on src/libsystemd/sd-journal/journal-file.c
>          /* And now, continue seeking until we find an entry that exists in both bisection arrays. */
Not exactly related to your changes, but I'm super confused by this comment, why do we need to find an entry that exists in both bisection arrays? Can you expand this comment a bit so I understand what's going on in this function? That would help me to review the changes.

2023-10-04 08:37 UTC, yuwata commented
@DaanDeMeyer Thank you for the review. I added more comments in the code. Please take a look.

2023-10-04 09:03 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                /* If we are goind downwards, then we need to return the first object that passes the test.
goind => goind

2023-10-04 09:04 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                 * test_object() returns TEST_RIGHT. */
"we need to return the the first object that test_object() returns TEST_RIGHT" Seems there's something missing in this sentence?

2023-10-05 12:52 UTC, DaanDeMeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                                           TEST_RIGHT, and no object exsits that passes the test. */
"... returns TEST_RIGHT for ..."

2023-10-05 12:52 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                                           TEST_RIGHT, and no object exsits that passes the test. */
"exists"

2023-10-05 12:52 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                                         * necessary to bisect the chained arrays. */
"finding" => "looking for"

2023-10-05 12:52 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                /* Otherwise, the 'extra' object is not the one we are finding now. Search in the array. */
"finding" => "looking for"

2023-10-05 12:52 UTC, daandemeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                /* If we are goind upwards, then we need to return the last object that passes the test.
"going"

2023-10-05 12:53 UTC, DaanDeMeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                 * test_object() returns TEST_LEFT. */
"returns TEST_LEFT for"

2023-10-05 12:54 UTC, DaanDeMeyer commented on src/libsystemd/sd-journal/journal-file.c
> +                                   * return TEST_FOUND or TEST_LEFT. There is no object we are finding. */
"The object we are looking for does not exist"

2023-10-06 00:58 UTC, yuwata commented
@DaanDeMeyer Thank you for the review. The suggestions are applied. Upgrading the green label.

2023-10-06 02:04 UTC, merged