networkd: link files belong to udev
systemd/systemd pull request #29500
Opened 2023-10-09 09:32 UTC by iam-TJ

When rules in a link file result in a failure to configure an interface there is no indication in networkd log nor 'networkctl status' as to the cause but udevd log may contain a clue.

Remind the administrator the link is managed by udev to avoid confusion.

Fixes: issue #12308

2023-10-09 14:16 UTC, YHNdnzj requested changes
I don't think this is necessary. `systemd.link(5)` has made this clear enough IMO, and this disturbs the table output quite a bit...

2023-10-09 14:16 UTC, YHNdnzj commented on src/network/networkctl.c
> +                           TABLE_STRING, "(via systemd-udevd)",
This is wrong. You're using the `dot` column of the `Network File` field.

2023-10-09 16:07 UTC, poettering commented
> When rules in a link file result in a failure to configure an interface there is no indication in networkd log nor 'networkctl status' as to the cause but udevd log may contain a clue.

I am pretty sure this is what we should address, i.e. make sure that logs from udev about failure to configure a network interface should show up in "networkctl status".

this might need some minor tweaking of the journal expression "network status" uses to show logs.

do you have a failure of this kind handy? What does the "journalctl -o verbose" output look like for the offending line that is so far missing from "networkctl status" output?

2023-10-11 19:26 UTC, iam-TJ commented
Given the following:
```
$ cat /etc/systemd/network/50-usb-KY688.link
# friendly name for USB Armory link
[Match]
MACAddress=00:e0:4c:68:04:68

[Link]
# USB CDC Ethernet device
# this file needs to be named to ensure loading BEFORE /usr/lib/systemd/network/73-usb-net-by-mac.link
# sets NamePolicy=mac because cannot over-ride that setting later
NamePolicy=
Name=usb3hubKY688
```
When trying to configure a VLAN using these:
```
$ for f in /run/systemd/network/*vlan.manage.99.net{dev,work}; do echo "# $f"; cat $f; done

# /run/systemd/network/vlan.manage.99.netdev
[NetDev]
Name=manage
Kind=vlan

[VLAN]
Id=99

# /run/systemd/network/00-vlan.manage.99.network
[Match]
Name=manage

[Network]
DHCPServer=no
MulticastDNS=yes
LLDP=yes

[Address]
Address=10.254.99.11/24

[DHCPServer]
PoolOffset=0
PoolSize=0
```
`systemd-udevd` reports:
```
Mon 2023-10-09 05:57:23.796318 BST [s=bdced089c3fe4357a2f2bcd7a7d9ba18;i=279a87;b=b5d6babf217449a097ef9cf56fc29dda;m=3d5880afe5;t=607416d08598c;x=6adbf0488401c739]
    SYSLOG_FACILITY=3
    _TRANSPORT=journal
    _SELINUX_CONTEXT=unconfined
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=b5d6babf217449a097ef9cf56fc29dda
    _MACHINE_ID=c486455029ec45a893cb6617385be0b0
    _HOSTNAME=sunny
    _RUNTIME_SCOPE=system
    _UID=0
    _GID=0
    PRIORITY=3
    _CAP_EFFECTIVE=1f7fdffffff
    _SYSTEMD_CGROUP=/system.slice/systemd-udevd.service/udev
    _SYSTEMD_UNIT=systemd-udevd.service
    _SYSTEMD_INVOCATION_ID=c508a07b06af49c18b4dc0d73488f680
    CODE_FILE=src/udev/udev-event.c
    CODE_LINE=925
    CODE_FUNC=rename_netif
    DEVICE=usb3hubKY688
    SYSLOG_IDENTIFIER=(udev-worker)
    _COMM=(udev-worker)
    _EXE=/usr/bin/udevadm
    _CMDLINE="(udev-worker)"
    TID=3389266
    MESSAGE=usb3hubKY688: Failed to rename network interface 41 from 'manage' to 'usb3hubKY688': File exists
    _PID=3389266
    _SOURCE_REALTIME_TIMESTAMP=1696827443796318
Mon 2023-10-09 05:57:23.796331 BST [s=bdced089c3fe4357a2f2bcd7a7d9ba18;i=279a88;b=b5d6babf217449a097ef9cf56fc29dda;m=3d5880b120;t=607416d085ac7;x=93c3468a4d557cb9]
    SYSLOG_FACILITY=3
    _TRANSPORT=journal
    _SELINUX_CONTEXT=unconfined
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=b5d6babf217449a097ef9cf56fc29dda
    _MACHINE_ID=c486455029ec45a893cb6617385be0b0
    _HOSTNAME=sunny
    _RUNTIME_SCOPE=system
    _UID=0
    _GID=0
    PRIORITY=4
    _CAP_EFFECTIVE=1f7fdffffff
    _SYSTEMD_CGROUP=/system.slice/systemd-udevd.service/udev
    _SYSTEMD_UNIT=systemd-udevd.service
    _SYSTEMD_INVOCATION_ID=c508a07b06af49c18b4dc0d73488f680
    DEVICE=usb3hubKY688
    SYSLOG_IDENTIFIER=(udev-worker)
    _COMM=(udev-worker)
    _EXE=/usr/bin/udevadm
    _CMDLINE="(udev-worker)"
    CODE_FILE=src/udev/udevd.c
    CODE_LINE=663
    CODE_FUNC=worker_device_monitor_handler
    MESSAGE=usb3hubKY688: Failed to process device, ignoring: File exists
    TID=3389266
    _PID=3389266
    _SOURCE_REALTIME_TIMESTAMP=1696827443796331
```

2024-09-24 06:05 UTC, closed without merging