rules: add mtd/by-name symlinks
systemd/systemd pull request #29535
Opened 2023-10-11 14:43 UTC by schiffermtq

Add persistent symlinks for MTD devices like SPI-NOR flash, based on the partition names specified on the cmdline, in a Device Tree, or by other MTD partitioning parser drivers. Using the persistent name can be preferable to using the numbered /dev/mtdX device, as the latter can change depending on probe order or when partitioning has changed.

---

Open questions:
- Should we do something about /dev/mtdX-ro (read-only) devices? They don't have any MTD-specific udev attributes like `name`, so they at least don't interfere with the rule this PR adds, but it might be nice to have symlinks with an `-ro` suffix for them if there is a good way to achieve this
- MTD devices currently don't have `ENV{ID_PATH}`, so no `by-path` symlinks are added. Is this something we want?

2023-10-11 15:35 UTC, yuwata requested changes

2023-10-11 15:35 UTC, yuwata commented on rules.d/60-persistent-storage-mtd.rules
> +ENV{UDEV_DISABLE_PERSISTENT_STORAGE_MTD_FLAG}=="1", GOTO="persistent_storage_mtd_end"
I do not think this is necessary, at least now.

2023-10-11 15:35 UTC, yuwata commented on rules.d/60-persistent-storage-mtd.rules
> +SUBSYSTEM=="mtd", KERNEL=="mtd[0-9]*", ATTR{name}=="?*", SYMLINK+="mtd/by-name/$attr{name}"
Not a matter, but this file is for mtd devices, so, I'd like to place the condition `SUBSYSTEM=="mtd"` at the beginning of the file:
```
ACTION=="remove", GOTO="persistent_storage_mtd_end"
SUBSYSTEM!="mtd", GOTO="persistent_storage_mtd_end"
KERNEL!="mtd[0-9]*", GOTO="persistent_storage_mtd_end"

ATTR{name}=="?*", ...
```

2023-10-11 15:35 UTC, yuwata commented
> Open questions:
> 
>     * Should we do something about /dev/mtdX-ro (read-only) devices? They don't have any MTD-specific udev attributes like `name`, so they at least don't interfere with the rule this PR adds, but it might be nice to have symlinks with an `-ro` suffix for them if there is a good way to achieve this
> 
>     * MTD devices currently don't have `ENV{ID_PATH}`, so no `by-path` symlinks are added. Is this something we want?

Let's do that later if someone request that.

2023-10-12 07:14 UTC, schiffermtq commented on rules.d/60-persistent-storage-mtd.rules
> +ENV{UDEV_DISABLE_PERSISTENT_STORAGE_MTD_FLAG}=="1", GOTO="persistent_storage_mtd_end"
Okay, removed.

2023-10-12 07:16 UTC, schiffermtq commented on rules.d/60-persistent-storage-mtd.rules
> +SUBSYSTEM=="mtd", KERNEL=="mtd[0-9]*", ATTR{name}=="?*", SYMLINK+="mtd/by-name/$attr{name}"
Done. I've also added another rule to explicitly skip `mtd*ro` devices, so they don't interfere if they ever get a `name` attr in the future.

2023-10-17 09:43 UTC, keszybz commented
LGTM.

2023-10-17 09:43 UTC, merged