unit: Implement passing empty string to reset unit dependencies
systemd/systemd pull request #29739
Opened 2023-10-27 09:40 UTC by arthurshau

Supports resetting the dependency list for any given UnitDependency type (Before=, After=, etc.) by passing in the empty string. This means that  when an empty string is encountered in a unit file, any dependencies that have been previously encountered for that type will be discarded, and only those encountered after it will be applied.

2023-10-27 10:03 UTC, bluca commented
Yeah this is something we definitely should do. But please add documentation and tests for it (somewhere in `test/test-execute/` for unit test coverage, and `TEST-23-UNIT-FILE` for full integration test).

2023-10-27 10:12 UTC, DaanDeMeyer requested changes

2023-10-27 10:12 UTC, DaanDeMeyer commented on src/core/unit.c
> +                if (!strv_isempty(dep_names)) {
No need for this check, the for loop will be a noop if the strv is empty

2023-10-27 10:12 UTC, DaanDeMeyer commented on src/core/unit.c
> +                                r = unit_add_dependency_by_name(u, i, *n, true, UNIT_DEPENDENCY_FILE);
For boolean arguments, please add an inline comment with the name of the argument

2023-10-27 10:12 UTC, DaanDeMeyer commented on src/core/unit.c
> +        }
No braces for single line blocks

2023-10-31 10:49 UTC, poettering commented
So the idea was to add this via the unit dependency mask stuff, i.e. we need to carefully make sure that the deps created via explicit config are added with `UNIT_DEPENDENCY_FILE` as UnitDependencyMask setting. Then you can use `unit_remove_dependencies(u, UNIT_DEPENDENCY_FILE)` to simply remove all deps add with the same mask.

This would need require thorough testing. And we need to make sure that `UNIT_DEPENDENCY_FILE` is never set for the wrong deps, i.e. exclusively by explicitly configured fields

2023-11-10 01:01 UTC, arthurshau commented
> This would need require thorough testing. And we need to make sure that `UNIT_DEPENDENCY_FILE` is never set for the wrong deps, i.e. exclusively by explicitly configured fields

That makes sense - that means we will have to go through the current code and change some of the deps currently being added as UNIT_DEPENDENCY_FILE to (I'm assuming) UNIT_DEPENDENCY_DEFAULT then? Also, what about implied dependencies? Do we want those to also be removed when `unit_remove_dependencies(u, UNIT_DEPENDENCY_FILE)` is called? Technically those count as being added through explicit config, right?

2023-11-13 12:05 UTC, poettering commented
> That makes sense - that means we will have to go through the current code and change some of the deps currently being added as UNIT_DEPENDENCY_FILE to (I'm assuming) UNIT_DEPENDENCY_DEFAULT then? Also, what about implied dependencies? Do we want those to also be removed when `unit_remove_dependencies(u, UNIT_DEPENDENCY_FILE)` is called? Technically those count as being added through explicit config, right?

so in theory we should have set those flags correctly already, but I am not sure we did always get this right. The idea is that UNIT_DEPENDENCY_FILE is set for all dependencies that are generated due to explicit configuration in a unit file (and no others), and it's exactly those that we should unset. implicit/automatic deps otoh should not be resettable this way, and hence should use a different flag. and hopefully already do.

The dependency flag concept exists for purposes like the one of this PR. The only reason why I have the suspicion we might have set the flag incorrectly in some cases so far is that it wasn't used this way yet, and that usually means it's broken a bit.

2023-11-15 16:13 UTC, arthurshau commented
Also, to clarify, with this approach the expected behavior will be to reset ALL the dependencies from explicit config, regardless of the type of UnitDependency enum? Because with the string vector implementation, if you give for example "After=", it will only reset UNIT_AFTER dependencies. But with the mask approach I don't think we have that level of control.

2024-04-02 15:32 UTC, Werkov commented
How is it intended with responses to `systemctl daemon-reload`? I'm thinking about `StopWhenUnneeded=` which on one hand should enqueue stop jobs of a unit that ceases to be needed, on the other hand I think it's a precedent of starting the jobs upon mere config reload.

As for ordering deps, how is it supposed to work if a job A is ordered after (long running) job B and reload is issued in the middle. Shall job A be unblocked from the queue?

2024-04-05 15:46 UTC, Werkov commented
> You could already edit the unit file and call daemon-reload. 

[Yes but removal wasn't possible. However,] I realize now that adding `Upholds=` + reload already responds with new jobs. So it's truly a non-concern.

2024-06-28 23:16 UTC, closed without merging