recurse-dir: add new readdir_all_by_path() helper
systemd/systemd pull request #30147
Opened 2023-11-22 14:29 UTC by poettering

This new helper combines open() with readdir_all() to simplify a few callers.

2023-11-22 14:29 UTC, poettering commented
just to shorten the code. doesn't change behaviour, and doesn't fix anything. hence let's play safe and leave it for v256

2023-11-22 14:56 UTC, yuwata approved these changes

2023-11-22 17:30 UTC, yuwata commented
CentOS CI (Arch + sanitizers) failure is #30056, unrelated.

2023-11-30 16:13 UTC, DaanDeMeyer requested changes

2023-11-30 16:13 UTC, DaanDeMeyer commented on src/basic/recurse-dir.c
> +int readdir_all_by_path(int fd, const char *path, RecurseDirFlags flags, DirectoryEntries **ret) {
Can we name this `readdir_all_at()`? I very much prefer that we use the same naming scheme for all these functions that work in an openat() style.

2023-11-30 22:08 UTC, poettering commented on src/basic/recurse-dir.c
> +int readdir_all_by_path(int fd, const char *path, RecurseDirFlags flags, DirectoryEntries **ret) {
addressed

2023-12-06 21:12 UTC, merged