even if a device is a zac device, scsi-$ID_SERIAL will be reserved fo…
systemd/systemd pull request #30459
Opened 2023-12-13 09:12 UTC by YoruStar

[issue 30424](https://github.com/systemd/systemd/issues/30424)

2023-12-13 12:48 UTC, yuwata requested changes

2023-12-13 12:48 UTC, yuwata commented on rules.d/60-persistent-storage.rules.in
> +KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}=="?*", ENV{ID_PERIPHERAL_DEV_TYPE}=="20", PROGRAM="scsi_id -u -g $devnode", \
Is it necessary to call `scsi_id` here? I mean, the serials reported by ata_id and scsi_id are different??
If they are equivalent, then simply use `ID_SERIAL`.
If they are different, then why the condition `ENV{ID_SERIAL}=="?*"` is in this line?
Also, I think, it is better to add condition `ENV{ID_BUS}=="ata"`.

2023-12-13 12:48 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +                         int *out_peripheral_device_type) {
Please prefix `ret_` rather than `out_`, that is, `ret_peripheral_device_type`.

2023-12-13 12:48 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +        peripheral_device_type = *out_peripheral_device_type = inquiry_buf[0] & 0x1f;
Please do not update the argument to store a result in intermediate stage of the function.
Instead, please update it on success.
```c
        if (all_nul_bytes)
                return log_debug_errno(SYNTHETIC_ERRNO(EIO), "IDENTIFY data is all zeroes.");

        if (ret_peripheral_device_type)
                *ret_peripheral_device_type = peripheral_device_type;

        return 0;
}

```

2023-12-13 12:48 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +                        printf("ID_PERIPHERAL_DEV_TYPE=%d\n", peripheral_device_type);
Please prefix `ID_ATA_`, and I think it is better to not abbreviate 'DEV'.
That is, `"ID_ATA_PERIPHERAL_DEVICE_TYPE=%d\n"`.

2023-12-13 12:48 UTC, yuwata commented on src/udev/ata_id/ata_id.c
> +                if (peripheral_device_type != -1) {
Maybe, `peripheral_device_type >= 0` is better.

2023-12-13 12:50 UTC, yuwata commented on rules.d/60-persistent-storage.rules.in
> +  SYMLINK+="disk/by-id/scsi-$result"
Missing `$env{.PART_SUFFIX}` ?? Or, is this applied only whole disks?

2023-12-14 03:26 UTC, jiayi0118 commented on src/udev/ata_id/ata_id.c
> +                        printf("ID_PERIPHERAL_DEV_TYPE=%d\n", peripheral_device_type);
[The peripheral device type sense code 0x14 indicates host managed zoned block.](https://sg.danny.cz/sg/sdebug26.html)

I think it is better to use ID_TYPE="zoned" or ID_TYPE="host managed zoned block" instead, rather than adding a new environment variable.

Just like what the sg_inq can detect:

```
# sg_inq --export /dev/sdf
SCSI_TPGS=0
SCSI_TYPE=host managed zoned block
SCSI_VENDOR=ATA
SCSI_VENDOR_ENC=ATA\x20\x20\x20\x20\x20
SCSI_MODEL=HGST_HSH721414AL
SCSI_MODEL_ENC=HGST\x20HSH721414AL
SCSI_REVISION=T105
```

2023-12-14 03:26 UTC, jiayi0118 commented on src/udev/ata_id/ata_id.c
> +                        printf("ID_PERIPHERAL_DEV_TYPE=%d\n", peripheral_device_type);
By a way, scsi_id should keep consistent with ata_id on setting ID_TYPE as it also detect the peripheral device type sense code.

2023-12-14 03:26 UTC, jiayi0118 commented on rules.d/60-persistent-storage.rules.in
> +KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}=="?*", ENV{ID_PERIPHERAL_DEV_TYPE}=="20", PROGRAM="scsi_id -u -g $devnode", \
Unfortunately, the `ID_SERIAL` can be different between ata_id and scsi_id, which is weird.

```
# /lib/udev/ata_id /dev/sdf --export | grep -v ID_ATA | sort > ~/ata
# /lib/udev/scsi_id --export --whitelisted -d  /dev/sdf | grep -v ID_SCSI > ~/scsi
# /lib/udev/scsi_id --export --whitelisted -d  /dev/sdf | grep -v ID_SCSI | sort > ~/scsi
# diff ~/ata ~/scsi
1,7c1,8
< ID_BUS=ata
< ID_MODEL_ENC=HGST\x20HSH721414ALE6M0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
< ID_MODEL=HGST_HSH721414ALE6M0
< ID_REVISION=L4GMT105
< ID_SERIAL=HGST_HSH721414ALE6M0_VEG0A1MK
< ID_SERIAL_SHORT=VEG0A1MK
< ID_TYPE=disk
---
> ID_MODEL_ENC=HGST\x20HSH721414AL
> ID_MODEL=HGST_HSH721414AL
> ID_REVISION=T105
> ID_SERIAL=35000cca25bc025bc
> ID_SERIAL_SHORT=5000cca25bc025bc
> ID_TYPE=generic
> ID_VENDOR=ATA
> ID_VENDOR_ENC=ATA\x20\x20\x20\x20\x20
```

2024-01-10 19:50 UTC, bluca commented on src/udev/ata_id/ata_id.c
> +        int peripheral_device_type = -1;
merge in the line above

2024-01-10 19:50 UTC, bluca approved these changes

2024-01-16 05:57 UTC, merged