resolved: actually check authenticated flag of SOA transaction
systemd/systemd pull request #30549
Opened 2023-12-20 16:37 UTC by msekletar

Fixes #25676

2023-12-20 16:40 UTC, msekletar commented
I tried to take a stab at #25676 and this is what I came up with,  it seems to fix the issue but please review it carefully as I am not really resolved expert.

2023-12-20 16:43 UTC, yuwata requested changes

2023-12-20 16:43 UTC, yuwata commented on src/resolve/resolved-dns-transaction.c
> +                        return FLAGS_SET(dt->answer_query_flags, SD_RESOLVED_AUTHENTICATED);
Exactly same mistake can be found in the above case block. Could you also fix it?

2023-12-20 16:58 UTC, msekletar commented on src/resolve/resolved-dns-transaction.c
> +                        return FLAGS_SET(dt->answer_query_flags, SD_RESOLVED_AUTHENTICATED);
Done

2023-12-20 18:32 UTC, yuwata approved these changes

2023-12-20 18:33 UTC, yuwata commented
@poettering Could you double check?

2023-12-21 09:48 UTC, poettering commented
ouch.

lgtm

2023-12-21 09:54 UTC, merged

2023-12-22 19:31 UTC, pemensik commented
I have taken a look into this commit and it seemed a *way too* simple to fix the issue properly. I made my own rawhide build with added only this patch [on top](https://src.fedoraproject.org/fork/pemensik/rpms/systemd/tree/CVE-2023-7008) of last build.

As I have suspected this changes *IS NOT* sufficient to prevent the cache poisoning. I have used simple addition to libvirt's dnsmasq backed network.

```
# sudo virsh net-edit default
<network>
  <!-- ... -->
  <dns>
    <txt name='example.net' value='v=spf1 +all'/>
    <host ip='127.0.0.255'>
      <hostname>example.net</hostname>
    </host>
  </dns>
  <!-- ... -->
</network>
```

Unless I have made mistake with build, this is not sufficient fix. It may protect SOA query itself, but does not protect other records. It is still possible to spoof own records. All example domains ARE signed, so any their spoofing should make them broken and inaccessible.

```
# resolvectl dnssec
Global: yes
Link 2 (host0): yes
# rpm -q systemd-resolved
systemd-resolved-255.1-2.fc40.x86_64
# resolvectl query example.net
example.net: 127.0.0.255                       -- link: host0
             2606:2800:220:1:248:1893:25c8:1946 -- link: host0

-- Information acquired via protocol DNS in 5.9ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache network
# resolvectl query -t txt example.net
example.net IN TXT "v=spf1 +all"                            -- link: host0

-- Information acquired via protocol DNS in 2.1ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: network
# delv example.net
;; broken trust chain resolving 'example.net/A/IN': 127.0.0.53#53
;; resolution failed: broken trust chain
# unbound-host -rvD example.net
example.net has address 127.0.0.255 (BOGUS (security failure))
validation failure <example.net. A IN>: SERVFAIL no DS for DS net. while building chain of trust
example.net has IPv6 address 2606:2800:220:1:248:1893:25c8:1946 (BOGUS (security failure))
validation failure <example.net. AAAA IN>: key for validation net. is marked as invalid because of a previous no DS
example.net mail is handled by 0 . (BOGUS (security failure))
validation failure <example.net. MX IN>: key for validation net. is marked as invalid because of a previous no DS
```

2023-12-22 20:05 UTC, pemensik reviewed
I am afraid it is not as simple as demanding AD bit in SOA queries. First problem is those SOA queries are not necessary anyway. But it is possible to keep SOA query intact and replace just record type you want to modify. That is done by *dnsmasq* for example, it does not care about zone definitions.

2023-12-22 22:44 UTC, pemensik commented
False alarm, this seems to fix the issue well, but Fedora package does not contain instruction to restart *systemd-resolved.service*, therefore it had no immediate effect.