Execute hwdb for hidraw subsystem devices
systemd/systemd pull request #30611
Opened 2023-12-23 21:30 UTC by djantti

Systemd PR #22730 added usb and hidraw subsystem uaccess rule tags for AV production devices defined in hwdb.d/70-av-production.hwdb.

Unfortunately rules.d/50-udev-default.rules.in only executes hwdb for the usb subsystem and not for hidraw. Hidraw devices never actually get the uaccess tag from rules.d/70-uaccess.rules.in and never have proper user permissions.

This single line PR implements hwdb execution also for hidraw subsystem devices.

2023-12-24 09:46 UTC, yuwata requested changes

2023-12-24 09:46 UTC, yuwata commented on rules.d/50-udev-default.rules.in
> +SUBSYSTEM=="hidraw", IMPORT{builtin}="usb_id", IMPORT{builtin}="hwdb"
Why "usb_id" is called? At least, please do not import usb_id unconditionally, but conditionalize with `SUBSYSTEMS=="usb", if it really necessary.

2023-12-24 10:53 UTC, djantti commented on rules.d/50-udev-default.rules.in
> +SUBSYSTEM=="hidraw", IMPORT{builtin}="usb_id", IMPORT{builtin}="hwdb"
Got it, thanks! Calling usb_id definitely is not necessary here.

2023-12-24 12:40 UTC, yuwata approved these changes

2023-12-24 17:16 UTC, merged

2023-12-30 07:55 UTC, Be-ing commented
Thank you for fixing this! :heart: That's probably why I couldn't get the changes working on my machine in the [original PR](https://github.com/systemd/systemd/pull/20561#issuecomment-1067150666).