boot/efi: change parameter type of efivar_get_raw's buf to void**
systemd/systemd pull request #30812
Opened 2024-01-06 23:35 UTC by AtariDreams

Having a char** means we have to violate C's pointer rules as we often just pass structs and char16_t, and the underlying function uses void* anyway, so we should change buf to match.

You can cast anything to char *, but that does not mean you can have a double char pointer pointing to that variable. This change means that there is no odd type aliasing going on.

2024-01-11 05:00 UTC, yuwata requested changes
Sorry, but NAK for most changes, especially for passing `HandleProtocol`.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/random-seed.c
> +        _cleanup_free_ void *data = NULL;
This looks OK.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +        err = efivar_get_raw(vendor, name, &buf_raw, &size);
Please directly pass `&buf` with casting.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +        err = efivar_get_raw(vendor, name, &buf_raw, &size);
Also here.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +        _cleanup_free_ void *buf_raw = NULL;
Maybe, better to make it `uint8_t *`, as `char` should be used for string.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +        _cleanup_free_ void *buf_raw = NULL;
Here also.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +EFI_STATUS efivar_get_raw(const EFI_GUID *vendor, const char16_t *name, void **ret, size_t *ret_size) {
This is OK.

2024-01-11 05:00 UTC, yuwata commented on src/boot/efi/util.c
> +        _cleanup_free_ void *b = NULL;
As the function name suggests, this should be `uint8_t *`.

2024-01-13 18:47 UTC, AtariDreams commented on src/boot/efi/util.c
> +        err = efivar_get_raw(vendor, name, &buf_raw, &size);
That is technically undefined behavior.

2024-01-13 18:48 UTC, AtariDreams commented on src/boot/efi/util.c
> +        err = efivar_get_raw(vendor, name, &buf_raw, &size);
Ditto. Undefined behavior.

2024-01-13 18:49 UTC, AtariDreams commented on src/boot/efi/util.c
> +        _cleanup_free_ void *buf_raw = NULL;
I get a warning that is propagated to error when I do this.

2024-01-13 18:49 UTC, AtariDreams commented on src/boot/efi/util.c
> +        _cleanup_free_ void *buf_raw = NULL;
Ditto.

2024-01-13 18:50 UTC, AtariDreams commented on src/boot/efi/util.c
> +        _cleanup_free_ void *b = NULL;
Ditto.

You can cast char * to void *, but not char** to void **

2024-01-14 07:14 UTC, yuwata commented on src/boot/efi/util.c
> +        err = efivar_get_raw(vendor, name, &buf_raw, &size);
I do not understand the meaning of "technically undefined" here. Please elaborate more.
If this violates C standard, then please give us references.

Even if it violates something, I guess GCC and clang nicely support that. Why they do not warn about the violation?
Also, we enable several static and dynamic code analyzers, but none of them report such issue.

Anyway, please explain more.

2024-01-17 13:02 UTC, poettering commented
So, changing efivar_get_raw() to return a void* makes sense to me, but I am not sure what the point of having an intermediary variable when we need another type? why not cast this directly?

2024-07-02 17:28 UTC, bluca commented
replaced by https://github.com/systemd/systemd/pull/33574

2024-07-02 17:28 UTC, closed without merging