nspawn: permit `--ephemeral` with `--link-journal=try-*` (treat as =no)
systemd/systemd pull request #31051
Opened 2024-01-22 19:00 UTC by intelfx

Common sense says that to "try" something means "to not fail if something turns out not to be possible", thus do not make this combination a hard error.

The actual implementation ignores any `--link-journal=` setting when `--ephemeral` is in effect, so the semantics are upheld.

---

This improves the usability of the default `systemd-nspawn@.service` unit (hence `machinectl start` and friends) when the user sets `Ephemeral=yes` in the nspawn configuration file.

2024-01-24 16:51 UTC, keszybz requested changes

2024-01-24 16:51 UTC, keszybz commented on src/nspawn/nspawn.c
>                  return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "--ephemeral and --link-journal= may not be combined.");
So… now the error message is not true anymore. (Or more precisely, it's even wronger now that before.)
Maybe instead say
"--ephemeral and --link-journal=guest/host cannot be combined."

IIUC, it's only those two values that would be rejected.

2024-01-25 16:14 UTC, poettering commented
lgtm, too

2024-01-29 10:46 UTC, keszybz commented
@intelfx update?

2024-01-29 17:56 UTC, intelfx commented
Apologies, slightly busy, I'll get back to this and the other PR later today.

2024-02-02 18:03 UTC, yuwata approved these changes

2024-02-02 18:03 UTC, merged