network: netdev - bond add support for ARP missed max
systemd/systemd pull request #31338
Opened 2024-02-15 11:03 UTC by ssahani

```
Name=bondtest
Kind=bond

[Bond]
Mode=active-backup
PrimaryReselectPolicy=always
MIIMonitorSec=1s
ARPMissedMax=10

```

```
 ip -d link show bondtest
8: bondtest: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 96:f1:40:59:40:40 brd ff:ff:ff:ff:ff:ff promiscuity 0 allmulti 0 minmtu 68 maxmtu 65535
    bond mode active-backup miimon 1000 updelay 0 downdelay 0 peer_notify_delay 0 use_carrier 1 arp_interval 0 arp_missed_max 10 arp_validate none arp_all_targets any primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 1 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_active on lacp_rate slow ad_select stable tlb_dynamic_lb 1 numtxqueues 16 numrxqueues 16 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536
```

2024-02-15 11:12 UTC, bluca commented on man/systemd.netdev.xml
> +          <xi:include href="version-info.xml" xpointer="v255"/>
256

2024-02-15 13:18 UTC, yuwata requested changes
Please add a simple test to verify the value is applied.

Also please update the commit message to explain what the setting is, rather than an example configuration and result.

2024-02-15 15:50 UTC, poettering approved these changes

2024-02-15 16:12 UTC, yuwata commented
Could you drop the example setting and result of `ip` command in the commit message? At least, please wrap the long lines...

2024-02-16 12:04 UTC, ssahani commented
Updated. Thanks for the review

2024-02-16 21:15 UTC, yuwata approved these changes

2024-02-16 21:16 UTC, merged