network: add basic support of neighbor advertisement
systemd/systemd pull request #31373
Opened 2024-02-18 06:34 UTC by yuwata

Closes #28421.

2024-02-18 06:39 UTC, yuwata commented
@LiveFreeAndRoam Please test this PR. Thank you!

2024-02-18 10:25 UTC, LiveFreeAndRoam commented
Will do. I should have the results late afternoon on Monday.

On Sun, 18 Feb 2024, 4:39 pm Yu Watanabe, ***@***.***> wrote:

> @LiveFreeAndRoam <https://github.com/LiveFreeAndRoam> Please test this
> PR. Thank you!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/systemd/systemd/pull/31373#issuecomment-1950979900>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB6ZRGBCTNUG56GW4CDLPNDYUGO3ZAVCNFSM6AAAAABDN5FMUWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJQHE3TSOJQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-18 21:14 UTC, bluca commented
@mrc0mmand looks new:

```
18:58:52 [   58.835810] systemd-journald[317]: Failed to create new system journal: No space left on device
18:58:52 [   58.871275] kernel: Buffer I/O error on dev loop0, logical block 188, lost async page write
18:58:52 [   59.002224] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   59.092183] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   59.165246] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   60.383763] testsuite-58.sh[8600]: Creating journal (262144 blocks): done
18:58:52 [   61.063267] testsuite-58.sh[8600]: Writing superblocks and filesystem accounting information:    0/8192         mkfs.ext4: Input/output error while writing out and closing file system
18:58:52 [   61.063733] testsuite-58.sh[8598]: (mkfs) failed with exit status 1.
18:58:52 [   61.063733] testsuite-58.sh[8598]: Failed to sync loop block device, ignoring: Input/output error
```

2024-02-19 05:46 UTC, LiveFreeAndRoam commented
Hi @yuwata.  I was about to start an IPv6 Conformance test cycle.  It looks like you've begun pushing changes to systemd/systemd.  What branch would you like me to test? Your `network-neighbor-advertisement` branch or some other?

2024-02-19 05:50 UTC, yuwata commented
> Hi @yuwata. I was about to start an IPv6 Conformance test cycle. It looks like you've begun pushing changes to systemd/systemd. What branch would you like me to test? Your `network-neighbor-advertisement` branch or some other?

Yes, `network-neighbor-advertisement` please. Thank you! This should not be still perfect. But I hope the situation should be better than previous when you open several issues.

2024-02-19 06:07 UTC, LiveFreeAndRoam commented
I'm seeing failures at the moment. I'll have to dig in deeper to see what's tripping up one of the tests. I'll need some time to track this down.

2024-02-19 06:44 UTC, yuwata commented
Which test(s)? Please provide the list of failed tests. I will also take a look.

2024-02-19 07:48 UTC, LiveFreeAndRoam commented
Sorry for the delay, I had to run some errands.  I'm back looking at it now. The failed test is the same described in #28421.  I'm guessing the default route is not being deleted upon receipt of the NA with isRouter=false.

2024-02-19 08:27 UTC, LiveFreeAndRoam commented
To get the tests to pass, I had to comment out your checks for `sd_ndisc_neighbor_is_solicited` and `sd_ndisc_neighbor_is_override`.  The diff is:

```
diff --git a/src/network/networkd-ndisc.c b/src/network/networkd-ndisc.c
index 672e07438d..3b738e9178 100644
--- a/src/network/networkd-ndisc.c
+++ b/src/network/networkd-ndisc.c
@@ -1819,15 +1819,15 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         assert(link);
         assert(na);
 
-        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
-        r = sd_ndisc_neighbor_is_solicited(na);
-        if (r != 0)
-                return r;
+        // /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
+        // r = sd_ndisc_neighbor_is_solicited(na);
+        // if (r != 0)
+        //         return r;
 
         /* It is not necessary to update anything if the override flag is not set. */
-        r = sd_ndisc_neighbor_is_override(na);
-        if (r <= 0)
-                return r;
+        // r = sd_ndisc_neighbor_is_override(na);
+        // if (r <= 0)
+        //         return r;
 
         r = sd_ndisc_neighbor_is_router(na);
         if (r < 0)
```

2024-02-19 08:31 UTC, LiveFreeAndRoam commented
Probably a better way to look at this is that the processing for `IsRouter` flag ought to trump checks for `solicited` and `override` flags.  In which case, a more appropriate patch would be to move the `IsRouter` processing above other checks.  E.g.:

```
diff --git a/src/network/networkd-ndisc.c b/src/network/networkd-ndisc.c
index 672e07438d..58794ed18e 100644
--- a/src/network/networkd-ndisc.c
+++ b/src/network/networkd-ndisc.c
@@ -1819,16 +1819,6 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         assert(link);
         assert(na);
 
-        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
-        r = sd_ndisc_neighbor_is_solicited(na);
-        if (r != 0)
-                return r;
-
-        /* It is not necessary to update anything if the override flag is not set. */
-        r = sd_ndisc_neighbor_is_override(na);
-        if (r <= 0)
-                return r;
-
         r = sd_ndisc_neighbor_is_router(na);
         if (r < 0)
                 return r;
@@ -1839,6 +1829,16 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         if (r < 0)
                 return r;
 
+        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
+        r = sd_ndisc_neighbor_is_solicited(na);
+        if (r != 0)
+                return r;
+
+        /* It is not necessary to update anything if the override flag is not set. */
+        r = sd_ndisc_neighbor_is_override(na);
+        if (r <= 0)
+                return r;
+
         return 0;
 }
```

2024-02-19 12:13 UTC, poettering commented on src/libsystemd-network/sd-ndisc-neighbor.c
> +        }
the {} is redudnant.

2024-02-19 12:15 UTC, poettering commented on src/network/networkd-ndisc.c
> +static int ndisc_drop_outdated(Link *link, struct in6_addr *router, usec_t timestamp_usec) {
const?

2024-02-19 12:17 UTC, poettering commented on src/libsystemd-network/sd-radv.c
> +        };
this is not modified, hence make it static const?

2024-02-19 12:17 UTC, poettering commented on src/libsystemd-network/sd-radv.c
> +        };
ditto

2024-02-19 12:18 UTC, poettering commented on src/libsystemd-network/sd-radv.c
> +        };
static const?

2024-02-19 12:19 UTC, poettering commented on src/libsystemd-network/sd-radv.c
> +        _cleanup_free_ uint8_t *buf = new0(uint8_t, buflen);
why new0() rather than new()?

2024-02-19 20:50 UTC, LiveFreeAndRoam commented
I want to add a little more context... (for future reference)

Even though networkd is not yet sending NS packets, the kernel does.

The neighbor responds to an NS with an NA (`solicited`).  In that same NA it could also flip the (`IsRouter`) flag.  So, regardless of the NA `solicited` flag, we still need to process the `IsRouter` flag for routes that networkd created.

2024-02-19 21:12 UTC, LiveFreeAndRoam commented
_Question_: Currently, networkd intercepts the RA packets and prevents the kernel from processing them by setting the sysctl variable `accept_ra=0`.  With NA packets, it looks like both networkd and the kernel will process them, since there doesn't appear to be a way to tell the kernel to ignore them. For NA packets, I think this is ok (and necessary) because the kernel will need to resolve a neighbor's address with an NS/NA exchange. Though, it leaves me wondering if there are cases where having both _networkd_ and the _kernel_ process the same NA might cause problems.

Thoughts?

2024-02-19 22:30 UTC, LiveFreeAndRoam commented
FYI, I'm running the IPv6 Conformance _Base_ tests,  using my patch (described above).  The tests will be complete in about 3 hours.  I'll need another hour to collate the results and report my findings.  Keep in mind, these are just the _Base_ tests (a collection of **333** protocol tests). There are another set of tests (_PMTU, DAD, Ping_ - **81** tests in total) that take quite a bit longer to run, so those results will come at a later point in time.

2024-02-20 01:25 UTC, LiveFreeAndRoam commented
Today's results are in... there has been a big improvement since we first started looking at these issues.

In summary:

| Version | v254<sup>(1)</sup> | v255<sup>(2)</sup> | v255+patches to-current-date<sup>(1)</sup> |
|--------|--------|--------|--------|
| **Passing** | 31 | 36 | 53 |
| **Failing** | 42 | 67 | 22 |
| **TBD** | 28 | 0 | 28 |

* **(1)** Only base tests were run. There are 28 more tests that have failed in the past that I am yet to run.
* **(2)** All tests were run

I'll write up the next batch of cases that would be good to address.

2024-02-20 01:57 UTC, yuwata commented on src/libsystemd-network/sd-radv.c
> +        };
It can be, but if we make it static const, we need to cast it when setting `msg.msg_name`.

2024-02-20 01:58 UTC, yuwata commented on src/libsystemd-network/sd-radv.c
> +        };
The same as the above.

2024-02-21 03:57 UTC, LiveFreeAndRoam requested changes
I still need the changes referenced in my [comment ](https://github.com/systemd/systemd/pull/31373#issuecomment-1951939104) to be applied.  The IPv6 Compliance test won't pass without those changes.

I also consulted with the owners of the test program, and they confirmed the R flag must be processed independently of the O or S flags.

2024-02-21 04:08 UTC, LiveFreeAndRoam approved these changes
Getting in with an early approval.  Tests pass and code looks good to me.

2024-02-21 04:28 UTC, yuwata commented
Will push an updated version after #31423 is merged.

2024-03-08 03:04 UTC, LiveFreeAndRoam commented
Sorry to say, but these tests are failing again.  I'm build with SHA ba8017c0d3.

I won't get a chance to investigate until I get back from 1 week away.

2024-03-25 18:38 UTC, yuwata commented
@LiveFreeAndRoam Sorry for late. Could you try with this branch again?

2024-03-26 18:38 UTC, yuwata commented
Yay, CentOS CIs are green again. @LiveFreeAndRoam Could you test again?

2024-03-26 19:50 UTC, LiveFreeAndRoam commented
The tests from the 2.1.21 suite are still failing.  I will investigate further a little later today.  Let me know if there is something specific you'd like me to look for.

I rebuilt using:

```
$ git log -n 1
commit 59b72d6f47160c74a1d7f44bc3e2373b4e14dd58 (HEAD -> network-next, origin/network-next)
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Sat Mar 16 02:32:50 2024 +0900
```

2024-03-26 20:01 UTC, yuwata commented
Hm, debugging logs of networkd please.

2024-03-26 23:39 UTC, LiveFreeAndRoam commented
@yuwata, here is the debug log after running _2.1.21a_.


```
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 20s
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '100000'
No change in value '100000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (n/a): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received new NDisc route (configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received new NDisc address (configured): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: ndisc_check_ready(): no SLAAC address is ready.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 13s, preferred for 18h 12min 13s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=21 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=22 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=23 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: Received new foreign route (configured): dst: 2001:2:0:1000:f1c5:7f81:2ff6:19fd/128, src: n/a, gw: n/a, prefsrc: n/a, table: local(255), priority: 0, proto: kernel, scope: global, type: local, flags: n/a
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 0
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Removing NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Found an existing route that conflicts with new route based on a received RA, removing.
enp0s9: Removing NDisc route (configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc route (configured,removing): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Setting SLAAC addresses and router.
enp0s9: Refuse to configure NDisc route with zero lifetime.
enp0s9: Forgetting removed NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Forgetting removed NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
```

2024-03-26 23:52 UTC, LiveFreeAndRoam commented
I corrected the config file (disabling the stable-privacy that I needed for other tests to pass). I reran the tests and they are passing.  

This issue can be closed.

@yuwata, Apologies for the misdirect; my dud results were a quick test between other tasks and I had forgotten about the stable-privacy changes to make other tests pass.

2024-03-28 00:58 UTC, yuwata commented
@LiveFreeAndRoam Thank you for testing! I am happy to hear that this now works fine.

@bluca @YHNdnzj @keszybz This is now ready for review. Could you review this?

2024-03-28 04:10 UTC, yuwata commented
Note, our own test case will be added later, already waiting in #30569.

2024-04-03 21:02 UTC, bluca commented on src/libsystemd-network/sd-ndisc.c
> +                  IN6_ADDR_TO_STRING(&na->packet->sender_address),
ASSERT_PTR or check na->packet

2024-04-03 21:03 UTC, bluca commented on src/network/networkd-ndisc.c
> +        /* Received Neighbor Advertisement message without Router flag. The node might be a router, and now
"might have been a router"

2024-04-03 21:04 UTC, bluca approved these changes

2024-04-04 17:17 UTC, yuwata commented
@bluca Thank you for the review. The above comments are addressed. Upgrading the green label.

2024-04-04 20:54 UTC, merged