catalog,po: update Polish translation 240303
systemd/systemd pull request #31601
Opened 2024-03-03 14:53 UTC by piotrdrag

2024-03-04 13:56 UTC, poettering commented
needs a rebase

2024-03-05 13:15 UTC, keszybz requested changes

2024-03-05 13:15 UTC, keszybz commented on catalog/systemd.pl.catalog.in
> +Subject: Inicjacja kontenera uległa awarii
Nie, "container init" to w tym kontekście proces. "Proces init kontenera uległ awarii" ?

2024-03-05 13:15 UTC, keszybz commented on catalog/systemd.pl.catalog.in
> +Subject: Wykonanie inicjacji się zawiesiło
Process init został zatrzymany w wyniku awarii

2024-03-05 13:15 UTC, keszybz commented on catalog/systemd.pl.catalog.in
> +Systemd zawiesiło wykonanie po błędzie krytycznym.
Raczej "zawiesił"

2024-03-05 13:15 UTC, keszybz commented on catalog/systemd.pl.catalog.in
> +Subject: Inicjacja otrzymała sygnał krytyczny, kiedy zrzut core jest wyłączony
Inicjacja → proces init, to i dalej.

2024-03-05 13:15 UTC, keszybz commented on catalog/systemd.pl.catalog.in
> +Subject: Zapisanie listy wyłącznych możliwości Smack przez menedżera się nie powiodło
Ja bym zostawił "onlycap" — ta nazwa jest elementem interfejsu Smack.

2024-03-12 10:37 UTC, merged