Update mmap-cache.c to avoid double free corruption
systemd/systemd pull request #31630
Opened 2024-03-05 10:51 UTC by SidhuRupinder

There is no need for a while loop, as we are freeing the memory of f->windows on the first go. While loop gives a "double free memory corruption" error

2024-03-05 10:59 UTC, YHNdnzj requested changes
No. `f->windows` is a linked list. When `window_free` is called, `window_unlink` unlinks one entry from the linked list.

2024-03-05 11:27 UTC, mrc0mmand commented
Yeah, this seems wrong. If you have a report of the mentioned double free, please feel free to share it.

2024-03-05 14:41 UTC, poettering commented
Please provide a valgrind output/backtrace of the memory corruption you are seeing.

2024-03-06 06:50 UTC, SidhuRupinder commented
This issue was reported during Coverity scan

2024-03-06 09:09 UTC, poettering commented
coverity is wrong on this one, it's a false positive. it doesn't understand that this is a linked list and the function updates it internally.

2024-03-06 09:09 UTC, closed without merging