Add new unittest file for basic:label module
systemd/systemd pull request #31693
Opened 2024-03-09 12:34 UTC by devdekunle

The new test files contains testcases for the basic:label module. it tests the three functions label_ops_set, label_ops_pre and label_ops_post

2024-03-09 12:46 UTC, bluca commented on src/test/test-label.c
> +#include <errno.h>
SPDX license line is missing

2024-03-09 12:46 UTC, bluca commented on src/test/test-label.c
> +#include "string-util.h"
sort alphabetically

2024-03-09 12:47 UTC, bluca commented on src/test/test-label.c
> +DEFINE_TEST_MAIN(LOG_INFO)
new line at the end of file missing

2024-03-10 01:06 UTC, devdekunle commented on src/test/test-label.c
> +DEFINE_TEST_MAIN(LOG_INFO)
Thank you @bluca for the corrections

2024-03-10 01:10 UTC, devdekunle commented
I've implemented the changes @bluca Kindly review

2024-03-10 11:57 UTC, bluca commented
The test is failing, also rebase squash fixups commits

2024-03-11 13:20 UTC, bluca commented
Still failing:

```
stderr:
/* test_label_ops_post */
/* test_label_ops_pre */
Assertion 'label_ops_pre(1, "/restricted_directory", 0755) == -1' failed at src/test/test-label.c:47, function test_label_ops_pre(). Aborting.
```

2024-03-11 15:18 UTC, poettering requested changes

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +}
please follow coding style, i.e. 8space indentation.

https://systemd.io/CODING_STYLE/

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +
spurious double empty line

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +    };
static const

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +int post_labelling_func(int dir_fd, const char *path);
why these prototypes?

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +        return -1;
do not make up errors like -1. Return negative errno style errors, i.e. -EINVAL or so. See coding style

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +    if (streq(path, "/restricted_directory"))
path_equal()

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +        return -1;
as above

2024-03-11 15:18 UTC, poettering commented on src/test/test-label.c
> +    return -1;
indentation is not right

2024-03-12 14:36 UTC, devdekunle commented on src/test/test-label.c
> +        return -1;
Thank you @poettering I have refactored the code by removing the prototypes and adjusting indentations

2024-03-12 16:56 UTC, closed without merging