Add unittest file for basic:label
systemd/systemd pull request #31762
Opened 2024-03-13 15:49 UTC by devdekunle

Write a new unittest file for basic:label testing the three functions, label_ops_set, label_ops_post and label_ops_pre

2024-03-13 16:21 UTC, devdekunle commented
@bluca please kindly review. i have fixed up the commits and implemented changes

2024-03-13 22:27 UTC, bluca approved these changes

2024-03-14 07:46 UTC, keszybz requested changes

2024-03-14 07:46 UTC, keszybz commented on src/basic/label.c
> +void label_ops_reset(void) {
Newline missing here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +static int pre_labelling_func(int dir_fd, const char *path, mode_t mode) {
Newline missing here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +        if (strlen(path) > 40)
Please add a comment explaining this "40".

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +
Unnecessary newline here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +
Unnecessary newline here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +
Unnecessary newline here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +        label_ops_reset();
Newline is missing here.

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +        return 0; /*on sucess*/
Just `return check_path(dir_fd, path)` ?

2024-03-14 07:46 UTC, keszybz commented on src/test/test-label.c
> +        return 0; /* on success */
Just `return check_path(dir_fd, path)` ?

2024-03-16 06:59 UTC, devdekunle commented
@keszybz Good morning. Please I made changes as you requested while I added more functionality. The pre_labelling_func and post_labelling_func are custom functions. I also have an issue. The unit tests pass from my local tests but some checks on the ci are failing such the mkosi/ci and unittest with Asan and ubsan specified. Please can you guide me on what these checks are testing for because I can't see any failure from my local machine. Maybe there's something I'm not checking.

2024-03-17 08:57 UTC, devdekunle commented
@bluca @keszybz. I have successfully fixed the errors after lots of debugging and persistence. Please kindly review. Thank you.

2024-03-18 11:04 UTC, bluca approved these changes

2024-03-18 11:04 UTC, merged