Document SYSTEMD_REPART_MKFS_* in repart.d manual
systemd/systemd pull request #31786
Opened 2024-03-14 13:02 UTC by gdonval

2024-03-14 13:02 UTC, gdonval commented
Not sure what to do with `mkfs.FILESYSTEM`.

2024-03-14 13:10 UTC, DaanDeMeyer requested changes

2024-03-14 13:10 UTC, daandemeyer commented on man/repart.d.xml
> +    </para>
Please format the same as other `Environment` sections. Grep for `<title>Environment</title>` for examples

2024-03-14 13:28 UTC, gdonval commented on man/repart.d.xml
> +    </para>
Do you want a full exhaustive list with each filesystem explicitly named? Or something like in `bootctl` would work?

2024-03-19 08:54 UTC, keszybz commented on man/repart.d.xml
> +    </para>
The general format is fine, but please use
`<command>mkfs.<replaceable>filesystem</replaceable></command>` so this gets formatted.

In the last sentence, maybe instead say "The contents of those variables are passed as-is to the command, without any verificiation."

2024-03-25 18:08 UTC, merged