timer: introduce AlwaysRealtime setting
systemd/systemd pull request #31795
Opened 2024-03-14 20:00 UTC by arthurshau

By default, in instances where timers are running on a realtime schedule, in the case where the system goes to sleep, if the timer event elapses during the sleep, the service unit is immediately triggered when the system wakes up. Similarly, if a service takes longer to run than the interval of a timer, thus causing the calendar event to elapse while the service is still running, the service will immediately start again when the previous invocation finishes.

This behavior can be changed by enabling the new AlwaysRealtime setting, which will cause all calendar events that elapsed during sleep/while a service was running to be ignored. Thus, if a timer is on an realtime interval, the trigger will always adhere to that specified interval. E.g. if you have a timer that runs on a minutely interval, the setting guarantees that triggers will happen at *:*:00 times, whereas by default this may skew depending on sleeps/runtimes.

More detailed example:
```
[root@fedora system]# cat realtime-test.service
[Unit]
Description=Testing

[Service]
Type=simple
ExecStart=bash -c 'date >>/tmp/realtime-test.log ; sleep 90s'
[root@fedora system]# cat realtime-test.timer
[Unit]
Description=Testing

[Timer]
OnCalendar=minutely
AccuracySec=1us
AlwaysRealtime=true

[Install]
WantedBy=timers.target
[root@fedora system]# cat /tmp/realtime-test.log
Thu Mar 14 12:54:00 PDT 2024
Thu Mar 14 12:56:00 PDT 2024
Thu Mar 14 12:58:00 PDT 2024
```
Without AlwaysRealtime=true, we would expect to see 
```
Thu Mar 14 12:54:00 PDT 2024
Thu Mar 14 12:55:30 PDT 2024
Thu Mar 14 12:57:00 PDT 2024
```
as the service takes 90 seconds to run. But with the setting enabled, we can make it so that the the service unit is only triggered on the minute marks.

Any feedback about the naming of the setting and the man page documentation is extra appreciated.

2024-03-22 09:40 UTC, DaanDeMeyer requested changes
We're also going to need find a better name than `AlwaysRealtime`, as we don't use the realtime anymore with the most recent changes. I'm coming up blank though.

2024-03-22 09:40 UTC, daandemeyer commented on src/core/timer.c
> +                        } else if (dual_timestamp_is_set(&t->last_trigger))
I think we can simply this a bit:

```
if (t->always_realtime && dual_timestamp_is_set(&trigger->inactive_enter_timestamp))
...
else if (!t->always_realtime && dual_timestamp_is_set(&t->last_trigger)
...
```

2024-03-22 21:05 UTC, arthurshau commented
Addressed comments, thanks!

Also agree that we could use a better name for this setting, will continue to brainstorm.

2024-03-25 13:48 UTC, bluca commented on tools/dbus_ignorelist
> +org.freedesktop.systemd1.Timer.AlwaysRealtime
this is new so it must be documented, not ignored

2024-03-25 13:49 UTC, bluca commented
This also needs a real integration test that checks the intended behaviour

2024-03-27 19:57 UTC, bluca commented
Then rather than a boolean that is hard to understand, it would be better to add a new setting like OnCalendarInactive or so, that is re-armed only after the linked unit has become inactive

2024-06-28 23:15 UTC, closed without merging

2024-09-30 17:33 UTC, teknoraver commented
Hi, I'm taking this PR and continuing it in #34591