core/mount: if mount is gone eventually, consider it success
systemd/systemd pull request #32004
Opened 2024-03-28 17:09 UTC by YHNdnzj

Currently, if unmount initiated by us fails, we record
that in result. Later, if we tried again and succeeded,
or someone else successfully unmounted it, the unit
state is still considered failed. Let's be more tolerant
instead, and forget about previous failure.

Alternative to https://github.com/systemd/systemd/pull/32002

2024-03-29 00:42 UTC, yuwata requested changes

2024-03-29 00:42 UTC, yuwata commented on src/core/mount.c
> +                        mount_enter_dead(m, MOUNT_SUCCESS, /* flush_failure = */ true);
That makes sense, but please add a short comment why we flush previous failure here.

2024-03-29 00:42 UTC, yuwata commented on src/core/mount.c
> +                        mount_enter_dead_or_mounted(m, f, /* flush_failure = */ true);
Why true here? Could you add comment about that?

2024-03-31 12:31 UTC, DaanDeMeyer approved these changes

2024-03-31 12:31 UTC, DaanDeMeyer commented on src/core/mount.c
> +static void mount_enter_dead(Mount *m, MountResult f, bool flush_failure) {
`flush_failure` seems like a bad name since this will flush "success" as well. I would use `flush_result` instead.

2024-04-02 14:34 UTC, yuwata approved these changes

2024-04-02 14:52 UTC, bluca approved these changes

2024-04-02 14:52 UTC, merged

2024-04-23 18:06 UTC, keszybz commented
I took the first commit, but the second one conflicts heavily.

2024-04-24 06:50 UTC, keszybz commented
Nvm, it applies cleanly now. Maybe I messed something up yesterday.