network: netdev - BareUDP Add support for srcportmin
systemd/systemd pull request #32067
Opened 2024-04-03 13:10 UTC by ssahani

2024-04-23 14:17 UTC, poettering requested changes

2024-04-23 14:17 UTC, poettering commented on man/systemd.netdev.xml
> +        <term><varname>MinimumSourcePort=</varname></term>
almost everywhere else we abbreviate "Minimum" to "Min".

I generally dislike needless abbreivations, but this one is a very common abbreviation that is already used all over the place in our tree, hence please call this just Min, not Minimum

2024-04-23 14:18 UTC, poettering commented
i'll leave the final review to @yuwata

2024-06-17 01:31 UTC, ssahani commented
/CC @yuwata

2024-08-02 06:06 UTC, yuwata approved these changes
Sorry for late review. LGTM. One nitpick.

2024-08-02 06:06 UTC, yuwata commented on man/systemd.netdev.xml
> +        <xi:include href="version-info.xml" xpointer="v256"/>
`v256` -> `v257`

2024-08-14 20:34 UTC, yuwata commented
CentOS CI failure is unrelated:
```
======================================================================
FAIL: test_invalid_captive_portal (__main__.NetworkdRATests.test_invalid_captive_portal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/test/test-network/systemd-networkd-tests.py", line 5919, in test_invalid_captive_portal
    self.wait_address('client', '2002:da8:1:99:1034:56ff:fe78:9a00/64', ipv='-6', timeout_sec=10)
  File "/build/test/test-network/systemd-networkd-tests.py", line 1163, in wait_address
    self.assertRegex(output, address_regex)
AssertionError: Regex didn't match: '2002:da8:1:99:1034:56ff:fe78:9a00/64' not found in ''
```

2024-08-14 20:35 UTC, merged

2024-08-15 09:44 UTC, ssahani commented
thank you!