doc: fix .ssh credential examples
systemd/systemd pull request #32325
Opened 2024-04-17 19:57 UTC by poettering

Let's create the .ssh dir with the right perms first.

Suggested by @gcb.

Fixes: #28172

2024-04-18 00:56 UTC, yuwata requested changes

2024-04-18 00:56 UTC, yuwata commented on docs/CREDENTIALS.md
> +        -smbios type=11,value=io.systemd.credential.binary:tmpfiles.extra=$(echo -e "d /root/.ssh 0750 root root -\nf~ /root/.ssh/authorized_keys 700 root root - $(ssh-add -L | base64 -w 0)" | base64
700??? Why not 600?

2024-04-18 00:56 UTC, yuwata commented on man/tmpfiles.d.xml
> +      <programlisting>-smbios type=11,value=io.systemd.credential.binary:tmpfiles.extra=$(echo -e "d /root/.ssh 0750 root root -\nf~ /root/.ssh/authorized_keys 700 root root - $(ssh-add -L | base64 -
Also here.

2024-04-18 07:30 UTC, poettering commented on docs/CREDENTIALS.md
> +        -smbios type=11,value=io.systemd.credential.binary:tmpfiles.extra=$(echo -e "d /root/.ssh 0750 root root -\nf~ /root/.ssh/authorized_keys 700 root root - $(ssh-add -L | base64 -w 0)" | base64
uh, indeed

2024-04-18 07:30 UTC, poettering commented
force pushed new version. ptal

2024-04-18 07:43 UTC, yuwata approved these changes

2024-04-18 08:53 UTC, bluca approved these changes

2024-04-18 08:53 UTC, merged

2024-04-30 12:26 UTC, gcb commented
Thanks for addressing this! Makes downstream guides cleaner.

FWIIW, the loose permissions were kept from the original code. Wasn't sure there was a reason for it. Better all around now :+1: