networkd: Correct documentation for LinkLocalAddressing
systemd/systemd pull request #32472
Opened 2024-04-25 10:34 UTC by Geod24

```
LinkLocalAddressing accepts a boolean. This can be seen by looking at `link_local_address_family_from_strong(cont char *s)` in `src/network/netword-util.c#L102-108` which falls back to `address_family_from_string`, defined two lines above (L100) using `DEFINE_STRING_TABLE_LOOKUP_WITH_BOOLEAN`.
```

https://github.com/systemd/systemd/blob/68ee2ba1ee8813e4d5e8f9c933614d90b200b445/src/network/networkd-util.c#L100-L108

2024-04-25 11:42 UTC, Geod24 commented
CI failure on semaphore seems to be a timeout ?

2024-04-26 03:06 UTC, yuwata requested changes

2024-04-26 03:06 UTC, yuwata commented on man/systemd.network.xml
> +          and <option>ipv6</option>. An IPv6 link-local address is configured when <option>true</option>
Not a strict rule, but we usually prefer `yes` over `true`.

2024-04-26 03:06 UTC, yuwata commented on man/systemd.network.xml
> +          <para>Defaults to <option>false</option> when <varname>KeepMaster=</varname> or
`false` -> `no`.

2024-04-26 08:29 UTC, Geod24 commented
@yuwata : Changed true/false to yes/no

2024-04-26 08:36 UTC, yuwata requested changes

2024-04-26 08:36 UTC, yuwata commented on man/systemd.network.xml
> +          <para>Enables link-local address autoconfiguration. Accepts a Boolean, <option>ipv4</option>,
Boolean -> boolean

2024-04-26 08:36 UTC, yuwata commented on man/systemd.network.xml
> +          or <option>ipv6</option>. An IPv4 link-local address is configured when <option>no</option>
no -> yes

2024-04-26 15:16 UTC, Geod24 commented
@yuwata : Fixed

2024-04-27 04:55 UTC, yuwata approved these changes
LGTM. Thank you!

2024-04-27 10:55 UTC, merged