varlink: add ability to talk to remote ssh Varlink service
systemd/systemd pull request #32560
Opened 2024-04-29 14:19 UTC by poettering

So far our varlink client could connect to remote AF_UNIX sockets via SSH. This adds a 2nd SSH-based transport: invoke a binary remotely via ssh, and talk to it via stdin/stdout.

This is v257 material, don't bother with this for v256

2024-06-25 10:31 UTC, DaanDeMeyer commented on src/shared/varlink.c
> +
Spurious newline

2024-06-25 10:42 UTC, DaanDeMeyer commented on man/varlinkctl.xml
> +      this case the comman is invoked and the Varlink protocol spoken on the standard input and output of the
comman => command

2024-06-25 10:43 UTC, DaanDeMeyer commented on man/varlinkctl.xml
> +      this case the comman is invoked and the Varlink protocol spoken on the standard input and output of the
"Varlink protocol is spoken"

2024-06-25 10:44 UTC, DaanDeMeyer commented on src/shared/varlink.c
> +        r = strv_split_full(&cmdline, e + 1, /* serparators= */ NULL, EXTRACT_CUNESCAPE|EXTRACT_UNQUOTE);
"separators"

2024-06-25 10:55 UTC, DaanDeMeyer requested changes
This could really do with some kind of integration test.

A man page example would also help a lot in understanding how to use this.

Also, the title feels wrong in a way. This allows you to invoke a command on a remote host  and communicate with it using varlink. On its own it doesn't really allow you to talk to a running service on a remote host using varlink.

Shouldn't this also add systemd-varlink-bridge like we have systemd-stdio-bridge for D-Bus which connects to a varlink service running on a remote host?

2024-06-27 07:38 UTC, poettering commented
> Shouldn't this also add systemd-varlink-bridge like we have systemd-stdio-bridge for D-Bus which connects to a varlink service running on a remote host?

There's no need, we already support that. See varlinkctl(1) man page. You can already access remote services that are bound to some AF_UNIX support. This requires the new support for connecting to a remote AF_UNIX socket via "ssh -W". Only available since OpenSSH 9.4, which is really recent though.

systemd-stdio-bridge is a concept from a time where "ssh -W" didn't exist. I mean, we can't kill it for now, as older ssh versions are still popular. And maybe it even makes sense to keep after that, since it actually patches the negotation protocol of D-Bus to disable fd passing, since that doesn't work via ssh. (This concept like this doesn't exist in varlink anyway, hence no need for anything like this in a varlink world).

To summarize, with this PR we support two different things:

1. varlinkctl ssh-unix:hostxyz:/run/some/socket
2. varlinkctl ssh-exec:hostabc:/usr/bin/some/binary

And neither requires any particular tool on the other side to invoke, we just need the target socket or binary to talk to.

2024-06-27 09:37 UTC, poettering commented
rebased, addressed the issues, added examples to the varlinkctl man page and a CI test. ptal.

2024-06-27 09:38 UTC, DaanDeMeyer approved these changes

2024-06-27 10:47 UTC, merged