Add TEST-06-SELINUX to mkosi integration tests
systemd/systemd pull request #32588
Opened 2024-04-30 17:55 UTC by richardmaw-codethink

This is based on https://github.com/systemd/systemd/pull/32540

2024-04-30 19:03 UTC, DaanDeMeyer requested changes
Instead of having `--setup-selinux`, can we just have a generic `kernel_command_line` field in `test_params` which we modify in TEST-06-SELINUX/meson.build?

2024-05-02 07:46 UTC, richardmaw-codethink commented
> Instead of having `--setup-selinux`, can we just have a generic `kernel_command_line` field in `test_params` which we modify in TEST-06-SELINUX/meson.build?

Could even go the whole way and do it as `test_params += {'mkosi_args' : ['--kernel-command-line-extra=...']}` if we want to keep the number of explicitly implemented features down.

2024-05-02 08:48 UTC, DaanDeMeyer commented
> > Instead of having `--setup-selinux`, can we just have a generic `kernel_command_line` field in `test_params` which we modify in TEST-06-SELINUX/meson.build?
> 
> Could even go the whole way and do it as `test_params += {'mkosi_args' : ['--kernel-command-line-extra=...']}` if we want to keep the number of explicitly implemented features down.

Yeah that's actually better for now, let's do it like that.

2024-05-04 18:48 UTC, bluca approved these changes

2024-05-04 18:48 UTC, merged