network/tc: Avoid concurrent set modification in tclass_drop()/qdisc_drop()
systemd/systemd pull request #32611
Opened 2024-05-01 12:46 UTC by DaanDeMeyer

With the current algorithm, we can end up removing entries from the qdisc/tclass sets while having multiple open iterators over the sets at various positions which leads to assertion failures in the hashmap logic as it's only safe to remove the "current" entry.

To avoid the problem, let's split up marking and dropping of tclasses and qdiscs. First, we recursively iterate tclasses/qdiscs and mark all that need to be removed. Next, we iterate once over tclasses and qdiscs and remove all marked entries.

2024-05-01 14:03 UTC, yuwata requested changes
Thank you. The basic change looks good, but CIs are unhappy.

2024-05-01 14:03 UTC, yuwata commented on src/network/tc/tclass.c
> +TClass *tclass_drop(TClass *tclass) {
Nitpick, but `TClass* tclass_drop()` rather than `TClass *tclass_drop()`, please.

2024-05-01 14:03 UTC, yuwata commented on src/network/tc/qdisc.c
> +        link_tclass_drop_marked(qdisc->link);
`qdisc` may be invalidated here. So, please take a reference of `qdisc->link` before calling `_drop_marked()`.

2024-05-01 14:03 UTC, yuwata commented on src/network/tc/tclass.c
> +        link_qdisc_drop_marked(tclass->link);
Also here.

2024-05-01 14:04 UTC, yuwata commented
Could you mention the previous offending commit 632d321050f58fe1b5bed7cfe769d212377c0301 in the commit message?

2024-05-01 14:05 UTC, yuwata commented
The commit 632d321050f58fe1b5bed7cfe769d212377c0301 has been backported to stable repository. Hence, this also needs to be backported.

2024-05-01 14:23 UTC, yuwata commented
> Addressed comments and added two commits required to run systemd-networkd-tests.py in mkosi, PTAL!

Nice! Thank you!

2024-05-01 14:23 UTC, yuwata approved these changes

2024-05-01 14:26 UTC, bluca commented on test/meson.build
> +                        rsync_r = rsync.full_path() + ' -rLpt --exclude .gitattributes -- "@0@" "${DESTDIR:-}@1@"'
if I understand correctly the comment above, rsync was added specifically to copy symlinks, and the default in install-subdir is to follow them, so can this be dropped entirely then?

2024-05-01 14:27 UTC, DaanDeMeyer commented on test/meson.build
> +                        rsync_r = rsync.full_path() + ' -rLpt --exclude .gitattributes -- "@0@" "${DESTDIR:-}@1@"'
@bluca It depends on whether we still get the ugly warning or not

2024-05-01 14:41 UTC, bluca commented on test/meson.build
> +                        rsync_r = rsync.full_path() + ' -rLpt --exclude .gitattributes -- "@0@" "${DESTDIR:-}@1@"'
ok, we can revisit it later

2024-05-01 15:51 UTC, merged

2024-05-09 07:50 UTC, keszybz commented
> The commit [632d321](https://github.com/systemd/systemd/commit/632d321050f58fe1b5bed7cfe769d212377c0301) has been backported to stable repository. Hence, the last commit also needs to be backported.

Thanks. Done.