sd-netlink: Fix build against older kernel headers
systemd/systemd pull request #32646
Opened 2024-05-03 22:55 UTC by ffainelli

NFPROTO_NETDEV was added with commit
e687ad60af09010936bbd0b2a3b5d90a8ee8353c ("netfilter: add netfilter ingress hook after handle_ing() under unique static key") which is present in in Linux v4.2 and newer. Provide a definition if we do not have one already.

2024-05-04 05:15 UTC, yuwata requested changes
Please define that in src/basic/missing_xyz.h, or copy relevant header file from the kernel tree into src/basic/kernel.

2024-05-06 09:10 UTC, poettering commented
Hmm, we copy most netfilter headers into our tree these days, see src/basic/linux/netfilter/*.h

Maybe we are just missing one more header to copy in?

2024-05-06 17:39 UTC, ffainelli commented
Yes, good point it would appear that netfilter.h has not been copied. V2 incoming.

2024-05-09 13:27 UTC, bluca approved these changes

2024-05-09 13:27 UTC, merged

2024-05-10 00:39 UTC, yuwata commented
Belated LGTM. Thanks.