machinectl/vmspawn: implement machinectl shell for vm class machines
systemd/systemd pull request #32701
Opened 2024-05-07 21:51 UTC by bluca

Cannot push to org, so continuing here from https://github.com/systemd/systemd/pull/32208

2024-05-07 22:24 UTC, evverx commented
Can I ask why instead of stabilizing the release and addressing known regressions like https://github.com/systemd/systemd/issues/30421 introduced by sloppy merges new features with no tests are being pushed in a hurry?

2024-05-08 06:28 UTC, YHNdnzj commented
Yeah, since we've already taken over the PR, there's genuinely no need to rush it in. I'll move the milestone to v257.

2024-05-08 08:05 UTC, bluca commented
> Yeah, since we've already taken over the PR, there's genuinely no need to rush it in. I'll move the milestone to v257.

See yesterday's chat

2024-05-08 08:14 UTC, YHNdnzj commented
> > Yeah, since we've already taken over the PR, there's genuinely no need to rush it in. I'll move the milestone to v257.
> 
> See yesterday's chat

I've read that. But there's no clear indication that we need to get this in for v256, and when you asked "anyone disagrees" I wasn't there...

2024-05-08 08:32 UTC, DaanDeMeyer commented
This breaks registering vmspawn vms when using newer vmspawn with older machined, which is pretty much every vmspawn invocation right now. The varlink method will not be available and registering will fail.

2024-05-08 08:36 UTC, YHNdnzj commented on src/shared/varlink-io.systemd.Machine.c
> +#include "varlink-idl.h"
Not sorted.

2024-05-08 08:45 UTC, YHNdnzj commented on src/vmspawn/vmspawn.c
> +                r = machine_credential_set(&arg_credentials,
break line before `&arg_credentials`?

2024-05-08 08:45 UTC, YHNdnzj commented on src/vmspawn/vmspawn.c
> +                                "ExecStart=/usr/sbin/sshd -i -o 'AuthorizedKeysFile=${CREDENTIALS_DIRECTORY}/ssh.ephemeral-authorized_keys-all .ssh/authorized_keys'\n"
```suggestion
                                "ExecStart=/usr/sbin/sshd -i -o 'AuthorizedKeysFile=%d/ssh.ephemeral-authorized_keys-all .ssh/authorized_keys'\n"
```

2024-05-08 08:45 UTC, YHNdnzj commented on src/shared/json.c
> +
please drop the empty line

2024-05-08 09:25 UTC, bluca commented
Rebased on top of https://github.com/systemd/systemd/pull/32709

2024-05-08 09:30 UTC, evverx commented
> See yesterday's chat

Can anyone copy-paste that here for mere mortals to see?

2024-05-08 09:51 UTC, evverx commented
Either way I guess the question isn't going to be answered. It answers my question too in a different way.

2024-05-08 10:17 UTC, YHNdnzj commented
> > See yesterday's chat
> 
> Can anyone copy-paste that here for mere mortals to see?

Basically: this is a contract work from STF, and payment requires all the PRs to be merged.

I think there should have been a better way to communicate that these are optional and the payment should be done nonetheless, but realistically I'm never involved in all these contract works so I can't tell.

2024-05-08 10:44 UTC, evverx commented
@bluca can you please stop deleting comments? That's not how open source projects are supposed to operate.

I've found the feedback form on the STF site and I'll contact them. I was going to do that anyway in the context of their bug resilience program. Thanks to the recent improvements (which I have no problem with) and miscommunications (which are problematic) I pulled out my downstream fuzzing infrastructure (even though it isn't broken yet) and they'd probably be interested to see the spreadsheets showing how much they should invest in the infrastructure alone to even cover the basics. Just to be clear I don't think it's STF fault. They were probably be misled into thinking that there is some actual upstream infrastructure where use-after-frees appear out of thin air.

2024-05-08 12:41 UTC, bluca commented
Rebased and picked changes from https://github.com/systemd/systemd/pull/32482

2024-05-08 15:37 UTC, keszybz requested changes
Since we're supposed to merge this after -rc1, the commits must include a solid explanation what is being done and why and what the implications are.

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +                        return log_oom();
```C
char vm_address[STRLEN("vsock/") + DECIMAL_STR_MAX(unsigned)];
xsprintf(vm_address, "vsock/%u", child_cid);
```

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn-register.c
> +        r = varlink_connect_address(&vl, "/run/systemd/machine/io.systemd.Machine");
Please explain in the commit message why a D-bus call is replaced by a varlink call.

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +                                "ExecStart=/usr/sbin/sshd -i -o 'AuthorizedKeysFile=%d/ssh.ephemeral-authorized_keys-all .ssh/authorized_keys'\n"
Maybe drop `/usr/sbin/`? Split-bin is deprecated.

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +static int bus_open_in_machine(sd_bus **ret, unsigned cid, unsigned port, const char *private_key_path) {
This is `static` and unused, so the compilation will at least cause a warning. Please merge this the commit that adds the use.

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +        /* Backup method to shutdown the VM when D-BUS access over SSH is not available */
"shut down"

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +                /* if we don't know the SSH information fallback to signalling qemu */
I don't grok this sentence.

2024-05-08 15:37 UTC, keszybz commented on src/vmspawn/vmspawn.c
> +        SSHInfo ssh_info;
Maybe add a comment that this is only used conditionally, but must survive until the function finishes? I think it'd be better to even move this before definition of `bus`, to underline the fact that it needs to survive longer.

2024-05-09 08:22 UTC, keszybz commented
Code LGTM.

I think it's fine to merge this now. The first commit is a fix, and the other two are relatively simple plumbing changes that will make `machinectl shell` much more useful. The work of vmspawn and related parts is a big part of this release, so we want to make it work as well as we can. We're after -rc1, but I think this a change of this magnitude is reasonable if it complements some changes that were done earlier in the cycle.

2024-05-09 08:23 UTC, keszybz commented
Ubunutautopkgtests are busted.

2024-05-09 08:23 UTC, merged

2024-05-10 02:44 UTC, evverx commented
Looking at
```sh
ssh: Could not resolve hostname vsock/2747562528: Name or service not known
Failed to get init process of VM: Transport endpoint is not connected
```
I'm not sure stuff should get stuck like that for several hours but OK.