cryptsetup: allow customizing cache behavior
systemd/systemd pull request #32761
Opened 2024-05-11 08:45 UTC by kszczek

The new "password-cache" option allows customizing behavior of the ask-password module in regards to caching credentials in the kernel keyring. There are 3 possible values for this option:
  * `read-only` - look for credentials in kernel keyring before asking
  * `on` - same as read-only, but also save credentials input by user
  * `off` - disable keyring credential cache

Currently the cache is forced upon the user and this can cause issues. For example, if user wants to attach two volumes with two different FIDO2 tokens in a quick succession, the attachment operation for the second volume will use the PIN cached from the first FIDO2 token, which of course will fail and since tokens are only attempted once, this will cause fallback to a password prompt.

2024-05-11 09:13 UTC, kszczek commented
Overlooked an issue with the default value for PKCS#11 tokens, fixed it. Sorry for the noise.

2024-05-12 01:58 UTC, yuwata requested changes
Several superficial comments.

2024-05-12 01:58 UTC, yuwata commented on man/crypttab.xml
> +        <option>password-cache=yes</option>.</para>
`Defaults to <literal>yes</literal>.`

2024-05-12 01:58 UTC, yuwata commented on man/crypttab.xml
> +        password/PIN before requesting one interactively. If set to true, in addition to
`If set to <literal>yes</literal>, in addition to`

2024-05-12 01:58 UTC, yuwata commented on man/systemd-cryptsetup.xml
> +      <option>read-only</option>, the kernel keyring is then checked for a suitable cached password from
`<option>` -> `<literal>`

2024-05-12 01:58 UTC, yuwata commented on man/systemd-cryptsetup.xml
> +      <listitem><para>If the <varname>password-cache</varname> option is set to <option>yes</option> or
Please suffix with `=`, that is `<varname>password-cache=</varname>`.

2024-05-12 01:58 UTC, yuwata commented on src/cryptsetup/cryptsetup.c
> +                        arg_ask_password_flags &= ~(ASK_PASSWORD_ACCEPT_CACHED|ASK_PASSWORD_PUSH_CACHE);
This works, but usually, handling inference with other options should be handled later.
So, please move this to `parse_crypt_config()`.

2024-06-05 19:14 UTC, kszczek commented
Rebased.

2024-06-13 14:18 UTC, poettering commented on src/cryptsetup/cryptsetup.c
> +                        SET_FLAG(arg_ask_password_flags, ASK_PASSWORD_PUSH_CACHE, r);
you can merge these two lines:

```c
SET_FLAG(arg_ask_password_flags, ASK_PASSWORD_ACCEPT_CACHED|ASK_PASSWORD_PUSH_CACHE, r);
```c

2024-06-13 14:24 UTC, poettering commented
lgtm, just one trivial nitpicj.

2024-06-13 14:24 UTC, poettering commented
the cryptsetup loop was recently reworked, can you make sure this works as intended still?

2024-06-17 01:32 UTC, kszczek commented
Yup, just tested and can confirm that `password-cache` option works as expected with all the code paths listed below, the table also lists the default behavior of each code path before and after this PR.

| Path | Old Cache Read | Old Cache Write | New Cache Read | New Cache Write |
| --- | --- | --- | --- | -- |
| built-in tpm2 | No | No | **Yes** | **Yes** |
| built-in fido2 | Yes | Yes | Yes | Yes |
| build-in pkcs11 | No | No | No | No |
| password/recovery | Yes | Yes | Yes | Yes |
| plugin auto | Yes | Yes | Yes | Yes |
| plugin tpm2 | Yes | Yes | Yes | Yes |
| plugin fido2 | Yes | Yes | Yes | Yes |
| plugin pkcs11 | No | No | No | No |

2024-06-20 04:11 UTC, yuwata commented
All requests are addressed by the author. The green label is upgraded. @poettering Could you take a final look?

2024-06-27 11:00 UTC, bluca approved these changes

2024-06-27 11:00 UTC, merged