journal-importer: Consider ECONNRESET as EOF
systemd/systemd pull request #32853
Opened 2024-05-15 19:40 UTC by DaanDeMeyer

Otherwise we log a noisy error when we get ECONNRESET.

2024-05-15 20:31 UTC, yuwata requested changes

2024-05-15 20:31 UTC, yuwata commented on src/shared/journal-importer.c
> +                        if (errno == ECONNRESET)
`ERRNO_IS_DISCONNECT(errno)` ?
Also, showing debugging log is better, I think.

2024-05-15 20:31 UTC, yuwata commented on src/shared/journal-importer.c
> +                        if (errno == ECONNRESET)
Also here.

2024-05-16 09:08 UTC, bluca approved these changes

2024-05-16 09:15 UTC, YHNdnzj approved these changes

2024-05-16 09:15 UTC, YHNdnzj commented on src/shared/journal-importer.c
> +                                log_debug("Got disconnect for importer %s", strna(imp->name));
log_debug_errno to keep errno in structured log?

2024-05-16 09:15 UTC, YHNdnzj commented on src/shared/journal-importer.c
> +                                log_debug("Got disconnect for importer %s", strna(imp->name));
Also, please add a period

2024-05-16 09:15 UTC, YHNdnzj commented on src/shared/journal-importer.c
> +                                log_debug("Got disconnect for importer %s", strna(imp->name));
ditto

2024-05-16 09:44 UTC, yuwata approved these changes

2024-05-16 11:23 UTC, merged