added hwdb rules for micmute and power button on Acer Nitro AN 515-58
systemd/systemd pull request #32867
Opened 2024-05-16 15:50 UTC by leomonta

Added hwdb rules needed for the microphone mute button (Fn+f7) and the power button in the 60-keyboard.hwdb

2024-05-16 20:41 UTC, yuwata requested changes

2024-05-16 20:41 UTC, yuwata commented on hwdb.d/60-keyboard.hwdb
> +evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAcer*:pnNitro*AN*515-58:*
`pnNitro*AN*515-58:*` -> `pnNitro*AN*515-58:pvr*`
Otherwise, `AN` and `515-58` can be in other field.

2024-05-31 12:47 UTC, leomonta reviewed
Applied requested changes

2024-06-01 02:28 UTC, yuwata approved these changes

2024-06-01 02:29 UTC, merged