basic: Add BCACHEFS magic
systemd/systemd pull request #33108
Opened 2024-05-30 22:02 UTC by cpackham-atlnz

Import magic.h from Linux 6.9 to get the definition of BCACHEFS_SUPER_MAGIC. Update filesystems-gperf.gperf to add knowledge of bcachefs.

This fixes the following error building against a bleeding edge kernel.
```
src/basic/meson.build:234:8: ERROR: Problem encountered: Unknown filesystems defined in kernel headers:

Filesystem found in kernel header but not in filesystems-gperf.gperf: BCACHEFS_SUPER_MAGIC
```

2024-05-30 22:44 UTC, bluca approved these changes

2024-05-30 23:56 UTC, yuwata requested changes

2024-05-30 23:56 UTC, yuwata commented on src/basic/linux/magic.h
> +#define BCACHEFS_SUPER_MAGIC	0xca451a4e
Please use missing_magic.h

2024-05-31 00:00 UTC, yuwata commented
BTW, the change is already waiting in #33034. @bluca Is #33034 too big for v256? That may look so, but all changes in the PR are actually trivial, like hwdb update that we always do before release.

2024-05-31 00:08 UTC, cpackham-atlnz commented
@yuwata sorry I missed your PR I did do a quick search but obviously the github search doesn't catch the content of a PR (it does seem to find my PR because I mention BCACHEFS_SUPER_MAGIC in the message).

2024-05-31 00:29 UTC, yuwata commented
> @yuwata sorry I missed your PR I did do a quick search but obviously the github search doesn't catch the content of a PR (it does seem to find my PR because I mention BCACHEFS_SUPER_MAGIC in the message).

No problem. By moving the definition to missing_magic.h, then this can be merged earlier. After this is merged, I will rebase my PR on this.

2024-05-31 00:41 UTC, cpackham-atlnz commented
Updated per @yuwata 's request. When #33034 is merged the change in missing_magic.h can be dropped

2024-05-31 00:45 UTC, yuwata approved these changes
LGTM. Thank you!

2024-05-31 02:14 UTC, merged

2024-05-31 09:51 UTC, bluca commented
> BTW, the change is already waiting in #33034. @bluca Is #33034 too big for v256? That may look so, but all changes in the PR are actually trivial, like hwdb update that we always do before release.

Given it doesn't fix a bug and compilation with kernel headers is often troublesome on weird architectures, let's wait for the next cycle