homed: flush fscrypt key on lock/deactivate
systemd/systemd pull request #33189
Opened 2024-06-04 02:19 UTC by bluca

The fscrypt key is added to the user keyring, and needs to be flushed out too.

Fixes https://github.com/systemd/systemd/issues/33138

2024-06-04 12:04 UTC, poettering commented on src/home/homework-fscrypt.c
> +                }
we have this same loop twice now, can we please get a helper call for this, i.e. add a helper to src/shared/keyring-util.c called keyring_describe() or so, that does this describe loop.

2024-06-04 12:05 UTC, poettering commented
I am not sure i grok why this is even necessary. i.e. the per-user keyring should go away automatically when the kernel does not see any process owned by the keyring owner's key anymore.

hence, how come the keyring remains pinned for the original poster?

2024-06-04 12:06 UTC, poettering commented
I don't think we need to hurry this into v256. This isn't really a regression.

2024-06-04 12:07 UTC, bluca commented
> I am not sure i grok why this is even necessary. i.e. the per-user keyring should go away automatically when the kernel does not see any process owned by the keyring owner's key anymore.
> 
> hence, how come the keyring remains pinned for the original poster?

I don't know - but it's easily reproducible, it is there with the home deactivated and the user logged out

2024-06-04 12:08 UTC, bluca commented
> I don't think we need to hurry this into v256. This isn't really a regression.

It isn't, however one of the key selling point of homed is to drop private key material from memory when the user is logged out, so I thought it would be good to fix anyway since it's not too difficult. It's also self-contained to homed+fscrypt and all done in a forked process, so should be as safe as it could be.

2024-06-04 12:11 UTC, poettering commented
> I don't know - but it's easily reproducible, it is there with the home deactivated and the user logged out

well, what i am saying is that there probably is something else wrong here, if the the thing doesn#t get cleaned up automatically by the kernel

2024-06-04 12:14 UTC, poettering commented on src/home/homework-fscrypt.c
> +                        c = keyctl(KEYCTL_DESCRIBE, ((key_serial_t *) keyring)[i], (unsigned long) tuple, c, 0);
i think we should handle ENOKEY gracefully here (i.e. just silently skip over it, after all we might race against something else that deletes keys)

2024-06-04 12:14 UTC, poettering commented on src/home/homework-fscrypt.c
> +                                log_debug_errno(r,
first arg should be errno

2024-06-04 12:15 UTC, poettering commented on src/home/homework-fscrypt.c
> +                        log_debug_errno(r,
errno

2024-06-04 12:23 UTC, poettering commented
So I am pretty sure there's some other bug lurking somewhere if the kernel doesn't clean this up automatically, but it might be ok to clean-up a user's keyring explicitly if we assume the user is fully logged out.

But I am pretty sure this should be dumbed down, and not be placed in homed, but logind, i.e. in user_finalize() at the same place where we call clean_ipc_by_uid().

This should really delete *all* keys of the user, i.e. fire a "clear" operation (KEYCTL_CLEAR).

2024-06-04 12:32 UTC, bluca commented
> So I am pretty sure there's some other bug lurking somewhere if the kernel doesn't clean this up automatically, but it might be ok to clean-up a user's keyring explicitly if we assume the user is fully logged out.
> 
> But I am pretty sure this should be dumbed down, and not be placed in homed, but logind, i.e. in user_finalize() at the same place where we call clean_ipc_by_uid().
> 
> This should really delete _all_ keys of the user, i.e. fire a "clear" operation (KEYCTL_CLEAR).

Doing this in logind doesn't help with `homectl activate` -> `homectl deactivate` though, no? This specific issue is about the combination of homed+fscrypt, and it's homed that puts this key in the keyring, so it seems right to me that it's homed that removes it once it is not needed, just like it removes the other stuff from the keyrings. If issues with other things handled by logind show up then we can handle it there and then, but I think this fix should be targeted to this specific bug.

2024-06-06 10:24 UTC, keszybz commented on src/home/homework-fscrypt.c
> +                        FORK_RESET_SIGNALS|FORK_CLOSE_ALL_FDS|FORK_DEATHSIG_SIGTERM|FORK_LOG|FORK_WAIT|FORK_REOPEN_LOG,
Indentation is off here.

2024-06-06 10:26 UTC, keszybz commented on src/home/homework-fscrypt.c
> +                                       h->uid);
Putting `r` on a separate line makes those logging calls very vertically spread out. We generally don't do that. It'd be nicer to make merge the first two lines.

The message should be "Failed to fork".

2024-06-06 10:27 UTC, keszybz commented on src/home/homework-fscrypt.c
> +        r = fully_set_uid_gid(
It'd be nicer to move the implementation of child into a separate function that does a normal negative return. All those `_exit(EXIT_FAILURE)` calls are overly verbose and error-prone.

2024-06-06 11:41 UTC, keszybz requested changes

2024-06-06 11:41 UTC, keszybz commented on src/home/homework-fscrypt.c
> +                                user_record_gid(h));
That's even worse now. What's wrong with
```C
return log_debug_errno(r, "Failed to change UID/GID to " UID_FMT "/" GID_FMT ": %m",
                       h->uid, user_record_gid(h));
```
?

2024-06-06 11:41 UTC, keszybz commented on src/home/homework-fscrypt.c
> +                        NULL);
Indentation still off.

2024-06-06 11:41 UTC, keszybz commented on src/home/homework-fscrypt.c
> +                                        h->uid);
No, don't split message strings like this.

2024-06-06 11:41 UTC, keszybz commented on src/home/homework.c
> +                r = home_flush_keyring_fscrypt(h);
That function logs, so just `(void) home_flush_keyring_fscrypt(h)`.

2024-06-06 11:42 UTC, keszybz commented
This looks better, but the (automatic, I assume) formatting is still rather ugly.

2024-06-06 11:56 UTC, bluca commented
> This looks better, but the (automatic, I assume) formatting is still rather ugly.

Updated - but the issue is that this changes depending on who's reviewing. Some want multiple parameters per line starting on the same line, some want one parameter per line starting on the next line. We should really just get clang-formatter going and enforce it via CI and let that be the end of it...

2024-06-06 12:01 UTC, keszybz commented
I think you're looking at this from the wrong angle. Code is something that is read much more than it is written. Thus, self-consistent, legible, clean code is worth a bit of extra formatting effort. Clang-format and other tools can be a useful tool, especially for beginners and a new codebase, but are not powerful enough for us.

FWIW, people tried to build a clang format specification before, and it always fell short.

2024-06-06 12:08 UTC, DaanDeMeyer commented
> I think you're looking at this from the wrong angle. Code is something that is read much more than it is written. Thus, self-consistent, legible, clean code is worth a bit of extra formatting effort. Clang-format and other tools can be a useful tool, especially for beginners and a new codebase, but are not powerful enough for us.
> 
> FWIW, people tried to build a clang format specification before, and it always fell short.

I would much rather have us use clang-format as well. I couldn't care less that it isn't always perfect if only to save both longterm and new contributors the hassle of having to deal with formatting.

2024-06-06 12:13 UTC, bluca commented
> > I think you're looking at this from the wrong angle. Code is something that is read much more than it is written. Thus, self-consistent, legible, clean code is worth a bit of extra formatting effort. Clang-format and other tools can be a useful tool, especially for beginners and a new codebase, but are not powerful enough for us.
> > FWIW, people tried to build a clang format specification before, and it always fell short.
> 
> I would much rather have us use clang-format as well. I couldn't care less that it isn't always perfect if only to save both longterm and new contributors the hassle of having to deal with formatting.

Exactly - the problem is that "self-consistent, legible, clean" are in the eye of the beholder, so depending on who happens to review a PR, requirements change, which is not great. If it's enforced by a tool, then you cannot argue against the tool (well you can try, but the tool will just look at you with a funny face)

2024-06-06 12:13 UTC, keszybz commented
That'd mean having ugly formatting. If people want to use clang format or some other helper, that's fine. It's up to them, as long as they fix the most egregious shortcomings. But making this enforced is a completely different thing.  That'd force people who want and can do better to commit badly formatted code.

2024-06-06 12:33 UTC, poettering commented on src/home/homework-fscrypt.c
> +        r = keyring_read(KEY_SPEC_USER_KEYRING, (void **) &keyring, &keyring_size);
the cast seems unnecessary

2024-06-06 12:34 UTC, poettering commented on src/home/homework-fscrypt.c
> +        n_keys = keyring_size / sizeof(key_serial_t);
maybe add: `assert(keyring_size % sizeof(key_serial_t) == 0)`

2024-06-06 12:44 UTC, poettering commented on src/home/homework.c
> +        if (user_record_storage(h) == USER_FSCRYPT && uid_is_valid(h->uid))
please move the uid_is_valid() check into home_flush_keyring_fscrypt()

2024-06-06 12:45 UTC, poettering commented on src/home/homework-fscrypt.c
> +        assert(h);
add: 
```c
assert(user_record_storage(h) == USER_FSCRYPT));
```

2024-06-06 12:46 UTC, poettering commented on src/home/homework-fscrypt.c
> +                return log_debug_errno(r, "Failed to fork to delete fscrypt key from keyring: %m");
you already set FORK_LOG, hence no need to log again, just drop this and do a simple `return r`

2024-06-06 12:46 UTC, poettering commented on src/home/homework-fscrypt.c
> +                                       h->uid, user_record_gid(h));
should be at log_error_errno()

2024-06-06 12:48 UTC, poettering commented on src/home/homework-fscrypt.c
> +                return log_debug_errno(r, "Failed to read the keyring of user " UID_FMT ": %m", h->uid);
log_error_errno

2024-06-06 12:48 UTC, poettering commented on src/home/homework-fscrypt.c
> +                        return log_debug_errno(r, "Failed to describe key id %d: %m", *key);
also LOG_ERR level

2024-06-06 12:48 UTC, poettering commented on src/home/homework-fscrypt.c
> +                                        description);
ditto here (and everywhere else, i.e. hte functions in homework-fscrypt.c all log on their own)

2024-06-06 12:49 UTC, poettering commented on src/home/homework-fscrypt.c
> +                log_debug("Deleted encryption key with id '%d' from the keyring of user " UID_FMT ".", *key, h->uid);
this one is ok to stay at debug level

2024-06-06 12:56 UTC, poettering commented
lgtm

2024-06-06 15:34 UTC, merged