hwdb performance improvements
systemd/systemd pull request #33205
Opened 2024-06-04 22:32 UTC by q66

After finding that hwdb.bin generation is incredibly slow on musl (~30s on a fast x86_64 machine) I went to figure out why. Turns out that strbuf reallocs on every string insertion.

Doing so is bad, even on glibc; the only reason it happens to be fast enough on glibc is due to a particular quirk of glibc's memory allocator. On other allocators, it makes the code spend ages in memory allocation and particularly memcpy, as the string store can grow very large (`hwdb.bin` is ~12M on most machines and most of it is the serialized string store).

I chose the strategy of reserving 16M. This is virtual memory, so it should be okay. On most systems this will mean there will be only one big allocation and that is during the initial reservation. If not, it will still fall back on reallocation but it will double the capacity instead of just adding a bit more.

After the changes, the hwdb only now takes ~1 second on the same machine.

2024-06-04 23:20 UTC, bluca commented on src/basic/strbuf.c
> +        if ((str->len + len + 1) > str->cap) {
check GREEDY_REALLOC it should be usable here to do the same

2024-06-05 05:19 UTC, yuwata requested changes
Yeah, please use `GREEDY_REALLOC()` and friends.

2024-06-06 11:31 UTC, q66 commented
what's the benefit of using GREEDY_REALLOC here? as far as i can tell one still needs to do the capacity tracking for this to work correctly; other than that, GREEDY_REALLOC adds a bunch of internal logic that seems fairly unnecessary

2024-06-06 11:32 UTC, bluca commented
As a coding style rule we reuse internal interfaces, rather than creating new duplications for each use case

2024-06-06 11:34 UTC, q66 commented
okay, but unless i am missing something, this basically involves replacing the `realloc` call with a `GREEDY_REALLOC` call; i don't see a way to simplify any of the other code, unless i am missing something about how it's meant to be used?

2024-06-06 11:37 UTC, q66 commented
well, i guess since it requests `need * 2`, i can remove the multiplication; that seems to be about it, though

2024-06-06 11:41 UTC, bluca commented
The suggestion is to drop the new logic, and instead just swap the existing realloc with a GREEDY_REALLOC. This does an exponential increase, so that there's no need to reserve in advance, and it will get to where it needs to with a few calls.

2024-06-06 11:44 UTC, q66 commented
ah, i guess it does; i misunderstood the behavior a bit

i just tested it with just the realloc replaced and indeed the performance issue is gone

2024-06-06 11:47 UTC, q66 commented
alright, this should be sufficient then

2024-06-06 11:52 UTC, bluca approved these changes

2024-06-11 05:11 UTC, yuwata approved these changes

2024-06-12 07:23 UTC, closed without merging