network: sd-radv - Allow to set the MTU option is used in Router Adve…
systemd/systemd pull request #33360
Opened 2024-06-16 13:27 UTC by ssahani

…rtisement

closes https://github.com/systemd/systemd/issues/33160

2024-06-16 20:59 UTC, polarina commented on man/systemd.network.xml
> +          <para>Specifies the size of the peakrate bucket. When suffixed with K, M, or G, the specified
Typo? Peakrate bucket?

2024-06-17 09:19 UTC, poettering commented on man/systemd.network.xml
> +          <xi:include href="version-info.xml" xpointer="v256"/>
256 is already released. please update to v257

2024-06-17 09:20 UTC, poettering commented
Shouldn't we have some mechanism to copy the value from out own configured MTU for the link? for this and the dhcp server, it seems it makes a ton of sense, to be able to propagate our setting to the clients, to have a single source of truth.

2024-06-17 09:21 UTC, poettering commented
i.e. maybe MTUBytes=auto or MTUBytes=copy or so?

2024-07-21 17:43 UTC, bluca approved these changes
Could you please add some minimal tests for this in test/test-network/systemd-networkd-tests.py ?

2024-07-21 17:43 UTC, bluca commented on man/systemd.network.xml
> +          router advertisement MTU. Defaults to<literal>auto</literal>.</para>
missing space before <literal>

2024-08-02 05:56 UTC, yuwata requested changes
Sorry for late review.

Please add test cases.

2024-08-02 05:56 UTC, yuwata commented on src/network/networkd-radv.c
> +                r = sd_radv_set_mtu(link->radv, link->network->router_mtu_auto ? link->mtu : link->network->router_mtu);
I think this should be IPv6 MTU rather than link MTU.

2024-08-02 05:56 UTC, yuwata commented on src/network/networkd-radv.c
> +                return config_parse_mtu(unit, filename, line, section, section_line, lvalue, ltype, rvalue, data, userdata);
There is no way to disable emitting MTU once it is enabled. Also, the auto flag needs to be disabled when a number is specified:
```c
if (isempty(rvalue)) {
        network->router_mtu_auto = false;
        return 0;
}

if (streq(rvalue, "auto")) {
        network->router_mtu_auto = true;
        return 0;
}

r = config_parse_mtu(...);
if (r <= 0)
        return r;

network->router_mtu_auto = false;
return 0;
```

2025-10-10 18:04 UTC, closed without merging