mountpoint-util: do not assume symlinks are not mountpoints
systemd/systemd pull request #33496
Opened 2024-06-26 16:12 UTC by YHNdnzj

They very much can be with the new mount API.

2024-06-26 16:14 UTC, YHNdnzj commented
So I really think we should reconsider how we treat symlinks across the codebase. The outdated practice of assuming symlinks aren't mountpoints or always canonicalizing before mounting would no longer work well under the new mount API.

2024-06-27 09:42 UTC, poettering commented
Hmm, I am pretty sure this is wrong. With the new mount api you can overmount symlinks, but you cannot overmount inodes with symlinks.

are you sure this actually works?

2024-06-27 10:55 UTC, YHNdnzj commented
> Hmm, I am pretty sure this is wrong. With the new mount api you can overmount symlinks, but you cannot overmount inodes with symlinks.
> 
> are you sure this actually works?

Added a test case which illustrates how this would work.

2024-06-27 12:43 UTC, DaanDeMeyer requested changes

2024-06-27 12:43 UTC, DaanDeMeyer commented on src/test/test-mountpoint-util.c
> +        assert_se(fd >= 0);
`ASSERT_OK_ERRNO` should be used here.

2024-06-27 12:43 UTC, DaanDeMeyer commented on src/test/test-mountpoint-util.c
> +        assert_se(mfd >= 0);
Ditto

2024-06-27 12:43 UTC, DaanDeMeyer commented on src/test/test-mountpoint-util.c
> +        assert_se(rfd >= 0);
Ditto

2024-07-02 08:07 UTC, bluca approved these changes

2024-07-02 08:07 UTC, merged