Hashmap ensure replace
systemd/systemd pull request #33536
Opened 2024-06-28 15:22 UTC by teknoraver

Add a helper to replace hashmap members while ensuring it's allocated.

This helper is pulled from PR #32212

2024-06-28 16:43 UTC, DaanDeMeyer requested changes

2024-06-28 16:43 UTC, DaanDeMeyer commented on src/test/test-hashmap-plain.c
> +        char *s;
I would get rid of this variable and just inline every call to hashmap_get() into the assertion

2024-06-28 16:43 UTC, DaanDeMeyer commented on src/test/test-hashmap-plain.c
> +        assert_se(val1);
ASSERT_NOT_NULL

2024-06-28 16:43 UTC, DaanDeMeyer commented on src/test/test-hashmap-plain.c
> +        assert_se(val2);
ditto

2024-06-28 16:43 UTC, DaanDeMeyer commented on src/test/test-hashmap-plain.c
> +        assert_se(hashmap_ensure_replace(&m, &string_hash_ops, val1, val2) >= 0);
ASSERT_OK

2024-06-28 16:43 UTC, DaanDeMeyer commented on src/test/test-hashmap-plain.c
> +        assert_se(hashmap_ensure_replace(&m, &string_hash_ops, "key 1", val1) >= 0);
ditto here and below

2024-06-28 16:58 UTC, DaanDeMeyer approved these changes

2024-06-28 17:04 UTC, YHNdnzj approved these changes

2024-06-28 17:04 UTC, YHNdnzj commented on src/libsystemd/sd-hwdb/sd-hwdb.c
> +        r = ordered_hashmap_ensure_replace(&hwdb->properties, &string_hash_ops, key, (void *)entry);
If you touch this:


```suggestion
        r = ordered_hashmap_ensure_replace(&hwdb->properties, &string_hash_ops, key, (void *) entry);
```

2024-06-29 08:30 UTC, bluca approved these changes

2024-06-29 08:31 UTC, merged