Make vcs-tag do something useful for non-developer mode as well
systemd/systemd pull request #33780
Opened 2024-07-19 11:12 UTC by DaanDeMeyer

When building packages of arbitrary commits of systemd-stable, distributors might want to include a git sha of the exact commit they're on. Let's extend vcs-tag a little to make this possible.

If we're on a commit matching a tag, don't generate a git sha at all. If we're not on a commit matching a tag, generate a vcs tag as usually. However, if we're not in developer mode, don't append a '^' if the tree is dirty to accomodate package builds applying various patches to the tree which shouldn't be considered as "dirty" edits.

2024-07-19 13:14 UTC, Conan-Kudo requested changes
This won't work in isolated build environments that fetch using GitHub's archive generation URLs. GitHub archives don't have git metadata, so you need a workaround for that.

2024-07-19 13:26 UTC, Conan-Kudo commented
What I mean is if there's an env var I can use to formulate the result instead, or a file I can write to that it would pick up instead, that'd work.

2024-07-19 13:32 UTC, YHNdnzj commented on tools/vcs-tag.sh
> +#!/bin/bash
SPDX header?

2024-07-19 13:32 UTC, YHNdnzj commented on tools/vcs-tag.sh
> +if [[ -d .git ]] && ! git describe --tags --exact-match &>/dev/null; then
Exit early if we have nothing?

2024-07-19 16:18 UTC, bluca approved these changes

2024-07-22 10:02 UTC, keszybz approved these changes
Looks reasonable. Though I think the only way to know is to deploy this. This is maybe the sixtieth iteration of tag generation and we clearly find it hard to get it right.

2024-07-22 10:02 UTC, keszybz commented on meson.build
> +        command : [vcs_tag ? 'tools/vcs-tag.sh' : 'true', get_option('mode')],
`vcs-tag.sh` returns from the dead ;)

2024-07-22 10:04 UTC, merged

2024-07-22 10:06 UTC, keszybz commented
> What I mean is if there's an env var I can use to formulate the result instead, or a file I can write to that it would pick up instead, that'd work.

I guess this could be added, if there is a concrete need. So far this hasn't come up…