systemd-analyze: Add svg scaling options
systemd/systemd pull request #33858
Opened 2024-07-29 12:17 UTC by rajmohanrgithub

+ Scale the x-axis of the resulting plot by a factor (default 1.0)
+ Add activation timestamps to each bar

2024-08-01 02:47 UTC, rajmohanrgithub commented
Below test was failing
1415/1514 systemd:dist / check-help-systemd-analyze                                   OK               0.08s
==
hence ci-fails/needs-rework.
==
fixed as below:
changed (having 85 characters including " " at beginning, hence failing)
     --scale-svg=FACTOR      Stretch the x-axis of the plot by FACTOR (default: 1.0)
to (<80 charcaters , 77 characters for this change including " " at beginning)
     --scale-svg=FACTOR      Stretch x-axis of plot by FACTOR (default: 1.0)
fixed the failure for above test case.
--
changed (91 characters including " " at beginning. hence failing for above test case)
     --detailed              Add more details to SVG plot, e.g. show activation timestamps
to (76 characters)
     --detailed              Detail SVG plot,e.g.show activation timestamps
==
test case passes now after the above change.

2024-08-01 08:59 UTC, bluca commented on src/analyze/analyze.c
> +bool detailed_svg = false;
arg_detailed_svg

2024-08-01 08:59 UTC, bluca commented on src/analyze/analyze.c
> +double svg_timescale = 1.0;
arg_svg_timescale

2024-08-01 09:00 UTC, bluca requested changes
Please document the new options in man/systemd-analyze.xml. Please add a test case (superficial to just call with the new options is fine just to exercise it under sanitizers, no need to do complex output checks) in test/units/TEST-65-ANALYZE.sh

2024-08-01 09:20 UTC, rajmohanrgithub commented on src/analyze/analyze.c
> +bool detailed_svg = false;
sure, will change it.

2024-08-05 09:29 UTC, rajmohanrgithub commented
> Please document the new options in man/systemd-analyze.xml. Please add a test case (superficial to just call with the new options is fine just to exercise it under sanitizers, no need to do complex output checks) in test/units/TEST-65-ANALYZE.sh

kindly review as the changes related to above request is completed.

2024-08-05 09:38 UTC, bluca commented on man/systemd-analyze.xml
> +        <xi:include href="version-info.xml" xpointer="v256"/></listitem>
257 here and below

2024-08-05 09:38 UTC, bluca approved these changes

2024-08-05 09:44 UTC, bluca commented
I forgot, please also add completion support to shell-completion/bash/systemd-analyze for the new arguments

2024-08-05 09:51 UTC, rajmohanrgithub commented
> I forgot, please also add completion support to shell-completion/bash/systemd-analyze for the new arguments

added. please check. thanks

2024-08-05 13:23 UTC, merged