networkd: Replace existing objects instead of doing nothing if they exist
systemd/systemd pull request #33901
Opened 2024-08-01 12:39 UTC by DaanDeMeyer

Currently, if for example a traffic control object already exist, networkd will silently do nothing, even if the settings in the network file for the traffic control object have changed. Let's instead replace the object if it already exists so that new settings from the network file are applied as expected.

Fixes #31226

2024-08-01 14:58 UTC, yuwata approved these changes
LGTM. But several comments.

2024-08-01 14:58 UTC, yuwata commented on test/test-network/systemd-networkd-tests.py
> +        restart_networkd()
Not a matter, but `networkctl_reload()` should be sufficient.

2024-08-01 14:58 UTC, yuwata commented on src/libsystemd/sd-netlink/netlink-message-rtnl.c
> +                (*ret)->hdr->nlmsg_flags |= NLM_F_CREATE | NLM_F_REPLACE;
Does this work? IIUC the code below, the flag is refused.
https://github.com/torvalds/linux/blob/v6.10/net/core/rtnetlink.c#L3667-L3668

2024-08-01 14:59 UTC, yuwata commented
Hm, but CIs said no...

2024-08-01 15:23 UTC, yuwata requested changes

2024-08-01 15:23 UTC, yuwata commented on src/libsystemd/sd-netlink/netlink-message-rtnl.c
> +                (*ret)->hdr->nlmsg_flags |= NLM_F_CREATE | NLM_F_REPLACE;
NEWRULE does not support NLM_F_REPLACE. Please drop this change.

2024-08-01 15:29 UTC, yuwata requested changes

2024-08-01 15:29 UTC, yuwata commented on test/test-network/conf/25-qdisc-cake.network.d/bandwith.conf
> +Bandwidth=250M
```
/run/systemd/network/25-qdisc-cake.network: More than one root qdisc section is defined. Ignoring the qdisc section from line 9.
```

qdisc sections like `[CAKE]` does not support override.
Please directly edit .network file something like the following:
```python
with open(os.path.join(network_unit_dir, '25-qdisc-cake.network'), mode='w', encoding='utf-8') as f:
        f.write('Bandwidth=250M\n')
```

2024-08-02 05:11 UTC, yuwata commented
Ah, that's not so simple, and we need to redesign how to handle qdiscs in networkd.

2024-08-02 07:06 UTC, DaanDeMeyer commented
@yuwata Can you clarify a little more what needs to be reworked? We have a lot of requests to make this work so if it's not too much work I'd like to take a stab at it (unless you'd like to work on it yourself of course).

2024-09-02 03:34 UTC, yuwata commented
Sorry for late reply. Now I am working on this issue.

2024-09-02 09:15 UTC, closed without merging