basic|boot: silence Wunterminated-string-initialization gcc15 warnings
systemd/systemd pull request #33937
Opened 2024-08-04 22:56 UTC by crrodriguez

gcc15 has -Wunterminated-string-initialization in -Wextra and warns about string constants that are not null terminated even though the functions do not do out of bounds access.
Silence the warnings by simply not providing an explicit size.

2024-08-04 22:59 UTC, bluca approved these changes

2024-08-05 00:18 UTC, yuwata requested changes
LGTM, but nitpick.

2024-08-05 00:18 UTC, yuwata commented on src/basic/hexdecoct.c
>                                        "ABCDEFGHIJKLMNOPQRSTUV";
indentation.

2024-08-05 00:18 UTC, yuwata commented on src/basic/hexdecoct.c
>                                        "0123456789+/";
Also here and below.

2024-08-06 12:20 UTC, yuwata approved these changes

2024-08-06 22:14 UTC, merged