Add example uki.conf
systemd/systemd pull request #34069
Opened 2024-08-21 16:41 UTC by cvlc12

Kernel-install already has an example [install.conf](https://github.com/systemd/systemd/blob/main/src/kernel-install/install.conf); provide a similar example uki.conf with default paths which are picked up by other tools like cryptenroll, for quicker configuration.

2024-08-21 17:45 UTC, yuwata requested changes
The file is never installed. Please update meson.build.

Also, the file does not provide the default configuration, but an example. So, please rename uki.conf -> uki.conf.example .

2024-08-21 17:45 UTC, yuwata commented on src/kernel-install/uki.conf
> +#PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
Missing line-break at the end of the file.

2024-08-21 17:47 UTC, yuwata commented
BTW, the man page ukify(1) has more detailed examples. Is this really necessary??

2024-09-03 02:03 UTC, yuwata requested changes
> I'm happy to change it to `.example` if necessary, however how is this file different from the current `install.conf` file provided ?(which does not end in `.example`).

Indeed. Actually, install.conf is spurious. OK. Let's go with the current form. Then, extend examples later.

Please update the commit message, and address the comment below.

2024-09-03 02:03 UTC, yuwata commented on src/kernel-install/uki.conf
> +[PCRSignature:NAME]
Please comment out `[PCRSignature:NAME]` for safety.

2024-09-03 03:35 UTC, cvlc12 commented on src/kernel-install/uki.conf
> +[PCRSignature:NAME]
Yes, will do when I get back in a few days. 

I'm wondering though, should the PCR private key path be set to `/etc/systemd/` instead of `/etc/kernel/` for consistency?

I think `/etc/kernel/`makes more sense but that's not where cryptenroll picks up the public key.

2024-09-03 03:41 UTC, yuwata commented on src/kernel-install/uki.conf
> +#PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
I noticed that one uses /etc/kernel, but the other uses /etc/systemd...

2024-09-03 03:45 UTC, yuwata commented on src/kernel-install/uki.conf
> +[PCRSignature:NAME]
I think /etc/kernel is fine. Please use the consistent directory.

2024-09-08 23:03 UTC, cvlc12 commented on src/kernel-install/uki.conf
> +[PCRSignature:NAME]
I'm really not sure we should be using anything else than `/etc/systemd/` for the proposed PCR Public Key path. This is automatically sourced by systemd-creds and systemd-cryptenroll.

Meaning that if the public key is rotated and the path is `/etc/kernel/`, then as long as the system is not rebooted, systemd-creds and systemd-cryptenroll will be using the old public key in `/run/systemd/` and secrets/storage devices might become impossible to decrypt after next boot... 

Therefore if we want to use consistent paths for public and private keys, I think the paths should be:

```
#PCRPrivateKey=/etc/systemd/tpm2-pcr-key.pem
#PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
```

Or else add `/etc/kernel/` to the paths sourced by other components? Seems complicated...

2024-09-11 16:16 UTC, poettering commented on src/kernel-install/uki.conf
> +#PCRPrivateKey=/etc/systemd/tpm2-pcr-key.pem
hmm, the systemd-measure man page calls this file `tpm2-pcr-private.pem`. I think we should stick to that.

2024-09-11 16:27 UTC, cvlc12 commented on src/kernel-install/uki.conf
> +#PCRPrivateKey=/etc/systemd/tpm2-pcr-key.pem
What a mess.. Since `tpm2-pcr-public-key.pem` is the hard-coded name passed by systemd-stub (`/.extra/tpm2-pcr-public-key.pem`) and read by `systemd-creds` and `systemd-cryptenroll`, how about `tpm2-pcr-private-key.pem` for consistency ? We can update it later in systemd-measure(1) and all other places.

2024-09-11 18:29 UTC, cvlc12 commented on src/kernel-install/uki.conf
> +#PCRPrivateKey=/etc/systemd/tpm2-pcr-key.pem
See https://github.com/systemd/systemd/pull/34380

2024-09-19 20:19 UTC, yuwata approved these changes
LGTM. One minor issue.

2024-09-19 20:19 UTC, yuwata commented on src/kernel-install/uki.conf
> +#Phases=
Missing trailing new line.

2024-09-19 23:24 UTC, merged