repart: Add compression support
systemd/systemd pull request #34190
Opened 2024-08-30 12:22 UTC by DaanDeMeyer

Now that mkfs.btrfs is adding support for compressing the generated filesystem (https://github.com/kdave/btrfs-progs/pull/882), let's add general support for specifying the compression algorithm and compression level to use.

We opt to not parse the specified compression algorithm and instead pass it on as is to the mkfs tool. This has a few benefits:

- We support every compression algorithm supported by every tool automatically.
- Users don't need to modify systemd-repart if a mkfs tool learns a new compression algorithm in the future
- We don't need to maintain a bunch of tables for filesystem to map from our generic compression algorithm enum to the filesystem specific names.

2024-08-31 20:49 UTC, DaanDeMeyer commented
@hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):

```
 TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
TEST-58-REPART.sh[958]: =================================================================
TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
TEST-58-REPART.sh[958]: ==958==ABORTING
```

Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.

2024-09-01 02:59 UTC, hsiangkao commented
> @hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):
> 
> ```
>  TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
> TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
> TEST-58-REPART.sh[958]: =================================================================
> TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
> TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
> TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
> TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
> TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
> TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
> TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
> TEST-58-REPART.sh[958]: ==958==ABORTING
> ```
> 
> Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.

Hi @DaanDeMeyer, `mkfs.erofs` is a seperate program in a seperate memory addess space, I'm not sure why it could be compiled with AddressSanitizer?  does mkfs.erofs compile by yourself? which version are you using?

2024-09-01 08:04 UTC, DaanDeMeyer commented
> > @hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):
> > ```
> >  TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
> > TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
> > TEST-58-REPART.sh[958]: =================================================================
> > TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
> > TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
> > TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
> > TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
> > TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
> > TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
> > TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
> > TEST-58-REPART.sh[958]: ==958==ABORTING
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.
> 
> Hi @DaanDeMeyer, `mkfs.erofs` is a seperate program in a seperate memory addess space, I'm not sure why it could be compiled with AddressSanitizer? does mkfs.erofs compile by yourself? which version are you using?

It's not compiled with AddressSanitizer, but various tools link end up opening systemd libraries, either by linking against them or indirectly via NSS since we ship an nss plugin. To make this work we have to make sure those binaries load the sanitizer libraries first by using `LD_PRELOAD=`. This is what we do for mkfs.erofs as well which means it ends up running under sanitizers.

I've just verified that mkfs.erofs neither links against libudev nor does its operation end up loading nss_systemd so we can drop the sanitizer wrapper script for mkfs.erofs that loads the sanitizer libraries for it with `LD_PRELOAD`.

2024-09-01 12:26 UTC, hsiangkao commented
> > > @hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):
> > > ```
> > >  TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
> > > TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
> > > TEST-58-REPART.sh[958]: =================================================================
> > > TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
> > > TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
> > > TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
> > > TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
> > > TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
> > > TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
> > > TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
> > > TEST-58-REPART.sh[958]: ==958==ABORTING
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.
> > 
> > 
> > Hi @DaanDeMeyer, `mkfs.erofs` is a seperate program in a seperate memory addess space, I'm not sure why it could be compiled with AddressSanitizer? does mkfs.erofs compile by yourself? which version are you using?
> 
> It's not compiled with AddressSanitizer, but various tools link end up opening systemd libraries, either by linking against them or indirectly via NSS since we ship an nss plugin. To make this work we have to make sure those binaries load the sanitizer libraries first by using `LD_PRELOAD=`. This is what we do for mkfs.erofs as well which means it ends up running under sanitizers.
> 
> I've just verified that mkfs.erofs neither links against libudev nor does its operation end up loading nss_systemd so we can drop the sanitizer wrapper script for mkfs.erofs that loads the sanitizer libraries for it with `LD_PRELOAD`.

which mkfs.erofs version are you using? Is it reproducible with some simple commands since I don't have a full environment so I could investgate too?

2024-09-01 13:05 UTC, DaanDeMeyer commented
> > > > @hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):
> > > > ```
> > > >  TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
> > > > TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
> > > > TEST-58-REPART.sh[958]: =================================================================
> > > > TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
> > > > TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
> > > > TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
> > > > TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
> > > > TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
> > > > TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
> > > > TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
> > > > TEST-58-REPART.sh[958]: ==958==ABORTING
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.
> > > 
> > > 
> > > Hi @DaanDeMeyer, `mkfs.erofs` is a seperate program in a seperate memory addess space, I'm not sure why it could be compiled with AddressSanitizer? does mkfs.erofs compile by yourself? which version are you using?
> > 
> > 
> > It's not compiled with AddressSanitizer, but various tools link end up opening systemd libraries, either by linking against them or indirectly via NSS since we ship an nss plugin. To make this work we have to make sure those binaries load the sanitizer libraries first by using `LD_PRELOAD=`. This is what we do for mkfs.erofs as well which means it ends up running under sanitizers.
> > I've just verified that mkfs.erofs neither links against libudev nor does its operation end up loading nss_systemd so we can drop the sanitizer wrapper script for mkfs.erofs that loads the sanitizer libraries for it with `LD_PRELOAD`.
> 
> which mkfs.erofs version are you using? Is it reproducible with some simple commands since I don't have a full environment so I could investgate too?

This is erofs-utils 1.8.1. I don't have an easy reproducer. I assume that simply linking mkfs.erofs using the same sanitizers as used by systemd `address,undefined` and then trying to use it should be sufficient to trigger the error. If that doesn't trigger it I wouldn't bother investigating further.

2024-09-01 20:22 UTC, evverx commented
There seem to be memory leaks in `mkfs.erofs`
```sh
systemd-repart --empty=create --size=auto --pretty=yes --dry-run=no --definitions="$defs" "$image"
...
Filesystem total deduplicated bytes (of source files): 0                                                                                     20:09:00 [9/1916]
                                                                                                                                                              
=================================================================                                                                                             
==7310==ERROR: LeakSanitizer: detected memory leaks                                                                                                           
                                                                                                                                                              
Direct leak of 107 byte(s) in 2 object(s) allocated from:                                                                                                     
    #0 0x7fdc3c101933 in malloc (/usr/lib/clang/18/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so+0x101933) (BuildId: 0fdfee544ad2f2b68b191945f7eab9dcca606b8
3)                                                                                                                                                            
    #1 0x43f068 in parse_one_xattr /root/erofs-utils/lib/xattr.c:254:10                                                                                       
    #2 0x43f068 in read_xattrs_from_file /root/erofs-utils/lib/xattr.c:446:10                                                                                 
    #3 0x43ed20 in erofs_scan_file_xattrs /root/erofs-utils/lib/xattr.c:582:8

Direct leak of 53 byte(s) in 1 object(s) allocated from:
    #0 0x7fdc3c101933 in malloc (/usr/lib/clang/18/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so+0x101933) (BuildId: 0fdfee544ad2f2b68b191945f7eab9dcca606b83)
    #1 0x43f068 in parse_one_xattr /root/erofs-utils/lib/xattr.c:254:10
    #2 0x43f068 in read_xattrs_from_file /root/erofs-utils/lib/xattr.c:446:10
    #3 0x44385b in erofs_count_all_xattrs_from_path /root/erofs-utils/lib/xattr.c:752:9
    #4 0x4426ae in erofs_build_shared_xattrs_from_path /root/erofs-utils/lib/xattr.c:896:8
    #5 0x7fdc3bd7a087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #6 0x7fdc3bd7a14a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #7 0x404b14 in _start (/usr/bin/mkfs.erofs+0x404b14) (BuildId: 50175ac57b15c5cea8b18aede8b430027e207763)

SUMMARY: AddressSanitizer: 160 byte(s) leaked in 3 allocation(s).
(mkfs) failed with exit status 1.
```
 but it's hard to tell where `SEGV` came from.

2024-09-02 06:54 UTC, hsiangkao commented
> > > > > @hsiangkao I seem to be hitting the following sanitizer error in mkfs.erofs when running systemd-repart under sanitizers (which itself invokes mkfs.erofs):
> > > > > ```
> > > > >  TEST-58-REPART.sh[958]: ThreadSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=958)
> > > > > TEST-58-REPART.sh[958]: AddressSanitizer:DEADLYSIGNAL
> > > > > TEST-58-REPART.sh[958]: =================================================================
> > > > > TEST-58-REPART.sh[958]: ==958==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffb9301cb8 sp 0x7fffb9301bc8 T0)
> > > > > TEST-58-REPART.sh[958]: ==958==Hint: pc points to the zero page.
> > > > > TEST-58-REPART.sh[958]: ==958==The signal is caused by a READ memory access.
> > > > > TEST-58-REPART.sh[958]: ==958==Hint: address points to the zero page.
> > > > > TEST-58-REPART.sh[958]:     #0 0x0  (<unknown module>)
> > > > > TEST-58-REPART.sh[958]: AddressSanitizer can not provide additional info.
> > > > > TEST-58-REPART.sh[958]: SUMMARY: AddressSanitizer: SEGV (<unknown module>)
> > > > > TEST-58-REPART.sh[958]: ==958==ABORTING
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Do you have any clue what might be going wrong here? We're not running mkfs.erofs in any special way or with any special options.
> > > > 
> > > > 
> > > > Hi @DaanDeMeyer, `mkfs.erofs` is a seperate program in a seperate memory addess space, I'm not sure why it could be compiled with AddressSanitizer? does mkfs.erofs compile by yourself? which version are you using?
> > > 
> > > 
> > > It's not compiled with AddressSanitizer, but various tools link end up opening systemd libraries, either by linking against them or indirectly via NSS since we ship an nss plugin. To make this work we have to make sure those binaries load the sanitizer libraries first by using `LD_PRELOAD=`. This is what we do for mkfs.erofs as well which means it ends up running under sanitizers.
> > > I've just verified that mkfs.erofs neither links against libudev nor does its operation end up loading nss_systemd so we can drop the sanitizer wrapper script for mkfs.erofs that loads the sanitizer libraries for it with `LD_PRELOAD`.
> > 
> > 
> > which mkfs.erofs version are you using? Is it reproducible with some simple commands since I don't have a full environment so I could investgate too?
> 
> This is erofs-utils 1.8.1. I don't have an easy reproducer. I assume that simply linking mkfs.erofs using the same sanitizers as used by systemd `address,undefined` and then trying to use it should be sufficient to trigger the error. If that doesn't trigger it I wouldn't bother investigating further.

I tried with `-fsanitize=address,undefined` but no luck with `SIGSEGV`.  I wonder if it'd be better to fix it with erofs-utils 1.8.2, but still no idea what happened though.

2024-09-02 10:10 UTC, poettering commented on man/repart.d.xml
> +
I think if we add this, the help text here should actively useful. i.e. say that the supported compression algorithms and their identifying names vary between file systems, and than add a brief table or so listing known algorithms for each fs at this time. No need to be complete though. And maybe add a sentence emphesizing that this is table is not supposed to be comprehensive, and further algorithms might be supported, and that people should consult the relevant docs for the actual list of algorithms.

i.e.:

file system | compression algorithms         | documentation
------------|--------------------------------|---------------
squashfs    | gzip, lzo, lz4, xz, zstd, lzma | mksquashfs(1)

2024-09-02 10:14 UTC, poettering commented on man/repart.d.xml
> +
here too say that the defined range and meaning is dependent on the file system and choice of compression algorithm, and that one should consult the relevant documentation for precise meanings.

no need for a table here.

2024-09-02 10:16 UTC, poettering commented on src/partition/repart.c
> +        uint64_t compression_level;
hmm, are you sure the compression level is always an integer? don't i remember some compression alg that knew weird levels such as "0", "1", …, "9", "9a", "9b", "9c" or so? or was i hallucinating?

maybe play dumb here, just pass this through as string?

2024-09-03 01:33 UTC, yuwata requested changes

2024-09-03 01:33 UTC, yuwata commented on man/repart.d.xml
> +        <varname>Format=</varname>. Takes a single argument specifying the compression algorithm. </para>
Unnecessary space before `</para>`

2024-09-03 01:33 UTC, yuwata commented on man/repart.d.xml
> +        that support compression:</para>
three `support` in the sentence...

2024-09-03 01:33 UTC, yuwata commented on src/partition/repart.c
> +                { "Partition", "CompressionLevel",         config_parse_string,            0, &p->compression_level       },
Setting CONFIG_PARSE_STRING_SAFE_AND_ASCII is better for safety? As these arguments are directly passed to mkfs. We should not provide fuzzing surface for mkfs.

2024-09-03 06:21 UTC, DaanDeMeyer commented
Dropped the btrfs logic so we can merge this already, will open a separate PR for the btrfs addition.

2024-09-03 06:35 UTC, yuwata approved these changes

2024-09-03 08:17 UTC, poettering commented
lgtm too?

2024-09-03 08:48 UTC, merged

2024-09-06 14:55 UTC, keszybz reviewed
LGTM too.