man: Correct flag description of systemd-cat
systemd/systemd pull request #34335
Opened 2024-09-09 19:27 UTC by sinus-x

It is not true that "no string" is written to journal; the binary name is used when run via `systemd-cat command`, or `cat` is used when run via `command | systemd-cat`.

2024-09-09 20:08 UTC, yuwata requested changes

2024-09-09 20:08 UTC, yuwata commented on man/systemd-cat.xml
> +        input is read from a pipe.</para></listitem>
Not your fault, but that's slightly misleading.

`--identifier=` specifies SYSLOG_IDENTIFIER field of the journal entry, and if it is unset, the field actually will not set. However, each journal entry also has _COMM field, and it is automatically picked by journald from the PID of the process, hence _COMM will be `cat` or the name of the executed binary in this case.
journalctl will use SYSLOG_IDENTIFIER if it exists, and falls back to _COMM. So, when `--identifier=` is unspecified, people will see 'cat' or the executed binary name in the output of `journalctl`.

You can confirm that behavior with `journalctl --reverse --output=export`.

2024-09-10 21:14 UTC, sinus-x commented on man/systemd-cat.xml
> +        input is read from a pipe.</para></listitem>
Aha, that's why I didn't find anything related to this in the `cat.c`. Thanks for the explanation. Let me know if this second version is better.

2024-09-11 11:21 UTC, YHNdnzj approved these changes

2024-09-11 13:00 UTC, bluca approved these changes

2024-09-11 13:00 UTC, merged