bootctl: multi-profile UKI support
systemd/systemd pull request #34347
Opened 2024-09-10 14:33 UTC by poettering

Now that sd-stub and sd-boot understand multi-profile UKIs, let's also teach bootspec.c/bootctl the concept.

Split out of #33512.

2024-09-10 20:29 UTC, yuwata requested changes

2024-09-10 20:29 UTC, yuwata commented on src/shared/bootspec.c
> +            streq(a->id_without_profile, b->id_without_profile)) {
The same comment as https://github.com/systemd/systemd/pull/34339#discussion_r1751718593.
`streq()` can be dropped.

2024-09-10 20:29 UTC, yuwata commented on src/shared/bootspec.c
> +        } else
Why not like the following?
```c
if (profile_title)
        ...
else if (profile_id)
        ...
else if (profile > 0)
        ...
else
        tmp.title = strdup(good_name);
```

2024-09-10 20:29 UTC, yuwata commented on src/shared/bootspec.c
> +        if (pe_is_addon(pe_header, sections))
missing `!`

2024-09-10 20:29 UTC, yuwata commented on src/shared/bootspec.c
> +                        printf("\n");
Not a matter, but `puts("")`

2024-09-11 05:03 UTC, poettering commented
force pushed new version. ptal!

2024-09-15 06:38 UTC, yuwata approved these changes

2024-09-15 07:06 UTC, merged