resolved: add new "DNS Delegate" concepts
systemd/systemd pull request #34368
Opened 2024-09-11 14:52 UTC by poettering

Various long standing issues (at least: #5573 #14159 #20485 #21260 #24532 #32022) have been asking for a way to delegate DNS resolution of specific domains to very specific DNS servers. 

This PR goes a major step towards that goal by adding a new concept "DNS Delegate" which allows to configure just that. Basically, this adds a third kind of DNS scope to resolved's logic: besides the per-link and global DNS scopes there are now also "delegate" scopes, which can be created by dropping in a new file /etc/systemd/dns-delegate/*.conf. They carry DNS= and Domains= lines just like the global setting or what the per-link configuration can carry.

And they are consulted the same way as link DNS scopes are considered, following the same routing rules.

This allows to configure these DNS delegates statically via drop-in files as mentioned, and only adds the most basic functionality. Later on we might want to extend this:

1. Allow dynamic creation of DNS delegates via IPC with lifecycle bound to IPC client (usecase: installing a DNS delegate that routes traffic to some DNS-over-TLS server once basic setup is complete).
2. Allow configuration of protocol details per delegate the same way this is currently allowed per-link.
3. Instead of strictly using DNS as delegation protocol, support an alternative varlink based protocol (without retransmission problems and so on) that systemd-machined and similar can implement.

This PR is not complete yet. Lacks docs and tests. Seems to work fine in my local tests however.

2025-05-09 09:21 UTC, poettering commented
This is complete now, now contains a simple integration test

2025-05-13 13:31 UTC, DaanDeMeyer requested changes

2025-05-13 13:31 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
This can be a forward declaration

2025-05-13 13:31 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate.h
> +#include "resolved-dns-server.h"
All of these includes can be replaced with forward declarations

2025-05-13 13:31 UTC, DaanDeMeyer commented on src/resolve/resolved-dns-delegate.h
> +#include "resolved-dns-server.h"
(Here and elsewhere)

2025-05-13 14:12 UTC, poettering commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
you are making my hair grow grey.

2025-05-13 14:13 UTC, poettering commented on src/resolve/resolved-dns-delegate.h
> +#include "resolved-dns-server.h"
so so grey

2025-05-13 14:22 UTC, DaanDeMeyer commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
> you are making my hair grow grey.

I'm pretty sure they're already gray.

But no worries, I have something in the works that will ungrey your hair

2025-05-13 20:02 UTC, poettering commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
but frankly, i don't even know what precisely should be a forward declaration? is there any tool that can tell me what i am supposed to make a foreard declaration? I ran "clang-tidy" on the PR, and it has nothing to complain?

2025-05-13 20:50 UTC, mcatanzaro commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
It's more a problem in very large C++ projects, where `#include` statements often slow down the build drastically. Trying to reduce `#include` statements wherever possible is highly valuable in these projects. I doubt it matters at all for systemd. But anyway:

If it builds with just a forward declaration, then it can be just a forward declaration. For example:

```
char* dns_delegate_bus_path(const DnsDelegate *d);
```

Using `DnsDelegate *` as a pointer only requires a declaration. The definition isn't needed, so don't need to include any headers.

```
static inline void foo(DnsDelegate *d) {
    return d->whatever;
}
```

You're dereferencing `d` so a `#include` will be required.

2025-05-13 20:53 UTC, mcatanzaro commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
> I'm pretty sure they're already gray.

This might have been a joke related to your avatar. If not, it should have been. Definitely all gray .

2025-05-13 21:18 UTC, DaanDeMeyer commented on src/resolve/resolved-dns-delegate-bus.h
> +#include "resolved-dns-delegate.h"
> but frankly, i don't even know what precisely should be a forward declaration? is there any tool that can tell me what i am supposed to make a foreard declaration? I ran "clang-tidy" on the PR, and it has nothing to complain?

The struct itself, check the rest of the resolved for plenty of examples.

`typedef struct DnsDelegate DnsDelegate` will do just fine.

I'm a bit surprised this is so confusing, you were already doing forward declarations all over the place to make the circular includes work before I removed them.

2025-05-16 08:42 UTC, behrmann commented on man/systemd.dns-delegate.xml
> +DNS=47.11.8.15
That address seems to belong to some Indian ISP. Let's maybe use an address from 192.0.2.0/24, 198.51.100.0/24  or 203.0.113.0/24, which are [specified for documentation usage](https://datatracker.ietf.org/doc/html/rfc5737#section-3).

2025-05-20 10:16 UTC, DaanDeMeyer approved these changes
LGTM, just minor nits

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-scope.c
> +        assert(origin < _DNS_SCOPE_ORIGIN_MAX);
Do we have prior art for such checks? Seems a bit excessive if you ask me

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-scope.c
> +                DnsScope **ret,
Move this to be the last argument while you're at it?

2025-05-20 10:16 UTC, daandemeyer commented on man/org.freedesktop.resolve1.xml
> +      <para><function>GetDelegate()</function> and <function>ListDelegates()</function> were added in version 257.</para>
Should be 258

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-bus.c
> +        return sd_bus_send(NULL, reply, NULL);
sd_bus_message_send

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/meson.build
> +        'resolved_dns_delegate_gperf.c',
Please use hyphens, I pushed a commit onto https://github.com/systemd/systemd/pull/37510 to convert all the other cases to hyphens as well

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate-bus.c
> +static int property_get_dns(
property_get_dns_server?

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate-bus.c
> +        r = sd_bus_message_open_container(reply, 'a', "(sb)");
Shouldn't we make this future proof and make the second field a flags field?

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate.c
> +        if (if_current && d->current_dns_server != if_current)
So this comment and the next ones explains what this function does, but not why, I'm having a hard time understanding why this function works the way it does.

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-delegate.c
> +                        return 0;
`break` for consistency?

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-scope.c
> +                return dns_delegate_get_dns_server(s->delegate);
Is this ordering right? Shouldn't explicit configuration take priority over link configuration?

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-scope.c
> +                return dns_delegate_get_dns_server(s->delegate);
Probably deserves a comment

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-scope.c
> +                return dns_delegate_get_dns_server(s->delegate);
Hmm looking around more, I guess these can't both be true at the same time

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-server.c
> +                if (l->dns_servers && l->default_route)
Hmm `default_route` is an int, please use explicit comparisons with a number instead of treating it as a boolean.

2025-05-20 10:16 UTC, daandemeyer commented on src/resolve/resolved-dns-server.c
> +                if (d->dns_servers && d->default_route)
Ditto

2025-05-20 10:16 UTC, DaanDeMeyer commented on src/resolve/resolvectl.c
> +        return map_dns_servers_internal(bus, member, m, READ_DNS_WITH_IFINDEX|READ_DNS_EXTENDED, error,userdata);
Missing whitespace

2025-05-20 16:18 UTC, poettering commented
@DaanDeMeyer any reason you set the "ci-fails" label? can't find any ci that failed related to any resolved issue?

2025-05-20 16:21 UTC, poettering commented on src/resolve/resolved-dns-scope.c
> +        assert(origin < _DNS_SCOPE_ORIGIN_MAX);
yeah, at various places, for example in compress.c, look for _COMPRESSION_MAX, or in glyph-util around _GLYPH_MAX, or in log.c log_get_target_max_level().

It's quite common actually.

2025-05-20 16:24 UTC, poettering commented on src/resolve/resolved-dns-delegate-bus.c
> +static int property_get_dns(
the property is just called "DNS". And that's quit systematically named that way, i.e. the resolved.conf option is also called DNS=, and the property on the link objects and so on.

the nomenclature ain't great for this, but i think it#s better to be systematic here.

2025-05-20 16:27 UTC, poettering commented on src/resolve/resolved-dns-delegate-bus.c
> +        r = sd_bus_message_open_container(reply, 'a', "(sb)");
hmm, this mimics the props from the link and manager objects, and we use the same parsers everywhere. yes, it would have made sense to make this a flags parameter, but i think we should stick to uniformity for now, and if we actually need more than one flags look for a solution for this property on all three object types.

2025-05-20 16:37 UTC, poettering commented on src/resolve/resolved-dns-scope.c
> +                return dns_delegate_get_dns_server(s->delegate);
yeah, can only be one. will add assert() that checks for this, and also codifies this for the reader

2025-05-20 16:39 UTC, DaanDeMeyer commented on src/resolve/resolved-dns-delegate-bus.c
> +        r = sd_bus_message_open_container(reply, 'a', "(sb)");
Sounds good to me

2025-05-20 22:32 UTC, merged