tree-wide: make sigprocmask() changes more automatic
systemd/systemd pull request #34401
Opened 2024-09-13 09:01 UTC by poettering

This tries to get rid of most manual sigprocmask() changes, in favour of:

1. The SD_EVENT_SIGNAL_PROCMASK flag to sd_event_add_signal()
2. The sd_event_set_signal_exit() call for handling SIGTERM/SIGINT
3. Move masking of SIGWINCH into ptyfwd, out of nspawn/vmspawn/run

And while we are at it get rid of a bunch of event source fields whose lifetime is bound to the sd_event object they belong to anyway, and make use of the "floating" event source feature of sd-event instead.

2024-09-13 09:01 UTC, poettering commented
(this should not add/change anything in effect, it's just refactoring things to make use of our newer helpers more)

2024-09-13 09:10 UTC, DaanDeMeyer requested changes

2024-09-13 09:10 UTC, DaanDeMeyer commented on src/portable/portabled.c
> +        r = sd_event_add_signal(m->event, /* ret_event_source*/ NULL, (SIGRTMIN+18)|SD_EVENT_SIGNAL_PROCMASK, sigrtmin18_handler, NULL);
Formatting of `ret_event_source` is all off here

2024-09-13 09:10 UTC, DaanDeMeyer commented on src/portable/portabled.c
> +        r = sd_event_add_signal(m->event, /* ret_event_source*/ NULL, (SIGRTMIN+18)|SD_EVENT_SIGNAL_PROCMASK, sigrtmin18_handler, NULL);
Also last argument doesn't have an associated comment

2024-09-13 09:10 UTC, DaanDeMeyer commented on src/portable/portabled.c
> +        assert_se(sigprocmask_many(SIG_BLOCK, NULL, SIGCHLD) >= 0);
Missing comment

2024-09-13 09:10 UTC, DaanDeMeyer commented on src/resolve/resolved-manager.c
> +        (void) sd_event_add_signal(m->event, /* ret_event_source= */ NULL, (SIGRTMIN+18) | SD_EVENT_SIGNAL_PROCMASK, sigrtmin18_handler, &m->sigrtmin18_info);
You might as well add debug logging for these if they fail since you do it elsewhere as well

2024-09-14 15:46 UTC, YHNdnzj approved these changes

2024-09-14 15:47 UTC, merged