Make sure bus_connect_transport_systemd() actually connects to the private manager bus
systemd/systemd pull request #34686
Opened 2024-10-09 10:14 UTC by DaanDeMeyer

This gets rid of various fallbacks and moves others around so that we'll fail if we request the private manager bus and can't use it instead of silently falling back to the system bus. This matters when using for example `systemctl daemon-reexec` which relies on using the private manager bus in order to be able to properly wait for the reexec to finish which isn't possible when using the system bus.

2024-10-09 10:48 UTC, poettering commented on src/shared/bus-util.c
> -         * instance, instead of going via the bus */
please move the comment over too (or something like it)

2024-10-09 10:49 UTC, poettering commented
i guess we can try this. i am not 100% sure i grok all implications, but superficially looks good, so as long as we merge it before the rc cylce looks good.

2024-10-09 11:58 UTC, bluca commented
Looks suspicious: `TEST-01-BASIC.sh[904]: ● user@4711.service loaded failed failed User Manager for UID 4711`

2024-10-09 14:21 UTC, DaanDeMeyer commented
@yuwata This breaks your fix from https://github.com/systemd/systemd/pull/27173/. I think it's probably not good for the code in `get_current_runlevel()` to rely on this fallback path to work properly?

2024-10-09 17:08 UTC, yuwata requested changes

2024-10-09 17:08 UTC, yuwata commented on src/update-utmp/update-utmp.c
> +                        goto reconnect;
Potentially, `bus_connect_system_systemd()` may be tried infinite times, as here `n_attempts` is not incremented.

2024-10-09 18:08 UTC, yuwata commented on src/update-utmp/update-utmp.c
> +                        goto reconnect;
BTW, we usually do not loop by goto. How about the following?
```c
#define MAX_ATTEMPTS 64
for (unsigned n_attempts = 0;;) {
        if (n_attempts++ > 0) {
                c->bus = sd_bus_flush_close_unref(c->bus);

                usec_t usec = ...;
                log_debug("Retrying to get current runlevel after %s.", FORMAT_TIMESPAN(usec, USEC_PER_MSEC));
                (void) usleep_safe(usec);

                r = bus_connect_system_systemd(&c->bus);
                if (r == -ECONNREFUSED && n_attempts < MAX_ATTEMPTS) {
                        log_debug_errno(r, "...");
                        continue;
                }
                if (r < 0)
                        return log_error_errno(...);
        }

        FOREACH_ELEMENT(...)
}
```

2024-10-09 18:08 UTC, yuwata commented on src/analyze/analyze.c
> +        if (geteuid() != 0 || (use_full_bus && *use_full_bus)) {
Please also mention run.c in the commit message.

2024-10-09 18:19 UTC, yuwata requested changes

2024-10-09 18:19 UTC, yuwata commented on src/update-utmp/update-utmp.c
> +                        if (r == -ECONNREFUSED && ++n_attempts < 64) {
Incremented twice...

2024-10-09 18:19 UTC, yuwata commented on src/update-utmp/update-utmp.c
>                              ++n_attempts < 64) {
Here also.

2024-10-09 18:51 UTC, yuwata approved these changes
LGTM.

2024-10-09 20:07 UTC, poettering commented on src/cgls/cgls.c
> +                                        r = bus_connect_transport(BUS_TRANSPORT_LOCAL, NULL, scope, &bus);
uh, hm, i am not conviced. I thinks systemd-cgls is tremendously useful when debugging early boot/initrd issues.

I think it's very important it works in that scenario

2024-10-09 20:08 UTC, poettering commented on src/shared/cgroup-show.c
> +                r = bus_connect_transport(BUS_TRANSPORT_LOCAL, NULL, RUNTIME_SCOPE_SYSTEM, &bus);
same here cgls + cgtop should work during early boot I am sure.

2024-10-09 20:09 UTC, poettering commented on src/analyze/analyze.c
> +        if (geteuid() != 0 || (use_full_bus && *use_full_bus)) {
comment would be good here too

2024-10-09 20:09 UTC, poettering commented on src/run/run.c
> +            (arg_runtime_scope == RUNTIME_SCOPE_SYSTEM && geteuid() != 0) ||
here as well

2024-10-10 12:51 UTC, YHNdnzj commented on src/run/run.c
> +            (arg_runtime_scope == RUNTIME_SCOPE_SYSTEM && geteuid() != 0) ||
Hmm, this completely ignores the case when connecting to remote bus, no? Our uid is irrelevant there, and system bus should be used unconditionally.

2024-10-10 12:56 UTC, YHNdnzj commented on src/shared/bus-util.c
> -        if (geteuid() != 0)
So I'm not convinced by this change. See comment above, this needs to be enclosed in local transport, and only then the uid matters. bus_connect_transport_systemd() serves as a dispatcher, and the caller stepping into the low-level territory would result in pitfalls like this

2024-10-10 13:48 UTC, DaanDeMeyer commented
@YHNdnzj Agreed, I moved the check to `bus_connect_transport_systemd()` instead so that `bus_connect_system_systemd()` is solely about connecting to the local private manager bus.

2024-10-11 13:16 UTC, merged