run: add --job-mode= argument
systemd/systemd pull request #34708
Opened 2024-10-10 20:10 UTC by gh2o

systemctl has a --job-mode= argument, and adding the same argument to systemd-run is useful for starting transient scopes with dependencies. For example, if a transient scope BindsTo a service that is stopping, specifying --job-mode=replace will wait for the service to stop before starting it again, while the default job mode of "fail" will cause the systemd-run invocation to fail.

2024-10-10 20:22 UTC, DaanDeMeyer requested changes
Needs a man page update as well

2024-10-10 20:36 UTC, yuwata requested changes
Please add test cases and update the man page and the shell completions.

2024-10-10 20:36 UTC, yuwata commented on src/run/run.c
> +                        arg_job_mode = optarg;
Please check the value.

Also, support "--job-mode=help", and list the possible job modes.
See e.g. https://github.com/systemd/systemd/blob/7d3ae6b21308ca8959d7c70b1f9fa9012db6ec15/src/journal/journalctl.c#L459-L463

2024-10-10 21:26 UTC, yuwata commented
```
1530/1926 systemd:dist / check-help-systemd-run                                             FAIL             0.02s   exit status 1
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
systemd-run --help output is too wide:
     --job-mode=MODE              Specify how to deal with already queued jobs, when
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

2024-10-11 08:50 UTC, poettering commented on src/run/run.c
> +               "                                  queueing a new job\n\n"
the double \n is not right

2024-10-11 08:51 UTC, poettering commented on src/run/run.c
> +static const char *arg_job_mode = "fail";
please copy the string. With `--scope` mode we'll fork off a child, and then try to rename the process via touching `argv[]` which will invalidate all pointers into it. Hence, let's please copy this, the same way as systemctl.c does it. i.e. drop the "const" here, use strdup(), and STATIC_DESTRUCTOR_REGISTER()

2025-01-03 07:25 UTC, gh2o commented on src/run/run.c
> +                        arg_job_mode = optarg;
Validation added and help added.

2025-01-03 07:25 UTC, gh2o commented on src/run/run.c
> +               "                                  queueing a new job\n\n"
Fixed.

2025-01-03 07:25 UTC, gh2o commented on src/run/run.c
> +static const char *arg_job_mode = "fail";
Fixed by storing a JobMode enum instead.

2025-01-04 03:10 UTC, yuwata requested changes

2025-01-04 03:10 UTC, yuwata commented on shell-completion/zsh/_systemd-run
> +        _modes=(fail replace replace-irreversibly isolate ignore-dependencies ignore-requirements flush)
Also here.

2025-01-04 03:12 UTC, yuwata requested changes
Looks mostly good.
Several minor requests.

2025-01-04 03:12 UTC, yuwata commented on shell-completion/bash/systemd-run
> +                         ignore-dependencies ignore-requirements flush'
Please use `--job-mode=help` to list suggestions:
```sh
local comps=$( systemd-run --job-mode=help 2>/dev/null )
```

2025-01-04 03:12 UTC, yuwata commented on shell-completion/zsh/_systemd-run
> +        _modes=(fail replace replace-irreversibly isolate ignore-dependencies ignore-requirements flush)
Also here.

2025-01-04 03:12 UTC, yuwata commented on man/systemd-run.xml
> +          <option>--job-mode=</option> option. The default job mode is <literal>fail</literal>.</para>
Please mention that `help` lists the possible values.

2025-01-04 03:12 UTC, yuwata commented on src/run/run.c
> +                        }
```c
if (streq(optarg, "help"))
        return DUMP_STRING_TABLE(...);
```

2025-01-21 03:59 UTC, gh2o commented
@yuwata I've addressed your changes, please review again.

2025-01-21 04:09 UTC, YHNdnzj commented on src/shared/job-mode.h
We usually place such definitions in basic/. E.g. unit-def.[ch]

2025-01-21 04:09 UTC, YHNdnzj commented on src/shared/job-mode.h
> +enum JobMode {
Please merge these

2025-01-21 04:22 UTC, gh2o commented on src/shared/job-mode.h
That seems like a better place to put it. I've moved the JobMode definition there, thanks.

2025-01-22 16:27 UTC, yuwata commented on man/systemd-run.xml
> +          <para>Running <command>--job-mode=help</command> shows a list of available job modes.</para>
`<command>` -> `<option>` is better ?

2025-01-23 07:09 UTC, gh2o commented on man/systemd-run.xml
> +          <para>Running <command>--job-mode=help</command> shows a list of available job modes.</para>
Good point, fixed.

2025-01-23 09:10 UTC, yuwata approved these changes
LGTM. Thank you!

2025-01-23 09:11 UTC, merged