Draft: attempt to drop more lib64 links and see what fails
systemd/systemd pull request #34804
Opened 2024-10-17 11:40 UTC by helmutg

The symlinks removed here make Debian's `base-files` package fail to install. It is not clear what their purpose is and what would break in their absence. Hence attempt deleting them and see what happens with CI (which is not run on forked repositories). If it turns out that there is a failure, we can document why they are needed in the source code. Otherwise, the PR may be undrafted and merged.

2024-11-29 13:30 UTC, YHNdnzj requested changes
Sorry, but let's not introduce something purely to make Debian happy. Especially considering that distros without `/usr/lib64/` exists, e.g. Arch uses `/usr/lib/` for 64-bit libs and `/usr/lib32/` for 32-bit ones. And we should make things robust in the sense that `/lib64/` would preferably exist than to appease dpkg.

2024-11-29 16:19 UTC, helmutg commented
I think your argument can be turned upside down. Why do we need to create obviously broken symbolic links to appease the Arch package manager? I am not proposing to drop the `/lib64` link. It'll be created and it'll point to `/usr/lib64` as before. What must not happen is to create it as `/lib64` -> `/usr/lib` as that is just broken. In particular, it breaks the promise that you can use `/lib64` and `/usr/lib64` interchangeably. That was the promise of the `/usr`-merge.

In addition, I think we should first manage observable problems and then hypothetical problems. The Debian side has been demonstrated. The systemd CI has found 0 problems arising from this change. I have asked repeatedly for what it could possibly break, but thus far no actual use case of the `/lib64` -> `/usr/lib` symlink has been brought forward.

In the event that this change is unacceptable, can you propose a different solution to avoid the conflict? The Debian `base-files` package installs `/lib64` as a symlink pointing to `usr/lib64`. Pointing it elsewhere causes an unpack error from `dpkg`. That is the underlying problem we need to solve here. If no upstream-acceptable solution can be found. We may have to carry a delta in Debian as we cannot tell our users that sometimes `systemd` makes upgrading an essential package to fail. There is no question of whether this needs fixing in one way or another. The only question is where we can fix it.

2024-11-29 16:30 UTC, bluca commented
> Sorry, but let's not introduce something purely to make Debian happy. Especially considering that distros without `/usr/lib64/` exists, e.g. Arch uses `/usr/lib/` for 64-bit libs and `/usr/lib32/` for 32-bit ones. And we should make things robust in the sense that `/lib64/` would preferably exist than to appease dpkg.

Note that it's not even dpkg, this is a regression introduced a couple of months ago by a change in a debian-specific package scriptlet: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1076491;filename=base-files_13.3%2Bnmu1.debdiff;msg=59

A fix for that Debian-specific scriptlet has been posted and can be used instead: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077866#31

2024-11-29 16:37 UTC, helmutg commented
> Note that it's not even dpkg, this is a regression introduced a couple of months ago by a change in a debian-specific package scriptlet: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1076491;filename=base-files_13.3%2Bnmu1.debdiff;msg=59

Note that it actually is an unpack error from `dpkg`. The script merely exists to produce a meaningful error message. So in practice, it now is a `preinst` failure, yes, but the failure prevents `dpkg` from attempting and failing the unpack.

> A fix for that Debian-specific scriptlet has been posted and can be used instead: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077866#31

I am happy to apply that patch once the underlying `systemd` bug has been fixed. Not fixing the systemd side just means that the link will flip back and forth.

2024-11-29 16:44 UTC, YHNdnzj commented
> What must not happen is to create it as `/lib64` -> `/usr/lib` as that is just broken. In particular, it breaks the promise that you can use `/lib64` and `/usr/lib64` interchangeably. That was the promise of the `/usr`-merge.

How? The libdir is supposed to be part of distro policy. Arch has always used `/usr/lib/` to contain 64-bit libs.

But let's build up some consensus I guess. Can you explain what Debian is expecting here precisely? We always prefer symlinking to `/usr/lib64/` if exists, and `/usr/lib/` is just a fallback. Why would dpkg care about `/lib64/` if there's no `/usr/lib64/`, and that's where Debian's 64-bit libs reside?

2024-11-29 17:21 UTC, helmutg commented
The technical requirement on the Debian side becomes that `/lib64` always points to the same thing. In principle, it is not that important whether that's `usr/lib` or `usr/lib64`, but the `usr/lib` target breaks the promise of using `/lib64` and `/usr/lib64` interchangeably. Whatever it always points to, we can reasonably accommodate in the `base-files` package. What does not work for Debian is having it point to two different locations depending on whatever.

On Debian, all of `/lib64`, `/lib32`, `/libo32` and `/libx32` (as well as the corresponding locations below `/usr`) only exist for compatibility and API purposes. The dynamic loader can reside below `/lib64` and that's pretty much it. On a typical `amd64` installation `/lib64` contains exactly one symbolic link. `/lib` (and `/usr/lib`) has been almost emptied these days. Even on my Debian 12 system it only contains one shared library that has not moved. Shared libraries generally have been moved to `/lib/<triplet>` (`/usr/lib/<triplet>` really), so we can install libraries for all architectures at the same time without producing any file conflicts.

The aspect about `/lib64` being an API path on some architectures is crucial. The `base-files` package contains this symbolic link for precisely those architectures that have their dynamic loader below it. If `base-files` were not containing it and we'd be creating it using a maintainer script, there would be a chicken and egg problem as the maintainer script would likely use a dynamic executable that would require `/lib64` and thus fail to run unless `/lib64` already exists.

I hope this answers your questions about the Debian side.

I am glad to see that Arch prefers the `/lib64` -> `usr/lib64` link. Is anything wrong with not just preferring but always installing it that way? In order to support this, Arch would have to ensure that `/usr/lib64` always exists (likely as a symbolic link pointing to `lib` aka `/usr/lib`), but that generally seems like a useful thing to do to me, because otherwise Arch breaks the `/usr`-merge compatibility promise. Why would it?

2025-01-03 15:53 UTC, bluca commented
The reported issue turns out not to be reproducible: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079329#66

Given this breaks other distributions as already mentioned, and it looks plainly wrong, and nobody else is convinced, let's just close this as there's no point leaving it lingering

2025-01-03 15:53 UTC, closed without merging

2025-04-03 09:22 UTC, helmutg commented
At this time, the change proposed is a focal point of contention on the Debian side. In talking about it with various parties, I realized a wrinkle that appears new to me and I therefore hope that this comment is not seen as beating a dead horse nor as a code of conduct violation. If it is, please let me know and I'll stop.

My impression is that the conversation here did not succeed due to a subtle difference in interpretation. The way I perceive it now is that the view of systemd upstream developers is that the code in question would only be relevant to hermetic-/usr and since hermetic-/usr and using a package manager is relatively incompatible, Debian should have no need to touch this code. I appreciate feedback on whether that perception is accurate.

Evidently, that code does influence installations that are not hermetic-/usr (or we would not be having this conversation), but my changed understanding now is that this code was *meant* to affect hermetic-/usr only. It merely failed to achieve that in a subtle way. Is that a reasonable interpretation?

Telling different distributions apart and making the code behave in distribution-dependent ways was ruled out rather early with reason. Maybe another angle to look at this would instead be improving the detection of whether we are in a hermetic-/usr situation? To that end, I assume that all distributions agree on how the /bin, /lib and /sbin symbolic links should look. Evidently, there is disagreement about /lib64. Therefore, we may consider the first three links as a bit of information. How about changing the logic to look like this?

    Ensure that /bin, /lib, and /sbin exist as symbolic links (as before)
    If any of these three links was in need of creation: (assume that we are in a hermetic-/usr setting)
        Ensure that /lib64 exists as a symbolic link to usr/lib64 falling back to usr/lib (as before)

The crucial change here is making the check for /lib64 dependent on the creation of any of /bin, /lib and /sbin.

In a truly hermetic-/usr setting, those three links will all be absent and systemd will create /lib64 as before. On a Debian installation, the presence of all of /bin, /lib and /sbin will opt ouf of the hermetic-/usr code and assume that the Linux distribution has taken care of creating the necessary aliasing links.

Would this be an alternative worth considering? I'm happy to provide the code if there is basic agreement that this approach is worth exploring.

2025-04-03 22:52 UTC, bluca commented
> Would this be an alternative worth considering? I'm happy to provide the code if there is basic agreement that this approach is worth exploring.

Such a workaround seems harmless for other distributions, which was the main issue here, so sounds fine to me. But others have to agree as well