core-execute: Setup ExecDirectories before stdin/stdout
systemd/systemd pull request #34889
Opened 2024-10-24 21:21 UTC by talisein

Fixes #27591

2024-10-25 19:33 UTC, yuwata requested changes

2024-10-25 19:33 UTC, yuwata commented on test/test-execute/exec-runtimedirectory-stdoutput.service
> +ExecStart=sh -c 'printf "hello\nhello\n"'
Please use bash.

2024-10-25 19:33 UTC, yuwata commented on test/test-execute/exec-runtimedirectory-stdoutput.service
> +RuntimeDirectory=test-exec_runtimedirectory_standardoutput
Please set `RuntimeDirectoryPreserve=yes`, and check the contents of the output file.

2024-10-25 19:42 UTC, yuwata requested changes
BTW, rather than test-execute, please try to add test cases in test/units/TEST-07-PID1.exec-context.sh .

2024-10-30 09:48 UTC, poettering commented
I am not sure how I feel about this.

So one of the primary benefits of using RuntimeDirectory=/StateDirectory= is that it chown()s the dir it creates to the user/group of the user configured via User=/Group=. But if you use StandardOutput=file:… then we do no such chown()ing, it's owned by root:root. So we suddenly will have a root-owned file in an unpriv dir, and that raises all kinds of alarm bells in my head.

if we'd want to officially support this we'd have to do two things probably:

1. first of all use `chase_and_open()` in `acquire_path()` (instead of plan `open()`) with the CHASE_SAFE|CHASE_PROHIBIT_SYMLINKS flag, so that we do not run into symlink attacks scenarios.
2. and then we have to probably do something about the ownership of the created file, maybe add a new `StandardOutput=file-owned:…` which chowns the file to the service's user.

What also gives me a headache is how this would play together with #34078. I.e. we should not open these files from outside the service#s sandbox if they are located within any of the runtime/state dirs, but from inside, so that the right idmapping is applied. And that makes things really hard to deal with. A reasonably easy way out might be to simply refuse operation in this mode for now (i.e. refuse `StandardOutput=file-owned:` for DynamicUser= or so (where we'd use idmapped mounts for this).

2024-10-30 09:49 UTC, poettering commented
regarding the 2nd thing, also see RFE #14385

2026-05-26 23:33 UTC, tacerus commented
Hello,

```
[Service]
DynamicUser=yes
LogsDirectory=bot/%i
StandardError=file:%L/bot/%i/raw
...
```

Currently this fails on the first start - one needs to temporarily unset `StandardError`. After starting once without `StandardError` (which makes it create the directory structure), it can be set again, and log redirection works well.

Given the concerns above, is there a different solution other than this patch which I am missing?

2026-05-27 00:44 UTC, talisein commented
@tacerus Some comments in the bug report may have some other approaches (https://github.com/systemd/systemd/issues/27591#issuecomment-2103017201). 

I'll close this PR since I've forgotten sufficient context knowledge at this point.

2026-05-27 00:44 UTC, closed without merging