tree-wide: basename -> path_extract_filename
systemd/systemd pull request #34906
Opened 2024-10-27 00:46 UTC by awilfox

This includes the "non-controversial" changes from #34303, so that these pieces can be merged while those are still discussed.

2024-10-27 00:47 UTC, awilfox commented
I believe this has split all of the reviewed changes from #34303 into its own PR.  If I have brought in a change that needs to go back into #34303 I'm happy to put it back, so that this can be merged.  Once this is merged I'll rebase the original PR and we can finish it.

2024-10-27 04:43 UTC, yuwata requested changes

2024-10-27 04:43 UTC, yuwata commented on src/core/load-dropin.c
> +                                               unit_dependency_to_string(dependency), *p);
The log message sounds slightly spurious. How about the following?
```c
log_unit_warning_errno(u, r, "Failed to extract file name of %s dependency dropin %s, ignoring: %m", 
                       unit_dependency_to_string(dependency), *p);
```

2024-10-27 04:43 UTC, yuwata commented on src/core/load-dropin.c
> +                        log_unit_warning_errno(u, r, "Can't determine file name for dropin target %s, ignoring: %m",
"determine" sounds slightly spurious for me. How about the following?
`"Failed to extract file name of dropin target %s, ignoring: %m"`

2024-10-27 04:43 UTC, yuwata commented on src/network/netdev/netdev.c
> +                return log_error_errno(r, "Failed to extract file name of '%s': %m", filename);
Please downgrade the log level 'log_error_errno()' -> `log_warning_errno()`.

2024-10-27 04:43 UTC, yuwata commented on src/network/networkd-network.c
> +                return log_warning_errno(r, "Couldn't determine file name for \"%s\": %m", filename);
I'd like to make the all log messages consistent:
`"Failed to extract file name of '%s': %m"`

2024-10-27 04:43 UTC, yuwata commented on src/shared/unit-file.c
> +                                dst = TAKE_PTR(dst_inst);
Previous assignment of `dst` is leaked.
```c
free_and_replace(dst, dst_inst);
```

2024-10-27 04:43 UTC, yuwata commented on src/shared/unit-file.c
> +                _cleanup_free_ char *inst = NULL, *dst_inst = NULL, *dst = NULL;
Please move the declaration of `dst_inst` to the inner most `if` block below.

2024-10-27 04:43 UTC, yuwata commented on src/systemctl/systemctl-show.c
> +                                log_error_errno(r, "Failed to extract basename of '%s': %m", *dropin);
`basename` -> `file name`

2024-10-27 04:43 UTC, yuwata commented on src/systemctl/systemctl-sysv-compat.c
> +                        return log_error_errno(j, "Failed to extract basename from '%s': %m", p);
`basename` -> `file name`

2024-10-27 04:43 UTC, yuwata commented on src/test/test-fileio.c
>          assert_se(r == -ENOENT);
When you touch the code, please use `ASSERT_ERROR(search_and_fopen(...), ENOENT);`

2024-10-27 04:43 UTC, yuwata commented on src/test/test-fileio.c
>          assert_se(r == -ENOENT);
Also here. please use `ASSERT_ERROR()`.

2024-10-27 04:43 UTC, yuwata commented on src/test/test-fileio.c
>          assert_se(r == -ENOENT);
ASSERT_ERROR()

2024-10-27 04:43 UTC, yuwata commented on src/test/test-install.c
>          assert_se(r < 0);
`ASSERT_FAIL(unit_file_get_state(...));`

2024-10-27 04:43 UTC, yuwata commented on src/test/test-install.c
>          assert_se(r < 0);
ASSERT_FAIL()

2024-10-27 04:43 UTC, yuwata commented on src/test/test-install.c
>          assert_se(r < 0);
Also here.

2024-10-27 04:43 UTC, yuwata commented on src/test/test-mountpoint-util.c
> +        assert_se(fd_is_mount_point(fd, strjoina(tmpdir_basename, "/"), 0) == 0);
`ASSERT_OK_EQ(fd_is_mount_point(...), 0);`

2024-10-27 04:43 UTC, yuwata commented on src/udev/net/link-config.c
> +                return log_error_errno(r, "Failed to extract basename of '%s': %m", filename);
`basename` -> `file name`

2025-03-03 13:24 UTC, poettering commented
Is there still interest in this?

2025-03-03 13:25 UTC, poettering commented
(if there is: my strong recommendation would be to split this up, get the already ready stuff of, let's get that merged, and the rest can come later)

2025-03-10 22:34 UTC, awilfox commented
Yes, we still have significant interest in merging this; we just had some other projects come up that had higher criticality.  I apologise for the delay and the radio silence.  Since this was already split off #34303, I would *much* rather just fix everything that is here and merge this at once.  I do not want to see it split yet again.

I'll try to get this rebased and all the review comments addressed by the end of the week.

2025-04-20 03:17 UTC, awilfox commented
I believe those CI failures are unrelated to my changes and they should be ready for review.  I would be happy to rebase them again, but it shouldn't be necessary?

2025-04-22 16:41 UTC, poettering commented on src/test/test-mountpoint-util.c
> +        ASSERT_OK_EQ(is_mount_point_at(fd, tmpdir_basename, 0), 0);
ASSERT_OK_ZERO

2025-04-22 16:41 UTC, poettering commented on src/test/test-mountpoint-util.c
> +        ASSERT_OK_EQ(is_mount_point_at(fd, strjoina(tmpdir_basename, "/"), 0), 0);
ditto

2025-05-04 20:41 UTC, YHNdnzj commented on src/core/load-dropin.c
>                   * long time. Nevertheless, we warn, because such mismatch can be mighty confusing. */
The comment belongs to `unit_symlink_name_compatible` below, not here

2025-05-04 22:24 UTC, mjeveritt commented on src/core/load-dropin.c
>                   * long time. Nevertheless, we warn, because such mismatch can be mighty confusing. */
I'm not seeing that comment as being 'new', here? Is that really a blocker, or a prompt for a new PR?!

2025-05-04 22:30 UTC, mjeveritt commented on src/test/test-mountpoint-util.c
> +        ASSERT_OK_EQ(is_mount_point_at(fd, tmpdir_basename, 0), 0);
@awilfox I think Lennart is proposing using the macro at https://github.com/systemd/systemd/blob/a50fa2a40f4a91d49503d3588a3dd29ea05e559b/src/shared/tests.h#L263 FYI

2025-05-04 22:31 UTC, mjeveritt commented on src/test/test-mountpoint-util.c
> +        ASSERT_OK_EQ(is_mount_point_at(fd, strjoina(tmpdir_basename, "/"), 0), 0);
@awilfox again https://github.com/systemd/systemd/pull/34906#discussion_r2072729314

2025-05-04 22:45 UTC, YHNdnzj commented on src/core/load-dropin.c
>                   * long time. Nevertheless, we warn, because such mismatch can be mighty confusing. */
Please move it down I mean, close to unit_symlink_name_compatible

2025-05-04 22:56 UTC, mjeveritt commented on src/core/load-dropin.c
> +                r = unit_symlink_name_compatible(entry, target_file, u->instance);
I think you meant here, @YHNdnzj :) @awilfox

2025-05-04 22:58 UTC, mjeveritt commented on src/core/load-dropin.c
> +                r = unit_symlink_name_compatible(entry, target_file, u->instance);
Moving original L81/82 down to L90 unless I'm mistaken.

2025-05-04 23:24 UTC, mjeveritt commented
LGTM from the peanut gallery! :+1: :peanuts:

2025-05-05 09:53 UTC, yuwata requested changes
Looks mostly good. Two minor requests.

2025-05-05 09:53 UTC, yuwata commented on src/shared/unit-file.c
> +                        _cleanup_free_ char *dst_inst = NULL;
Please move the declaration to `if (t == UNIT_NAME_INSTANCE)` branch below.

2025-05-05 09:53 UTC, yuwata commented on src/test/test-path-util.c
> +        ASSERT_OK_ERRNO((fd = mkostemp_safe(fn)));
This is our own function. Please use `ASSERT_OK()`. Also redundant `()`.
```
ASSERT_OK(fd = mkostemp_safe(fn));
```

2025-05-08 06:07 UTC, mjeveritt commented on src/shared/unit-file.c
> +                        _cleanup_free_ char *dst_inst = NULL;
just two lines below, yes.. under `if (t < 0)` , that does makes sense in context.

@awilfox nearly there! :grinning:

2025-06-06 10:08 UTC, yuwata commented
Rebased, and several more use cases are replaced. PTAL, especially the last two commits.

2025-06-06 10:36 UTC, poettering commented
lgtm. thank you for picking this up!

2025-06-06 13:53 UTC, merged

2025-06-06 16:55 UTC, awilfox commented
Sorry, this got lost during onboarding for my new job.  Appreciate the help and glad to see it merged in!  🎉