bootspec fixups
systemd/systemd pull request #34959
Opened 2024-10-30 19:52 UTC by AdrianVovk

Various fixes for the bootspec util-lib. See commit messages for more details.

Split out from #34767

2024-10-30 20:35 UTC, yuwata commented
```
../src/shared/bootspec.c: In function ‘boot_entries_find_unified_global_addons’:
../src/shared/bootspec.c:1165:81: error: passing argument 5 of ‘boot_entries_find_unified_addons’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1165 |         return boot_entries_find_unified_addons(config, dirfd(d), d_name, root, &ret_addons);
      |                                                                                 ^~~~~~~~~~~
      |                                                                                 |
      |                                                                                 BootEntryAddons **
../src/shared/bootspec.c:1087:34: note: expected ‘BootEntryAddons *’ but argument is of type ‘BootEntryAddons **’
 1087 |                 BootEntryAddons *ret_addons) {
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~
../src/shared/bootspec.c: In function ‘boot_entry_to_json’:
../src/shared/bootspec.c:1961:29: error: passing argument 2 of ‘json_cmdline’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1961 |         r = json_cmdline(e, &c->global_addons, opts, &v);
      |                             ^~~~~~~~~~~~~~~~~
      |                             |
      |                             const BootEntryAddons (*)[2]
../src/shared/bootspec.c:1754:40: note: expected ‘const BootEntryAddons *’ but argument is of type ‘const BootEntryAddons (*)[2]’
 1754 |                 const BootEntryAddons *global_arr,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
```

2024-10-30 20:54 UTC, YHNdnzj requested changes

2024-10-30 20:54 UTC, YHNdnzj commented on src/shared/bootspec.c
> +                        text = strjoin(ansi_grey(), e->root, "/", ansi_normal(), p);
This is intentional and double / is printed consistently for paths under $BOOT. See comment in boot_entry_file_list for details. Hence please drop this change

2024-10-30 22:04 UTC, yuwata commented
fuzz-bootspec is unhappy.

2024-11-27 10:55 UTC, merged

2024-11-27 10:57 UTC, YHNdnzj commented on src/shared/bootspec.c
> +        FOREACH_ARRAY(i, config->global_addons, _BOOT_ENTRY_SOURCE_MAX)
FOREACH_ELEMENT

2024-11-27 10:57 UTC, YHNdnzj commented on src/shared/bootspec.h
> +const char* boot_entry_source_json_to_string(BootEntrySource);
mark as `_const_`/`_pure_`?