test-dhcp-client: utilize log_info instead of printf
systemd/systemd pull request #34985
Opened 2024-11-01 20:45 UTC by colin-foster-in-advantage

log_info appears to be the preferred method to convey information from tests. Convert all the printfs to log_info to follow this standard.

2024-11-02 13:48 UTC, yuwata requested changes

2024-11-02 13:48 UTC, yuwata commented on src/libsystemd-network/test-dhcp-client.c
> +                log_info("* %s\n", __func__);
Then, please drop trailing `\n` here and below.

2024-11-04 11:57 UTC, bluca approved these changes

2024-11-04 11:57 UTC, merged

2024-11-05 18:02 UTC, yuwata commented
Belated LGTM. Thank you.