Avoid generating ton of D-Bus traffic when there are many concurrent private connections
systemd/systemd pull request #35152
Opened 2024-11-13 18:10 UTC by msekletar

This is in attempt to fix #32381.

@mrc0mmand I'd appreciate testing this against reproducer with 1600 or more concurrent mounts.

2024-11-13 18:20 UTC, YHNdnzj commented on src/core/dbus-manager.c
> +        } else {
else if (... != m->system_bus)

2024-11-14 03:29 UTC, yuwata requested changes

2024-11-14 03:29 UTC, yuwata commented on src/core/dbus.c
> +int bus_foreach_bus_signal(
Not a matter, but bus_foreach_bus_send_signal() or bus_foreach_send_signal() is better?

2024-11-14 03:29 UTC, yuwata commented on src/core/dbus-manager.c
> +        } else {
Or, set_contains(m->private_buses, ...) ?

2024-11-14 03:29 UTC, yuwata commented on src/core/dbus-manager.c
Please drop this empty line.

2024-11-14 03:29 UTC, yuwata commented on src/core/dbus.c
> +        m->private_buses_subscribed = set_free(m->private_buses_subscribed);
destroy_bus() should drop the private bus connection from the set, and please check if the set is empty before free.

2024-11-14 10:06 UTC, poettering commented
Hmm, so for each job we maintain a list of bus peers which "own" it. This is done via the `job->bus_track` stuff. the owner of a job is the peer who created it. (There can be multiple owners of a single job, because we merge jobs). So far the logic that we send out notification signals for a job when either there's a global subscriber, *or* if there's at least one live owner on ths bus still.

So far we implicitly made that direct connections are always global subscribers, and didn't bother with tracking the direct connections which own a job. If you now changer the first think you have to add the 2nd thing however. I.e. each Job object needs to keep track of direct connections that own it. And this set of connections needs to be maintained as direct connections come an go... kinda nasty.

2024-11-14 10:29 UTC, msekletar commented
@poettering but do we really "have to" go that far? I mean wouldn't be situation drastically better with these changes and then we can take another incremental step if there is need and time to implement it?

2024-11-14 21:44 UTC, poettering commented
> @poettering but do we really "have to" go that far? I mean wouldn't be situation drastically better with these changes and then we can take another incremental step if there is need and time to implement it?

Well, you are breaking the interface if you don't, because the rule so far is that if you create a job yourself, you don't need to subscribe. But now you start requiring the subscription. Which makes things worse, since it means you definitely will get the events for *all* jobs now, even though you only want the ones you created yourself. So you are making some things better but also some things worse, all while breaking API (because old versions of systemctl won't do the Subscribe() and not get any events anymore)

2024-11-19 16:33 UTC, mrc0mmand commented
> This is in attempt to fix #32381.
> 
> @mrc0mmand I'd appreciate testing this against reproducer with 1600 or more concurrent mounts.

I gave this a quick run with the original reproducer from #32381 and it unfortunately reproduced the issue:

```
# git -C systemd log -1
commit 35027e7139e659ec83cfa3715ac11b5f5bd8d5f9 (HEAD -> pr)
Merge: d5bb359429 550f38cb14
Author: Michal Sekletár <msekleta@redhat.com>
Date:   Tue Nov 19 14:32:27 2024 +0100

    Merge 550f38cb1424b084e1d815b12fd628a05e9a7c5b into d5bb359429796d0859db9d85b59574919d86a60d
# systemctl --version
systemd 257 (257~rc2-g35027e7)
# journalctl -o short-monotonic --no-hostname -b --grep "Connection terminated"
[  676.099699] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.226934] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.resolve1', failing connection: Connection terminated
[  676.227522] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.228775] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.timesync1', failing connection: Connection terminated
[  676.229056] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.229327] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.network1', failing connection: Connection terminated
[  676.229604] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.229875] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.NetworkManager', failing connection: Connection terminated
[  676.230160] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.332273] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.login1', failing connection: Connection terminated
[  676.332639] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.333886] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.hostname1', failing connection: Connection terminated
[  676.334167] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.334451] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.home1', failing connection: Connection terminated
[  676.334717] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.485876] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.UDisks2', failing connection: Connection terminated
[  676.486250] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.487622] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.import1', failing connection: Connection terminated
[  676.487893] systemd[1]: systemd-importd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  676.488177] systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.systemd1.Activator',member='ActivationRequest', failing connection: Connection terminated
[  676.488462] systemd[1]: Unable to request name, failing connection: Connection terminated
[  676.488731] systemd[1]: Unable to add match type='method_call',interface='org.freedesktop.MemoryAllocation1',path='/org/freedesktop/MemoryAllocation1',destination='org.freedesktop.systemd1',member='GetMallocInfo', failing connection: Connection terminated
[  824.515603] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515650] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515691] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515727] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515765] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515800] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515834] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515869] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515905] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  824.515940] systemd[1]: systemd-importd.service: Unexpected error response from GetNameOwner(): Connection terminated
```

2024-12-10 09:49 UTC, rpigott commented
Is there any merit in dispatching the timeouts last when we process events on the bus? And possibly making a good faith effort to flush the rqueue first? It seems unfortunate if the reply we're waiting for may actually have been delivered but we were too busy to check it before the timeout expired.

2025-05-07 16:07 UTC, closed without merging