core: Add PrivateUsers=full
systemd/systemd pull request #35183
Opened 2024-11-15 15:28 UTC by ryantimwilson

Recently, PrivateUsers=identity was added to support mapping the first 65536 UIDs/GIDs from parent to the child namespace and mapping the other UID/GIDs to the nobody user.

However, there are use cases where users have UIDs/GIDs > 65536 and need to do a similar identity mapping. Moreover, in some of those cases, users want a full identity mapping from 0 -> UID_MAX.

To support this, we add PrivateUsers=full that does identity mapping for all available UID/GIDs.

Note to differentiate ourselves from the init user namespace, we need to set up the uid_map/gid_map like:
```
0 0 1
1 1 UINT32_MAX - 1
```

as the init user namedspace uses `0 0 UINT32_MAX` and some applications - like systemd itself - determine if its a non-init user namespace based on uid_map/gid_map files.

Fixes: #35168

2024-11-15 16:05 UTC, DaanDeMeyer approved these changes

2024-11-15 20:28 UTC, poettering commented on src/core/exec-invoke.c
> +                r = asprintf(&uid_map, "0 0 1\n1 1 " UID_FMT "\n", UINT32_MAX - 1);
please format this with a line break, i.e:

```c
r = asprintf(&uid_map, "0 0 1\n"
                       "1 1 " UID_FMT "\n", UINT32_MAX - 1);
```

2024-11-15 20:28 UTC, poettering commented on src/core/exec-invoke.c
> +                r = asprintf(&gid_map, "0 0 1\n1 1 " UID_FMT "\n", UINT32_MAX - 1);
ditto

2024-11-15 22:05 UTC, bluca commented
This is a new option so it's really material for 258

2024-11-15 22:22 UTC, ryantimwilson commented
@bluca yea waiting for 258 is fine. I assumed there was another 257 branch but guess we just use main, then branch after all RC releases? Anyways, I'm fine to wait

2024-11-30 22:29 UTC, ryantimwilson commented
@poettering @DaanDeMeyer I'm requesting a re-review from you since this PR isn't merged yet.

I added a second commit in the PR to fix: https://github.com/systemd/systemd/issues/35425. TL;DR: PrivateUsers=full also sets /proc/pid/setgroups = "allow"

I decided against adding another setting ProtectGetGroups since 1) It would be duplicative of SystemCallFilter (in terms of result) 2) The semantics of ProtectGetGroups= were confusing since it was so highly tied to user namespaces

Happy to hear other ideas/approaches!

2024-12-01 05:36 UTC, yuwata commented on src/core/exec-invoke.c
> +                r = setup_private_users(pu, saved_uid, saved_gid, uid, gid, false /*allow_setgroups=*/);
Spurious order of the short comment: `/*allow_setgroups=*/ false`

2024-12-04 15:30 UTC, yuwata requested changes

2024-12-04 15:30 UTC, yuwata commented on src/core/exec-invoke.c
> +                                        context->private_users == PRIVATE_USERS_FULL);
Please also add short comment for the boolean: `/* allow_setgroups = */`

2024-12-04 17:02 UTC, ryantimwilson commented
@yuwata nice, didn't see that PR, yes lets remove the hack then

The only gotcha is while Meta deploys 258, we will be booting containers with 257 (aka without https://github.com/systemd/systemd/pull/35382). But we can always add a hotpatch on our Meta build to use the old hack - agree that upstream doesn't need to support the hack

2024-12-04 17:36 UTC, ryantimwilson commented
@DaanDeMeyer @yuwata maybe a compromise - we can keep the old version but add a TODO to remove this in 259?

2024-12-04 18:46 UTC, yuwata commented
> > @yuwata nice, didn't see that PR, yes lets remove the hack then
> > The only gotcha is while Meta deploys 258, we will be booting containers with 257 (aka without #35382). But we can always add a hotpatch on our Meta build to use the old hack until we're fully on 258 - agree that upstream doesn't need to support the hack
> 
> Frankly I find this a good argument to keep the previous approach. The code is trivial and it makes sure we keep compat with older versions of systemd running in containers or other sandboxes that still use the old heuristics. @yuwata What do you think?

Not a strong opinion, but I do not think it is necessary. The PR #35382 just drops old heuristic logic about userns. In v257, we already have a2429f507ca72278bb6d2893b58906ab313d6e0c, and that should enough to detect non-init userns.
If you want to only run v257 (or newer) containers on `PrivateUsers=full`, then such workaround is not necessary. The workaround is only necessary If you want to run not-patched v256 (or older) containers.

2024-12-04 19:05 UTC, ryantimwilson commented
@yuwata the problem with https://github.com/systemd/systemd/commit/a2429f507ca72278bb6d2893b58906ab313d6e0c#diff-d5b6c9503f12e3cfcc77bbdc2e1184b772ccedbaa2826605a5a3dae0dbd9149fR893 in a container with PrivateUsers=full is that `namespace_is_init(NAMESPACE_USER)` will return `0` and we will fall through to the other heuristics and will do the uid_map/gid_map check. https://github.com/systemd/systemd/pull/35382 will fix this correctly by removing the other heuristics.

So unfortunately, this will affect containers with 256+257.

If you don't mind, I'll revert to the previous hack but add a comment on why and to remove this in 259.

2024-12-04 19:17 UTC, yuwata commented
Ah, indeed. Bad... OK. Feel free to keep the maps as previous.

2024-12-04 19:40 UTC, YHNdnzj approved these changes

2024-12-04 19:40 UTC, YHNdnzj commented on src/core/exec-invoke.c
> +                                       "1 1 " UID_FMT "\n", UINT32_MAX - 1);
Please cast `UINT32_MAX - 1` to uid_t. We prefer being explicit for typedef-ed types.

2024-12-04 19:40 UTC, YHNdnzj commented on src/core/exec-invoke.c
> +                                       "1 1 " UID_FMT "\n", UINT32_MAX - 1);
GID_FMT and cast to gid_t

2024-12-04 19:40 UTC, YHNdnzj commented on src/core/exec-invoke.c
> +                                        /*allow_setgroups=*/ context->private_users == PRIVATE_USERS_FULL);
```suggestion
                                        /* allow_setgroups= */ context->private_users == PRIVATE_USERS_FULL);
```

2024-12-12 11:38 UTC, DaanDeMeyer commented
I made the logic of the second commit slightly cleaner (It's what I would have requested in a review if ryan was available, but as he isn't I just pushed the fix to this PR). Setting the green label.

2024-12-13 12:23 UTC, bluca approved these changes

2024-12-13 12:25 UTC, merged