core/unit: ignore timeouts for GetNameOwner()
systemd/systemd pull request #35450
Opened 2024-12-03 01:05 UTC by rpigott

This method call may timeout, but a timeout here is unnecessarily fatal for the unit whose bus name we are trying to monitor. Let's just log about it and continue. If the NameOwnerChanged match is installed successfully, we should get a notification eventually about the bus name. If it fails, we will lose our connection to the bus and have to set up the watch again anyway.

---

This is my suggestion from https://github.com/systemd/systemd/issues/32381#issuecomment-2494704753

Fixes: #32381 (by ignoring it)

2024-12-03 07:19 UTC, YHNdnzj reviewed
> If the NameOwnerChanged match is installed successfully, we should get a notification eventually about the bus name.

This disregards the deserialization during daemon-reexec though? We must re-acquire bus name through GetNameOwner() in that case.

2024-12-03 08:51 UTC, yuwata requested changes
I cannot follow. The previous code already ignore failures unconditionally...

2024-12-03 08:51 UTC, yuwata commented on src/core/unit.c
> -                new_owner = NULL;
On error path, uninitialized value will be passed to `UNIT_VTABLE(u)->bus_name_owner_change()`.

2024-12-03 09:26 UTC, rpigott commented
> This disregards the deserialization during daemon-reexec though? We must re-acquire bus name through GetNameOwner() in that case.

Hm I think you're right. I didn't consider reexec.

> I cannot follow. The previous code already ignore failures unconditionally...

No it doesn't? When new_owner = NULL the bus name appears to have been lost, and the dbus service is terminated by systemd. That's what is reported in #32381, right? Seems like a bit of an overreaction from systemd here. Since the service is very likely still fine, I think we should try to recover more gracefully here.

2024-12-03 09:35 UTC, rpigott commented
> > This disregards the deserialization during daemon-reexec though? We must re-acquire bus name through GetNameOwner() in that case.

> Hm I think you're right. I didn't consider reexec.

Perhaps we can just return the unit to the load queue in this case?

2024-12-03 10:21 UTC, yuwata requested changes

2024-12-03 10:21 UTC, yuwata commented on src/core/unit.c
> +                                        bus_error_message(e, r));
- Spurious line break ?
- Please add comments why we ignore the errors here.
- This is a callback. So please return 0 and do not propagate the negative errno.

2024-12-03 10:49 UTC, rpigott commented
Now that I'm looking at it, is this function not already racy as-written? It seems historically synchronous bus calls were used to install the match and then call GetNameOwner.

But with both calls made asynchronously, is it not possible for GetNameOwner to return first, the name to change, and then the match installed? Maybe we should move GetNameOwner into the install callback?

2024-12-10 16:41 UTC, rpigott commented
> This disregards the deserialization during daemon-reexec though? We must re-acquire bus name through GetNameOwner() in that case.

OK, so I guess a reasonable strategy then is just to nuke the bus connection and let it recover, just as it would from a timeout in the AddMatch above. Kinda meh, but certainly better than terminating the units anyway. PTAL.

I think it's really unexpected that GetNameOwner would fail with a timeout but AddMatch would not, so I suspect we never actually have to take action in this case.

2024-12-14 22:15 UTC, rpigott commented
OK so now I only bother to ignore the timeout if the bus connection really is closed. This should be correct even in the case of daemon-reexec (though it may still be possible for a disconnect during daemon-reexec to cause us to terminate the unit, then).

I think all three of these changes are reasonable, but they are also mostly independent so we could take just some of them if you want. PTAL.

2025-01-07 21:14 UTC, rpigott commented
Ok, looks like the first commit was effectively implemented in 37ce3fd2b7dd.

2025-05-13 18:44 UTC, closed without merging