TEST-50-DISSECT: always use systemd-notify to send notify message
systemd/systemd pull request #35652
Opened 2024-12-17 06:17 UTC by yuwata

Follow-up for d0a63cf0412ccb9b4edd1f6048e25aa7f68b0133.
Fixes #35619.

2024-12-17 07:50 UTC, DaanDeMeyer approved these changes
Having a non flaky test seems more important than testing the notify socket protocol without systemd-notify in this case. We can always add that back in a dedicated test for systemd-notify. This test is about making sure the notify socket is mounted at the right location in the sandbox, not about the notify socket protocol itself. And I double checked that systemd-notify uses the BARRIER=1 protocol which should eliminate all races.

2024-12-17 07:51 UTC, daandemeyer commented on test/units/TEST-50-DISSECT.dissect.sh
> +mkdir -p /tmp/img
Seems `unsquashfs` will create the directory itself and this causes the test to fail.

2024-12-17 09:44 UTC, bluca commented
> Having a non flaky test seems more important than testing the notify socket protocol without systemd-notify in this case. We can always add that back in a dedicated test for systemd-notify. This test is about making sure the notify socket is mounted at the right location in the sandbox, not about the notify socket protocol itself. And I double checked that systemd-notify uses the BARRIER=1 protocol which should eliminate all races.

If that's all it needs to do, then just do `test -S` instead, that will be enough to verify the socket is available. The builds are already very slow as it is, adding the systemd package and all its dependencies to this image will make them even slower.

2024-12-17 10:00 UTC, DaanDeMeyer commented
> > Having a non flaky test seems more important than testing the notify socket protocol without systemd-notify in this case. We can always add that back in a dedicated test for systemd-notify. This test is about making sure the notify socket is mounted at the right location in the sandbox, not about the notify socket protocol itself. And I double checked that systemd-notify uses the BARRIER=1 protocol which should eliminate all races.
> 
> If that's all it needs to do, then just do `test -S` instead, that will be enough to verify the socket is available. The builds are already very slow as it is, adding the systemd package and all its dependencies to this image will make them even slower.

Without this PR: https://github.com/systemd/systemd/actions/runs/12366308331/job/34512776149
With this PR: https://github.com/systemd/systemd/actions/runs/12367485430/job/34515871742?pr=35652

No difference at all in image build time and test runtime

2024-12-17 10:21 UTC, bluca commented
An extra 10 seconds here, and almost 20M increase in size

2024-12-18 01:54 UTC, yuwata commented
> An extra 10 seconds here, and almost 20M increase in size

That Should not impact anything.
E.g. TEST-73-LOCALE takes about 500 sec on fedora, and 1000 sec on rawhide with sanitizers. So, extra 10 seconds on building image should not impact whole test performance.
Also, the uncompressed main image size is 9.1G for fedora rawhide. Additional 20M can be negligible.

2024-12-18 11:35 UTC, bluca commented
> > An extra 10 seconds here, and almost 20M increase in size
> 
> That Should not impact anything. E.g. TEST-73-LOCALE takes about 500 sec on fedora, and 1000 sec on rawhide with sanitizers. So, extra 10 seconds on building image should not impact whole test performance. Also, the uncompressed main image size is 9.1G for fedora rawhide. Additional 20M can be negligible.

Those are test runs times, I am talking about build times, which are paid every time a rebuild is done, given these images are always built. And the minimal image is supposed to be minimal, it's not really minimal anymore if the whole kitchen sink is thrown into it.
Again if the purpose is to check the socket being mounted, just do `test -S`? Simpler and less error prone.

2024-12-18 12:59 UTC, yuwata commented
OK. Made the minimal image minimal again. PTAL.

2024-12-18 13:09 UTC, DaanDeMeyer requested changes
I don't think this will work, the socket won't be at /run/host/notify unless Type=notify is used. And if Type=notify is used, `systemd-run` will fail with a protocol error unless the service properly sends `READY=1`

2024-12-18 13:12 UTC, DaanDeMeyer commented
So given we can't properly implement the notify socket protocol race free in bash and we have to use `Type=notify`, maybe we can protocol error exit code from `systemd-run` if it's different from the exit code from `test -S`?

2024-12-18 13:15 UTC, bluca commented
> I don't think this will work, the socket won't be at /run/host/notify unless Type=notify is used. And if Type=notify is used, `systemd-run` will fail with a protocol error unless the service properly sends `READY=1`

Mmh should we just mount it unconditionally then? In the end the notify protocol is also useful for sending status updates that are shown by "systemctl status"

2024-12-18 13:20 UTC, DaanDeMeyer commented
Actually I misspoke, it seems to be gated purely on the value of `NotifyAccess=`, so this might work after all

2024-12-18 14:17 UTC, bluca approved these changes

2024-12-18 14:50 UTC, merged