nspawn: support unpriv directory-tree containers
systemd/systemd pull request #35685
Opened 2024-12-19 14:31 UTC by poettering

So far nspawn supported unpriv containers only if backed by a DDI. This adds dir-based unpriv containers too.

To make this work this introduces a new UID concept to systemd: the "foreign UID range". This is a high UID range of size 64K. The idea is that disk images that are "foreign" to the local system can use that, and when a container or similar is invoked from it, a transiently allocated dynamic UID range is mapped from that foreign UID range via id mapped mounts.

This means the fully dynamic, transient UID ranges never hit the disk, which should vastly simplify management, and does not require that uid "subranges" are persistently delegated to any users.

The mountfsd daemon gained a new method call for acquiring an idmapped mount fd for an mount tree owned by the foreign UID range. Access is permitted to unpriv clients – as long as the referenced inode is located within a dir owned by client's own uid range.

2024-12-19 15:24 UTC, DaanDeMeyer commented
Can you write down how I would use this for `mkosi boot`? After a directory image build I end up with a root directory with all files owned by my own user. I want to run a container from that directory unprivileged by invoking systemd-nspawn. Will that work with this somehow?

2024-12-20 17:21 UTC, poettering commented
> Can you write down how I would use this for `mkosi boot`? After a directory image build I end up with a root directory with all files owned by my own user. I want to run a container from that directory unprivileged by invoking systemd-nspawn. Will that work with this somehow?

so for any of this to work you'd have to pass owenership of that dir to the foreign UID range. I think the right way to do that would be to already start out like that. i.e. in mkosi you'd ask for a userns range from nsresourced, and then ask mountfsd to get a dir created in the user's home dir with the right ownership. But here's the thing: for the latter there's currently no api. 

right now you have to invoked "systemd-dissect --shift …" to pass ownership explicitly, but that requires privs...

anyway this will take a bit more work to be fully complete, it's too early to get mkosi moved over to this yet I'd say.

2024-12-20 20:04 UTC, DaanDeMeyer commented
> > Can you write down how I would use this for `mkosi boot`? After a directory image build I end up with a root directory with all files owned by my own user. I want to run a container from that directory unprivileged by invoking systemd-nspawn. Will that work with this somehow?
> 
> so for any of this to work you'd have to pass owenership of that dir to the foreign UID range. I think the right way to do that would be to already start out like that. i.e. in mkosi you'd ask for a userns range from nsresourced, and then ask mountfsd to get a dir created in the user's home dir with the right ownership. But here's the thing: for the latter there's currently no api. 
> 
> right now you have to invoked "systemd-dissect --shift …" to pass ownership explicitly, but that requires privs...
> 
> anyway this will take a bit more work to be fully complete, it's too early to get mkosi moved over to this yet I'd say.

Will the user still be able to remove those files without privs after shifting ownership? Though tbf that doesn't work now either because permissions on base directories are too strict in distributions.

2024-12-20 21:06 UTC, poettering commented
> Will the user still be able to remove those files without privs after shifting ownership? Though tbf that doesn't work now either because permissions on base directories are too strict in distributions.

on UNIX an unpriv user can remove a dir owned by another user, if it's place inside a directory the unpriv user owns – as long as that dir is empty. Hence, in order to be able to remove a container tree you'll effectively need some tool that first acquires an idmapping mount for the tree to kill, then removes all files within the dir, then releases the idmapping mount. the dir is now empty (but still owned by the foreign UID range), and can hence be removed directly by the user.

2024-12-23 05:32 UTC, yuwata reviewed
Too big... Could you split this into small PRs? Also, CIs are unhappy.

2025-01-22 19:42 UTC, yuwata requested changes

2025-01-22 19:42 UTC, yuwata commented on src/mountfsd/mountwork.c
> +enum {
I'd like to typedef the enum, then `default_mount_map_mode()` should take the enum, rather than int.

2025-01-22 19:42 UTC, yuwata commented on src/mountfsd/mountwork.c
> +        if (p.directory_fd_idx != UINT_MAX) {
If `directoryFileDescriptor` is UINT_MAX, then `directory_fd` is `-EBADF`, and `validate_directory_fd()` triggers assertion.
Please explicitly return an error when `p.directory_fd_idx == UINT_MAX`.

2025-01-22 19:42 UTC, yuwata commented on src/mountfsd/mountwork.c
> +        if (p.mode < 0 || p.mode == MOUNT_MAP_AUTO) {
Maybe, better to make `MOUNT_MAP_AUTO` zero, that is, list it at first in the definition of the enum? Then, we can make the condition `p.mode <= 0`, and `MOUNT_MAP_AUTO` can be used in the initializer of `MountDirectoryParameters` in the above.

2025-01-22 19:42 UTC, yuwata commented on src/mountfsd/mountwork.c
> +                        "io.systemd.MountFileSystem.MountDirectory", vl_method_mount_directory);
Please align.

2025-01-22 19:42 UTC, yuwata commented on src/shared/varlink-io.systemd.MountFileSystem.c
> +                SD_VARLINK_SYMBOL_COMMENT("Selects the type of UID/GID mapping to apply"),
Missing period.

2025-01-22 19:42 UTC, yuwata commented on src/shared/varlink-io.systemd.MountFileSystem.c
> +                &vl_type_MountMapMode,
Not a matter, but maybe better to first list types, then methods, finally errors ?

2025-01-22 19:42 UTC, yuwata commented on src/shared/varlink-io.systemd.MountFileSystem.c
> +                SD_VARLINK_DEFINE_ENUM_VALUE(root),
No comments?

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
>  static int outer_child(
commit message: THis -> This

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn-settings.c
>  DEFINE_CONFIG_PARSE_ENUM(config_parse_userns_ownership, user_namespace_ownership, UserNamespaceOwnership);
commit message: lik -> like

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn-cgroup.c
>                  CGroupUnified unified_requested,
commit message: 
we can also user -> we can also use
numbre of codepaths -> number of codepaths

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn-mount.c
>                  /* If we are not privileged but the entry is marked as privileged and to be mounted outside the user namespace, then skip it */
Please update the comment.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
> +                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Unprivileged operation requires private networking, as otherwise /sys/ may not be mounted.");
Maybe, `Unprivileged operation requires` -> `managed user namespaces requires` ??

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
>                  log_debug("Not digging mount tunnel, because running unprivileged.");
Please update the log message.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
>                  log_debug("Not opening up mount tunnel, because running unprivileged.");
Also here.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
> +                log_notice("AFTER");
Are they for debugging ?? Please drop them.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
>                  log_debug("Not digging socket tunnel, because running unprivileged.");
Please update the log message.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
> +                        (gid_t) chown_uid);
Not a matter, but I'd like to make it inline, not necessary to break the line.

2025-01-22 19:42 UTC, yuwata commented on src/nspawn/nspawn.c
>                          /* In unprivileged operation, sysfs + procfs are special, we'll have to mount them
Please update the comment. `unprivileged operation` -> `managed namespace operation`

2025-01-22 20:04 UTC, yuwata commented
BTW, is it not necessary to add modprobe service dependencies in mountfsd.service ?

2025-01-22 20:06 UTC, yuwata commented on src/mountfsd/mountwork.c
> +         * the foreign UID range and within another dir owned by the peer). Returns 0 if it's owened by
The return values in the comment are outdated.

2025-01-23 13:56 UTC, poettering commented
> BTW, is it not necessary to add modprobe service dependencies in mountfsd.service ?

→ #36132

2025-01-23 18:44 UTC, yuwata commented on src/mountfsd/mountwork.c
> +        log_debug("Mount with mapping mode: %s", mount_map_mode_to_string(p.mode));
Maybe better to swap the order with fd_get_path() below and include the path that `directory_fd` points to in the log message?

2025-01-23 18:45 UTC, yuwata commented on src/mountfsd/mountwork.c
> +                "read_only", one_zero(p.read_only > 0),
yes_no ?

2025-01-23 18:48 UTC, yuwata commented on src/mountfsd/mountwork.c
> +        r = get_common_dissect_directory(NULL);
Not a big matter, but this looks spurious. Please add a short comment that this prepares dissect directory ?

2025-01-23 18:49 UTC, yuwata commented on src/mountfsd/mountwork.c
> +                return log_debug_errno(errno, "Failed to issue open_tree() of provided directory: %m");
Better to include the path to directory ?

2025-01-23 18:54 UTC, yuwata commented on src/mountfsd/mountwork.c
> +                }
Missing error check.

2025-01-23 18:57 UTC, yuwata commented on src/shared/varlink-io.systemd.MountFileSystem.c
> +                SD_VARLINK_FIELD_COMMENT("Whether to mark the resulting mount file descriptor as read-only."),
Maybe better to mention that defaults to false ?

2025-01-23 19:00 UTC, yuwata commented on src/shared/dissect-image.c
> +} MountDirectoryReplyParameters;
Not a matter, but this is not necessary, and an unsigned can be directly passed to the dispatcher.

2025-01-23 19:01 UTC, yuwata commented on src/shared/dissect-image.c
> +        };
Not a matter, but I'd like to move this to mostly end of this function before dispatching.

2025-01-23 19:12 UTC, yuwata commented on src/nspawn/nspawn.c
> +               "     --private-users=yes|pick|identity|managed\n"
Please update shell completion, at least for bash. Fix should be simple.

2025-01-23 20:41 UTC, poettering commented on src/mountfsd/mountwork.c
> +                "read_only", one_zero(p.read_only > 0),
in similar cases where we pass a boolean as polkit "detail" we already used one_zero(), including in mountwork.c itself, hence I think we should stick to that.

moreover, I think given that this data is mostly for consumption by polkit js scripts I think it kinda makes sense to use one_zero() given it is more "programmatic" and less "human-languagy" than yes_no()

2025-01-23 21:02 UTC, yuwata commented on src/mountfsd/mountwork.c
> +                "read_only", one_zero(p.read_only > 0),
OK. Makes sense to me.

2025-01-23 22:34 UTC, merged