shell-completion: add bash completion for userdbctl
systemd/systemd pull request #35720
Opened 2024-12-21 20:58 UTC by jdholtz

Closes #35660.

2024-12-21 22:45 UTC, bluca commented
Needs to be listed in `shell-completion/bash/meson.build` otherwise it won't be installed

2024-12-21 23:30 UTC, bluca approved these changes

2024-12-22 00:29 UTC, yuwata requested changes

2024-12-22 00:29 UTC, yuwata commented on shell-completion/bash/userdbctl
> +__get_all_users () { userdbctl user --no-legend -B | { while read -r a b; do printf "%s\n" "$a"; done; } ; }
Please break the line. Also, use `local a b` for safety.

2024-12-22 00:29 UTC, yuwata commented on shell-completion/bash/userdbctl
> +__get_all_groups () { userdbctl group --no-legend -B | { while read -r a b; do printf "%s\n" "$a"; done; } ; }
Also here. Moreover, please insert an empty line between function defs.

2024-12-22 00:29 UTC, yuwata commented on shell-completion/bash/userdbctl
> +                comps='true false'
Please use yes and no.

2024-12-22 00:29 UTC, yuwata commented on shell-completion/bash/userdbctl
> +
Doubled empty lines

2024-12-22 17:24 UTC, merged