hwids: add a new efi firmware type of device entry
systemd/systemd pull request #35747
Opened 2024-12-24 14:17 UTC by ani-sinha

This change adds a new firmware type device entry for the .hwids section.
It also adds compile time validations and appropriate unit tests for them.
chid_match() and related helpers have been updated accordingly.

Duplicate of https://github.com/systemd/systemd/pull/35281

2024-12-24 15:46 UTC, anonymix007 approved these changes

2024-12-27 01:38 UTC, ani-sinha commented
@yuwata please take a look at this PR. It's been reviewed already.

2024-12-30 10:33 UTC, ani-sinha commented
Ping @poettering

2025-01-02 00:49 UTC, yuwata requested changes
Sorry for late review. Several superficial coding style comments.

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.c
> +                if ((dev_type != DEVICE_TYPE_FW) && (dev_type != DEVICE_TYPE_DEVICETREE))
Please use `IN_SET()` macro, then you can drop `dev_type`:
```c
if (!IN_SET(DEVICE_TYPE_FROM_DESCRIPTOR(devices[n_devices].descriptor), 
            DEVICE_TYPE_FW, DEVICE_TYPE_DEVICETREE))
```

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.h
> +        DEVICE_TYPE_FW, /* a firmware blob */
Please explicitly specify the value:
```c
DEVICE_TYPE_FW = 0x2,
```

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.h
> +                           They are nul-terminated strings when present or 0 if not present */
Not a matter, but please insert a `*` at the beginning of the line, like other comments.

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.h
> +                        uint32_t compatible_offset; /* compatibility identifier to match a specific fw blob */
Please align the comment.

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.h
> +        {
Please locate `{` at the end of the previous line:
```c
switch (DEVICE_TYPE_FROM_DESCRIPTOR(device->descriptor)) {
```

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.h
> +        {
Also here.

2025-01-02 00:49 UTC, yuwata commented on src/boot/chid.c
>                          EFI_GUID chid = dev->chid;
Maybe not necessary to declare `chid` ??

2025-01-02 03:55 UTC, ani-sinha commented on src/boot/chid.c
>                          EFI_GUID chid = dev->chid;
I have not changed that line in my patch.

2025-01-02 04:39 UTC, yuwata commented on src/boot/chid.c
>                          EFI_GUID chid = dev->chid;
Right. I just commented in the case if you want to address it. Feel free to ignore.

2025-01-02 04:44 UTC, yuwata approved these changes
Superficially LGTM. One more minor request.

I am not familiar with the functionality. Leaves the merging to @poettering.

2025-01-02 04:44 UTC, yuwata commented on src/boot/chid.h
> +        DEVICE_TYPE_FW = 0x2, /* a firmware blob */
Please align with `=`.

2025-01-02 07:08 UTC, anonymix007 commented on src/boot/chid.c
>                          EFI_GUID chid = dev->chid;
There's literally a comment explaining why it's here...

2025-01-02 07:21 UTC, ani-sinha commented on src/boot/chid.c
>                          EFI_GUID chid = dev->chid;
right.

2025-01-02 16:59 UTC, poettering commented
ah, this is a resubmission of https://github.com/systemd/systemd/pull/35281?

2025-01-02 17:04 UTC, poettering commented on src/boot/chid.h
> +        DEVICE_TYPE_FW         = 0x2, /* A firmware blob */
i'd probably rename this to DEVICE_TYPE_UEFI_FW or so, i.e. make this just about uefi for now. if we later on add support for other types of fw, we can then add more types like this. otherwise we have to add a secondary fw type field somewhere, and I think it would be simpler to just have a single field which indicates both that this is a firmware, and what kind of firmware it is.

2025-01-02 17:05 UTC, poettering commented on src/boot/chid.h
> +                        uint32_t compatible_offset; /* compatibility identifier to match a specific fw blob */
so, my understanding is that the "compatible" field here is supposed to be some string that we look for in the uefi firmware blob metadata, right? maybe call that fwid or so? 

i think thta would make things clearer, since this has nothing to do with the devicetree "compatible" string...

2025-01-02 17:08 UTC, ani-sinha commented on src/boot/chid.h
> +                        uint32_t compatible_offset; /* compatibility identifier to match a specific fw blob */
> so, my understanding is that the "compatible" field here is supposed to be some string that we look for in the uefi firmware blob metadata, right?

Right. We had that hashed out in the other PR I sent.

2025-01-02 17:25 UTC, ani-sinha commented
> ah, this is a resubmission of https://github.com/systemd/systemd/pull/35281?

Yea.

2025-01-03 11:30 UTC, poettering commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
you shouldn't return the fwid if the "compatible" string is requested. The concept does not exist for this firmware entries, hence just do `return NULL;` here. that makes the most sense.

2025-01-03 11:31 UTC, poettering commented on src/boot/chid.h
> +                } fw;
rename this field fw → uefi_fw to match the renamed enum.

2025-01-03 12:35 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
So `ukify.py` and adjoining code also needs to know that. See `parse_hwid_dir()` . That would be another big change I think.

2025-01-03 12:36 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
Then `# (devtype, name, compatible) pair uniquely identifies the device ` is no longer true.

2025-01-03 12:37 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
I wish I could get some help in wrapping up this work. It does not seem to be converging but more work is getting added :(

2025-01-03 12:46 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
`pack_device()` also expects `compatible`.

2025-01-03 12:52 UTC, anonymix007 commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
I think the intention is to return the unique string identifier for this type of `Device`. For DT it's `compatible`, for FW it's `fwid`, but in the end it's just a nul-terminated string that's going to be used for matching. 
I'm not sure how to better reflect this in the code though.

2025-01-03 12:55 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
Also should we change this for fw devices? https://github.com/systemd/systemd/pull/35747/commits/66d0d10240ca549b227462159a70043e2526053f#diff-ab21a39981d4e3e22fdb11c4ae48bec631b51db70c5aed141ed54b4f9ea12764R4

2025-01-03 13:08 UTC, ani-sinha commented
I pushed the changes suggested by @poettering but I think `ukify.py` needs work to accept fwid for fw devices.

2025-01-03 14:18 UTC, poettering commented on src/boot/hwids/device4.json
> +    "type": "firmware",
should be updated to `"type": "uefi-fw"`

2025-01-03 14:18 UTC, poettering commented on src/boot/hwids/device4.json
> +    "compatible": "test,vmware",
should be changed to `"fwid" : "...."`

2025-01-03 14:19 UTC, poettering commented on src/ukify/ukify.py
> +        'firmware': DEVICE_TYPE_UEFI_FW,
uefi-fw

2025-01-03 14:22 UTC, ani-sinha commented
These are cosmetic changes. Please see my other concern above

2025-01-03 14:24 UTC, ani-sinha commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
@poettering

2025-01-03 14:31 UTC, poettering commented on src/boot/chid.h
> +                off = device->fw.fwid_offset;
i am not a python guru, i cannot comment on the best, most pythonic way to implement this in ukify. @keszybz can you help?

you could just name the field compatible_or_hwid in the ukify code? slightly hacky but if you ask me ok. otherwise it probably should be some dict that contains either one field or another, instead of a tuple...

2025-01-03 14:32 UTC, ani-sinha commented on src/boot/hwids/device4.json
> +    "compatible": "test,vmware",
Yes when you change this, it invites lots of more work in ukify.py.

2025-01-03 14:39 UTC, poettering commented
these are api relevant changes, we should get those right from the beginning.

2025-01-03 14:45 UTC, ani-sinha commented
> these are api relevant changes, we should get those right from the beginning.

by cosmetic, I meant changes like `"type": "uefi-fw"`

2025-01-03 14:49 UTC, ani-sinha commented on src/boot/hwids/device4.json
> +    "compatible": "test,vmware",
I will try to fix this somehow.

2025-01-04 03:10 UTC, ani-sinha commented
> these are api relevant changes, we should get those right from the beginning.

Ok made the changes to ukify. Not a python expert so maybe some of it is not quite pythonic. Tests are passing.

2025-01-08 21:31 UTC, merged