Follow-ups for recent PRs plus modernizations prompted thereby
systemd/systemd pull request #35760
Opened 2024-12-26 19:55 UTC by YHNdnzj

2024-12-28 03:39 UTC, yuwata requested changes

2024-12-28 03:39 UTC, yuwata commented on src/core/unit-serialize.c
> +                        fputs_with_separator(f, unit_marker_to_string(m), /* separator = */ NULL, &space);
Please mention the commit hash that causes the issue in the commit message. Then, we can easily backport the fix.

2024-12-28 03:39 UTC, yuwata commented on src/basic/capability-util.c
> +                                  " suppressing automatically.", capability_to_name(i));
I prefer to not break error message into multiple lines, even if the line exceeds the 109ch limit.
Then, we can easily grep code by the log message.

2024-12-28 14:24 UTC, yuwata approved these changes

2024-12-30 15:35 UTC, merged

2025-01-02 11:11 UTC, poettering commented
lgtm