Fixes & improvments for using homed-luks on 4k disks
systemd/systemd pull request #35776
Opened 2024-12-28 08:23 UTC by scarlet-storm

Mostly consists of fixes to 

- use the same sector_size as the fdisk context we are using, when converting between sectors returned by libfdisk to bytes. Fixes #30394 , Fixes #30393 
- Use the explicit sector size if specified in the home record when are probing the image file using libblkid. Fixes #30393 

Also contains some other improvements with using physical block devices.

- Automatically probe sector size of physical block device, if user does not pass luks-sector-size explicitly.
- Assign partitions to 1 MiB boundaries, as it is the standard practice followed by all tools, fdisk, gptfdisk, gnu parted etc.
- Avoid stacking of loop device on top of physical block device in home_create_luks as it leads to degradation of discard operations, and mkfs getting stuck.

2025-01-03 11:34 UTC, poettering commented on src/home/homework-luks.c
> +#include <libfdisk.h>
we so far don't include this directly but only via fdisk-util.h. no need to change that...

2025-01-03 11:36 UTC, poettering commented on src/home/homework-luks.c
> +        // Use same sector size as the fdisk context when converting to bytes
coding style: in our tree we use `/* */` style coments for explanatory stuff, and `//` style comments for "fixme" style stuff. this here is explanatory, hence please change comment style.

(coding style is documented here: https://systemd.io/CODING_STYLE)

2025-01-03 11:38 UTC, poettering commented on src/home/homework-luks.c
> +        assert(fdisk_sector_size);
coding style: for arithmetic values we prefer explicit non-null comparisons. only for bools (and boolean-like values) and pointers we are fine with using C's "downgrade-to-bool" syntax.

or in other words:

`assert(fdisk_sector_size > 0);`

here please

2025-01-03 11:38 UTC, poettering commented on src/home/homework-luks.c
> +                assert(fdisk_sector_size);
as above

2025-01-03 11:39 UTC, poettering commented on src/home/homework-luks.c
> +        fdisk_sector_t fdisk_sector_size;
that's such a weird type. I think it would be better to just use uint64_t here.

and maybe drop the "fdisk" prefix, we don't name ther other fields we retrieve from libfdisk with such a prefix either

2025-01-03 11:41 UTC, poettering commented on src/home/homework-luks.c
> -
why remove this? i added this explicitly because libfdisk got confused by the old partition table, and its pmbr.

2025-01-03 11:41 UTC, poettering commented on src/home/homework-luks.c
> +        fdisk_sector_t fdisk_sector_size;
as above, just use uint64_t and drop the fdisk prefix

2025-01-03 11:42 UTC, poettering commented on src/home/homework-luks.c
> +        if ( h->luks_sector_size == UINT64_MAX) {
spurious space

2025-01-03 11:43 UTC, poettering commented on src/home/homework-luks.c
> +        }
coding style: no {} around single line if blocks

2025-01-03 11:48 UTC, poettering commented on src/home/homework-luks.c
> +        }
indetnation is off

2025-01-03 11:49 UTC, poettering commented on src/home/homework-luks.c
> +                image_sector_size = UINT32_MAX;
man, this type confusion everywhere is confusing. libcryptsetup wants 32bit, libfdisk wants somathing opaque. I am pretty sure we should just use uint64_t everywhere and convert to the right types at the latest moment possible.

hence I think we should really use UINT64_MAX here for probing, and then inside of image_sector_size() map that to UINT32_MAX (and refuse any values > UINT32_MAX and < UINT64_MAX

2025-01-03 11:51 UTC, poettering commented on src/home/homework-luks.c
> +                image_sector_size = UINT32_MAX;
ah, christ, our own loop_device_make() already gets that wrong... grmbl. i guess it's fine then to leave that cleanup to another day

2025-01-03 11:53 UTC, poettering commented on src/home/homework-luks.c
> +                        &size);
we indent function parameters to twice the regular indentation, according to our coding style

2025-01-03 11:55 UTC, poettering commented on src/home/homework-luks.c
> +        /* libblkid returns partitions size in count of 512-sectors */
maybe emphasize that this is *not* the native sector size

2025-01-03 12:00 UTC, poettering commented on src/home/homework-luks.c
> +         * if the device does not support discard_zeroes_data */
i am not sure i get this. wouldn't the more correct fix to simply disable discard on the loopback device if the underlying device cannot do this?

2025-01-03 12:01 UTC, poettering commented on src/home/homework-luks.c
> +                }
coding style: no {} around single line if blocks

2025-01-03 12:01 UTC, poettering commented on src/home/homework-luks.c
> +                        &setup->loop);
coding style: please indent function param lists to double the usual indentation

2025-01-03 12:04 UTC, poettering commented
hmm, i am tempted to say we should use 4k sectors everywhere by default, unless specified in the user record otherwiwse. (and of course the gpt partition table should use the native sector size if we are talking about raw block devices).

afaik there's now downside of using larger sector sizes on the luks and fs level, but it makes our images more portable...

2025-01-04 08:37 UTC, scarlet-storm commented
> hmm, i am tempted to say we should use 4k sectors everywhere by default, unless specified in the user record otherwiwse. (and of course the gpt partition table should use the native sector size if we are talking about raw block devices).
> 
> afaik there's now downside of using larger sector sizes on the luks and fs level, but it makes our images more portable...

Hi, thanks for the review.
I was also thinking about using a 4k image size by default. Most of the filesystems use 4k sector size by default anyways even when the underlying sector size is 512. There should be downsides to using 4k by default for file based images.
The concerns  might be
- Small filesystems or lot of small files with sizes < 4k. xfs by default still uses a 512 default sector size, if the underlying image supports it and ext4 uses 512  sector size if filesystem < 2G iirc.
- With respect to backwards compatibility we will have to always probe image files we are opening assuming a sector size of 512 & 4k, as the image might have been created with an old version of systemd-homework. This should be fine to implement and not an issue.

Also my thoughts were that these functions can be rewritten to use an internal systemd-repart  library in the future. I think all the partition, luks & fs creation / resizing operations can be handled by the repart library. It will require creation of an repart api and add an additional dependency for homed

2025-01-04 08:40 UTC, scarlet-storm commented on src/home/homework-luks.c
> -
I did not face an issue with writing out the new partition table.  Also I was not able to understand the exact issue that the pmbr is causing from the earlier commit message. I'm not sure why fdisk wouldn't like the existing partition table.
Could you explain the issue in detail, and I will try reproducing it.

2025-01-04 08:55 UTC, scarlet-storm commented on src/home/homework-luks.c
> +         * if the device does not support discard_zeroes_data */
The problem is this
- loop device historical semantics dictates that when the device is discarded, it needs to return zero data on read. This can be implemented easily on a filesystem. since fallocate zero-range would return immediately & the holes are handled at the filesystem level to return zero data on read.
- For a raw block device, the feature (discard_zeroes_data) depends on the capabilities of the physical device that is exposed to the block device by the driver.

This means that to guarantee that the loop device stacked on a block device returns zero on discarded data, it needs to convert discarded range into write_zero on the block device.
https://github.com/torvalds/linux/blob/63676eefb7a026d04b51dcb7aaf54f358517a2ec/drivers/block/loop.c#L773
For example on a local nvme I see

cat /sys/class/block/nvme1n1/queue/write_zeroes_max_bytes
131072
cat /sys/class/block/nvme0n1/queue/discard_max_hw_bytes
2199023255040

This means maximum size of a write_zero operation can be 128KiB & maximum size of discard operation can be 2TiB. So discarding for example 1TB of data, which would be a single block device operation, gets split into 8.3 million block device operations when issued on top of loop device.
 So the issue is not with the block device supporting the feature, but loop device adding extra overhead since it's trying to add additional guarantees on the discarded data.

2025-02-26 13:31 UTC, GreyXor commented
Hi @scarlet-storm 
I have a 4k ssd and I'm interested in this patch. Do you need any tests? or do we miss anything?

2025-03-03 07:37 UTC, scarlet-storm commented
I will work on cleaning up some of the code style issues mentioned in this PR.
I think the other changes can be follow up patches.

2025-04-29 10:20 UTC, GreyXor commented
Hi @scarlet-storm,
Just wanted to check in regarding the code style cleanup and the follow-up patches you mentioned. Did you had a chance to make any progress or if there’s anything I can do to help move things forward.
Thanks!

2025-11-17 09:54 UTC, GreyXor commented
> I will work on cleaning up some of the code style issues mentioned in this PR. I think the other changes can be follow up patches.

Hello, gentle ping :) any news about it ? thank you

2025-11-18 07:47 UTC, scarlet-storm commented
I have addressed the code style issues. For the open comments

- zeroing of PMBR, I don't understand why this is needed. Could you provide a simple example to reproduce this ? I did not face any issue with allowing fdisk to write out the partition table, without zeroing.
- Changing default sector size to 4k for file based images. I think this can be taken up as part of a future PR. As I mentioned earlier, I think ideally we could rewrite the image creation to use systemd-repart

2025-11-20 09:03 UTC, keszybz commented on src/home/homework-luks.c
> -
Yeah, I think that it should be fine to drop this, if current libfdisk works without it. Maybe it was a bug in an old version, maybe it was a misunderstanding. If the issue pops up again, we'll revert the removal.

2025-11-20 09:18 UTC, keszybz reviewed
Those changes look generally reasonable, but I don't think I grok all the implications. Some small comments on style.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> + * partitions to that too. In the worst case we'll waste 1 MiB per partition that way, but I think I can live
Why do you want to do this? The commit describes what is being done, but not really why. Doing something the same as others is not enough motivation, unless the difference is causing problems.

After those changes, the comment doesn't quite make sense. The sentence about wasting 4k bytes was partially a joke. If we're wasting 1MB, a better explanation is needed.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> +                if(r != 0)
Missing space after `if`.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> +        }
Please drop {} here.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> +         * if the device does not support discard_zeroes_data */
Please put this comment in the commit message.

EDIT: this is not clear without context. I was refererring to the long comment made in the review thread, not the comment in the code.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> +                        }
This out `if (r < 0)` check is not necessary. Please dedent the check for `r == -ENONET` by one level.
And keep the block comment formatted as before, with `*` aligned.

2025-11-20 09:18 UTC, keszybz commented on src/home/homework-luks.c
> +                         *sector size. Else the partition will not be discoverable by kernel/udev. */
`* For`
`* sector`

2025-11-20 11:26 UTC, scarlet-storm commented on src/home/homework-luks.c
> +         * if the device does not support discard_zeroes_data */
I have added the explanation in the commit message. I can reword it to be more elaborate to match this thread. 716e94bd74803fb847db2065589f4ac921b5c1b2

2025-11-20 11:35 UTC, scarlet-storm commented on src/home/homework-luks.c
> +                        }
Sorry, I didn't quite understand this. Why do we not want to check if `r < 0` ?

2025-11-20 12:04 UTC, scarlet-storm commented on src/home/homework-luks.c
> +         * if the device does not support discard_zeroes_data */
I have reworded the commit in 15b92902af08bb687c91cd64618b3e24e3695e58

2025-11-20 12:08 UTC, scarlet-storm commented on src/home/homework-luks.c
> +        }
It doesn't look like this code is from HEAD

2025-11-20 12:22 UTC, scarlet-storm commented on src/home/homework-luks.c
> + * partitions to that too. In the worst case we'll waste 1 MiB per partition that way, but I think I can live
- For standardization. the code does not explicitly set the alignment when using fdisk as 4k, so by default fdisk is already using 1MiB alignment for initial partition creation. So the comment says 4k, but the created partition is already aligned to 1MiB boundary. Moreover during resize, fdisk_partition_size_explicit is called with enable=1 . This means that fdisk no longer will align the partitions. So we have a mix of partitions where the initial partition is aligned to 1MiB & if any resize is applied, the partition is aligned to 4KiB.
- As for the reason why 1MiB is used a standard partition size by all linux tools (fdisk, gparted, gptfdisk), it's probably because it is a multiple of most common sector sizes. Note that even for 4K disk, the sector size of 4k is applicable for read/write operations. Other operations like discard might have much higher granularity like 8k / 16k. Also for nand cells probably write amplification also plays a part.
- wasting 1 MiB is still a joke imo.

2025-11-20 12:26 UTC, scarlet-storm commented
> Those changes look generally reasonable, but I don't think I grok all the implications. Some small comments on style.

Thank you for the review. If there is anything particular you want to discuss in detail, let me know.

2025-11-25 16:17 UTC, poettering commented on src/home/homework-luks.c
> +        }
indentation is off

2025-11-25 16:20 UTC, keszybz commented on src/home/homework-luks.c
> +        }
> It doesn't look like this code is from HEAD

It's the code from your patch.

2025-11-25 16:22 UTC, keszybz commented on src/home/homework-luks.c
> +                }
The general structure we expect is:
```C
if (r == -ENOENT) {
 ...
} 
if (r < 0)
    return log_error_errno(r, ...);
```

2025-11-27 09:24 UTC, scarlet-storm commented on src/home/homework-luks.c
> +        }
just to clarify what I meant is this code seems to be from some old dangling commit & not HEAD of this PR.
I don't see this code in my homework-luks.c from HEAD, nor do I see this particular comment & corresponding lines in the github UI files changed tab, or in the diff of this patch
https://patch-diff.githubusercontent.com/raw/systemd/systemd/pull/35776.diff

2025-11-29 06:40 UTC, scarlet-storm commented on src/home/homework-luks.c
> +        }
This is fixed now, the diff from a earlier commit in the series, which was rewritten in later commit.

2026-01-04 19:44 UTC, yuwata commented
Sorry for late review, but now this needs to be rebased.

2026-02-04 04:35 UTC, scarlet-storm commented
@poettering , @keszybz Is there any pending action items to merge this PR ?

2026-02-13 12:39 UTC, keszybz requested changes
Looks reasonable. Still some style comments.

2026-02-13 12:39 UTC, keszybz commented on src/home/homework-luks.c
> +                return -errno;
Elsewhere in this function, we log on error. So this needs to be
`return log_error_errno(errno, "Failed to stat …`.

2026-02-17 06:43 UTC, yuwata requested changes
Several coding style requests.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +        assert(first_lba <= UINT64_MAX/fdisk_sector_size);
Please insert space around `/`.
(Yeah, it is not your fault, and we sometimes do not insert spaces for constant arithmetic, but never with variable(s).)

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +        assert(last_lba < UINT64_MAX/fdisk_sector_size);
Also here.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +        assert(start_lba <= UINT64_MAX/fdisk_sector_size);
Also here.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +        assert(last_lba < UINT64_MAX/fdisk_sector_size);
And here.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
>          r = fdisk_create_disklabel(c, "gpt");
Please insert an empty line between the error handling and the next function call.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +                r = sym_crypt_resize(setup->crypt_device, setup->dm_name, new_fs_size / 512U);
If it is not necessary to use sector size here, maybe better to add a short comment about that?

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
>          r = fdisk_create_disklabel(c, "gpt");
Oh you did it in the second commit. Please move to the first commit.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +#define DISK_SIZE_ROUND_DOWN(x) ((x) & ~UINT64_C(1048575))
I prefer `(U64_MB - 1)`

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +                _x > UINT64_MAX - 1048575U ? UINT64_MAX : (_x + 1048575U) & ~UINT64_C(1048575); \
Also here. `(U64_MB - 1)`, rather than 1048575.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +                                h->luks_sector_size == UINT64_MAX ? UINT32_MAX : user_record_luks_sector_size(h), /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
The line is too long. Please move the comment before the argument:
```c
/* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
h->luks_sector_size == UINT64_MAX ? UINT32_MAX : user_record_luks_sector_size(h),
```

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> -
Please keep the empty line after the assertions.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +        /* Ensure we don't create a loop device over block device as it leads to huge overhead for discard operations
Please insert an empty line between the error handling and the comment for the next.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +                setup->image_fd = safe_close(setup->image_fd);
Please insert an empty line after the error check.

2026-02-17 06:43 UTC, yuwata commented on src/home/homework-luks.c
> +                r = loop_device_open_from_path(
Also here.

2026-02-17 13:01 UTC, yuwata approved these changes

2026-02-17 14:23 UTC, merged

2026-02-17 16:36 UTC, GreyXor commented
Thank you everyone for this PR!
@scarlet-storm :tada:

2026-03-25 13:26 UTC, GreyXor commented
Hello @scarlet-storm, I just tried a new homectl 260.1
This PR should `Automatically probe sector size of physical block device, if user does not pass luks-sector-size explicitly.`

I created my user like so:
```
homectl create greyxor \
    --shell=/usr/bin/zsh \
    --member-of="wheel" \
    --disk-size="max" \
    --auto-resize-mode="off" \
    --luks-extra-mount-options compress=zstd
```

```bash
sudo fdisk -l                      
[sudo: authenticate] Password:         
Disk /dev/nvme0n1: 931,51 GiB, 1000204886016 bytes, 244190646 sectors
Disk model: CT1000T500SSD8                          
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 4F8C2039-A66D-4BF2-9DD7-0D346F4CC561

Device            Start       End   Sectors   Size Type
/dev/nvme0n1p1      256    524543    524288     2G EFI System
/dev/nvme0n1p2   524544   2621695   2097152     8G Linux swap
/dev/nvme0n1p3  2621696  36176127  33554432   128G Linux root (x86-64)
/dev/nvme0n1p4 36176128 244190463 208014336 793,5G Linux home


Disk /dev/loop0: 779,97 GiB, 837484019712 bytes, 1635710976 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/home-greyxor: 779,95 GiB, 837467242496 bytes, 1635678208 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

Shouldn't `/dev/mapper/home-greyxor` and `/dev/loop0` would be 4096 luks-sector-size ? My nvme ssd is 4kn native and all my partitions too

2026-03-26 14:11 UTC, scarlet-storm commented
Hi @GreyXor ,
The automatic probing of sector size is for block device based home images not file based images. In your case it would be something like `homectl create <args>... --image-path=/dev/nvme0n1p4` **(this will erase data on /dev/nvme0n1p4)** . 
The reason it has to be done for block devices is mentioned in #30394 . The kernel will not be able to detect the partition table if it does not match sector size of the block device.
In case of file-based both 4k and 512b values should work fine. But we also need to account for backwards compatibility with old home images which were created with 512b sector size. That's why I'm using the same default. You can always override using `--luks-sector-size=4096` if you want a 4k file image.
Also note: If you are concerned about i/o performance, it won't make much difference for ext4 & btrfs. Both of them default to 4k block size even on 512 sector disk. So there won't be any overhead of realigning i/o.
Only xfs defaults to 512 block size if possible, and can face a penalty overhead if used with default 512 sector file image on a 4k disk

2026-03-26 14:47 UTC, GreyXor commented
Thanks @scarlet-storm, very informative.
Are you sure that I can do `homectl create <args>... --image-path=/dev/nvme0n1p4` ? Seem not possible: see [this issue](https://github.com/systemd/systemd/issues/15273).

2026-03-27 10:47 UTC, scarlet-storm commented
@GreyXor , I was not aware of the issue. You are right, it might not be possible to directly use the raw partition device because the kernel will not be able to autodetect the nested partition table. You can use one of the workarounds mentioned in the issue.
Another possibility is to create a systemd service that calls `losetup -fP -b 4096 /dev/nvme0n1p4` during boot and use the resultant loop device as the home image.
I can check if it's possible to add support for any block device as backing image instead of full disks.

2026-08-16 09:01 UTC, GreyXor commented
@scarlet-storm Hi! by any chance did you find if it's possible to add support for any block device ?
Seem that there's a solution here: https://github.com/systemd/systemd/issues/15273#issuecomment-5285031038