test: add sd-bus early-fd test case
systemd/systemd pull request #5520
Opened 2017-03-02 14:52 UTC by dvdhrm

A dbus connection setup is always special. It uses an ASCII line based
protocol to authenticate via SASL. Once that setup is done, normal DBus
messages are sent. Sadly, the line-based protocol does not allow us to
know message sizes up-front. Hence, we have a buffered reader.

Once the authentication phase is done, we use the trailing buffer data
as input for the first message. From them on, we always read exactly the
required sizes from the wire.

Now if the first message in the trailing SASL buffer contains
file-descriptors, we must be able to properly assign them to the
correct message. This commit adds a test case for exactly that. This
sd-bus does not allow us to have full control over the wire scheduling,
we have to hand-craft some messages here to trigger those code paths.

This test currently fails, since sd-bus is broken. So lets delay this until we fixed it.

2017-06-26 14:44 UTC, dvdhrm commented
The CI-fails here on purpose, since that's the point of the PR.

2020-06-10 18:53 UTC, SNiTEBoBy requested changes
Pull requested

2022-10-01 11:47 UTC, keszybz commented
Hmm, should we try to revive this? @dvdhrm can you update this if it's still relevant?

2026-05-13 13:53 UTC, closed without merging

2026-05-13 13:53 UTC, brauner commented
Let's close this issue. If this is still needed then it's no big issue to just open a new pull request for this.

2026-05-14 05:01 UTC, dvdhrm commented
This is a bug in sd-bus. By closing it, you remove the last tracking of it.

Not sure anybody is going to fix this, though.

2026-05-14 06:11 UTC, brauner commented
> This is a bug in sd-bus. By closing it, you remove the last tracking of it.
> 
> Not sure anybody is going to fix this, though.

Then maybe file an issue instead of letting a pull request linger for almost 10 years? Seems simpler if you're just worried about tracking the issue.

2026-06-23 08:58 UTC, dvdhrm commented
> Then maybe file an issue instead of letting a pull request linger for almost 10 years? Seems simpler if you're just worried about tracking the issue.

Ah no, I am not worried at all. I think the maintainers of sd-bus are worried about tracking bugs in it.